### ISSUE TITLE
Panic when event is fired from a text node

### ISSUE THREAD

**Issue by zoechi** [DioxusLabs/dioxus#1003]
**Problem**

This line https://github.com/DioxusLabs/dioxus/blob/master/packages/web/src/dom.rs#L387
causes a panic when I right-click a text node like

```html
<div id="main">
  <ul>
    <li>Some text</li> <!-- right click "Some text" -->
  </ul>
  <div class="other">Menu</div> <!-- oncontextmenu event handler -->
</div>
```
with an `oncontextmenu` event handler registered somewhere else in the app.

```
u_datagrid_dioxus_example.js:400 panicked at 'not a valid element: EventTarget { obj: Object { obj: JsValue(Text) } }', /home/user/.cargo/git/checkouts/dioxus-1e619ce595d3799d/8bf2475/packages/web/src/dom.rs:387:10
```

**Steps To Reproduce**

- 
- 
- 

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version: `master`
 - Rust version: `rustc 1.71.0-nightly (9ecda8de8 2023-04-30)`
 - OS info: Debian 11
 - App platform: `web` (Chrome)

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later
I might try fixing, but I first have to learn some basics about Dioxus and web_sys.

**Comment by Demonthos** [comment]
I tested this example on chrome on `windows 11`:
```rust
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    let count = 0;

    cx.render(rsx! {
        ul {
            li {
                "High-Five counter: {count}"
            }
            li {
                "static item"
            }
        }
        div {
            oncontextmenu: |evt| {
                panic!("event triggered {evt:?}");
            },
            "right click me"
        }
    })
}
```

Right clicking on "High Five counter" or "static item" doesn't trigger a panic.

This could be a bug that is specific to your operating system's version of chrome. [This branch](https://github.com/Demonthos/dioxus/tree/fix-web-event-bubbling-on-text-nodes) has a more resilient version of event bubbling that shouldn't panic when an event is triggered on a text node.
When you have time can you confirm that fixes this issue or post example code that triggers the issue?

**Comment by zoechi** [comment]
With latest Dioxus from branch master
- I can not reproduce with Firefox
- I can reproduce with Chrome `Version 112.0.5615.138 (Official Build) built on Debian 11.6, running on Debian 11.7 (64-bit)`


With branch `fix-web-event-bubbling-on-text-nodes`
- I can not reproduce with Chrome or Firefox
