### ISSUE TITLE
Missing html tag `hgroup` in `dioxus_elements`

### ISSUE THREAD

**Issue by Rigellute** [DioxusLabs/dioxus#1013]
**Problem**

**Steps To Reproduce**

-  Create a component that uses the [hgroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup) html tag:

```rust
fn app(cx: Scope) -> Element {
    cx.render(rsx!(
        header {
            hgroup {
                h1 {
                    "My big heading"
                }
                h2 {
                    "My subtitle"
                }
            }
        }
    ))
}

```
The compile error:
```
hgroup {
^^^^^^ could not find `hgroup` in `dioxus_elements`
```

**Expected behavior**

The `hgroup` html tag should be a valid element.

**Environment:**
 - Dioxus version: v0.3.2
 - Rust version:  v1.68.2
 - OS info: MacOS
 - App platform: [`web`, `ssr`]

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start

**Comment by Demonthos** [comment]
If you are interesting in adding this, we need to change the elements defined [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/html/src/elements.rs#L275).

The format is:
```rust
element Namespace_or_None {
    rust_attribute_name: unused_rust_type DEFAULT_or_html_name,
};
```

**Comment by Rigellute** [comment]
Thanks @Demonthos, I'll aim to raise a PR
