### ISSUE TITLE
Hot Reload doesn't start for dioxus-desktop on Mac

### ISSUE THREAD

**Issue by jmsfltchr** [DioxusLabs/dioxus#1037]
**Problem**

Trying to use hot-reload for desktop deployment compiles fine but does nothing on `cargo-run`

**Steps To Reproduce**

- In cargo.toml:
```
dioxus = { git="https://github.com/DioxusLabs/dioxus", rev="b476c6e8a73bd6591ec4827c6f9b196d7c270c3d"}

[target.'cfg(any(unix, windows))'.dependencies]
dioxus-desktop = { git="https://github.com/DioxusLabs/dioxus", rev="b476c6e8a73bd6591ec4827c6f9b196d7c270c3d", package="dioxus-desktop"}

[target.'cfg(target_family = "wasm")'.dependencies]
dioxus-web = { git="https://github.com/DioxusLabs/dioxus", rev="b476c6e8a73bd6591ec4827c6f9b196d7c270c3d", package="dioxus-web"}
```
- In `main.rs`:
```
use dioxus::prelude::*;

fn main() {
    hot_reload_init!();
    dioxus_desktop::launch(app);

    fn app(cx: Scope) -> Element {
        cx.render(rsx!(div{
            p{
                "p1"
            }
            // Adding this extra para does nothing
            p{
                "p2"
            }
        }))
    }
}
```
- Then `cargo run`. The application starts but there is no message to indicate hot reload is active. Saving changes inside the `rsx!` does not cause a reload.

**Expected behavior**

Expected hot reload to work when an extra `p` tag is added and saved to disk.

**Environment:**
 - Dioxus version: `master` (`b476c6e8a73bd6591ec4827c6f9b196d7c270c3d`)
 - Rust version: stable, `rustc 1.69.0 (84c898d65 2023-04-16)`
 - OS info: MacOS Ventura 13.3.1 (a) (22E772610a)
 - App platform: `desktop` (deploying to web is working!)

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
It looks like Interprocess uses a drop handler to close the socket when the socket listener is dropped, but the desktop window exits in a way that does not run that drop handler
