### ISSUE TITLE
`dioxus fmt --file src/main.rs` error

### ISSUE THREAD

**Issue by elliotwaite** [DioxusLabs/dioxus#1042]
**Problem**

Running `dioxus fmt --file src/main.rs` raises the following error:
```
[WARN] You appear to be creating a Dioxus project from scratch; we will use the default config
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `!`")', /Users/elliotwaite/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-autofmt-0.3.0/src/lib.rs:46:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Note: Running `dioxus fmt` without specifying a specific file works.

**Steps To Reproduce**

- Create a minimal "Hello, world!" app:
```
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(App);
}

fn App(cx: Scope) -> Element {
    cx.render(rsx! { div { "Hello, world!" } })
}
```
- Call `dioxus fmt --file src/main.rs` (where `src/main.rs` is the path to the file above).

**Expected behavior**

For it to autoformat the RSX of the specified file.

**Environment:**
 - Dioxus version: 0.3.2 (the latest commit: `{ git = "https://github.com/DioxusLabs/dioxus", rev = "b476c6e8a73bd6591ec4827c6f9b196d7c270c3d" }`)
 - Rust version: 1.71.0-nightly (8b4b20836 2023-05-22)
 - OS info: macOS Ventura 13.2.1 (22D68)
 - App platform: web

Cargo.toml:
```
[package]
name = "dioxus-test"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "b476c6e8a73bd6591ec4827c6f9b196d7c270c3d" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus", rev = "b476c6e8a73bd6591ec4827c6f9b196d7c270c3d" }
```

**Questionnaire**
- [x] I'm new to Dioxus so I don't think I know enough to try to fix this on my own yet.

**Comment by elliotwaite** [comment]
I tried using both versions and I get the same error for both.

**Comment by DogeDark** [comment]
I have this issue on Windows 10; CLI is installed via git. 
> I tested this example on the git version on Windows 11 and it successfully formatted the file
