### ISSUE TITLE
[feature request] - Hot Module Replacement

### ISSUE THREAD

**Issue by Sparkenstein** [DioxusLabs/dioxus#105]
Hey,
was trying out Dioxus. looks excellet so far really well done 👍 

was thinking is there any way dioxus support HMR? tools like tauri
rely on other dev server to provide updated code immediately
but not sure if same can be achieved with dioxus? since on every
change closing app and reopening is a bit tedious!

**Comment by jkelleyrtp** [comment]
Would you be interested in HMR for Web only, or Desktop/Mobile too?

**Comment by Sparkenstein** [comment]
Currently I am working on Desktop application. not really sure how the requirement will be for others.

**Comment by vikigenius** [comment]
I am working on Desktop as well, and would love to have HMR. I wonder if it's more difficult to implement in Desktop than Web?

**Comment by jkelleyrtp** [comment]
Just wanted to let you know that HMR is coming in the next release of Dioxus for both Desktop and Web!
