### ISSUE TITLE
`Drop` of return value of `use_hook_ not called when expected

### ISSUE THREAD

**Issue by ndarilek** [DioxusLabs/dioxus#1059]
**Problem**

`cx.use_hook` indicates that `Drop` is called on its return value, but that doesn't appear to be happening in the linked example.

**Steps To Reproduce**

- Clone and run https://github.com/ndarilek/dioxus_test
- Using down arrow or end, change the selection in the first list to "second list".

**Expected behavior**

I'd expect to see "Dropping first", "Dropping second", etc. printed as the `Drop` impls for `ItemEntry` run.

Instead, changing the selection in the first list doesn't run the `Drop` impls when the child components are presumably removed from the DOM, thus not updating the parent's view of the list and making the second list go out of sync. Arrows don't work and the ARIA representation doesn't update correctly.

**Environment:**
 - Dioxus version: Master
 - Rust version: 1.70.0
 - OS info: Windows 11
 - App platform: Desktop

**Comment by Demonthos** [comment]
Simpler example:
```rust
#![allow(non_snake_case)]

use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch_cfg(App, dioxus_desktop::Config::new());
}

fn App(cx: Scope) -> Element {
    let even = cx.generation() % 2 == 0;
    render! {
        Borrowed {
            label: if even { "Even" } else { "Odd" }
        }
        button {
            onclick: |_| {
                cx.needs_update();
            },
            "Rerender!"
        }
    }
}

#[inline_props]
pub fn Borrowed<'a>(cx: Scope<'a>, label: &'a str) -> Element {
    println!("Component run {label}");
    cx.use_hook(move || {
        println!("Hook runs {label}");
        struct Dropped {
            label: String,
        }
        impl Drop for Dropped {
            fn drop(&mut self) {
                println!("Dropped {}", self.label);
            }
        }
        Dropped {
            label: label.to_string(),
        }
    });
    render! {
        "{label}"
    }
}
```

Clicking the Rerender button result in:
```
Component run Even
Hook runs Even
Component run Odd
Component run Even
Component run Odd
Component run Even
Component run Odd
Component run Even
Component run Odd
Component run Even
Component run Odd
Component run Even
Component run Odd
Component run Even
Component run Odd
Component run Even
Component run Odd
Dropped Even
```

**Comment by ndarilek** [comment]
Sorry, for some reason I saw your original comment that you'd simplified the example, but not the answer you provided as an edit later.

I think maybe the bit that I'm missing is that `key` needs to be on the `ListboxOption` component in my linked example. Is that correct? Right now I have it on the `li`. If that's the case, 2 more questions:

1. Do I need to do anything special to indicate that the `key` property in my custom components behaves like the `key` property in regular components? If so, what?
2. If the `ListboxOption` component is managing a `li` that needs to be rerendered, is it sufficient to only include the key on the `ListboxOption`?

Thanks.

**Comment by ndarilek** [comment]
For anyone finding this in the future:

1. Nothing is needed, not even specifying `key` as a prop on the custom component. It's global and completely managed by Dioxus.
2. `key` goes on the custom component whose logic needs to rerun on change (I.e. `ListboxOption` in this case.)

Please correct me if I'm wrong. I haven't verified this yet either, just paraphrasing from Discord.

**Comment by Demonthos** [comment]
> For anyone finding this in the future:
> 
> 1. Nothing is needed, not even specifying `key` as a prop on the custom component. It's global and completely managed by Dioxus.

Yes, exactly key isn't a normal prop/attribute it is handled differently.

> 2. `key` goes on the custom component whose logic needs to rerun on change (I.e. `ListboxOption` in this case.)

I think the key should work the same if you put it on any part of the rsx it could be in an element or Component, as long as it is somewhere it the rsx of the children being diffed.
function.sig.inputs.iter().cloned()

```rust
render! {
    (0..5).map(|i| {
        rsx! {
            Comp {
                key: "{i}"
            }
            p { "{i}" }
        }
     })        
}
```
should work the same as
```rust
render! {
    (0..5).map(|i| {
        rsx! {
            Comp {}
            p { key: "{i}", "{i}" }
        }
     })        
}
```
