### ISSUE TITLE
How to pass functions as props like react?

### ISSUE THREAD

**Issue by pat0026** [DioxusLabs/dioxus#1067]
**Question**

I'm trying to explore hooks in dioxus. I'm currently curious about how to use use_memo and use_callback, but I'm having trouble passing a function or closure in the component's properties. Do you have any documentation or example on using these hooks properly in different components or creating component props that pass functions/closures or function pointers? 

I don't know how to create functions as members of structs but I tried following these instructions in Stackoverflow. Sadly to say I couldn't compile it. Please see this [link](https://stackoverflow.com/a/52934680) as a reference. Any advice would be appreciated.

**Environment:**
 - Dioxus version: 0.3.2
 - Rust version: 1.69
 - OS info :windows
 - App platform: web

**Comment by Demonthos** [comment]
You use generics to accept anything that implements Fn():
```rust
/*
[dependencies]
dioxus = "*"
*/

use dioxus::prelude::*;

fn main() {
    
}


fn app(cx: Scope) -> Element {
    render! {
        Comp {
            function: || println!("hello world")
        }
    }
}

#[derive(Props)]
struct CompProps<F: FnOnce()> {
    function: F
}

fn Comp<F: FnOnce()>(cx: Scope<CompProps<F>>) -> Element {
    render! {
        div {}
    }
}
```

**Comment by pat0026** [comment]
Thank you for the fast response. Closing this issue.
