### ISSUE TITLE
use_future's output doesn't get dropped

### ISSUE THREAD

**Issue by valyagolev** [DioxusLabs/dioxus#1082]
**Problem**

`use_future`'s output doesn't seem to ever get dropped

**Steps To Reproduce** / **Expected behavior**

Repro code: https://gist.github.com/valyagolev/02b059842ab5010de0fde17ccf380b7f#file-repro-rs-L46 
Repro for desktop: https://github.com/valyagolev/diox-rep

It should print "references left: 1" after clicking "Unmount", and it doesn't.

Identical code, that uses `cx.use_hook` and no futures,  prints "references left: 1" after unmount.

**Screenshots**

**Environment:**
 - Dioxus version: master (f63220019ddaac5a8bc44db855723c245d53632e)
 - Rust version: `rustc 1.70.0 (90c541806 2023-05-31)`
 - OS info: MacOS
 - App platform: tested on `liveview` on `axum`, and with dioxus-desktop as well

**Questionnaire**

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

I'd love to contribute but a bit stressed out lately, so no promises to do it quickly.

**Comment by valyagolev** [comment]
reproduced this for dioxus-desktop on master as well

**Comment by valyagolev** [comment]
repo with repro https://github.com/valyagolev/diox-rep

**Comment by jkelleyrtp** [comment]
This should be fixed in master now
