### ISSUE TITLE
special attributes cannot be set properly with boolean values

### ISSUE THREAD

**Issue by Busyvar** [DioxusLabs/dioxus#1086]
When a special attribute (like disabled, hidden, ...) is set with a boolean value, special attribute is not positional anymore.

For example :
_definition_
`disabled: X as bool,`
_results_
`<div disabled="true" ></div>` or
`<div disabled="false" ></div>` 
_What i expected_
`<div disabled></div>` or 
`<div></div>`

Here is a correct definition
`disabled: if X {"true"}else{"false"},`
_results_
`<div></div>` or
`<div disabled></div>`

Do you think current syntax can be enhanced to take boolean value as input?

**Environment:**
 - Dioxus version: 0.3.2
 - Rust version:  1.72.0 nightly
 - OS info: Arch x64
 - App platform: desktop

**Comment by onweru** [comment]
@Busyvar, 

> Do you think current syntax can be enhanced to take boolean value as input?

Assuming by `'input'` you mean props / local variable. If so,

Maybe:

```rust
fn Button(cx: Scope) -> Element {
    ...
    let is_disabled = if cx.props.disabled {
        true
    } else {
        false
    };
    cx.render(rsx!(
        button {
            disabled: is_disabled,
            ...
        }
    ))
    ...
}
```

For additional context

- [Boolean attributes](https://dioxuslabs.com/docs/0.3/guide/en/describing_ui/special_attributes.html#boolean-attributes)
- [Conditional rendering](https://dioxuslabs.com/docs/0.3/guide/en/interactivity/dynamic_rendering.html#conditional-rendering)

**Comment by onweru** [comment]
@Busyvar, 

First I want to clarify something, just in case I misunderstood your original question.

If you're using the button component as defined by under [dioxus html](https://docs.rs/dioxus-html/latest/src/dioxus_html/elements.rs.html#1022) you only need to specify the disabled prop value when its value is `true`

```rust
// same as setting `disabled: false`
button {
    "My button" 
}
// when disabled: true
button {
    disabled: true,
    "My button"
}
```  

👆🏼  This code will generate this html

```html
<button>My button</button> <!-- disabled is false by default i.e when the disabled attribute is missing ->
<button disabled="true">My button</button>
```

<img width="1109" alt="SCR-20230613-lpcs" src="https://github.com/DioxusLabs/dioxus/assets/16350351/a181e3cc-f61d-406c-acfa-247167bf8cde">

**Comment by onweru** [comment]
If you need a custom button component,

> @onweru what if your example is written it this way (assuming cx.props.disabled is Boolean)?

You can make prop optional.

```rust
#[inline_props]
fn Button(cx: Scope, disabled: Option<bool>) -> Element {
    let is_disabled = match cx.props.disabled.unwrap_or(false);

    cx.render(rsx!(
        button {
            disabled: is_disabled,
            "Button Label"
        }
    ))
}
```

Then you can call the component as follows:

```rust
Button {} // when disabled is false
Button { 
    disabled: true 
}
```

👆🏼  This code will generate this html

```html
<button>Button Label></button> <!-- Button {} // when disabled is false ->
<button disabled="true">Button Label</button> <!-- Button { disabled: true } ->
```

**Comment by Demonthos** [comment]
Boolean attributes should work the same as string attributes. I think this issue is the same as https://github.com/DioxusLabs/dioxus/issues/1070 which was fixed recently in the git version of Dioxus

**Comment by Demonthos** [comment]
Boolean attributes should work the same as string attributes. A similar issue was fixed before for special boolean attributes, but it appears the fix was not applied to normal boolean attributes. Currently, the code checks it the attribute is equal to the string false [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/interpreter/src/common.js#L61) we also need to check if it is equal to the value false
