### ISSUE TITLE
Special characters are rendered with an extra space

### ISSUE THREAD

**Issue by bernardodesousa** [DioxusLabs/dioxus#1087]
**Problem**

Special characters like emojis and accent-bearing letters are followed by an extra space.

**Steps To Reproduce**

* Replace the "Hello World!" string in the examples with something containing special characters, like "I🧡piñadas"
* cargo run

**Expected behavior**

Emojis are just nice, but localization is a requirement for some projects. So it would be nice to have accent bearing letters rendered in the space of one character.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/12608274/e076808f-b808-4ead-b04d-a606acaae466)

**Environment:**
 - Dioxus version: f63220019ddaac5a8bc44db855723c245d53632e, master
 - Rust version: 1.70.0
 - OS info: Windows 11, PowerShell 7.3.4
 - App platform: TUI

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
I believe the issue here is that the x offest is determined by the byte index [here](https://github.com/DioxusLabs/dioxus/blob/f63220019ddaac5a8bc44db855723c245d53632e/packages/rink/src/render.rs#LL58C50-L58C50) we should be able to fix this by using chars().enumerate() instead of char_indecies()

**Comment by Demonthos** [comment]
Typically when I see that error it is because one or more Dioxus libraries use a different source. If the Dioxus and renderer library don't use the same source then you can have places where identical types come from different versions of the dependency which causes this error message. In your example, I'm guessing that you pointed dioxus-tui to your new branch, but Dioxus is still using the main git branch.

**Comment by bernardodesousa** [comment]
Interesting. That's exactly right! Now I'm using my fork for both dioxus and dioxus-tui dependencies, and it compiles and runs fine. New problem, thou:

![image](https://github.com/DioxusLabs/dioxus/assets/12608274/92ad1c46-d59b-42ba-9f48-ff80f893e92b)

In the source, I have a p right after the heart. The ñ is perfect, so that's a step forward!

**Comment by Demonthos** [comment]
It looks like the heart takes up more than one terminal character of space. Instead of the number of characters, we can map each character to it's width (given by https://docs.rs/unicode-width/latest/unicode_width/trait.UnicodeWidthChar.html#tymethod.width) and sum the with of all the previous characters

**Comment by creatxrgithub** [comment]
hi, i meet the same problem just now:
the code is copy from helloworld example: https://dioxuslabs.com/docs/0.3/guide/en/getting_started/mobile.html

src/lib.rs
```
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx!{
        div {
            "hello world!"
        }
    })
}
```

Cargo.toml

```
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx!{
        div {
            "hello world!"
        }
    })
}
```

error message:

```
error[E0308]: mismatched types
  --> src/lib.rs:4:28
   |
4  |     dioxus_desktop::launch(app);
   |     ---------------------- ^^^ expected fn pointer, found fn item
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected fn pointer `for<'a> fn(dioxus_core::scopes::Scope<'a>) -> Option<dioxus_core::nodes::VNode<'a>>`
                 found fn item `for<'a> fn(&'a Scoped<'a>) -> Option<VNode<'a>> {app}`
   = note: when the arguments and return types match, functions can be coerced to function pointers

```

**Comment by Demonthos** [comment]
You may need to run `cargo update` to get the latest versions of the dioxus and dioxus-desktop crates

**Comment by creatxrgithub** [comment]
> You may need to run `cargo update` to get the latest versions of the dioxus and dioxus-desktop crates

i have tried before. it's nothing change in Cargo.toml

**Comment by creatxrgithub** [comment]
if i edit like this:

```
[dependencies]
mobile-entry-point = "0.1.0"
dioxus = { version = "0.3.2"}
dioxus-desktop = { version = "0.3.0" }
simple_logger = "*"
atk-sys = "*"
webkit2gtk-sys = "*"
```

then "cargo update" and "cargo run", the error message is:

```
warning: function `main` is never used
 --> src/lib.rs:3:4
  |
3 | fn main() {
  |    ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function `app` is never used
 --> src/lib.rs:7:4
  |
7 | fn app(cx: Scope) -> Element {
  |    ^^^

warning: `mobile-caller-blocker` (lib) generated 2 warnings
   Compiling mobile-caller-blocker v0.1.0 (/media/creatxr/WORK/DEV/APPS-CROSS-PLATFORM/mobile-caller-blocker)
error[E0425]: cannot find function `start_app` in crate `mobile_caller_blocker`
 --> gen/bin/desktop.rs:4:28
  |
4 |     mobile_caller_blocker::start_app();
  |                            ^^^^^^^^^ not found in `mobile_caller_blocker`

For more information about this error, try `rustc --explain E0425`.
```

**Comment by jkelleyrtp** [comment]
TUI has been put on ice while we overhaul its architecture based on http://github.com/dioxusLabs/blitz - lots of bugs will come out of its eventual re-release.
