### ISSUE TITLE
Event "onclick:" doesn't work on kali linux (debian)

### ISSUE THREAD

**Issue by git-user-cpp** [DioxusLabs/dioxus#1091]
**Problem**
_**onclick:**_ gives an error _**TypeError: undefined is not an object (evaluating 'config.intercept_link_redirects')**_

This error appears when in the launched rendered desktop window: click right mouse button -> inspect element -> console.
The error appears in console section every time you press the button.

**Steps To Reproduce**

- copy the following code:

```
#![allow(non_snake_case)]

use dioxus::prelude::*;

fn main() {
	dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    render!{
        rsx! {
            button {
                onclick: move |_| println!("Clicked!"),
                "click me!"
            }
        }
    }
}
```

- cargo run

**Expected behavior**

This code should return the text "click me!" in terminal.
Instead: nothing happens in terminal. (error visible only when you inspect elements in the rendered window).

![Screenshot_2023-06-13_12-35-37](https://github.com/DioxusLabs/dioxus/assets/61907955/5ae73473-fedb-4576-b6d8-e9d111b4006e)
![Screenshot_2023-06-13_12-35-13](https://github.com/DioxusLabs/dioxus/assets/61907955/16ea0a3c-e8d4-44b3-9af7-24cfabcb9cab)
![Screenshot_2023-06-13_12-35-24](https://github.com/DioxusLabs/dioxus/assets/61907955/69e91b5b-4e6e-43b7-a668-9cb8dc908be3)

**Environment:**
 - Dioxus version: v0.3.2
 - Rust version: 1.70.0 nightly
 - OS info: Arch x64; Kali GNU/Linux 2023.2
 - App platform: desktop

**P.S**
Maybe a solution to this problem is very simple or even stupid but I'll be glad if someone will help with this issue. No judgements I'm a beginner :smiling_face_with_tear:

**Comment by Demonthos** [comment]
This looks like the same underlying issue as https://github.com/DioxusLabs/dioxus/issues/1078. If you switch to the git version of Dioxus it should resolve the issue. We need to either yank the newest interpreter release or bump Dioxus desktop to resolve the issue on stable

**Comment by git-user-cpp** [comment]
Could you tell me please how can I switch to the git version of Dioxus to resolve the issue? Or is it better to just wait a bit for a new fixed version?

**Comment by Demonthos** [comment]
You need to edit all of your Dioxus dependencies to link to the git repo
```rust
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }
```

**Comment by git-user-cpp** [comment]
Thanks a million! :smiley: :crab:

**Comment by Demonthos** [comment]
The new interpreter-js release fixes this issue on stable
