### ISSUE TITLE
Introduction example in docs is broken

### ISSUE THREAD

**Issue by RobinBoers** [DioxusLabs/dioxus#1097]
**Problem**

The example in the docs shows an error when clicking run.

**Steps To Reproduce**

- Open docs (<https://dioxuslabs.com/docs/0.3/guide/en/>)
- Click play button

**Expected behavior**

The example should work

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/60298132/29b43b8d-edd3-46d4-9e63-c88c80876644)

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by marc2332** [comment]
Introduction examples on documentation are sometimes kept simple on purpose.
You just need to import dioxus like this to make it work:

```rs
use dioxus::prelude::*;
```

**Comment by RobinBoers** [comment]
The problem isn't that the example fails. I can see why that happens. I just expect the example to work if I run play. This doesn't seem professional.

**Comment by marc2332** [comment]
> The problem isn't that the example fails. I can see why that happens. I just expect the example to work if I click play. This doesn't seem professional.

These examples are not interactive, I'll open a PR later so the play button doesnt show up.
