### ISSUE TITLE
Dioxus CLI wasm-bindgen version mismatch

### ISSUE THREAD

**Issue by CrimsonPolar** [DioxusLabs/dioxus#1101]
**Problem**

The Dioxus CLI uses wasm-bindgen version 0.2.86 but dioxus_web now requires version 0.2.87. Brand new projects created from the web template fail to run.

**Steps To Reproduce**

1. Create a new project dioxus web project from the dioxus template
2. (Optional) Upgrade dependencies to latest versions in Cargo.toml
3. Run `dioxus serve`
4. `cargo update -p wasm-bindgen --precise 0.2.86` fails because web-sys requires 0.2.87 or higher. `cargo install -f wasm-bindgen-cli --version 0.2.87` succeeds, but does not resolve the issue.

**Expected behavior**

A web server will open with the app running.

**Screenshots**

**Environment:**
 - Dioxus version: 0.32 (or 0.3)
 - Rust version: 1.70
 - OS info: MacOS
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by DogeDark** [comment]
Whenever this happens, download the latest version of the CLI with ``cargo install --git https://github.com/DioxusLabs/cli`` 

It's set to use the latest minor version of 0.2. It's not the ideal solution, and eventually, dioxus-web and the cli will be locked onto a version, but it works for now.
