### ISSUE TITLE
3D

### ISSUE THREAD

**Issue by WREQI** [DioxusLabs/dioxus#1113]
We want to use Trust to develop high-performance apps that support 3D and AR, such as Apple's Android app. Can this be achieved?

**Comment by Demonthos** [comment]
Currently, Dioxus does not support any 3D renderers, but we do expose an API to allow you to create a [custom renderer](https://dioxuslabs.com/docs/nightly/guide/en/custom_renderer/index.html).

Closing this as a duplicate of https://github.com/DioxusLabs/dioxus/issues/265
