### ISSUE TITLE
Brief flash when opening a dark mode app on a light mode macOS desktop

### ISSUE THREAD

**Issue by terhechte** [DioxusLabs/dioxus#1120]
When opening a dark-mode only macOS Dioxus app on a light mode desktop, there is a very unpleasant flash when it is starting up where the WebView switches from light mode to dark mode.

You can see it in example in a video here:

https://github.com/DioxusLabs/dioxus/assets/132234/b2d274ff-dab5-49ee-8b1a-8768bfd23b4d

I currently maintain a [Dioxus fork](https://github.com/terhechte/dioxus/tree/dioxus_macos_hacks) so that [Ebou](https://github.com/terhechte/Ebou) doesn't have this unpleasant flash.

I'd love to contribute my change / fix but it is quite the hack. At the bottom of this post you can find the source that I'm using for the example app, and I've tried to enforce dark mode in all places.

My current hack to solve this is to delay displaying the web view for a brief amount of time right after window creation. The window itself is properly dark (via the `tao` theme), just the web view needs a couple of frames to parse the initial html / css and then go to dark mode. I also tried setting the background color of the web view to transparent but that lead to other problems.

[Here's my hack](https://github.com/DioxusLabs/dioxus/compare/master...terhechte:dioxus:dioxus_macos_hacks#diff-b0579535f28f7caa593a8664352df35bb34350c47fe2c326d6f4af792bb3a439R98)

``` rs
#[cfg(target_os = "macos")]
    {
        use objc::runtime::Object;
        use objc::runtime::{NO, YES};

        use crate::wry::webview::WebviewExtMacOS;
        let native_webview = build.webview();
        unsafe {
            use cocoa::appkit::NSApp;
            let _: () = msg_send![native_webview, setHidden: YES];

            dispatch::Queue::main().exec_after(Duration::from_millis(250), || {
                let mw: *mut Object = msg_send![NSApp(), mainWindow];
                let mx: *mut Object = msg_send![mw, contentView];
                let uux: *mut Object = msg_send![mx, subviews];
                let first: *mut Object = msg_send![uux, objectAtIndex: 0];
                let _: () = msg_send![first, setHidden: NO];
            });
        }
    }
```

I'm raising this issue to start a discussion around:

- Whether a fix for this is even wanted
- If the hack above would maybe even suffice to include it in Dioxus
- Or if there is a way to allow a Dioxus consumer to hook into window creation so that this hack could live in the corresponding Dioxus apps (such as Ebou).

**Environment:**
 - Dioxus version: `master`
 - OS info: macOS Ventura
 - App platform: `desktop

**Questionnaire**
- [x] I would like to fix and I have a solution

---

### Example app source

``` toml
[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus" }
```

``` rs
#![allow(non_snake_case)]
use dioxus::prelude::*;
use dioxus_desktop::{Config, WindowBuilder};

pub fn default_window() -> WindowBuilder {
    let builder = WindowBuilder::new();

    builder
        .with_title("Darkflash")
        .with_theme(Some(dioxus_desktop::tao::window::Theme::Dark))
}

pub fn main() {
    let style = r#":root { color-scheme: dark; }"#;
    let config = Config::new()
        .with_custom_head(format!(
            r#"
        <style>{style}</style>
        "#
        ))
        .with_window(default_window());

    dioxus_desktop::launch_with_props(RootApp, RootAppProps {}, config);
}

pub struct RootAppProps {}

pub fn RootApp(cx: Scope<'_, RootAppProps>) -> Element<'_> {
    render! {
        div {
            "Hello World"
        }
    }
}

```

**Comment by Demonthos** [comment]
I think this issue might be better addressed in wry (the webview library dioxus uses).
Wry exposes a [set_background_color](https://docs.rs/wry/0.29.0/wry/webview/struct.WebView.html#method.set_background_color) option meant to address this issue. #1123 exposes this in Dioxus but it looks like the feature was not implemented for MacOs in https://github.com/tauri-apps/wry/pull/682. If you have a fix for this issue, you could open a PR for wry

Wry issue: https://github.com/tauri-apps/tauri/issues/1564

**Comment by terhechte** [comment]
This is actually a bit more difficult. The `WKWebView` on macOS is just a proxy for a web view in a separate process. Therefore, most operations applied to it just end out in a noop. Here's a Apple developer thread where people discuss the different alternatives:

https://developer.apple.com/forums/thread/121139

The thing that works best is the initial hiding. Everything else seems to only work in old versions. I also gave it a try by forking wry and adding the `set_background_color` implementation for macOS but it just doesn't do anything. For reference:

``` rs
pub fn set_background_color(&self, background_color: RGBA) -> Result<()> {
    let (r, g, b, a) = background_color;
    #[cfg(target_os = "macos")]
    unsafe {
      use cocoa::appkit::NSColor;
      let ns_color: id = msg_send![class!(NSColor), alloc];
      // let ns_color: id = msg_send![ns_color, init];
      let color = NSColor::colorWithCalibratedRed_green_blue_alpha_(
        ns_color,
        r as f64 / 255.0,
        g as f64 / 255.0,
        b as f64 / 255.0,
        a as f64 / 255.0,
      );
      let _: () = msg_send![self.webview, setBackgroundColor: color];
    }
    Ok(())
  }
}
```
