### ISSUE TITLE
Doesn't compile for iOS

### ISSUE THREAD

**Issue by terhechte** [DioxusLabs/dioxus#1121]
**Dioxus doesn't compile for iOS anymore**

The [reason is the `rfd` dependency in the `dioxus-desktop` crate](https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/Cargo.toml#L40):

Rfd doesn't have support for iOS. This could be added to Rfd, but until that's the case I think it would be best to not depend on Rfd if the target is iOS (and Android I guess)

**Questionnaire**
- [x] I would like to fix and I have a solution

**Comment by Demonthos** [comment]
See also: #1107 

For the short term, I think disabling the rfd crate for mobile would be a good solution. In the longer term, we could add mobile support to rfd or use another library for mobile file dialogs.
