### ISSUE TITLE
Don't close app when last window is closed on macOS

### ISSUE THREAD

**Issue by terhechte** [DioxusLabs/dioxus#1122]
On macOS, the default behaviour for apps is to keep running even if the user closes all windows. If I'm in Safari, and I close all windows, the app is still running and I can go back and open new windows.

Single Window apps usually don't close the window, they just hide it, so that going back to the app opens the window again.

Dioxus, on the other hand, closes the app as soon as no Window is running anymore. This makes sense on other platforms, but on macOS this feels alien. I'd like to propose an addition to the `WindowBuilder` API to allow setting the close behaviour between:

``` rs
enum WindowCloseBehaviour {
  /// Default behaviour, closing the last window exits the app
  LastWindowExitsApp,
  /// Closing the last window will not actually close it, just hide it
  LastWindowHides,
  /// Closing the last window will close it but the app will keep running so that new windows can be opened
  CloseWindow,
}
```

I'd be happy to implement this if this is desired functionality.

**Comment by Demonthos** [comment]
This would be great! On windows, this could also be useful in once we implement [system tray support](https://docs.rs/wry/0.29.0/wry/application/system_tray/index.html).
