### ISSUE TITLE
Bump Dioxus Liveview Salvo Version

### ISSUE THREAD

**Issue by xinglixing** [DioxusLabs/dioxus#1124]
**Problem**

dioxus_liveview::salvo_socket(ws) - mismatched types 'WebSocket' and 'salvo_extra::ws::WebSocket'.

**Steps To Reproduce**

- Change salvo's version to 0.44 in Cargo.toml

**Environment:**
 - Dioxus version: [v0.3.2 `master`]
 - Rust version: [v1.70.0]
 - OS info: [MacOS]

**Comment by Demonthos** [comment]
Dioxus liveview uses salvo version `0.37.7`. If you downgrade the your salvo version to `0.37`, it should fix the error. If you are interested in contributing to Dioxus, you could bump the salvo version [here](https://github.com/DioxusLabs/dioxus/blob/dfa4d8d989385ceae0233ed6822b21d5e99869bc/packages/liveview/Cargo.toml#L40) and fix any breaking changes in the salvo adapter [here](https://github.com/DioxusLabs/dioxus/blob/dfa4d8d989385ceae0233ed6822b21d5e99869bc/packages/liveview/src/adapters/salvo_adapter.rs)

**Comment by Demonthos** [comment]
Closed by #1130
