### ISSUE TITLE
dioxus-web: console "spam"

### ISSUE THREAD

**Issue by mirkootter** [DioxusLabs/dioxus#1127]
**Problem**

dioxus-web logs events to the developer console. Unfortunately, this can get quite confusing if the log is used for other things as well. For example, a html `input` tag with type="text" and an `oninput` handler will log an InputEvent to the console on each keystroke.

**Steps To Reproduce**
Write a simple dioxus web app with a html input tag, `type="text"` and an oninput handler.

**Expected behavior**
No logs to the console except maybe some critical errors or warnings.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/20500035/e5dc431c-f686-4ed2-8557-0f520e03bac2)

**Environment:**
 - Dioxus version: [e.g. v0.3.2, `master`]
 - App platform: [`web`]

**Comment by Demonthos** [comment]
Implementation Overview

There is a console log in the web renderer code [here](
https://github.com/DioxusLabs/dioxus/blob/dfa4d8d989385ceae0233ed6822b21d5e99869bc/packages/web/src/dom.rs#L260) that we need to remove.

> If you are a new contributor and run into issues implementing this feature, don't hesitate to reach out here or ping me on [discord](https://discord.gg/XgGxMSkvUM) @Demonthos

**Comment by mxnnn** [comment]
Is this still an issue? (AFAIK seems to have been fixed in https://github.com/DioxusLabs/dioxus/commit/043aae16893e425d20d090fad57e34daf5caba21)

**Comment by Demonthos** [comment]
It looks like the logs no longer appear. Feel free to reopen the issue if you see other logs that are outputted without the log crate (which you can configure)
