### ISSUE TITLE
Dioxus + cargo-mobile  versions 0.3.0+ broken

### ISSUE THREAD

**Issue by ethankuhrts** [DioxusLabs/dioxus#1148]
**Problem**

All Dioxus versions 0.3.0 and on simply do not compile, I'm using cargo mobile

**Steps To Reproduce**

Simply follow the mobile getting started guide

**Expected behavior**
Error report:
error[E0308]: mismatched types2s]
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/interprocess-1.2.1/src/os/unix/udsocket/socket.rs:296:27
    |
296 |         hdr.msg_namelen = size_of_val(&addr_buf_staging).try_to::<u32>().unwrap();
    |         ---------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
    |         |
    |         expected due to the type of this binding

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/interprocess-1.2.1/src/os/unix/udsocket/c_wrappers.rs:54:13
     |
49   |         libc::bind(
     |         ---------- arguments to this function are incorrect
...
54   |             size_of::<sockaddr_un>() as u32,
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
     |
note: function defined here
    --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.147/src/unix/linux_like/mod.rs:1772:12
     |
1772 |     pub fn bind(socket: ::c_int, address: *const ::sockaddr, address_len: ::socklen_t) -> ::c_int;
     |            ^^^^
help: you can convert a `u32` to an `i32` and panic if the converted value doesn't fit
     |
54   |             (size_of::<sockaddr_un>() as u32).try_into().unwrap(),
     |             +                               +++++++++++++++++++++

error[E0308]: mismatched types
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/interprocess-1.2.1/src/os/unix/udsocket/c_wrappers.rs:73:13
    |
70  |         libc::connect(
    |         ------------- arguments to this function are incorrect
...
73  |             size_of::<sockaddr_un>() as u32,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
    |
note: function defined here
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.147/src/unix/mod.rs:630:12
    |
630 |     pub fn connect(socket: ::c_int, address: *const sockaddr, len: socklen_t) -> ::c_int;
    |            ^^^^^^^
help: you can convert a `u32` to an `i32` and panic if the converted value doesn't fit
    |
73  |             (size_of::<sockaddr_un>() as u32).try_into().unwrap(),
    |             +                               +++++++++++++++++++++

error[E0308]: mismatched types2s]
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/interprocess-1.2.1/src/os/unix/udsocket/c_wrappers.rs:104:17
    |
99  |             libc::setsockopt(
    |             ---------------- arguments to this function are incorrect
...
104 |                 size_of_val(&passcred) as u32,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
    |
note: function defined here
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.147/src/unix/mod.rs:679:12
    |
679 |     pub fn setsockopt(
    |            ^^^^^^^^^^
help: you can convert a `u32` to an `i32` and panic if the converted value doesn't fit
    |
104 |                 (size_of_val(&passcred) as u32).try_into().unwrap(),
    |                 +                             +++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `interprocess` due to 4 previous errors

**Environment:**
 - Dioxus version: 0.3.0, 0.3.1, 0.3.2
 - Rust version: 1.69.0
 - OS info: Manjaro Linux (Arch)
 - App platform: mobile

**Comment by jkelleyrtp** [comment]
Which target are you building for? iOS or Android?

On master I'm able to get our examples compiling for `aarch64-apple-ios-sim`. We did fix some stuff around interprocess, so we might need to get those fixes into the release.

**Comment by ealmloff** [comment]
0.4.0 is now released which has been checked to compile correctly works on IOS and android (with the exception of https://github.com/DioxusLabs/dioxus/issues/1158) along with a new [mobile guide](https://dioxuslabs.com/learn/0.4/getting_started/mobile). Feel free to open a new issue if you run into any issues after updating
