### ISSUE TITLE
UseFutureState::state returns Reloading instead of Completed

### ISSUE THREAD

**Issue by feral-dot-io** [DioxusLabs/dioxus#1151]
**Problem**

Once `UseFutureState::state` initially returns `Pending` then switches to `Reloading` once the future runs. However it should move to `Completed` and only switch to reloading if a dependency changes or is restarted.

**Steps To Reproduce**

Here's a test program:

```rust
use dioxus::prelude::*;

fn main() {
    wasm_logger::init(wasm_logger::Config::new(log::Level::Info));
    dioxus_web::launch(under_test);
}

pub fn under_test(cx: Scope) -> Element {
    let future = use_future(cx, (), |_| async {
        log::info!("future is running");
        123
    });

    cx.render(match future.state() {
        UseFutureState::Pending => {
            log::info!("PENDING");
            rsx!(p { "PENDING" })
        }
        UseFutureState::Reloading(val) => {
            log::info!("RELOADING ({})", val);
            rsx!(p { "RELOADING ({val})" })
        }
        UseFutureState::Complete(val) => {
            log::info!("COMPLETED ({})", val);
            rsx!(p { "COMPLETED ({val})" })
        }
    })
}
```

Cargo.toml:
```rust
[package]
name = "future-test"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "a75223cd8895ca6733164ddf03de314c91c1dbab" }
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "a75223cd8895ca6733164ddf03de314c91c1dbab" }
log = "0.4.19"
wasm-logger = "0.2.0"
```

**Expected behavior**

This should display and log "COMPLETED (123)".

The actual result is "RELOADING (123)" and the log:

```
INFO src/main.rs:16 PENDING [dioxus.js:868:13](http://localhost:8080/assets/dioxus/dioxus.js)
INFO src/main.rs:10 future is running [dioxus.js:868:13](http://localhost:8080/assets/dioxus/dioxus.js)
INFO src/main.rs:20 RELOADING (123) [dioxus.js:868:13](http://localhost:8080/assets/dioxus/dioxus.js)
```

**Environment:**
 - Dioxus version: master (a75223cd8895ca6733164ddf03de314c91c1dbab)
 - Rust version: rustc 1.70.0 (90c541806 2023-05-31)
 - OS info: Linux / NixOS
 - App platform: web

**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
This was fixed in https://github.com/DioxusLabs/dioxus/pull/1223
