### ISSUE TITLE
[RFC] Authentication - Minimal Example and Documentation

### ISSUE THREAD

**Issue by stephenandary** [DioxusLabs/dioxus#1152]
# Authentication in Dioxus

## Purpose

This RFC is to align on a desired authentication example for Dioxus and its relevant documentation as planned in: 
[Documentation Map](https://excalidraw.com/#room=d8e228990924048be951,MBE9NeSUUezwjkfPMyIv_A)

## Proposal

Create an initial example to leverage the [OAuth2 Crate](https://github.com/ramosbugs/oauth2-rs) to authenticate with an external provider. This will allow for social or email login as one can authenticate through [Auth0](https://auth0.com) if email signup is desired. 

This will document the basic authentication flow, and how it works with Dioxus (**with visuals**).

As such, I'd like to avoid sessions for this example; Auth0 can manage sessions. 

If desired I can use Auth0 instead of another OAuth provider for this example. 

Future PRs may involve simplifying the example by abstracting code into components, hooks or something less cumbersome, adding some form of sessions, and moving calls to server functions. 

## Reference

I am currently playing with code in this [Repo](https://github.com/stephenandary/dioxus_playground/tree/main/barebone_app) where I have placed OAuth Library calls in a "services" directory such that if a user wants to move these to a server function instead it should easily be possible. 

I have more previous work [Here](https://github.com/stephenandary/wasm_platform_examples/tree/main/wasmcloud/oauth2).

**Comment by stephenandary** [comment]
There is also this [OpenID Connect Crate](https://github.com/ramosbugs/openidconnect-rs) that can be looked at. But I am using OAuth2 for myself, so this is something I won't be able to look at right now.

**Comment by Demonthos** [comment]
This sounds great! Oauth is a good place to start. We could add extra chapters for other auth providers and sessions in the future.

**Comment by stephenandary** [comment]
After speaking with @jkelleyrtp can also just not use the OAuth2 Crate. I have work archived which does this already. Focus was on Authorization flow with PKCE. And can add other flows in the future. OAuth2 can be somewhat complex to use, and it may be better just to keep it simple.

**Comment by stephenandary** [comment]
I deleted my last comment, as I am sticking with using Oauth2 crate until I can't. Doesn't make sense to not when my blocker before was not being able to compile because of WASI. If I can't compile I will use work I have done to get around this. But I am optimistic wasm-unknown-unknown target shouldn't have this issue.

**Comment by stephenandary** [comment]
Working on this, closing issue.
