### ISSUE TITLE
Dioxus CLI `create` should generate mobile glue

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#1157]
## Specific Demand

Our tooling today doesn't know how to generate the right glue for mobile, so users are really confused when they try to build for mobile and we don't give them a good onramp.

We should include mobile templates and some default glue code into the dioxus-mobile crate.

We should also be a bit more opinionated about the defaults for mobile so things like logging, panic handling, viewport manipulation, etc. are not hoops to jump through. Most folks just want to `cargo run` and get a simulator running based on their project configuration.

## Implement Suggestion

Right now users have to use `cargo mobile`. This project is somewhat inactive and has been forked by the Tauri folks into Tauri mobile. I think we can just reuse that library in the CLI to allow generation of Dioxus mobile projects.

**Comment by sluedecke** [comment]
Hope it is not too much to ask, but deploying to web and mobile from a single codebase (even if an intermediate step like building an iOS / Android app is involved and one might need to adjust some generated gluecode) would be super awesome!

The [Quasar framework](https://quasar.dev/) offers just that (Javascript/Typescript framework based on Vue.js, can quite easily be deployed as single page application as well as a mobile application).

**Comment by semicolon-10** [comment]
@jkelleyrtp Currently the documentation for mobile https://dioxuslabs.com/learn/0.5/reference/mobile does it even work? I tried for ios and end up running into  failed to run custom build command for `objc_exception v0.1.2` . Do we have more step by step guide?

**Comment by jkelleyrtp** [comment]
We now generate glue for iOS (very little required!) and have some minimal support for android.
