### ISSUE TITLE
Component preview like Storybook

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/dioxus#1173]
## Specific Demand

When building design systems on Dixous, it's very difficult to preview components isolated from apps; this creates alot of friction between the design specs of a company and the implementation, JS frameworks have largely addressed this through Storybook and similar tooling.

## Implement Suggestion

It'd be great if we can solve this through Storybook or equivalently create another similar solution exclusive to the Rust / Dioxus ecosystem. Either approach would work as the underlying issue is to get components to be previewed, documented and have the ability to play around with the props dynamically where possible. MDX is also a great addition that Storybook comes with, and this might be worth investigating.

**Comment by Demonthos** [comment]
[At one point, rsx preview was implemented in the Dioxus VSCode extension](https://github.com/DioxusLabs/cli/pull/39). Restoring some version of that code could be beneficial. It used the dioxus-ssr renderer to render some rsx to HTML and then display it in a sidebar.

Previewing individual reactive components would be a more difficult next step. We would need a way to inject into the context API when some value is not found and some way to call a private component in an application from the VSCode extension.

I have been working on an equivalent of MDX for the Dioxus Doc site. It is included in https://github.com/DioxusLabs/include_mdbook/pull/1

**Comment by itsezc** [comment]
> [At one point, rsx preview was implemented in the Dioxus VSCode extension](https://github.com/DioxusLabs/cli/pull/39). Restoring some version of that code could be beneficial. It used the dioxus-ssr renderer to render some rsx to HTML and then display it in a sidebar.
> 
> Previewing individual reactive components would be a more difficult next step. We would need a way to inject into the context API when some value is not found and some way to call a private component in an application from the VSCode extension.
> 
> I have been working on an equivalent of MDX for the Dioxus Doc site. It is included in [DioxusLabs/include_mdbook#1](https://github.com/DioxusLabs/include_mdbook/pull/1)

This would be a great addition for the DX side of things.

However, it may still be beneficial to look to integrate with Storybook or perhaps make an alternative. Part of the experience with building tooling for design systems is so that it can be shared with wider stakeholders in the project.

**Comment by itsezc** [comment]
An external library that solves a large scope of this issue: https://github.com/matthunz/lookbook

I'd still be interested in MDX but for Dioxus, as it'll come in very handy where you might want to show case components, and let the user interact with its props.
