### ISSUE TITLE
Extensible Element & EventHandler generics

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/dioxus#1179]
## Specific Demand

For people building design systems, it's useful to allow users to pass event handlers and other relevant attributes on to your components for instance a `button` might have an `onClick`, `disabled`, `onMouseover` among many other events, which are different for every type of element. This is very important for the DX of both end users and design system engineers alike.

Users of components with such generic, should be able to pass any event that extends the elements possible event types. This functionality could also be extended onto Blitz (down the line), allowing for a feature parity with the web platform.

## Implement Suggestion

Dioxus should provide an abstraction to easily allow one or multiple EventHandlers onto the underlying component easily, this maybe through providing EventHandlers per element type i.e. `use dioxus::elements::ButtonAttributes`.

React is an amazing example to look at when implementing this to Dioxus, a good example:

```ts
import React from 'react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  title: string;
  showIcon: boolean;
}

const Button: React.FC<ButtonProps> = ({ title, showIcon, ...props }) => {
  return (
    <button {...props}>
      {title}
      {showIcon && <Icon/>}
    </button>
  );
};
```

**Comment by Demonthos** [comment]
Thinking about this some more. I don't think my original proposal will work because the macro cannot know what functions it will need to implement for DivExtension. Instead we can do this:

In the HTML, crate we define:
```rust
trait DivExtension {
    fn width(&mut self, value: &str);
    // ...
}

trait ExtendsDivMarker {}

impl<T> DivExtension for T where T: HasAttributesMut + ExtendsDivMarker {
   // ...
}
```

The props macro outputs
```rust
#[derive(Props)]
struct MyProps {
   #[extends(div)]
   attributes: Vec<Attribute<'a>>
}

impl HasAttributesMut for MyProps {
    fn attributes_mut(&mut self) -> &mut Vec<Attribute<'a>> {
        &mut self.attributes
    }
}

impl ExtendsDivMarker for MyProps {}
```
