### ISSUE TITLE
Static Site Generation

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/dioxus#1183]
## Specific Demand

Theres very little talk and documentation about SSGs, while maybe less popular these days due to SSR, its still a very useful concept where landing / marketing sites are concnered.

This would only concern the Web platform, and maybe PWAs.

## Implement Suggestion

Supporting this as part of the Dixous CLI and Tokamak - having different render strategies based on layouts / routes similar to how JS frameworks approach this feature.

**Comment by Demonthos** [comment]
#1020 adds static (and incremental) site generation with hydration. [Here is an example](https://github.com/Demonthos/dioxus/blob/router-typesafe/packages/fullstack/examples/static-hydrated/src/main.rs). https://github.com/DioxusLabs/docsite/pull/67 adds documentation about static site generation

**Comment by Demonthos** [comment]
#1020 has been merged, you can now do static site generation easily!
