### ISSUE TITLE
Option usage triggers error "This is an usual custom case for dynamic nodes. We don't know how to handle it yet."

### ISSUE THREAD

**Issue by feral-dot-io** [DioxusLabs/dioxus#1185]
**Problem**

I'm displaying a dynamic Option in rsx covered by a use_state bool. When the state changes, it triggers a todo! block and panics with error "This is an usual custom case for dynamic nodes. We don't know how to handle it yet."

https://github.com/DioxusLabs/dioxus/blob/970c43702ecd6dbcb8ee858472afd17898b8724f/packages/core/src/diff.rs#L172C18-L172C111

**Steps To Reproduce**

Running the following with `dioxus serve` and press the "toggle me" checkbox to trigger a crash:

```
use dioxus::prelude::*;

fn under_test(cx: Scope) -> Element {
    let toggle = use_state(cx, || false);
    let val = if *toggle.get() {
        Some("Hello world")
    } else {
        None
    };
    cx.render(rsx! {
        label {
            input {
                r#type: "checkbox",
                checked: *toggle.get(),
                oninput: move |evt| toggle.set(evt.value != "false")
            }
            "Toggle me"
        }
        p { val }
    })
}

fn main() {
    wasm_logger::init(wasm_logger::Config::new(log::Level::Info));
    dioxus_web::launch(under_test);
}
```

**Expected behavior**

Checkbox should be toggled and "Hello world" displayed below it.

**Environment:**
 - Dioxus version: 0.3.2 and master
 - Rust version: rustc 1.70.0 (90c541806 2023-05-31)
 - OS info: Linux / NixOS
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by valyagolev** [comment]
Similar repros here, one of them doesn't involve (an explicit) Option: https://github.com/valyagolev/dioxus-bug/blob/master/src/app.rs

**Comment by ealmloff** [comment]
Unterminated if statements will automatically get turned into an option:

```rust
if *m.get() {
    " why"
}
```
Turns into:
```rust
if *m.get() {
    Some(" why")
}
else {
    None
}
```

**Comment by ealmloff** [comment]
Updated reproduction for the main branch of dioxus:
```rust
use dioxus::prelude::*;

fn main() {
    launch(app);
}

fn app() -> Element {
    let mut toggle = use_signal(|| false);
    let val = if toggle() { Some("Hello world") } else { None };
    rsx! {
        label {
            input {
                r#type: "checkbox",
                checked: toggle(),
                oninput: move |evt| toggle.set(evt.value() != "false")
            }
            "Toggle me"
        }
        p { {val} }
    }
}
```

**Comment by ealmloff** [comment]
https://github.com/DioxusLabs/dioxus/pull/2799 handles the general case of this and we now fuzz swapping out dynamic nodes
