### ISSUE TITLE
Make `UserWindowEvent` public?

### ISSUE THREAD

**Issue by terhechte** [DioxusLabs/dioxus#1186]
I need a way for the JS in a `dioxus_desktop` app to communicate at random times back to the Rust host. I'm currently doing that via:

``` js
const msg =
    JSON.stringify({
        "method": "user_event",
        "params": {
            "name": "action",
            "data": id,
            "bubbles": true,
        }
    });
window.ipc.postMessage(
    msg
);
```

And then on the Rust side I'm using the `use_wry_event_handler` to catch the event and act accordingly. However, I can't access the fields on the event itself because the `UserWindowEvent` is not exported in `dioxus_desktop/lib.rs`. Is there a reason for it being not exported? Otherwise I'd love to open a PR to export it via a `pub use desktop_context::UserWindowEvent`

**Comment by terhechte** [comment]
Ok I took a stab at implementing this and I realise it doesn't make any sense because it exposes too many internals.

However, the idea of accessing custom messages from the JS world / runtime could be implemented via a single public method on the `UserWindowEvent` type:

``` rs
impl UserWindowEvent {
    pub fn custom_data(&self, method: &str) -> Option<serde_json::Value> {
        match self.0 {
            EventData::Ipc(ref ipc) => {
                if ipc.method() == method {
                    Some(ipc.params_ref().clone())
                } else {
                    None
                }
            }
            _ => None,
        }
    }
}
```

Or to introduce a completely new type.

**Comment by Demonthos** [comment]
For injecting events specifically, we could expose a DesktopContext.inject_event method (for testing).


More broadly I see two approaches to exposing a way to communicate with the webview in the future:

- https://github.com/DioxusLabs/dioxus/pull/1080 makes passing messages from javascript to rust easier more generally using channels. This should work on all platforms.

- Specifically, for desktop, I would love to expose a use_wry_protocal_handler hook that works similarly to [the wry function](https://docs.rs/wry/latest/wry/webview/struct.WebViewBuilder.html#method.with_custom_protoco). It would allow you to efficiently send binary data from rust to the webview. This would allow very efficient communication with javascript and make passing things like dynamically generated images/videos to the webview much faster.

**Comment by wooden-worm** [comment]
I need this, my use case is I have a portion of a screen fetched from a server, and in that portion I have some buttons that need to trigger actions on the Rust side.

```rust
let future = use_future(&cx, (), |_| async move {
    // fetch from server
    raw_html
});

cx.render(match future.value() {
    Some(Ok(raw_html)) => rsx! {
        rsx!{
            div {
                dangerous_inner_html: "{raw_html}",
            }
        }
    },
    Some(Err(_)) => rsx! { div { "Loading  failed" } },
    None => rsx! { div { "Loading dogs..." } },
})
```

The `raw_html` value: 
```html
<div>
  <button onclick="sendMsgToRust()">
      Do Something
  </button>
</div>
```

@ealmloff is `DesktopContext.inject_event` still the best way to implement this? What would `sendMsgToRust` look like in that case?
I can work on a PR for this feature.

**Comment by ealmloff** [comment]
We should expose `UserWindowEvent`. It is an internal implementation detail. https://github.com/DioxusLabs/dioxus/pull/1719 and https://github.com/DioxusLabs/dioxus/pull/1080 address sending messages from JS to your rust code

**Comment by ealmloff** [comment]
@wooden-worm 

If your HTML needs to be interactive, you should try to write it in rsx. You can send data from your server and construct rsx from that data that can have dioxus event handlers attached to it

If you need to inject interactive HTML from your server then you could try one of these approaches:
1) You can send a request from the JS and handle it in rust with a [dynamic request handler](https://github.com/DioxusLabs/dioxus/blob/master/examples/dynamic_asset.rs#L9-L18)
2) You can create your own global function attached to the window that you call from the html from an [eval](https://github.com/DioxusLabs/dioxus/blob/master/examples/eval.rs).

**Comment by wooden-worm** [comment]
I tried the `eval` approach but it doesn't seem to work

```rust
let create_eval = use_eval(cx);
    let mut eval = create_eval(
        r#"
        window.dioxus = dioxus;
        "#,
    )
    .unwrap();

    let future = use_future(cx, (), |_| {
        to_owned![eval];
        async move {
            // You can receive any message from JavaScript with the recv method
            loop {
                let msg = eval.recv().await.unwrap();
                debug!(?msg, "got new message");
            }
        }
    });
```

Sending messages via `dioxus.send()`, but the receiving end did not work.

I think the cleanest solution is to allow sending user defined messages through `window.ipc`. This only requires a public method on `EventData`
```rust
impl EventData {
    pub fn get_user_defined_ipc_message(&self) -> Option<&serde_json::Value> {
        let EventData::Ipc(ipc) = self else {
            return None;
        };

        if ipc.method != "user_defined" {
            return None;
        }

        return Some(&ipc.params);
    }
}

// Handing

let handler = use_wry_event_handler(&cx, |event, target_window| {
        let dioxus_desktop::tao::event::Event::UserEvent(val) = event else {
            return;
        };
        let x = &val.0;
        let Some(user_data) = x.get_user_defined_ipc_message() else {
            return;
        };
        // Handle user_data
    });

// JS side
 let msg = {
        "method": "user_defined",
        "params": {
            ...
        }
    };
    window.ipc.postMessage(JSON.stringify(msg));
```

**Comment by ealmloff** [comment]
> I tried the `eval` approach but it doesn't seem to work
> 
> ```rust
> let create_eval = use_eval(cx);
>     let mut eval = create_eval(
>         r#"
>         window.dioxus = dioxus;
>         "#,
>     )
>     .unwrap();
> 
>     let future = use_future(cx, (), |_| {
>         to_owned![eval];
>         async move {
>             // You can receive any message from JavaScript with the recv method
>             loop {
>                 let msg = eval.recv().await.unwrap();
>                 debug!(?msg, "got new message");
>             }
>         }
>     });
> ```
> 
> Sending messages via `dioxus.send()`, but the receiving end did not work.

You are recreating the eval every rerender. After the first render, `window.dioxus` will be assigned to a completely different channel from the one the future is reading

This version seems to work:
```rust
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    let mut count = use_state(cx, || 0);

    let future = use_future(cx, (), |_| {
        let mut eval = eval(
            r#"
                window.dioxus = dioxus;
            "#,
        )
        .unwrap();
        async move {
            // You can receive any message from JavaScript with the recv method
            loop {
                let msg = eval.recv().await.unwrap();
                panic!("got new message");
            }
        }
    });

    cx.render(rsx! {
        button { onclick: |_| {eval("window.dioxus.send(123)");}, "Button" }
    })
}
```

**Comment by wooden-worm** [comment]
Thank @ealmloff that works 👍
