### ISSUE TITLE
Create a lint for the rules of hooks

### ISSUE THREAD

**Issue by Demonthos** [DioxusLabs/dioxus#1202]
## Specific Demand

It would be nice if the Dioxus CLI could report when the [rules of hooks](https://dioxuslabs.com/docs/0.3/guide/en/interactivity/hooks.html) are not being followed. Eventually we could expand this to lint other [antipaterns](https://dioxuslabs.com/docs/0.3/guide/en/best_practices/antipatterns.html) like using an index as an iterator key.

## Implement Suggestion

Eventually adopting some of the tooling from the [Clippy tool](https://github.com/rust-lang/rust-clippy) would be helpful to add lints.

For the initial implementation we can use [syn](https://docs.rs/syn/latest/syn/) to search for any functions that start with `use_` that are being used within a if statement of loop. (Specifically the [Visit](https://docs.rs/syn/latest/syn/visit/trait.Visit.html) trait could be useful here).

That will only allow us to detect issues with the current crate, but that is ok for a MVP.

We could run linting before the build and serve commands and also add a new `dioxus check` command that just runs the linting.

**Comment by eventualbuddha** [comment]
I plan to try implementing this.
