### ISSUE TITLE
Can't add external CSS on diodes_web

### ISSUE THREAD

**Issue by Utshaan** [DioxusLabs/dioxus#1207]
**Problem**

Cannot add an external CSS file and use it with the launch_cfg() function.
Didn't find a method to do so in docs.

**Environment:**
 - Dioxus version: [v0.3.2, `master`]
 - Rust version: [1.71.0, `stable`]
 - OS info: [`MacOS`]
 - App platform: [`web`]

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
You can add styles in your Dioxus.toml file. [Here is an example](https://github.com/DioxusLabs/dioxus/blob/master/examples/tailwind/Dioxus.toml#L33)
