### ISSUE TITLE
Broken link re: dioxus cli plugins

### ISSUE THREAD

**Issue by karamvirsingh98** [DioxusLabs/dioxus#1214]
## Specific Demand

Found a broken link in the cli readme for further docs regarding plugins [Dioxus CLI Document (https://dioxuslabs.com/cli/configure.html). Was hoping to create a plugin using the standalone tailwind cli that ties into dioxus' hot realod, I often forget to start the cli in watch mode while running the dev server, which can get a bit annoying. 

## Implement Suggestion

Would be grateful for any more info about plugins, happy to help get any outdated docs back up to speed in the process

**Comment by Demonthos** [comment]
The docs now live at https://github.com/DioxusLabs/dioxus/tree/master/packages/cli/docs/src/plugin, soon they will be moving to the main dioxus website (https://github.com/DioxusLabs/docsite/pull/67).

The plugin system was reworked in https://github.com/DioxusLabs/docsite/pull/67, but it needs to be moved over to the new location in the main Dioxus repo. I think as part of that PR a tailwind plugin was implemented

**Comment by karamvirsingh98** [comment]
Awesome, thank you!

**Comment by ealmloff** [comment]
The plugin docs are now removed until the plugin system is finished
