### ISSUE TITLE
Compilation for desktop stuck at enumset crate.

### ISSUE THREAD

**Issue by Wehzie** [DioxusLabs/dioxus#1227]
**Problem**

During compile for desktop, the compiler appears stuck during the compilation of enumset.
The activity indicator keeps spinning, but no progress appears to be made.
This is also when compiling with `dioxus build --versbose`

Compilation appears stuck here.
`Compiling enumset 1.1.2 (registry+https://github.com/rust-lang/crates.io-index)`

**Steps To Reproduce**

- Set up default example as described at https://dioxuslabs.com/docs/0.3/guide/en/getting_started/desktop.html
- Run `dioxus build --verbose`
- -> Compilation doesn't progress after some point.

**Expected behavior**

Compilation should complete.

**Screenshots**

Not applicable.

**Environment:**
 - Dioxus version: 0.3.2
 - Rust version: 1.71.0
 - OS info: Ubuntu 23.04
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ x ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
By default `dioxus build` targets the web platform. You can use cargo directly for simple builds:
```sh
cargo run
```

**Comment by Demonthos** [comment]
Feel free to reopen this issue if that doesn't solve your problem.

**Comment by Wehzie** [comment]
Thank you, `cargo run` works.

As a side node for Ubuntu users, VSCode, installed via snap, sets the `GTK_PATH` environment variable to a path that leads `cargo run` to compile but not run. Execution via regular terminal fixed this.

Other methods are proposed below.
- https://robotics.stackexchange.com/questions/24627/symbol-lookup-error-snap-core20-current-lib-x86-64-linux-gnu-libpthread-so-0
- https://stackoverflow.com/questions/75921414/java-symbol-lookup-error-snap-core20-current-lib-x86-64-linux-gnu-libpthread
- https://github.com/ros2/ros2/issues/1406
