### ISSUE TITLE
Router: Active class if target's URL is within current URL

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/dioxus#1241]
## Specific Demand

Add the ability to let the user tell the `Link` prop to provide the `active_class` prop if the target's URL is within the current URL.

E.g, if the current URL is either `/listings` or `/listings/random/url/:something`, a `Link` component of the following, will provide the `active_class`:
```rs
Link {
    active_within_route: true, // Probably a better name than this
    active_class: "active",
    target: Route::MyTarget {}
    "my link text"
}
```

**Note:**
I imagine this is already possible with one of the router's hooks, however... I'm lazy.

## Implement Suggestion

Add a new prop to the ``Link`` component that determines whether it should follow the proposed behavior.

**Comment by Demonthos** [comment]
Instead of a new prop how about a `route.is_descendant_of(other_route)` function?

Link {
    active_within_route: true, // Probably a better name than this
    active_class: "active",
    target: Route::MyTarget {}
    "my link text"
}

**Comment by DogeDark** [comment]
> Instead of a new prop how about a `route.is_descendant_of(other_route)` function?

I would like to avoid manual formatting but this sounds like a good compromise 👍

**Comment by tirithen** [comment]
In case anyone else wants a usage example for `is_child_of` I added one in this discussion thread https://github.com/DioxusLabs/dioxus/discussions/1946#discussioncomment-8490957
