### ISSUE TITLE
Can't get hot-reload to work with wierd error

### ISSUE THREAD

**Issue by tonyalaribe** [DioxusLabs/dioxus#1243]
**Problem**

using the hot_reload_init macro results in an error making me add different imports which don't change anything. 

my main looks like:
```rust

#[tokio::main]
async fn main() {
    dioxus::prelude::hot_reload_init!();
    dioxus_desktop::launch(app);
    ..

}

```

```rust
error[E0433]: failed to resolve: use of undeclared crate or module `dioxus_hot_reload`
  --> src/main.rs:15:5
   |
15 |     dioxus::prelude::hot_reload_init!();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `dioxus_hot_reload`
   |
   = note: this error originates in the macro `dioxus::prelude::hot_reload_init` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
   |
3  + use dioxus_desktop::Config;
   |
3  + use dioxus_web::Config;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `dioxus_hot_reload`
  --> src/main.rs:15:5
   |
15 |     dioxus::prelude::hot_reload_init!();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `dioxus_hot_reload`
   |
   = note: this error originates in the macro `dioxus::prelude::hot_reload_init` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
```

**Steps To Reproduce**

- follow the docks and use the hot_reload_init!() macro.

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version: `master`
 - Rust version: `nightly`
 - OS info: MacOS
 - App platform:  `desktop`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
On the git version of Dioxus, the hot reload macro is no longer needed (since #1210).

You can now just run:
```rust
dioxus serve --platform desktop
```

**Comment by tonyalaribe** [comment]
Without the macro, the hot reloading isn't working either.
The nothing happens in the app irrespective of what changes I make, and nothing is logged by the dioxus cli either.

<img width="769" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/6564482/bb8c79e2-985d-47dd-a3c3-525c38586269">

**Comment by Demonthos** [comment]
You also need the latest version of the CLI installed with:
```sh
cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
```

**Comment by tonyalaribe** [comment]
Oh, that worked! Thanks!! I'll close this now.
