### ISSUE TITLE
`EventHandler` default trait

### ISSUE THREAD

**Issue by mrxiaozhuox** [DioxusLabs/dioxus#125]
I think the `EventHandler` must have a `Default` tarit, because I think its optional.

**Comment by jkelleyrtp** [comment]
> I think the `EventHandler` must have a `Default` tarit, because I think its optional.

Yep - you're right.

Today you can just wrap value in an `Option` and use the props attributes to get an optional handler

```rust
struct ButtonProps<'a> {
  #[props(default, strip_option] // which together will become #[optional] in an upcoming PR
  onclick: Option<EventHandler<'a, MouseEvent>>
}

fn Button(cx: Scope<ButtonProps>) -> Element {
  cx.render(rsx!{
    button {
      onclick: move |evt| if let Some(handler) = cx.props.onclick { handler.call(evt) },
      "click me"
    }
  })
}
```

But yes - I think it would make sense to provide a default implementation for handler so you don't need to wrap it an option.
