### ISSUE TITLE
meta http_equiv instead of http-equiv

### ISSUE THREAD

**Issue by paul2t** [DioxusLabs/dioxus#1268]
When rendering this:
`meta { http_equiv: "X-UA-Compatible", content: "IE=edge" }`
We get this in html: `<meta http_equiv="X-UA-Compatible" content="IE=edge">`
It should be `http-equiv` instead of `http_equiv`.

**Steps To Reproduce**

Create a component with this code:
`cx.render(rsx!(meta { http_equiv: "X-UA-Compatible", content: "IE=edge" }))`

Expecting `http-equiv` instead of `http_equiv`.

https://www.w3schools.com/tags/att_meta_http_equiv.asp

**Environment:**
 - Dioxus version: v0.3.2 (also using dioxus-ssr v0.3.0)
 - Rust version: 1.71.0 `stable`
 - OS info: `Windows`
 - App platform: `web`

**Comment by Demonthos** [comment]
To fix this issue, we need to change [this line](https://github.com/DioxusLabs/dioxus/blob/master/packages/html/src/elements.rs#L335) to output "http-equiv" instead of DEFAULT. ([example of renaming the output](https://github.com/DioxusLabs/dioxus/blob/master/packages/html/src/elements.rs#L855))

**Comment by ChrisCA** [comment]
When creating the fix for that issue, the code looks like its been generated, if I'm not mistaken.
I'm curious, Is there a mechanism to ensure, that if the generating process is updated, this fix doesn't get overwritten?
In example a place we we would test the http_equiv against actually generating the http-equiv output?

**Comment by Demonthos** [comment]
> When creating the fix for that issue, the code looks like its been generated, if I'm not mistaken. I'm curious, Is there a mechanism to ensure, that if the generating process is updated, this fix doesn't get overwritten? In example a place we we would test the http_equiv against actually generating the http-equiv output?

The code is not auto generated, just built up over time and copied from various sources
