### ISSUE TITLE
Bring pointer event data to parity with mouse event data

### ISSUE THREAD

**Issue by esimkowitz** [DioxusLabs/dioxus#1269]
## Specific Demand

The pointer events such as onpointerdown, etc. propagate the separate PointerData struct, which is missing the helper functions that MouseData has. To better support cross-platform applications and sites, PointerData should be updated with the same impls as MouseData for things like getting the pointer coordinates in reference to different spaces.

## Implement Suggestion

Create a common trait for both PointerData and MouseData that exposes their common values and holds the implementation logic for the helper functions.

**Comment by esimkowitz** [comment]
I am willing to take on this work. Here's my more-flushed-out proposal:

It seems to me like this is a good opportunity to fully retire the deprecated public fields in the MouseData struct and move them to a new private struct containing the common fields for both PointerData and MouseData. Then we can provide the common functions like *coordinates, modifiers, etc. via a common impl. We can then more easily convert to the common struct to access the common functions. 

The web_sys event binding is a little less clear to me. I am still fairly new to Rust so maybe there's a clean way to share the code for the From impls PointerEvent and MouseEvent to the Data structs but it wasn't obvious to me.

**Comment by Demonthos** [comment]
> I am willing to take on this work. Here's my more-flushed-out proposal:
> 
> It seems to me like this is a good opportunity to fully retire the deprecated public fields in the MouseData struct and move them to a new private struct containing the common fields for both PointerData and MouseData. Then we can provide the common functions like *coordinates, modifiers, etc. via a common impl. We can then more easily convert to the common struct to access the common functions.

This sounds great! I would like to make more of the fields of events private to help transition to a trait based model with https://github.com/DioxusLabs/dioxus/issues/93.

We could event extract the common functions between the PointerData and MouseData structs into a `PointInteration` trait to allow a function to take either struct.

> The web_sys event binding is a little less clear to me. I am still fairly new to Rust so maybe there's a clean way to share the code for the From impls PointerEvent and MouseEvent to the Data structs but it wasn't obvious to me.

I don't think there is any way to share the From impls... Just duplicating those two is fine

**Comment by esimkowitz** [comment]
One thing that's proving a bit tricky is dealing with the transport layer between the native event and the dioxus event. I can just simply move all the public fields into the private struct, use serde(flatten) to expose them to the event data struct at the same level and leave it at that, but I've been trying to use the MouseButton, Modifiers, etc. types instead to avoid needing to perform conversions back and forth to these types when setting and reading fields. Do you think it's worth doing this and writing custom serde logic to handle the conversions to the native events or sticking with the existing fields and eating the conversion at read/write time?

**Comment by esimkowitz** [comment]
Or I could modify the interpreter as well so that it writes events in the new structs too

**Comment by esimkowitz** [comment]
Closing as completed with v0.5 and the revamped events system :)
