### ISSUE TITLE
dioxus-cli: configure cmdline options for served app

### ISSUE THREAD

**Issue by shenek** [DioxusLabs/dioxus#1271]
## Specific Demand

Imagine a situation when there is an app which will print help when called without arguments
```
./my-cmd
Usage: my-cmd [COMMAND]

Commands:
  tui         start tui
  ...
```

Serving such app will cause that this help message is shown while serving the app.
```
dx --bin my-cmd serve --hot-reload --platform desktop
```

I'd like to have a way to pass arguments to the served app.

## Implement Suggestion

Extending `dioxus-cli` to pass extra cli params seems to be most intuitive way doing this and it would to similar to what `cargo run` does.
```
dx --bin my-cmd serve --hot-reload --platform desktop -- tui
```

**Comment by jkelleyrtp** [comment]
This has been merged! I forget the PR, but we did this.
