### ISSUE TITLE
Error in the example

### ISSUE THREAD

**Issue by dev-ardi** [DioxusLabs/dioxus#1279]
**Problem**

**Steps To Reproduce**
Using this example https://dioxuslabs.com/learn/0.4/getting_started/tui
I get this error:
```
error[E0308]: mismatched types
  --> src\main.rs:14:24
   |
14 |     dioxus_tui::launch(App);
   |     ------------------ ^^^ expected fn pointer, found fn item
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected fn pointer `for<'a> fn(&'a dioxus_core::scopes::Scoped<'a>) -> Option<dioxus_core::nodes::VNode<'a>>`
                 found fn item `for<'a> fn(&'a Scoped<'a>) -> Option<VNode<'a>> {App}`
   = note: when the arguments and return types match, functions can be coerced to function pointers
note: function defined here
  --> C:\Users\gonzalezo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dioxus-tui-0.4.0\src\lib.rs:18:8
   |
18 | pub fn launch(app: Component<()>) {
   |        ^^^^^^
```

**Environment:**
 - dioxus = "0.3.2"
 - dioxus-tui = "0.4.0"
 - Rust version: 1.70
 - OS info: Windows 10
 - App platform: terminal
 
**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
Are you using an existing dioxus project? You need to use `dioxus = "0.4"` with the latest TUI version. Running cargo `cargo add dioxus` on a blank project will add the latest (0.4) version. Running it on an existing project will not change anything

**Comment by dev-ardi** [comment]
Thanks, this solved it :) 
I don't know why I had the wrong dioxus version
