### ISSUE TITLE
Unified Asset Solution

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#1283]
## Specific Demand

Currently, different platforms manage assets in different ways. Dioxus desktop requires you to create a custom head, and dioxus web uses the dioxus.toml file. There is also a separate config section for bundling assets.

### Minimal

Move all asset configuration into the Dioxus.toml file. The Desktop/Mobile/Blitz renderers can include the file with a macro at compile time. All platforms read the file at runtime and include the assets in a platform specific way. We can also use this asset section for bundling purposes.

### Complete

We could create an asset macro that allows you to include an asset in your rust code. This would make including a library that uses assets automatically add those assets to your final bundle.

```rust
// Component library that uses tailwind
asset!("tailwind.css");
```

```rust
// This would pull in the tailwind.css file
use tailwind_components::Comp;
```

To collect the assets we would need to use either [LinkMe](https://github.com/dtolnay/linkme) or custom WASM sections like the [wasm-bindgen] macro. Both of these solutions would require some runtime like the dioxus-cli that knows how to collect that information from the final binary to determine what assets should be bundled

**Comment by Demonthos** [comment]
I'm working on this currently. It will be in a separate repo so that other frameworks can use it more easily and we can keep the version decoupled from the rest of this repository
