### ISSUE TITLE
The tailwind example doesn't work for multi-page web apps

### ISSUE THREAD

**Issue by swpecht** [DioxusLabs/dioxus#1292]
**Problem**

In the [tailwind example](https://dioxuslabs.com/learn/0.4/cookbook/tailwind), the style attribute is set as follows:
```
style = ["tailwind.css"]
```

This works fine for single page apps (index only), but will cause the style sheet to not be found for multi page apps.

Changing the style to the absolute path seems to fix the problem:

```
# Note the leading `/`
style = ["/tailwind.css"]
```

**Steps To Reproduce**

* Create a Dioxus app with multiple pages and a router.
* Navigate to the non-index page
* Refresh the page

**Expected behavior**

* Expect the tailwind styles to continue to apply

**Screenshots**

**Environment:**
 - Dioxus version: 0.4
 - Rust version: 1.71
 - OS info: Ubuntu
 - App platform: `web`

**Questionnaire**

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
If you are interested in fixing this issue, the source code you would need to change is [here](https://github.com/DioxusLabs/docsite/blob/master/docs-src/0.4/en/cookbook/tailwind.md?plain=1#L87) and [here](https://github.com/DioxusLabs/dioxus/blob/master/examples/tailwind/Dioxus.toml#L33)
