### ISSUE TITLE
prevent_default: "onsubmit" is not working

### ISSUE THREAD

**Issue by opensource-inemar-net** [DioxusLabs/dioxus#1297]
**Problem**

When adding the prevent_default trigger to an form the form is still evaluated

Adding prevent_default:"onclick" prevents the event

**Steps To Reproduce**

- Simple from program is attached
- 
- 

**Expected behavior**

The default behavior of the browser is suppressed

**Screenshots**

**Environment:**
 - Dioxus version: 0.4
 - Rust version: 1.71.9
 - OS info: Windows
 - App platform: web

**Questionnaire**

- [x ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solu
[form-example.zip](https://github.com/DioxusLabs/dioxus/files/12263216/form-example.zip)
tion
- [ ] I don't have time to fix this right now, but maybe later

**Comment by opensource-inemar-net** [comment]
According to code for forms the default is to prevent.

![image](https://github.com/DioxusLabs/dioxus/assets/65956766/8def2f22-a0fd-426b-8d0a-7b10f5805140)

Removing prevent_default from the form solves the problem.

The example code is wrong:
https://github.com/DioxusLabs/dioxus/blob/master/examples/login_form.rs

Issue/Feature was added with this commit

67a2d31f9cc941db6470d9f6c3da3a95aa4c8c79


Personally I think it is difficult to understand and breaks the logic.
But if you believe that this behavior make more sense then example and documentation should be fixed.

Waiting on your decision

**Comment by Demonthos** [comment]
If we were only targeting web renderers, I completely agree, but for desktop and native renderers redirecting does not make sense. One important thing to note is we only prevent the default redirect if the event listener is attached. For purely server side handled forms, if you don't attach a client side handler it should work like the default web behavior. (There was some more discussion in https://github.com/DioxusLabs/dioxus/pull/926)

We should fix the example
