### ISSUE TITLE
How to run exe without console window on windows

### ISSUE THREAD

**Issue by leoyoung07** [DioxusLabs/dioxus#1306]
on windows, how can I run a built exe file without console window
![image](https://github.com/DioxusLabs/dioxus/assets/8199708/29f56b9e-16f2-4181-8408-4d8a452d70d2)

**Comment by Demonthos** [comment]
You need to add `#![windows_subsystem = "windows"]` to the top of your project

For more details: https://github.com/DioxusLabs/dioxus/issues/603
