### ISSUE TITLE
Boolean attributes still showing even when set to false

### ISSUE THREAD

**Issue by ianpurton** [DioxusLabs/dioxus#1318]
**Problem**

Boolean attributes still showing https://dioxuslabs.com/learn/0.3/describing_ui/special_attributes.html#boolean-attributes

**Steps To Reproduce**

```rust
cx.render(rsx!(
        input {
            name: "name",
            required: false,
            readonly: "{false}",
            disabled: "false",
            "type": text"
        }
))
```

Produces

```html
<input  value="" name="name" required="false" disabled="false" readonly="false" type="text">
```

But the required, disabled, readonly attributes should not be there.

This used to work in 0.2

**Environment:**
 - Dioxus version: [v0.3 and 0.4]
 - Rust version: [e.g. 1.71.0]
 - OS info: [e.g. PopOs]
 - App platform: [e.g. `web`]

**Comment by Demonthos** [comment]
I did reproduce this issue in the SSR renderer

**Comment by ianpurton** [comment]
@Demonthos I noticed the PR is awaiting a review. Should I review it or someone from Dioxus?
