### ISSUE TITLE
cx.raw_text not working

### ISSUE THREAD

**Issue by ianpurton** [DioxusLabs/dioxus#1319]
**Problem**

```
cx.raw_text(format_args!("<!DOCTYPE html><html lang='en'>"))
```

This used to create a html element but since 0.4 it is somehow escaped.

**Steps To Reproduce**

As above

**Environment:**
 - Dioxus version: [e.g. v0.4, `master`]
 - Rust version: [e.g. 1.72.0, `nightly`]
 - OS info: [e.g. PopOs]
 - App platform: [e.g. `web`,]

**Comment by Demonthos** [comment]
Raw text is not for creating inner html text. It is just used to allocate a format_args string. In 0.3, dioxus ssr did not escape text nodes. In 0.4, escaping text nodes was added. If you would like to create some nodes around what dioxus ssr can currently render, you can use the format macro:

```rust
use dioxus::prelude::*;

fn main() {
    // Or we can render rsx! calls themselves
    let full_html = format!(
        "<!DOCTYPE html><html lang='en'>{}</html>",
        dioxus_ssr::render_lazy(rsx! {
            div {
                h1 { "Hello, world!" }
            }
        })
    );

    println!("{}", full_html);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx!(
        div {
            h1 { "Title" }
            p { "Body" }
        }
    ))
}
```
