### ISSUE TITLE
Pre-built Dioxus CLI binaries for GitHub Actions

### ISSUE THREAD

**Issue by esimkowitz** [DioxusLabs/dioxus#1331]
## Specific Demand

As the Dioxus CLI becomes a one-stop shop for development of Dioxus apps, it should also be the primary tool for automating CI/CD of Dioxus apps.

The default GitHub Actions agent does not have enough RAM to compile Dioxus CLI. I've managed to get it working by increasing the page file size of the agent, but it still takes over 30 minutes to build just the CLI. The GitHub Releases should include precompiled versions of the Dioxus CLI for x86 Linux, macOS, and Windows targets to support the default GitHub Actions agents. Dioxus should also publish a GitHub Action to wrap fetching of the latest Dioxus CLI binary from the releases feed.

### Quick and easy

As it seems like releases are a manual process currently, I think that a simple build script could work as a temporary solution. This would involve installing the necessary targets via RustUp and bundling and archiving the CLI for the targets, then they can be manually copied into the Release assets when creating it.

### More involved

I think the long-term goal should be to automate Release workflow so that when new tags are created, a GitHub Actions workflow is kicked off to run the building and bundling of the CLI. This could also be used to compile changelogs and publish releases to Crates.io. 

## Implementation Suggestion - Dioxus Action

This should be very straightforward and can copy the mechanisms used by this third-party [Trunk action](https://github.com/jetli/trunk-action). It just goes to the Trunk release feed and grabs the latest binary archive matching the target agent. The end setup would be the same regardless of the mechanism used to build and publish the CLI binaries.

**Comment by esimkowitz** [comment]
I'm happy to take this on

**Comment by Demonthos** [comment]
This would be great! Instead of creating our own way to install a prebuild version of a CLI, we can use `cargo-bininstal`? They already have an [action](https://github.com/taiki-e/install-action) setup to install rust CLI's in CI.

You can see the setup instructions for `cargo-bininstall` [here](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md)

**Comment by esimkowitz** [comment]
Agreed, this looks even better! I'll play around with this and see if I can integrate it into the existing CI
