### ISSUE TITLE
Resize Event

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#1346]
## Specific Demand

Dioxus should support a resize event similar to the web's [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/ResizeObserver).

## Implement Suggestion

```rust
render! {
    div {
        onresize: |evt| println!("{evt.size}")
    }
}
```

Each renderer will need to handle the event differently. We will need to change some of the event handling code that assumes every event name is a normal javascript event.

(Events are created in [this file](https://github.com/DioxusLabs/dioxus/blob/master/packages/interpreter/src/sledgehammer_bindings.rs#L221))

We will need to use [this macro](https://github.com/DioxusLabs/dioxus/blob/bdfb3b628578aea3290b43af018589a66e62e98f/packages/html/src/events.rs#L12) and create your [own event](https://github.com/DioxusLabs/dioxus/blob/bdfb3b628578aea3290b43af018589a66e62e98f/packages/html/src/events/drag.rs). Then you would need to handle [converting from web-sys](https://github.com/DioxusLabs/dioxus/blob/bdfb3b628578aea3290b43af018589a66e62e98f/packages/html/src/web_sys_bind/events.rs#L122)

We will need to create a special case for resize events that uses the JsResizeObserver to watch for changes instead of a normal listener. You could use the handler that the ListenerMap uses or create a new function that you get from wasm to inject raw events into the web renderer

**Comment by CyberDomovoy** [comment]
Hi, here is an example of how to setup a `ResizeObserver` so that it sends resize events to a Dioxus component.
```rust
#![allow(non_snake_case)]
use dioxus::prelude::*;
use wasm_bindgen::closure::Closure as JsClosure;
use wasm_bindgen::JsCast;
use js_sys::Array as JsArray;
use web_sys::Element as JsElement;
use web_sys::ResizeObserver as JsResizeObserver;
use web_sys::ResizeObserverEntry as JsResizeObserverEntry;

fn main() {
  dioxus_web::launch(App);
}

fn App(cx: Scope) -> Element {
  let size = use_ref(cx, ComponentSize::default);

  let on_resize = use_state(cx, || {
    to_owned![size];
    OnResize::new(move |new_size: ComponentSize| {
      size.set(new_size);
    })
  });

  render! {
    div {
      onmounted: |event| {
        on_resize.mount(event);
      },
      ul {
        li {
          "Generation: {cx.generation()}"
        },
        li {
          "Size: {size.read().width} x {size.read().height}"
        }
      }
    }
  }
}

struct ComponentSize {
  width: i64,
  height: i64
}

impl Default for ComponentSize {
  fn default() -> Self {
    Self {
      width: 0,
      height: 0
    }
  }
}

struct OnResize {
  // We keep ownership of that one so that it doesn't get dropped
  // when the constructor ends
  _js_closure: JsClosure<dyn FnMut(JsArray)>,
}

impl OnResize {
  fn new(mut callback: impl FnMut(ComponentSize) + 'static) -> Self {
    let _js_closure = JsClosure::<dyn FnMut(JsArray)>::new(
      move |entries: JsArray| {
        callback(Self::_get_size(entries));
      }
    );

    Self {
      _js_closure: _js_closure,
    }
  }

  fn mount(&self, event: Event<MountedData>) {
    let element = event.get_raw_element()
      .expect("Failed to get element")
      .downcast_ref::<JsElement>()
      .expect("Not a `JsElement`");

    JsResizeObserver::new(
      self._js_closure.as_ref().unchecked_ref()
    )
    .expect("Failed to create observer")
    .observe(element);
  }

  fn _get_size(entries: JsArray) -> ComponentSize {
    // TODO
    // We _can_ have several entries here (several elements observed).
    //
    // Using one observer for every element that setup a `onresize` event
    // _may_ save some memory and cpu time.
    //
    // Although it implies checking the obtained size in each entry
    // against the old one, and send the event only if changed.
    // But it seems there are many cases where an observer can trigger while
    // the element size hasn't actually changed.
    //
    // It also implies finding a way to tie the entry to the corresponding
    // Dioxus element.
    //
    // INVESTIGATE
    // https://drafts.csswg.org/resize-observer

    let entry = entries.at(0);
    let entry: JsResizeObserverEntry = entry
      .dyn_into()
      .expect(
        "Not a `JsResizeObserverEntry`"
      );
    let rect = entry.content_rect();

    ComponentSize {
      width: rect.width() as i64,
      height: rect.height() as i64
    }
  }
}
```

**Comment by matthunz** [comment]
Would hooks be a more ergonomic solution here? I'm working on adding a JS backend for `dioxus-desktop` in  https://github.com/dioxus-community/dioxus-resize-observer (which is modeled after similar React libraries) that I think could make it a solid cross-backend alternative
