### ISSUE TITLE
custom  component support

### ISSUE THREAD

**Issue by chensce** [DioxusLabs/dioxus#1359]
## Specific Demand

mix dioxus with vue

## Implement Suggestion
If dioxus can support custom component（element），then vue script can use the web component defined by dioxus

**Comment by Demonthos** [comment]
It would be great to get an example showing how to export your Dioxus component as a web component. You could use existing libraries like [webcomponent](https://lib.rs/crates/webcomponent) to register a web component, you will just need to create an adapter for dioxus

**Comment by chensce** [comment]
awesome！If there is an example project

**Comment by JJJHolscher** [comment]
I made custom elements work with dioxus in my [repo](https://github.com/JJJHolscher/jupyter-and-dioxus), but only if you have a _single_ custom element by dioxus, multiple elements will fail as you can see in the issue that just mentioned this one.

**Comment by ealmloff** [comment]
[dioxus-web-component](https://github.com/ilaborie/dioxus-web-component) seems like a really good community solution to exporting web components from dioxus

**Comment by lafleurdeboum** [comment]
Unfortunately, dioxus-web-component saw no update in the last two years, and is not compatible with dioxus 0.7 out of the box.

If I really needed to support that build target, I'd work with @JJJHolscher 's `LaunchInElement` trait.

I can offer my enthousiastic point of view on how web-components would be a killer feature for Dioxus on request anytime 😸
