### ISSUE TITLE
No hot reload --desktop

### ISSUE THREAD

**Issue by wilkinnovo** [DioxusLabs/dioxus#1377]
**Problem**
No hot reload --desktop. Targeting the web works.

**Steps To Reproduce**

Create a cargo project, add dioxus and dioxus-desktop.

run:  dx  serve --platform desktop --hot-reload

update app render >div > string

``` rust
#![allow(non_snake_case)]
// import the prelude to get access to the `rsx!` macro and the `Scope` and `Element` types
use dioxus::prelude::*;

fn main() {
    // launch the dioxus app in a webview
    dioxus_desktop::launch(App);
}

// define a component that renders a div with the text "Hello, world!"
fn App(cx: Scope) -> Element {
    cx.render(rsx! { div { "Hello, world!" } })
}
```

See terminal ERROR:
``` bash
[ERROR] I/O Error: The process cannot access the file because it is being used by another process. (os error 32)
```
**Expected behavior**

Expected "Hello, world!" to hot reload change on save after changing the string 

**Environment:**
 - Dioxus version: v0.4.0
 - Rust version: 1.71.1 (eb26296b5 2023-08-03)
 - OS info: Windows 11 pro
 - App platform: desktop

**Comment by Demonthos** [comment]
This looks like the same issue as https://github.com/DioxusLabs/dioxus/issues/1286. Closing this as a duplicate. You can follow that issue for updates 🙂
