### ISSUE TITLE
Web: How to pass custom html tags attributes to rsx

### ISSUE THREAD

**Issue by bishoyroufael** [DioxusLabs/dioxus#1385]
Hello, Is it possible to pass custom html attributes to rsx elements?
Consider a case where an external js library is used like `RequireJs`. I want the rsx equivilant for something like this:
```javascript
<script data-main="scripts/main" src="scripts/require.js"></script>
```

```rust
script {
    src: "scripts/require.js",
    ...?
}
```
I have looked around but didn't find a solution presented anywhere to such scenarios.

**Comment by Demonthos** [comment]
You can surround your attribute name in quotes to create a custom attribute ([documented here](https://dioxuslabs.com/learn/0.4/reference/rsx#custom-attributes)):
```
script {
    src: "scripts/require.js",
    "your-attribute": 1234
}
```
