### ISSUE TITLE
Dist/Build/Bundle misconception

### ISSUE THREAD

**Issue by TomaszWaszczyk** [DioxusLabs/dioxus#1387]
**Problem**

I would like to inquire about the logic behind the Dist/Bundle directories. Do they align with the intended structure?

![image](https://github.com/DioxusLabs/dioxus/assets/1605705/de79c9e5-b092-4e29-a9bb-1935216e9180)

Maybe I do not understand something, but for me `Dist` and `Bundle` are two **completely different** workflows and to show it explicitly could/should be stored in two different directories (same tree level, without nesting).

Just and idea and confusion about current state. If I am wrong, mea culpa and sorry.

**Comment by Demonthos** [comment]
I see the dist and bundle folder as similar. The dist directory is what you should publish to a server. The bundle directory is what you should publish for desktop/mobile builds. They should probably be at an equal level of nesting. I can see how debug builds that the CLI creates for development are more different from bundled builds.

We could create debug and release folders for each platform:
```
/dist
    /web
        /debug
        /release
    /desktop
        /debug
        /release
    /server
        /debug
        /release
```

**Comment by TomaszWaszczyk** [comment]
Firstly, thank you for the feedback. In my humble opinion, the `dist` structure directory you've presented is ideal and transparent for those who are building applications in Dioxus. It just makes sense and is easy to read and understand.

The current status is challenging to comprehend in terms of directory structure and their meanings.

**Comment by ranjanmangla1** [comment]
HI @ealmloff , can I work on this issue? If yes, am I allowed to directly send a pr or I should be assigned this issue first?

**Comment by ealmloff** [comment]
> HI @ealmloff , can I work on this issue? If yes, am I allowed to directly send a pr or I should be assigned this issue first?

Defiantly, we generally don't assign issues (although mentioning you are working on an issue is great!). Feel free to open a PR or a draft PR while you work on it

**Comment by jkelleyrtp** [comment]
Dist now goes to your target directory so the only "out dir" you should see in your top-level folder is "bundle".

**Comment by TomaszWaszczyk** [comment]
Thanks! ;-)
