### ISSUE TITLE
Passing struct as a prop leads to panic / allocation error

### ISSUE THREAD

**Issue by raffomania** [DioxusLabs/dioxus#1390]
**Problem**

The following example leads to a panic during runtime:

```rs
fn App(cx: Scope) -> Element {
    let song = Song {
        artist: "Artist".to_string(),
        title: "Title".to_string(),
    };
    debug!("{song:?}");

    render! {
        div { Child { song: &song } }
    }
}

#[derive(Debug)]
struct Song {
    artist: String,
    title: String,
}

#[inline_props]
fn Child<'a>(cx: Scope, song: &'a Song) -> Element {
    let Song { title, .. } = song;
    render! {"{title}"}
}
```

The error when running `dx serve`:
```
Dioxus @ v0.1.5 [18:41:54]


	> Profile : Debug
	> Hot Reload : Normal
	> Index Template : Default
	> URL Rewrite [index_on_404] : False

	> Build Time Use : 0 millis

[WARN] There were 1 warning messages during the build.
[DEBUG] dioxus_play - Song { artist: "Artist", title: "Title" }
thread 'main' panicked at 'encountered allocation error: Layout { size: 140728548278936, align: 1 (1 << 0) }', /home/rafael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bumpalo-3.13.0/src/alloc.rs:30:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] dioxus_core::any_props - Error while rendering component `Child`: Any { .. }
```

**Steps To Reproduce**

I've created a minimal reproduction repo that runs into the error on my machine:
```sh
git clone git@github.com:raffomania/dioxus-allocation-error-repro.git
cd dioxus-allocation-error-repro
dx serve
```

**Expected behavior**

I'm expecting the code not to crash, or not to compile if it does something wrong.

**Environment:**
 - Dioxus version: 0.4.0
 - Rust version: 1.71.1
 - OS info: Arch Linux
 - App platform: desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by raffomania** [comment]
Moving to an explicit prop struct with `#[derive(Props)]` doesn't fix the error.

**Comment by Demonthos** [comment]
This is the same issue as https://github.com/DioxusLabs/dioxus/issues/1341. https://github.com/DioxusLabs/dioxus/pull/1345 will fix this. Closing as duplicate
