### ISSUE TITLE
"This is an usual custom case for dynamic nodes. We don't know how to handle it yet."

### ISSUE THREAD

**Issue by FredrikNoren** [DioxusLabs/dioxus#1395]
**Problem**

**Steps To Reproduce**

If you have this

```rust
let state = use_state(cx, || Some("hi".to_string()));
cx.render(rsx!{
  if let Some(s) = &**state {
    "{s}"
  }
})
```

You get "This is an usual custom case for dynamic nodes. We don't know how to handle it yet."

It can be fixed by patching the above with an additional rsx!{}:

```rust
if let Some(s) = &**state {
    rsx!{ "{s}" }
}
```

**Expected behavior**

Original code should either error or work.

**Environment:**
 - Dioxus version: 0.4
 - Rust version: 1.72
 - OS info: MacOS
 - App platform: `web`

**Comment by ealmloff** [comment]
Thank you for the bug report. If statements will desugar into if /*condition*/ {/*body*/}else{None}. After you apply that transformation, this is the same issue as https://github.com/DioxusLabs/dioxus/issues/1185. See that issue for further updates
