### ISSUE TITLE
Polling future using state() and restart() calls stops after first future call

### ISSUE THREAD

**Issue by GTP95** [DioxusLabs/dioxus#1400]
**Problem**
Greetings,

I have to implement polling of a remote endpoint using an `async` call, if you're curious you can read the details [on Discord](https://discord.com/channels/899851952891002890/1143930250514931722).  
I tried implementing this using `use_future` and the related `state()` and `restart()` functions, but the application stops calling the async function after the first iteration.
 
**Steps To Reproduce**

I created a minimum reproducible example [here](https://github.com/GTP95/Dioxus-bug-MRE). If you run it and you look at the output on stdout, you can see that the application gets stuck in the `UseFutureState::Reloading(_)` branch.

**Expected behavior**

When the result of the async call is available, the component that makes the call (in this case the `App` component) gets re-rendered and this causes the contained `match`(s) statement(s) that use the returned value to be re-evaluated. Since the value returned from the call is less than the hardcoded value of the nested `if` statement, Dioxus should keep restarting the future and re-evaluating the future's result.

**Environment:**
 - dioxus version: [0.3.2]
 - dioxus-desktop version: [0.3.0]
 - Rust version: [`stable`]
 - OS info: [ArchLinux]
 - App platform: [`desktop`]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
We generally don't update old releases of Dioxus, so if this is working in 0.4 I will close the issue
