### ISSUE TITLE
dioxus-cli fails to install on windows 11

### ISSUE THREAD

**Issue by NicolasVIscool** [DioxusLabs/dioxus#1413]
**Problem**

We can't install dioxus-cli on windows 11.

**Steps To Reproduce**

run the command 
```bash
cargo install dioxus-cli
```
results in 
```bash
error[E0063]: missing field `desktop_template` in initializer of `tauri_bundler::DebianSettings`
   --> packages\cli\src\config.rs:381:9
    |
381 |         tauri_bundler::DebianSettings {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `desktop_template`
error[E0063]: missing fields `custom_language_files` and `template` in initializer of `tauri_bundler::NsisSettings`
   --> packages\cli\src\config.rs:517:9
    |
517 |         tauri_bundler::NsisSettings {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `custom_language_files` and `template`
```

**Expected behavior**

Installation success

**Environment:**
 - Dioxus version: 0.4.0 or 0.4.2 (github current)
 - Rust version: 1.71
 - OS info: Windows 11

**Workaround:**

Installing with --locked works (thanks @!marc on discord): 
```bash
cargo install dioxus-cli --locked
```

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by fanyang89** [comment]
Yet another fix for this: https://github.com/fanyang89/dioxus/commit/5b5ea2014f94d4e88db9200790e4e9ef3ff8352e

**Comment by ealmloff** [comment]
> Yet another fix for this: [fanyang89@5b5ea20](https://github.com/fanyang89/dioxus/commit/5b5ea2014f94d4e88db9200790e4e9ef3ff8352e)

We can merge both fixes. We need to pin the version because tauri doesn't follow semvar for tauri-bundle, but updating to the new version would be nice

**Comment by fanyang89** [comment]
> We can merge both fixes. We need to pin the version because tauri doesn't follow semvar for tauri-bundle, but updating to the new version would be nice

PR created #1416

**Comment by lebe-dev** [comment]
The same issue on the latest ArchLinux with rust 1.72.

**Comment by uxsoft** [comment]
Same issue on macOS

**Comment by ealmloff** [comment]
Diouxs 0.4.1 has now been published which fixes `cargo install dioxus-cli`
