### ISSUE TITLE
when refresh got 404

### ISSUE THREAD

**Issue by LitchiInn** [DioxusLabs/dioxus#1418]
**Problem**

**Steps To Reproduce**

- `dx create` to create a new project ,use router,tailwindcss,platform web
- `dx serve`
- click `Go to blog`, everything is well, but when i refresh(F5), i got 404

**Expected behavior**

 when i refresh(F5), i got 404

**Screenshots**

![before](https://i.imgur.com/spdBFOJ.png)
![after](https://i.imgur.com/XMHiGjL.png)

**Environment:**
 - Dioxus version: 0.4
 - Rust version: 1.72
 - OS info: WSL2
 - App platform: web

What should I do？

**Comment by ealmloff** [comment]
You need to set `index_on_404` to true to make the router work with `dx serve`:

```toml
[web.watcher]
index_on_404 = true
```
