### ISSUE TITLE
Autoformatter tries to format all macros

### ISSUE THREAD

**Issue by RubixDev** [DioxusLabs/dioxus#1419]
**Problem**

Instead of only touching `rsx!` and `render!` macros, the autoformatter tries to format _all_ macros. This causes issues with macros that use syntax different from the rsx macros.

**Steps To Reproduce**

```rust
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    let message = format!("Hello, {}!", "World");
    render!{
	message
	}
}
```

- `cargo new dioxus-broken-fmt-example`
- `cd dioxus-broken-fmt-example`
- `cargo add dioxus dioxus-web`
- copy the above code into `src/main.rs`
- `dx fmt`

**Expected behavior**

The file should be formatted to the following:

```rust
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    let message = format!("Hello, {}!", "World");
    render! {message}
}
```

**Actual Behaviour**

The `dx fmt` command panics:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("Expected Ident or Expression")', /home/deck/.local/share/cargo/registry/src/in
dex.crates.io-6f17d22bba15001f/dioxus-autofmt-0.4.0/src/lib.rs:71:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error formatting file: /home/deck/Downloads/dioxus-broken-fmt-example/src/main.rs
task 7 panicked
```

If you change the `format!` macro call to `format!("Hello, {0}!", "World")` so that it is acceptable rsx syntax, it is formatted to `format!( "Hello, {0}!", "World" )` (notice the added spaces). Dioxus should not change that macro call, and `cargo fmt` also reverts it to without the spaces.

**Environment:**
 - Dioxus version: v0.4.0
 - Rust version: `rustc 1.71.1 (eb26296b5 2023-08-03)`
 - OS info: Arch Linux
 - App platform: `web` (but should affect all platforms)

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [X] I don't have time to fix this right now, but maybe later

**Comment by srid** [comment]
e799c2efa2ad87603f90de623605cf8799a4f15a appears to be in tag 0.4.1, which is what I have:

```
❯ dx --version
dioxus 0.4.1
```

But I still get this error for the use of `println!` in https://github.com/srid/dioxus-desktop-template/pull/6/files#diff-87619baf236177a7a9fc38150961151b7583b6f2f082ade75915f3ac4ca49c41

<img width="437" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/3998/1ef7102a-c040-450a-8006-fd1f6016202d">

```
❯ find src -name \*.rs | xargs -n 1 dx fmt -f
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("Expected Ident or Expression")', /private/tmp/nix-build-dioxus-cli-0.4.1.drv-0/dioxus-cli-0.4.1-vendor.tar.gz/dioxus-autofmt/src/lib.rs:71:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
formatted src/main.rs
```

**Comment by ealmloff** [comment]
> [e799c2e](https://github.com/DioxusLabs/dioxus/commit/e799c2efa2ad87603f90de623605cf8799a4f15a) appears to be in tag 0.4.1, which is what I have:
> 
> ```
> ❯ dx --version
> dioxus 0.4.1
> ```
> 
> But I still get this error for the use of `println!` in https://github.com/srid/dioxus-desktop-template/pull/6/files#diff-87619baf236177a7a9fc38150961151b7583b6f2f082ade75915f3ac4ca49c41
> 
> <img alt="image" width="437" src="https://user-images.githubusercontent.com/3998/273057444-1ef7102a-c040-450a-8006-fd1f6016202d.png">
> ```
> ❯ find src -name \*.rs | xargs -n 1 dx fmt -f
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("Expected Ident or Expression")', /private/tmp/nix-build-dioxus-cli-0.4.1.drv-0/dioxus-cli-0.4.1-vendor.tar.gz/dioxus-autofmt/src/lib.rs:71:50
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> formatted src/main.rs
> ```

You can try installing the git version of the CLI with this command:
```sh
cargo install --git https://github.com/DioxusLabs/dioxus
```
