### ISSUE TITLE
Mark CLI library as private or unstable

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#1423]
**Problem**

Currently, the dioxus cli has a large public [API](https://docs.rs/dioxus-cli/0.4.0/dioxus_cli/). This makes it difficult to make large internal changes to the crate without breaking the library. Some of the API will need to be public for the plugin system, but that can be pulled out into a separate crate.

**Comment by jkelleyrtp** [comment]
we should just not have a lib.rs for the cli. 

I believe we had this for the extension but that has changed. We should just move lib.rs contents to main.rs such that the cli is no longer a library.

**Comment by ealmloff** [comment]
Fixed in #2698
