### ISSUE TITLE
WEB browser address  status is cleared

### ISSUE THREAD

**Issue by exten** [DioxusLabs/dioxus#1433]
**Problem**

When the browser address bar path is manually changed, the context state is fully initialized. My login status is cleared
from: http://127.0.0.1:8080/resource/ChangeInformation
to: http://127.0.0.1:8080/resource/HumanCooperation
**Steps To Reproduce**

```rust
pub fn App(cx: Scope) -> Element {
    // this code always exec...
    init_use_cool_data(cx);
    let is_sign = use_cool_data(cx).read().view(&1).cloned().unwrap();
    log::warn!("--- is_sign: {}", is_sign);
    match is_sign.as_str() {
        "FAIl_LOGIN" => render!(views::sign_in::SignIn {r_type: "".to_string()},),
        "SUCC_LOGIN" => {
            render! { Router::<Route> {
                 config: || RouterConfig::default().on_update(|state|{
                    (state.current() == Route::Home {}).then_some(
                        NavigationTarget::Internal(state.current())
                    )
                })
            }}
        },
        "TO_REGEDIT" => render!(views::sign_up::SignUp {r_type: "".to_string()},),
        _ => {None}
    }
}
```

**Expected behavior**

When you manually modify the browser address bar, the global state does not change. Otherwise, you will be redirected to the login page every time

**Screenshots**

**Environment:**
- Dioxus version: 0.4.0
- Rust version: 1.72
- OS info: Win10
- App platform: WEB MS Edge

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
If you manually enter a url, the browser will load the new page from scratch. This clears any state the application has in memory. If you would like to store data between page reloads, you can store some state in the browser's localstorage using [dioxus-storage](https://github.com/ealmloff/dioxus-storage) or cookies using [web-sys](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.HtmlDocument.html#method.set_cookie). This state will remain after you leave and return to a page
