### ISSUE TITLE
how to render pure html object ?

### ISSUE THREAD

**Issue by bingryan** [DioxusLabs/dioxus#144]
```
let rendered = "html object"


rsx!(cx,
    div { class: "prose lg:prose-xl",
            rendered
    })
```

but not work~

**Comment by jkelleyrtp** [comment]
use `dangerous_inner_html`

https://dioxuslabs.com/guide/elements/special_attributes.html#the-html-escape-hatch-dangerous_inner_html

**Comment by bingryan** [comment]
Thank you @jkelleyrtp , BTW,
