### ISSUE TITLE
CSS not behaving properly on Linux

### ISSUE THREAD

**Issue by DanielAlbl** [DioxusLabs/dioxus#1444]
**Problem**
I tried an example of a toggle switch from https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_switch in Dioxus. The background color of the switch is supposed to change when clicked but it doesn't. It does change however if you click anywhere in the window afterwards. This only seems to happen on linux (Ubuntu 22.04), and not on Windows or Mac OS, or in the browser using `dioxus_web`. 

**Steps To Reproduce**
Should be able to reproduce with the following code: https://github.com/DanielAlbl/slider-example. 

**Expected behavior**
Background of the toggle switch should turn blue when clicked, and then back to white when clicked again. 

**Screenshots**
After clicking toggle:
![toggle1](https://github.com/DioxusLabs/dioxus/assets/66034631/fd747cf8-d9a3-4926-9af1-9551ed4a31ab)
After clicking again in the window:
![toggle2](https://github.com/DioxusLabs/dioxus/assets/66034631/cba22050-e29a-4a9f-8eae-8d4e0f2c0014)

**Environment:**
 - Dioxus version: master
 - Rust version: 1.71.1
 - OS info: Ubuntu 22.04 LTS
 - App platform: desktop

I have seen other issues on ubuntu where the UI seems to not update until clicking in the window, this was just a concrete example. Maybe this is a lower level issue with tauri?

**Comment by ealmloff** [comment]
Dioxus (and tauri) just pass the style and HTML to the system browser. They don't control how CSS selectors are resolved or how elements are displayed
