### ISSUE TITLE
`#[inline_props]` macro fails when `use dioxus::core;` is present

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#1445]
**Problem**

The `#[inline_props]` macro fails when the `use dioxus::core;` import is present. Error message:
```
failed to resolve: could not find `default` in `core` [E0433]
Help: consider importing one of these items
Help: if you import `Default`, refer to it directly
```

I know this is very insignificant, as I don't think anybody would import `dioxus::core`, but I figured I would report it anyway.

**Steps To Reproduce**

- Add `use dioxus::core;` to your file.
- Create a component with an additional argument.
- Apply the `#[inline_props]` macro

**Expected behavior**

It should work as if there was no `dioxus::core` import.

**Environment:**
 - Dioxus version: `0.4.0`
 - Rust version: `1.73.0-nightly`
 - OS info: Windows 10
 - App platform: `web`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later
I'm working on a PR that improves the component macro system, so I'll try and fix this as well.

**Comment by ealmloff** [comment]
We should use `::crate::other_segments` instead of `crate::other_segments` in macros to fix this issue
