### ISSUE TITLE
Route based i18n

### ISSUE THREAD

**Issue by onichandame** [DioxusLabs/dioxus#1449]
## Specific Demand

I'd like to save the locale as part of the url in web app. For example: `/en/posts` for english localization, `/fr/posts` for french localization

## Implement Suggestion

#216 already presents a solution of i18n in SPA. #637 gives us the powerful router. I'd imagine combining those two will be the first workable solution.

**Comment by alexanderjophus** [comment]
I made a PR to update the docs for this
