### ISSUE TITLE
couldn't find a square icon to use as AppImage icon

### ISSUE THREAD

**Issue by jrouaix** [DioxusLabs/dioxus#1450]
Started a project and could not bundle the AppImage (but .deb is working)

Followed those steps : 
- https://dioxuslabs.com/learn/0.4/getting_started/desktop
Then
- https://dioxuslabs.com/learn/0.4/cookbook/publishing

```sh
cargo new --bin dioxus-example
cd dioxus-example
cargo add dioxus
cargo add dioxus-desktop
# then copy some hello world sample in main.rs
dx bundle --release
```

```sh
# ...
 release [optimized] target(s) in 44.10s
[INFO] 🚩 Build completed: [./dist]
build desktop done
[INFO] dioxus-example3_0.1.0_amd64.deb (..../dist/bundle/deb/dioxus-example_0.1.0_amd64.deb)
thread 'main' panicked at 'couldn't find a square icon to use as AppImage icon', .....cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-bundler-1.3.0/src/bundle/linux/appimage.rs:73:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Whould I tweak some tauri configuration ? If it's the case, how ?

**Comment by jrouaix** [comment]
Ok found : https://github.com/DioxusLabs/dioxus/blob/b7638f31a65f3d7f045acbe7fce86f43f584bd8e/packages/cli/src/config.rs#L337

this seems to work

```Dioxus.toml
[bundle]
icon = ["icons/icon.png"]
```

**Comment by dixtel** [comment]
@jrouaix Can you share the full config of Dioxus.toml and the **asset_dir** structure? The fix mentioned above worked for me but I encountered another error:
`Failed to bundle project: Failed to build data folders and files

**Comment by jrouaix** [comment]
```toml
asset_dir = "public"
```

```toml
resources = [
  "public/main.css",
  "other_dir/*",
]
```

Is that what you are looking for @dixtel ?

**Comment by dixtel** [comment]
@jrouaix Sorry I'm new to dioxus and I was using `dx bundle` instead of `dx build` to build the web app. Now it works like a charm. Anyway thanks for trying to help!
