### ISSUE TITLE
[docs] error: failed to run custom build command for `openssl-sys v0.9.92`

### ISSUE THREAD

**Issue by pierreprinetti** [DioxusLabs/dioxus#1455]
**Problem**

I couldn't install dioxus-cli

```shell
cargo install dioxus-cli --locked
```

Compiling failed right after `aho-corasick` with:
```plaintext
error: failed to run custom build command for `openssl-sys v0.9.92`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installHPSksA/release/build/openssl-sys-38e01451796cd7e4/build-script-main` (exit status: 101)
```

**Environment:**
 - Dioxus version: whatever is the latest release, I suppose
 - Rust version: 1.72.0
 - OS info: Fedora 38

**Solution**
Install Perl.

```shell
sudo dnf install perl
```

---

Maintainers: do you think this should go in the installation docs?

**Comment by ealmloff** [comment]
Yes, that would be great to add to the [installation docs of the CLI](https://github.com/DioxusLabs/docsite/blob/master/docs-src/0.4/en/CLI/installation.md)! (It looks like there is a more complete list of prerequisites [here](https://docs.rs/openssl/latest/openssl/#automatic)).

**Comment by tigerros** [comment]
Could someone close this? Fixed in https://github.com/DioxusLabs/docsite/pull/130
