### ISSUE TITLE
route fresh page error

### ISSUE THREAD

**Issue by ys2rice2yangsong** [DioxusLabs/dioxus#1457]
**Problem**

**Steps To Reproduce**

press F5 refresh: get result is error page
- 
- 
- 

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version: [e.g. v0.4.0, `master`]
 - Rust version: [e.g. 1.72.0, `nightly`]
 - OS info: [e.g. ubuntu]
 - App platform: [e.g. `web`, ]

**Questionnaire**

**Comment by ealmloff** [comment]
Can you provide more information about your project, the renderer you are using, and the version of dioxus you are using? The console output (accessed by right clicking and clicking inspect) could also contain some useful information. This isn't effecting all projects written with Dioxus (refreshing https://dioxuslabs.com/ works) so some more information to help track down this issue would be helpful.

**Comment by ys2rice2yangsong** [comment]
all   code:


#![allow(non_snake_case)]
use dioxus::prelude::*;
use dioxus_router::prelude::*;

fn main() {
	#[cfg(target_arch = "wasm32")]
	dioxus_web::launch(RouteApp);
}

fn App(cx: Scope) -> Element {
	render!(rsx! {
		div {
			"这是第一个组建"
		}
	})
}


fn RouteApp(cx: Scope) -> Element {
	render! {
		Router::<Route> {
            
        	}
	}
}

#[derive(Routable, Clone)]
#[rustfmt::skip]
enum Route {
	#[route("/")]
	Home {},
	#[nest("/main")]
		#[layout(Master)]
			#[route("/")]
			MainHome {},
			#[route("/:id")]
			Info { id: i32},
		#[end_layout]
	#[end_nest]
	#[route("/:..route")]
	PageNotFound {
		route: Vec<String>,
	},
}

fn Home(cx: Scope) -> Element {
	render! {
		div {
			span {
				class: "mr-2",
				"这是首页",
			}
			Link {
				to: "/main",
				"后台首页"
			},
			br {},
			Link {
				to: "/m",
				"测试没有这个页面如何显示"
			}
		}
	}
}

fn Master(cx: Scope) -> Element {
	render! {
		div {
			class: "bg-green-100",
			Link {
				class: "ml-2",
				to: "/",
				"首页"
			},
			br {},
			Link {
				to: "/main",
				"后台首页"
			},
			br {},
			Link {
				to: "/main/12",
				"用户信息"
			}
		}
		"这是后台主页布局"
		Outlet::<Route> {}
	}
}

fn MainHome(cx: Scope) -> Element {
	render! {
		div {
			"后台首页"
		}
	}
}

#[inline_props]
fn Info(cx: Scope, id: i32) -> Element {
	render! {
		"信息页面:{id}"
	}
}

#[inline_props]
fn PageNotFound(sc: Scope, route: Vec<String>) -> Element {
	sc.render(rsx! {
		div {
			"没有这个页面"
		}
	})
}

**Comment by ys2rice2yangsong** [comment]
first access:
![图片](https://github.com/DioxusLabs/dioxus/assets/57334741/fa9c7f33-08bc-48b9-96f5-981839d8ba43)

press F5:
![图片](https://github.com/DioxusLabs/dioxus/assets/57334741/56ab3699-6640-4ebc-8dbe-c952d23ee84c)

**Comment by ys2rice2yangsong** [comment]
code in VSCODE:


#![allow(non_snake_case)]
use dioxus::prelude::*;
use dioxus_router::prelude::*;

fn main() {
	#[cfg(target_arch = "wasm32")]
	dioxus_web::launch(RouteApp);
}

fn App(cx: Scope) -> Element {
	render!(rsx! {
		div {
			"这是第一个组建"
		}
	})
}


fn RouteApp(cx: Scope) -> Element {
	render! {
		Router::<Route> {
            
        	}
	}
}

#[derive(Routable, Clone)]
#[rustfmt::skip]
enum Route {
	#[route("/")]
	Home {},
	#[nest("/main")]
		#[layout(Master)]
			#[route("/")]
			MainHome {},
			#[route("/:id")]
			Info { id: i32},
		#[end_layout]
	#[end_nest]
	#[route("/:..route")]
	PageNotFound {
		route: Vec<String>,
	},
}

fn Home(cx: Scope) -> Element {
	render! {
		div {
			span {
				class: "mr-2",
				"这是首页",
			}
			Link {
				to: "/main",
				"后台首页"
			},
			br {},
			Link {
				to: "/m",
				"测试没有这个页面如何显示"
			}
		}
	}
}

fn Master(cx: Scope) -> Element {
	render! {
		div {
			class: "bg-green-100",
			Link {
				class: "ml-2",
				to: "/",
				"首页"
			},
			br {},
			Link {
				to: "/main",
				"后台首页"
			},
			br {},
			Link {
				to: "/main/12",
				"用户信息"
			}
		}
		"这是后台主页布局"
		Outlet::<Route> {}
	}
}

fn MainHome(cx: Scope) -> Element {
	render! {
		div {
			"后台首页"
		}
	}
}

#[inline_props]
fn Info(cx: Scope, id: i32) -> Element {
	render! {
		"信息页面:{id}"
	}
}

#[inline_props]
fn PageNotFound(sc: Scope, route: Vec<String>) -> Element {
	sc.render(rsx! {
		div {
			"没有这个页面"
		}
	})
}

**Comment by ys2rice2yangsong** [comment]
[dependencies]
dioxus = "0.4"
dioxus-router = "0.4.1"
dioxus-web = "0.4"
gloo = "0.10.0"
wasm-bindgen = "0.2.87"
wasm-logger = "0.2.0"

**Comment by ealmloff** [comment]
The code example you posted works correctly on Chrome (in mac):

https://github.com/DioxusLabs/dioxus/assets/66571940/222a6df1-b384-40d2-ba7d-c55b441719cb

What browser did you find this issue in?

**Comment by ys2rice2yangsong** [comment]
ubuntu22.04, edge,   google, firefox, They got the same result

**Comment by ealmloff** [comment]
> ubuntu22.04, edge, google, firefox, They got the same result

What error page do you get and how are you hosting the application?

I was using `dx serve` which seems to work correctly.

**Comment by ys2rice2yangsong** [comment]
![图片](https://github.com/DioxusLabs/dioxus/assets/57334741/8270edc7-e67b-4995-9f90-0e139e8f1a0c)

![图片](https://github.com/DioxusLabs/dioxus/assets/57334741/89140d04-502b-42b1-aeaa-8289a63334ff)
first access:
![图片](https://github.com/DioxusLabs/dioxus/assets/57334741/47fcf6d1-5547-4112-83db-2ee10acec918)
press F5:
![图片](https://github.com/DioxusLabs/dioxus/assets/57334741/094fda57-0059-45b6-adc6-af776288adbb)

**Comment by ys2rice2yangsong** [comment]
Is this issue caused by poor compatibility handling?

**Comment by ealmloff** [comment]
You need to add index_on_404 to your `Dioxus.toml`:
```toml
[web.watcher]

index_on_404 = true
```
