### ISSUE TITLE
After adding the configuration, all routes are inaccessible

### ISSUE THREAD

**Issue by ys2rice2yangsong** [DioxusLabs/dioxus#1469]
**Problem**

**Steps To Reproduce**

- According to the official document, after adding tailwindcss, all routes are inaccessible
- 
- 

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version: [e.g. v0.4.0, `master`]
 - Rust version: [e.g. 1.72.0, `nightly`]
 - OS info: [e.g. ubuntu]
 - App platform: [e.g. `web`]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ys2rice2yangsong** [comment]
my configure:


[application]

# App (Project) Name
name = "Tailwind CSS + Dioxus"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "dioxus | ⛺"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# uncomment line below if using Router
# index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["app.css"]

# Javascript code file
script = []

[web.resource.dev]

# serve: [dev-server] only

# CSS style file
style = []

# Javascript code file
script = []

**Comment by ys2rice2yangsong** [comment]
cargo.toml:

[dependencies]
dioxus = "0.4.0"
dioxus-router = "0.4.1"
dioxus-web = "0.4.0"
gloo = "0.10.0"

**Comment by ys2rice2yangsong** [comment]
Directory structure that can be accessed and refreshed normally
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/5f70e9e1-9f33-4536-8d7d-74a9965170dd)
Inaccessible directory structure
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/e57ec7a4-4305-4695-a597-13e84356532e)

**Comment by ys2rice2yangsong** [comment]
Configuration and directory structure of CSS
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/25c4091f-8e44-4c67-80f3-464b3164345e)

package.json:
{
  "name": "styles",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "NODE_ENV=production node_modules/.bin/postcss main.pcss -o ../public/app.css --watch"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "autoprefixer": "^10.4.15",
    "postcss": "^8.4.29",
    "postcss-cli": "^10.1.0",
    "tailwindcss": "^3.3.3"
  },
  "devDependencies": {
    "daisyui": "^3.7.3"
  }
}



tailwind.config.js:
module.exports = {
  purge: [
      '../src/**/*.rs'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      "tailwindCSS.experimental.classRegex": ["class: \"(.*)\""],
      "tailwindCSS.includeLanguages": {
          "rust": "html"
      },

    },
  },
  variants: {
    extend: {

    },
  },
  plugins: ["daisyui"],
}


postcss.config.js:
module.exports = {
    plugins: {
        tailwindcss: { config: './tailwind.config.js' },
        autoprefixer: {},
        'postcss-nested': {},
    }
}

main.pcss:
@tailwind base;

@tailwind components;

@tailwind utilities;

**Comment by ys2rice2yangsong** [comment]
my  dioxus  code:
#![allow(non_snake_case)]
use dioxus::prelude::*;
use dioxus_router::prelude::*;
fn main() {
    dioxus_web::launch(App);
}

fn App(cx: Scope) -> Element {
    render! (
        Router::<Route>{}
    )
}

#[derive(Routable, Clone)]
enum Route {
    #[route("/login")]
    Login {},
    #[nest("/main")]
        #[layout(MainMaster)]
            #[route("/")]
            MainHome {},
        #[end_layout]
    #[end_nest]
    #[route("/:..route")]
    PageNotFound {
        route: Vec<String>
    }
}

fn Login(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "登录页面"
        }
    })
}

fn MainMaster(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "后台主页"
        }
        Outlet::<Route> {}
    })
}

#[inline_props]
fn PageNotFound(cx: Scope, route: Vec<String>) ->Element {
    cx.render(rsx! {
        div {
            "没有这个页面"
        }
    })
}

fn MainHome (cx: Scope) -> Element {
    render! {
        div {
            "这是后台主页面"
        }
    }
}

**Comment by ys2rice2yangsong** [comment]
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/4af252ff-2f3d-4e67-8de4-dbfa8c85a0d1)
![image](https://github.com/DioxusLabs/dioxus/assets/57334741/5445aa67-981e-47e2-b984-fc0f42a7d94b)

**Comment by ealmloff** [comment]
@ys2rice2yangsong I appreciate the clarification in the title, but this looks like exactly the same issue as #1468 and #1467. If you would like to modify the title of an issue you can click the edit button at the top:

<img width="1512" alt="Screenshot 2023-09-17 at 8 08 49 PM" src="https://github.com/DioxusLabs/dioxus/assets/66571940/f99c93b1-f68c-4043-897b-9098a29576ff">

I am closing this as a duplicate, but I would be happy to help more with this issue in https://github.com/DioxusLabs/dioxus/issues/1468 if adding `index_on_404` does not fix your issue
