### ISSUE TITLE
Fullstack mobile examples (android, ios, desktop)

### ISSUE THREAD

**Issue by Anarchism-Noob** [DioxusLabs/dioxus#1470]

**Comment by ealmloff** [comment]
There is not a fullstack demo for dioxus, but the code should be the same as the desktop example [here](https://github.com/DioxusLabs/dioxus/tree/master/packages/fullstack/examples/axum-desktop). You can combine that with the mobile setup instructions [here](https://dioxuslabs.com/learn/0.4/getting_started/mobile) to get fullstack working for mobile

**Comment by XieHengHone** [comment]
> There is not a fullstack mobile example for dioxus, but the code should be the same as the desktop example [here](https://github.com/DioxusLabs/dioxus/tree/master/packages/fullstack/examples/axum-desktop). You can combine that with the mobile setup instructions [here](https://dioxuslabs.com/learn/0.4/getting_started/mobile) to get fullstack working for mobile

Thanks for the reply. I'll try.

**Comment by jkelleyrtp** [comment]
Now, most fullstack examples should work with mobile/desktop by default with no extra config required. You still do need to set your server_fn endpoint and we call that out in the docs.
