### ISSUE TITLE
Remove the "Deployments" and "Packages" sections from the repo

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#1476]
**Problem**

Maybe I'm being pedantic, but in [DioxusLabs/dioxus](https://github.com/DioxusLabs/dioxus) (and other repos as well), there's unnecessary sections on the right. It's not really a problem when they're empty, but the main repo is showing the old `docs` deployments, which is no longer an active deployment so it might be confusing. Also, the latest `docs` deployment failed, which just doesn't "look" good.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/76173380/5822b63e-4b38-41a9-8147-b0ec8b6f612a)

**Comment by ealmloff** [comment]
Fixed
