### ISSUE TITLE
CLI: Overwrite current line to show progress instead of writing new line

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#1478]
## Specific Demand

Currently, to show progress when compiling, the CLI writes a new line to the terminal instead of overwriting the current one. It would be preferable to simply overwrite the current line. Current behavior:

![image](https://github.com/DioxusLabs/dioxus/assets/76173380/721e0cb2-231d-4baa-82af-8837bb0d1a41)

## Implement Suggestion

We can use the [indicatif](https://crates.io/crates/indicatif) [spinner](https://docs.rs/indicatif/0.17.6/indicatif/struct.ProgressBar.html#method.new_spinner).

**Comment by ealmloff** [comment]
I just installed the latest git version of the CLI, and this appears to already be fixed. (fixed by https://github.com/DioxusLabs/dioxus/pull/1410)

https://github.com/DioxusLabs/dioxus/assets/66571940/044a7057-e540-43c9-80fa-9cadc60e10dc

**Comment by foresterre** [comment]
I had the same issue on Windows 11 x64 (with Powershel 7 and windows terminal 1.18), and dioxus-cli 0.5.4:

```
$ dx --version
dioxus 0.5.4
```

See: https://gist.github.com/foresterre/3630ef11472c4fdc1523af2397f73818
