### ISSUE TITLE
Formatting with dioxus plugin in VS Code is broken 

### ISSUE THREAD

**Issue by Natrocx** [DioxusLabs/dioxus#1491]
When writing a barebones component I tried matching on a prop and conditionally render a part of the component. 

Every time I save (format on save is on) or format otherwise the content of the match statement is indented by 4 additional spaces.

The code looks the following (as formatted by vs code with dioxus plugin):

```rust

#[derive(PartialEq, Clone, Debug, Props)]
struct ListPreviewProps<'a> {
  id: <List as Identifiable>::Id,
  name: &'a str,
  image_id: &'a Option<u64>,
}

// A Component that renders ListPreviewProps as a Card, fetching the image from the API or using a placeholder
pub fn list_preview<'a>(cx: Scope<'a, ListPreviewProps<'a>>) -> Element {
  let api = cx.consume_context::<ApiService>()?;

  cx.render(rsx!(
    div {
        match cx.props.image_id {
                        Some(id) => {
                            let src_url = api.get_img_url(*id);
                            rsx!(img { src: "{src_url}" })
                        },
                        None => rsx!( p { "?"}),
                        },
        div {
            p { cx.props.name }
        }
    }
))
}
```

**Expected behavior**

I would expect consistent formatting of the above code and identical behaviour between manually invoking `dx fmt` and saving with VS code.

**Environment:**
 - Dioxus cli version: v0.4.1 (https://github.com/DioxusLabs/dioxus#517a43d7)
 - Rust version: 1.74.0-nightly
 - OS info: macOS
 - App platform: desktop, web
 - Editor: stable vscode with dioxus plugin

Screen recording of saving:
https://github.com/DioxusLabs/dioxus/assets/17322576/9aeb7216-c289-4037-9d4d-d76e23454f28

**Comment by Natrocx** [comment]
This behaviour is not exerted when repeatedly calling `dx fmt` on the command line. Maybe this is an interaction with rustfmt?

**Comment by ealmloff** [comment]
Since https://github.com/DioxusLabs/dioxus/pull/1170, the VSCode extension has statically linked to the formatter instead of using the currently installed formatter. The git version of the CLI could have fixed an issue with match statements that hasn't been published in the extension yet

**Comment by Natrocx** [comment]
I have installed the dioxus plugin from git and I can no longer reproduce the bug. 
If I run across it again, I will reopen the issue.

Thank you for the quick response!
