### ISSUE TITLE
Make dioxus formatting respect rustfmt settings

### ISSUE THREAD

**Issue by Natrocx** [DioxusLabs/dioxus#1492]
## Specific Demand

Dioxus formatting (as in `dx fmt`) only applies default values for settings like tab size and maximum line length creating a break in style between "normal" rust code and the code inside `rsx!` macros.

## Implement Suggestion

Read the content of rustfmt.toml (and possibly overwrite configured values if other values are specified in dioxus.toml if that happens to make sense).

**Comment by jkelleyrtp** [comment]
Closed by 
https://github.com/DioxusLabs/dioxus/pull/1597
