### ISSUE TITLE
Refactor `examples/todomvc.rs` `App` component

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#1502]
## Specific Demand

The `App` component in `examples/todomvc.rs` is long, nested and hard to read. Since TodoMVC is a very popular way of showcasing a certain framework, the implementation should be clean and easy to read.

**Comment by alexanderjophus** [comment]
Can I take a look at this? Recently refactored my first dioxus site, would be good to get feedback/practice on the todomvc refactoring

**Comment by ealmloff** [comment]
> Can I take a look at this? Recently refactored my first dioxus site, would be good to get feedback/practice on the todomvc refactoring

That would be great!

**Comment by ealmloff** [comment]
Fixed by https://github.com/DioxusLabs/dioxus/pull/1556
