### ISSUE TITLE
isn't this a dangling pointer?

### ISSUE THREAD

**Issue by gfreezy** [DioxusLabs/dioxus#151]
https://github.com/DioxusLabs/dioxus/blob/fa70dd5f2101b192f02c6bd848d8867d4721b44c/packages/core/src/scopes.rs#L799-L829

**Comment by jkelleyrtp** [comment]
Hooks get freed here:

```rust
        self.hook_arena.reset();
        self.hook_vals.get_mut().drain(..).for_each(|state| {
            let as_mut = unsafe { &mut *state };
            let boxed = unsafe { bumpalo::boxed::Box::from_raw(as_mut) };
            drop(boxed);
        });
        ```

https://github.com/DioxusLabs/dioxus/blob/fa70dd5f2101b192f02c6bd848d8867d4721b44c/packages/core/src/scopes.rs#L895-L900

If the hooks don't get freed (through a panic?) then it's a memory leak

**Comment by gfreezy** [comment]
if the vec is extended when another `use_hook` is called, previous references will point to some invalid addrs ?

**Comment by jkelleyrtp** [comment]
> if the vec is extended when another `use_hook` is called, previous references will point to some invalid addrs ?

If we used references returned by `vec` then yes, but we use the pointer into the bump arena which is stable between vec pushes.

**Comment by gfreezy** [comment]
Got it. I didn't look into it carefully.

```
                 let raw_box = unsafe { &mut **inn }; 
```
