### ISSUE TITLE
Routes with query segments don't work

### ISSUE THREAD

**Issue by rvolz** [DioxusLabs/dioxus#1511]
**Problem**

Creating a route with query segments according to the recipe in the [router docs](https://dioxuslabs.com/learn/0.4/router/reference/routes) produces errors. The query segment information is not passed on to the receiving component.

```rust
impl FromQuery for SearchQuerySegments {
    fn from_query(query: &str) -> Self {
        debug!("from query {:?}", query);
        ...
```

According to the browser log `FromQuery::from_query` always gets an empty query string, although the query string was written using `Display::fmt`.

**Steps To Reproduce**

- Use the [query segment router demo](https://github.com/DioxusLabs/dioxus/blob/master/examples/query_segments_demo/src/main.rs)
- Run `dx serve` and navigate to `http://localhost:8080/blog?name=John&surname=Doe`
- The app will panic at line 53: panicked at 'called `Option::unwrap()` on a `None` value'. Because `from_query` received an empty query string, the query segments were never overwritten.

**Environment:**
 - Dioxus version: 0.4 (dioxus-router 0.4.1)
 - Rust version: 1.72.1, stable
 - OS info: Linux, Ubuntu
 - App platform: `web`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Query segments were fixed in https://github.com/DioxusLabs/dioxus/pull/1406. If you run the example inside of the main repo it should be fixed. You can switch Dioxus to the git version in your `Cargo.toml` to fix the issue in your own project:
```toml
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
```
