### ISSUE TITLE
`dx serve --verbose` should display warnings to the user

### ISSUE THREAD

**Issue by srid** [DioxusLabs/dioxus#1514]
## Specific Demand

<img width="569" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/3998/9cccd61a-ae2c-43e6-afdc-b050cf607301">

The screenshot shows `[WARN] There were 6 warning messages during the build.` - but **what are these warnings**, exactly? Why can't I view them? The `dx` cli clears the terminal, so you can't scroll back to see what came before this output. I passed `--verbose` hoping these warnings would be displayed.

**Comment by srid** [comment]
I realized that these are actually the Rust compiler warnings, and not specific to dx. In which case, my request becomes much less important. Maybe the WARN message can be clarified at the least.

**Comment by tigerros** [comment]
Is there a reason why it clears the terminal? In my IDE `cls` doesn't do anything so I never noticed. That must be pretty annoying though.

**Comment by srid** [comment]
I'm on macOS where it uses `clear` (rather than `cls`)

https://github.com/DioxusLabs/dioxus/blob/30a328343860ec66d48014bace616648c65993ce/packages/cli/src/server/output.rs#L25-L29

**Comment by tigerros** [comment]
> I'm on macOS where it uses clear (rather than cls)

The specifics on your OS might be different, but I was asking if there's a reason why it does that. It's directed towards the people who built/maintain the CLI. This might not be the right place to ask though. Just found it strange.

**Comment by ealmloff** [comment]
> Is there a reason why it clears the terminal? In my IDE `cls` doesn't do anything so I never noticed. That must be pretty annoying though.

It clears the current text on the terminal so that it acts more like an TUI and the different status' are placed at a consistent spot in the terminal. There was some discussion about using the `dioxus-tui` crate to implement the CLI. That would make the CLI act fully like an app (not just `dx create`).

For example, if we used `dioxus-tui` we could make the warning a clickable button that shows all of the warnings it encountered during the build.

**Comment by tigerros** [comment]
I think using `dioxus-tui` is overkill. It's just a build command. Also, @srid, do you think you can close this? #1524 got merged which just adds a message to run `cargo check` to view the warnings. I think that's good enough.

**Comment by ealmloff** [comment]
> I think using `dioxus-tui` is overkill. It's basically just a build command. Also, @srid, do you think you can close this? #1524 got merged which just adds a message to run `cargo check` to view the warnings. I think that's good enough.

> It's basically just a build command

There are future plans that will make it more complex. `dx create` is already a (minimal) TUI. In the future, the CLI could become a cross platform set of dev tools for Dioxus that shows logging for components, server functions and potentially your database.

- Explore the currently active props of components
- Explore why specific components on the page were rerendered
- Explore logs originating from a component
- Navigate through every server function to view logs, latency, CPU time, and suspicious activity
