### ISSUE TITLE
"Comment" for loop of first code piece of Guide -> State section of docs is not working.

### ISSUE THREAD

**Issue by PedroHBrasil** [DioxusLabs/dioxus#1521]
**Problem**

When trying to run the first code provided in the documentation at the _Guide -> State_ section, the code fails to compile. The error occurs because, at this stage of the guide, _Comment_ is still defined as a struct, and not a component. _Comment_ is defined as a component in the provided _Full Code_ section though. I believe the _Guide_ chapter needs to be reviewed to make sure that the code pieces of the sections match the code provided in the _Full Code_ section in such a way that the reader is able to follow the guide without errors.

**Steps To Reproduce**

- Follow the Guide chapter tutorial from the beginning, implementing the code provided.
- Once the Guide -> State section is reached, try to copy and paste the code. 
- Run the build command "dx build --features web" (it fails here)

**Expected behavior**

The code from the tutorial works without fails.

**Environment:**
 - Dioxus version: 0.4.1
 - Rust version: 1.72.1
 - OS info:  Debian Bookworm of Dev Container: mcr.microsoft.com/devcontainers/rust:1-1-bookworm
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
If you are interested in fixing this, the guide source code is [here]. We can just add the comment component code to the first codeblock in the state page
