### ISSUE TITLE
Be more explicit about which crates and features are needed at the Guide chapter of the docs.

### ISSUE THREAD

**Issue by PedroHBrasil** [DioxusLabs/dioxus#1522]
## Specific Demand

I believe it would make the documentation even better if it was made clear for the reader which crates should be added to the project while following the _Guide_ chapter. 

## Implement Suggestion

Either add the TOML lines or the `cargo add` commands needed for the reader to run the code without needing to find out which external crates and features (such as chrono with serde features) to include in the project.

**Comment by ealmloff** [comment]
The dependancies are included in the [main page of the guide](https://dioxuslabs.com/learn/0.4/guide) 🙂:
```sh
cargo add chrono --features serde
cargo add futures
cargo add reqwest --features json
cargo add serde --features derive
cargo add serde_json
cargo add async_recursion
```

<img width="1512" alt="Screenshot 2023-10-05 at 10 11 02 AM" src="https://github.com/DioxusLabs/dioxus/assets/66571940/b69d2e4b-aa07-409a-bdf8-5063a36c7881">

Dependancies for your renderer of choice are in the getting started section linked near the dependancies.

If you notice any dependancies we missed, we can add those to the [guide file in the docsite](https://github.com/DioxusLabs/docsite/blob/master/docs-src/0.4/en/guide/index.md)

**Comment by PedroHBrasil** [comment]
I see. I guess I skipped the intro and went straight to the sections. My bad. I believe the list you provided is complete. However, have you considered maybe including the dependencies in the sections as the reader needs them and moving this "all dependencies list" to the "Full Code" section.

To be clear, I think the current structure is great and I'm not very experienced with documentation elaboration and I'm just trying to be useful since I brought it up. I completely understand if you think I'm just being too picky or if what I'm proposing is as good as the current way of listing the dependencies.

**Comment by ealmloff** [comment]
> I see. I guess I skipped the intro and went straight to the sections. My bad. I believe the list you provided is complete. However, have you considered maybe including the dependencies in the sections as the reader needs them and moving this "all dependencies list" to the "Full Code" section.
> 
> To be clear, I think the current structure is great and I'm not very experienced with documentation elaboration and I'm just trying to be useful since I brought it up. I completely understand if you think I'm just being too picky or if what I'm proposing is as good as the current way of listing the dependencies.

That would be great! I generally like all the dependancies at the beginning for single page tutorials so that users don't need to keep switching between the terminal and the rust code ([like the liveview guide](https://dioxuslabs.com/learn/0.4/getting_started/liveview)). But the guide expanded into multiple pages and the dependancies line up nicely into two large chunks:
1) Chrono + Serde https://dioxuslabs.com/learn/0.4/guide/your_first_component#dynamic-text
2) Data fetching https://dioxuslabs.com/learn/0.4/guide/data_fetching#defining-the-api

**Comment by PedroHBrasil** [comment]
Yeah, that makes sense to me too!

**Comment by ealmloff** [comment]
> I was not able to find the installation instructions in the 0.5 guide, so I'm a bit lost. Is the issue still ongoing ?

The installation instructions are now in the [getting started guide](https://dioxuslabs.com/learn/0.5/getting_started)
