### ISSUE TITLE
Branding/icons/logo repo for people to include in their projects

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#1533]
## Specific Demand

We should have a repository for files used throughout the organization. I'm improving the docs.rs of each crate to include the Dioxus logo, but I can't find the "official" file of it. In fact, the `dioxus-fullstack` docs use the organization [avatar URL](https://avatars.githubusercontent.com/u/79236386), which I'm not a huge fan of.

Also, `awesome.json` could be in this repository. Not sure what other files.

**Comment by ealmloff** [comment]
There is a Dioxus icon here https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/assets/default_icon.png. It would be nice to have a more clear place to put the logos/branding related thing (either a new folder or a new repo). A generic "files" repository seems a bit too broad, `awesome.json` and the Dioxus logo file don't have much in common.

We need the logo to be inside of somewhere inside of the main repo for the desktop default icon, so I think a folder inside of the main repo would make more sense for now, but if the amount of branding related files grows we can pull it out into it's own repo later

**Comment by jkelleyrtp** [comment]
I made a branding repo!
