### ISSUE TITLE
Lock down the default branch

### ISSUE THREAD

**Issue by esimkowitz** [DioxusLabs/dioxus#1538]
## Specific Demand

The Dioxus repository should be configured to only allow PRs to modify the default branch and all PR merges should be enforced as squash-merges. This ensures a linear commit history, which is essential for any automation of semantic versioning. It also reduces the overall size of the repo metadata when cloning, since the total number of commits that must be downloaded and replayed is reduced, and ensures all commits are held to the same validation procedures, reducing the chance that a repo could be hijacked by stolen maintainer credentials.

## Implement Suggestion

This can be configured in the repository settings under branch policies

**Comment by jkelleyrtp** [comment]
Just did this!
