### ISSUE TITLE
feat/bug(html): certain html tags are ignored: em, s

### ISSUE THREAD

**Issue by sdwoodbury** [DioxusLabs/dioxus#1541]
**Problem**
We wish to use italics  and strikethrough but found that those tags (`<em>` and `<s>`) are ignored. `<strong>` works though. Reproduced on mac/linux using rev `60ee829` of Dioxus. 

**Steps To Reproduce**

for `<em>`
![image](https://github.com/DioxusLabs/dioxus/assets/8636602/7186250e-5073-4995-a03b-4b7770fd81a1)

for `<s>`
![image](https://github.com/DioxusLabs/dioxus/assets/8636602/fbae2f23-865f-4fbb-9933-eebb22b4fc7d)

**Expected behavior**
expect `<em>` tag to produce something like this
![image](https://github.com/DioxusLabs/dioxus/assets/8636602/b334a16a-2974-4e78-a395-974d22f512c8)

expect `<s>` tag to produce something like this
![image](https://github.com/DioxusLabs/dioxus/assets/8636602/39cf3bc4-8929-47ab-95ff-021dee33efdb)

**Environment:**
 - Dioxus version: rev `60ee829`, basically 0.4.0
 - Rust version:1.70.0
 - OS info: Linux, MacOs
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Dioxus uses your system browser to render. Your system browser will handle applying styles the set. This seems to work for a minimal example:

```rust
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        b {
            "this is bold"
        }
        i {
            "this is italic"
        }
    })
}
```

<img width="425" alt="Screenshot 2023-10-12 at 9 03 58 AM" src="https://github.com/DioxusLabs/dioxus/assets/66571940/70bf0885-a623-413b-b8fb-730eb9a71a7d">

My guess is somewhere in your stylesheet you override the behavior of one of those elements. If you look in the styles tab you can see where in the stylesheet specific behavior is coming from to see exactly why those styles are not applying in Uplink. For example, in my page the `<i>` element adds the italic font style attribute automatically

<img width="1512" alt="Screenshot 2023-10-12 at 9 06 46 AM" src="https://github.com/DioxusLabs/dioxus/assets/66571940/b8ea7039-0f40-4d27-812c-532bfeb8603f">

**Comment by sdwoodbury** [comment]
@ealmloff  thanks for the help! and sorry for the false alarm
