### ISSUE TITLE
Allow to use `dioxus-cli` within a cargo workspace

### ISSUE THREAD

**Issue by ryo33** [DioxusLabs/dioxus#1547]
I'd like to work on this on my own if this feature is welcomed.

## Specific Demand

I'm using dioxus in a cargo workspace and want to run the `dx` command within the workspace root instead of `cd` to the dioxus project before run `dx`. Also, although I did not do it yet, a workspace could include multiple dioxus projects in the monorepo context.

## Implement Suggestion

Add `-p, --package [<SPEC>]        Package with the target to run` option to several `dx`'s commands.

**Comment by ealmloff** [comment]
This would be a great addition to the CLI! This would be useful for the main Dioxus repo which uses workspace.

**Comment by jkelleyrtp** [comment]
Cargo build, serve, bundle, and fmt now all apply based on the package arg.

Only `check` is not yet supported on a per-package basis.
