### ISSUE TITLE
Why the bundled exe in Windows always displays a terminal window when running?

### ISSUE THREAD

**Issue by photino** [DioxusLabs/dioxus#1553]
**Problem**

**Steps To Reproduce**

```rust
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(App);
}

fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "Hello, world!"
        }
    })
}
```

- Compiles the `dioxus-app` project
- `dx bundle --release`
- Installs the `.msi` and runs the `.exe`.

**Expected behavior**

When the `dioxus-app.exe` runs, it should not display the terminal window.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/3446306/25ca8ade-4819-495c-a2b9-d9a23a0cb1e4)

**Environment:**
 - Dioxus version: `0.4`
 - Rust version: `nightly`
 - OS info: Windows 10
 - App platform: `desktop`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
You just need to add this line to the top of your rust project:
```rust
#![windows_subsystem = "windows"]
```

We should document this in the [bundling section](https://github.com/DioxusLabs/docsite/blob/708878ca8cdc86f87ce716e11020676c7d9da554/docs-src/0.4/en/cookbook/publishing.md?plain=1#L31) for desktop
