### ISSUE TITLE
bug: Dioxus crashes with nested elements using different types of Custom Attributes

### ISSUE THREAD

**Issue by marc2332** [DioxusLabs/dioxus#1561]
**Problem**

Dioxus crashes when having elements with custom attributes with children elements that also have custom attributes but of a different type.

![image](https://github.com/DioxusLabs/dioxus/assets/38158676/05a26da5-5021-4cc5-acc7-0d353f752d03)

[Crashes here](https://github.com/DioxusLabs/dioxus/blob/e41278af4539f3a46ac8bd9cd9940ef0b56cfeec/packages/core/src/nodes.rs#L610C15-L610C70)

**Steps To Reproduce**

- Run https://github.com/marc2332/freya/pull/346/files#diff-ac9d2c4101b4358b83e0d609aff2431db6bf4e235f8416b6ede5eee36ed94310
- Swap the `Works` for `DoesntWork` in [L17](https://github.com/marc2332/freya/pull/346/files#diff-ac9d2c4101b4358b83e0d609aff2431db6bf4e235f8416b6ede5eee36ed94310R17)
- Try to scroll
- `*crashes*`

**Expected behavior**

Not crash

**Environment:**
 - Dioxus version: `master`
 - Rust version: 1.71.0 (omg I should update asap)
 - OS info: Windows
 - App platform: Freya

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
- [x] I don't know how to fix this but I can try to help ❤️

**Comment by ealmloff** [comment]
The panic you are hitting means that the any attribute has been dropped. `Any` attributes are dropped when the scope that created the attribute is dropped or before the scope that created it is rerun

**Comment by ealmloff** [comment]
> So, it is a bug on my side? It was working before 🤔

I don't think so, I think we should drop the any attribute after we diff the component instead of before we diff the component. We need to drop event listeners before because they could borrow from borrowed props which would be dropped at that point. `Any` must be static, so it cannot borrow from borrowed props. The lifetime should be valid until the end of diffing just like a `&'bump str` attribute.
