### ISSUE TITLE
use_future is not clone

### ISSUE THREAD

**Issue by bbigras** [DioxusLabs/dioxus#1562]
**Problem**

use_future is not clone.

**Steps To Reproduce**

```rust
#![allow(non_snake_case)]
use dioxus::prelude::*;

async fn fetch_data() -> String {
    "ok".to_string()
}

fn main() {
    dioxus_desktop::launch(App);
}

fn App(cx: Scope) -> Element {
    let data = use_future(cx, (), |_| fetch_data());

    let log_in = move |_| {
        let data = data.clone();
        cx.spawn({
            async move {
                data.restart();
            }
        });
    };

    let data2 = format!("{:?}", data.value());

    render! {
        div {
            button {
                onclick: log_in,
                "test"
            },
            "data: {data2}"
        }
    }
}
```

```
error[E0521]: borrowed data escapes outside of function
  --> src/main.rs:13:16
   |
12 | fn App(cx: Scope) -> Element {
   |        --
   |        |
   |        `cx` is a reference that is only valid in the function body
   |        has type `&'1 Scoped<'1>`
13 |     let data = use_future(cx, (), |_| fetch_data());
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                |
   |                `cx` escapes the function body here
   |                argument requires that `'1` must outlive `'static`

For more information about this error, try `rustc --explain E0521`.
error: could not compile `test-dioxus` (bin "test-dioxus") due to previous error
```

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version: v0.4
 - Rust version: [e.g. 1.43.0, `nightly`]
 - OS info: nixos
 - App platform: `desktop`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
If you are interested in fixing this, we need to change [this code](https://github.com/DioxusLabs/dioxus/blob/master/packages/hooks/src/use_future.rs#L72) to derive clone. There are a few fields we need to be careful with:
```rust
needs_regen: Cell<bool>,
task: Rc<Cell<Option<TaskId>>>,
```
needs to change to this to make it `Clone`:
```rust
needs_regen: Rc<Cell<bool>>,
task: Rc<Cell<Option<TaskId>>>,
```

We also need to change the [dependancies](https://github.com/DioxusLabs/dioxus/blob/master/packages/hooks/src/use_future.rs#L76C37-L76C37) field. Because we only ever use dependancies within the hook function, we can move it from the `UseFuture` struct into its own hook [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/hooks/src/use_future.rs#L37):
```rust
let dependancies = cx.use_hook(Vec::new);
```

**Comment by Harjun751** [comment]
Hope I'm not beating a dead horse, but is there any way to implement this exact use case in dioxus 0.4.3? I've not been able to do it, and couldn't find any resources on it. Sorry if this is not the place for this!

**Comment by ealmloff** [comment]
Use future now [implements clone](https://docs.rs/dioxus-hooks/latest/dioxus_hooks/struct.UseFuture.html#impl-Clone-for-UseFuture%3CT%3E) so the original code will work out of the box

**Comment by Harjun751** [comment]
Thanks for this, it set me on the right track. In case anyone else stumbles onto this, my problem was that my future was returning a Result<T1, T2>. T2, the type of error, **did not implement copy**, which resulted in this error message that I could not decipher. Changing the error type to something that implemented Copy fixed it.
