### ISSUE TITLE
LinkError: WebAssembly.instantiate

### ISSUE THREAD

**Issue by FredrikNoren** [DioxusLabs/dioxus#1567]
**Problem**

Sometimes my app fails to load, with the following error in the console:
```
Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #292 module="wbg" function="__wbindgen_closure_wrapper327": function import requires a callable
```

The "fix" is just to refresh the page. I _think_ it is when I've deployed, so maybe there's some weird caching issue.

**Steps To Reproduce**

1. Deploy (I'm using firebase)
2. Go to the website
3. It fails to load

**Expected behavior**

No error, should work

**Environment:**
 - Dioxus version: 0.4
 - Rust version: 1.71.1
 - OS info: MacOS
 - App platform: `web`

**Comment by ealmloff** [comment]
Can you provide some more information about your project? This isn't effecting all Dioxus projects (the [docsite](https://dioxuslabs.com/) works fine).

- What are you using to host your project?
- What did you use to build your project (`trunk` or `dx`)?
- What does your application code look like?

**Comment by FredrikNoren** [comment]
@ealmloff I don't really have that right now (a way to reproduce); all I know is that sometimes when going to our website (https://ambient.run/) I get that error. I'll try to keep digging and see if there's anything.

**Comment by jkelleyrtp** [comment]
I think this is a race condition when serving out-of-date index.html and wasm. We've figured some of this out, but since we can't repro this exact issue, I'm assuming we fixed it at some point and/or our recent changes in this area have also fixed this.
