### ISSUE TITLE
Send + Sync Signals

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#1568]
## Specific Demand

Signals can currently only be used in the thread they were created in. This works great within the virtual dom, but it makes using signals within threads or tokio futures difficult.

## Implement Suggestion

We can add a generic to signals to make them automatically sync + send when you use them in a context like a new thread that requires them to be sync + send. Something like [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6681e7810eac2ed853ed6f26eb255720)

**Comment by jkelleyrtp** [comment]
Solved by #1791
