### ISSUE TITLE
`prevent_default` cannot take effect

### ISSUE THREAD

**Issue by mrxiaozhuox** [DioxusLabs/dioxus#157]
```rust
a {
    role: "button",
    class: "navbar-item",
    href: "/",
    "aria-label": "menu",
    "aria-expanded": "false",
    "data-target": "navbarMainMenu",
    prevent_default: "onclick",
    onclick: move |_| {cl.set(!cl)},
    img {
        src: "https://bulma.io/images/bulma-logo.png",
        width: "112",
        height: "28"
    }
}
```
when the img onclick, will redirect, the prevent_default is not take effect.

from: [Discord Discussion](https://discord.com/channels/899851952891002890/899851952891002893/935515214223384616)

**Comment by jkelleyrtp** [comment]
Sorry, I can't seem to reproduce this locally. I don't get the redirect (at least on Desktop).

**Comment by mrxiaozhuox** [comment]
> Sorry, I can't seem to reproduce this locally. I don't get the redirect (at least on Desktop).

dioxus version 0.1.7

**Comment by jkelleyrtp** [comment]
Can you try this on master?

**Comment by mrxiaozhuox** [comment]
I've try it on the git-master, and the `dioxus-web`:

```rust
a {
    class: "navbar-item",
    href: "/",
    prevent_default: "onclick",
    onclick: |_| { log::info!("Hello"); },
    strong {
        "Test"
    }
}
```
will be redirect .

**Comment by jkelleyrtp** [comment]
Oh... yep the Rust-based event handler works differently than the JS/TS based one.

**Comment by t1m0t** [comment]
> ```rust
> a {
>     role: "button",
>     class: "navbar-item",
>     href: "/",
>     "aria-label": "menu",
>     "aria-expanded": "false",
>     "data-target": "navbarMainMenu",
>     prevent_default: "onclick",
>     onclick: move |_| {cl.set(!cl)},
>     img {
>         src: "https://bulma.io/images/bulma-logo.png",
>         width: "112",
>         height: "28"
>     }
> }
> ```
> 
> when the img onclick, will redirect, the prevent_default is not take effect.
> 
> from: [Discord Discussion](https://discord.com/channels/899851952891002890/899851952891002893/935515214223384616)

You'll do something like this:
```
let service = use_context::<RouterService>(&cx)?;
a {
    role: "button",
    class: "navbar-item",
    href: "/",
    "aria-label": "menu",
    "aria-expanded": "false",
    "data-target": "navbarMainMenu",
    img {
        src: "https://bulma.io/images/bulma-logo.png",
        width: "112",
        height: "28",
        prevent_default: "onclick",
        onclick: move |_| {
           service.read().push_route("/")
        }
    }
}
```
But I'm facing a borrowing issue here #162 if you use this in more that one place in your app.

**Comment by mrxiaozhuox** [comment]
> But I'm facing a borrowing issue here #162 if you use this in more that one place in your app.

yes, this issue is from our discussion in `discord`.

**Comment by jkelleyrtp** [comment]
Just for some insight - the reason this exists is because the event target is the image, but the prevent_default is on the parent

If you need to work around this bug, then you can just put the prevent_default on the image:

```rust
        a {
            class: "navbar-item",
            href: "/",
            prevent_default: "onclick",
            onclick: |_| log::info!("Hello"),
            strong {
                prevent_default: "onclick",
                "Test"
            }
        }
```

**Comment by autarch** [comment]
I had the same issue and solved it with the double `prevent_default` approach too.
