### ISSUE TITLE
compile error in example packages/fullstack/examples/static-hydrated/src/main.rs error: cannot find attribute component in this scope

### ISSUE THREAD

**Issue by azharmgh** [DioxusLabs/dioxus#1574]
https://github.com/DioxusLabs/dioxus/blob/647815fa6f6db2304cda5bd36c78b4f8b0379f39/packages/fullstack/examples/static-hydrated/src/main.rs#L52

when trying to compile as a stand alone package, get a compile error: 
error: cannot find attribute `component` in this scope
  --> src/main.rs:52:3
   |
52 | #[component]
   |   ^^^^^^^^^

error: cannot find attribute `component` in this scope
  --> src/main.rs:70:3
   |
70 | #[component]
   |   ^^^^^^^^^

**Comment by ealmloff** [comment]
The github is checked with the current version of each crate in the workspace. If you want to see what an example looked like at a specific release of dioxus, you can change the tag on github to the tag matching your release. Here is the 0.4 tag: https://github.com/DioxusLabs/dioxus/blob/v0.4.0/packages/fullstack/examples/static-hydrated/src/main.rs

**Comment by azharmgh** [comment]
Thank you!
