### ISSUE TITLE
Blinking window at startup

### ISSUE THREAD

**Issue by HKalbasi** [DioxusLabs/dioxus#1585]
**Problem**

At the loading of window, at first an empty window is created, then it becomes filled with content.

**Steps To Reproduce**

- Create a hello world desktop project and run it.

**Expected behavior**

The content should immediately appear on the window. If it is not feasible, the window should be hidden until the content is loaded.

**Screenshots**

https://github.com/DioxusLabs/dioxus/assets/45197576/3e99ed95-50c4-4f18-b40e-87bd3b15aad7

Sorry if it is duplicate, and thanks for the great project!

**Comment by ealmloff** [comment]
This is somewhat similar to https://github.com/DioxusLabs/dioxus/issues/1120. The webview takes some time after the window opens to render the application. You can make the time to render the initial html faster by setting the initial html (like ebou does in #1120), but you can't eliminate the system browser loading time entirely.

It might be possible to use [set_visible](https://docs.rs/wry/latest/wry/application/window/struct.Window.html#method.set_visible) to make the window only visible after the first render message is finished in the browser

**Comment by HKalbasi** [comment]
I experimented a bit with `set_visible`, if I call it immediately after `webview::build`, it will create a blank page, make it invisible and then make it visible again. If I call it before the `WebViewBuilder::build` using `with_visible(false)`, it doesn't work at all. This bug in tauri might be related: https://github.com/tauri-apps/tauri/issues/7669

**Comment by HKalbasi** [comment]
By using `WindowBuilder::with_visible` instead of `WebViewBuilder::build`, it worked. I made a PR.
