### ISSUE TITLE
tab char ( `\t` ) is not working in RSX

### ISSUE THREAD

**Issue by felixf4xu** [DioxusLabs/dioxus#1586]
**Problem**

tab key ( `\t` ) is not working in RSX:
1) there is a error message when adding '\t' char during hot reloading. 
  the error message is:
>thread '<unnamed>' panicked at D:\github\dioxus\packages\hot-reload\src\lib.rs:34:83:
called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"hello\\tgui\", expected a borrowed string", line: 1, column: 166)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2) '\t' char is not displayed correctly 

**Steps To Reproduce**

- Create RSX like this:
```rust
fn App(ctx: Scope) -> Element{
    ctx.render(rsx!{
        div { 
            "hellogui"
        }
    })
}
```
- then run it with `dx serve --hot-reload --platform desktop`. 
 During hot reloading, add a tab char '\t' inside the string of "hellogui". In this step, make sure your editor **keeps** tab char, not converting it into spaces. This is the first bug, error messages will be displayed.
- Then re-run `dx serve` command
 the GUI can be displayed (so it's still valid RSX) but tab key is ignored. (I can verify this by copy the string to another editor and check if `\t` is copied. This is the second bug, tab char is not displayed.

**Expected behavior**

Hot reloading works, and tab char is displayed correctly.

**Environment:**
 - Dioxus version: 0.5/master, locally compiled.
 - Rust version: 1.73
 - OS info: Windows 11
 - App platform: desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This seems related to https://github.com/serde-rs/json/issues/907. Serde json will not accept unescaped `\t`s in the json. https://crates.io/crates/serde-json-fmt might be able to fix this

**Comment by i123iu** [comment]
I've looked into this and it is more complicated than just differently handling the serialization (as suggested with the crate `serde_json_fmt`). 

The problematic characters (`\n`, `\t`, …) need to be escaped in serialization by the JSON spec ([here](https://www.ietf.org/rfc/rfc4627.txt), 2.5)

The [current](https://github.com/DioxusLabs/dioxus/blob/main/packages/web/src/hot_reload.rs#L62) deserialization is done from a long JSON string to a message object that contains `&str`. The escaped characters take up 2 (or more) bytes (`\` and `n`) and need to be converted into their 1 byte variant (`\n`). 

A custom deserializer will probably be needed for every `&str`.
