### ISSUE TITLE
Some questions about handling events

### ISSUE THREAD

**Issue by bingryan** [DioxusLabs/dioxus#160]
hello,i'm writing an app using dioxus, but I have some difficulties:

1. How to handle close windows event

```
button { class: "bg-red-500 m-1 w-3 h-3 rounded-full",
    onclick: move |evt| {
        // TODO:  app exit
         println!("close windows:{:?}",evt);
    }
}
```

2.  How to handle system events when the app is hidden.

I can only handle events of a certain tag now, but sometimes  have to deal with system some shortcut keys

3.  Change CSS properties on event(click), looks like:

```
$('#image').click(function() {
  $('#foo').addClass('myClass');
});
```

**Comment by t1m0t** [comment]
You'll have something like this:
```rust
let is_closed = use_state(&cx, move || false);

cx.render(rsx!(if *is_closed {
    rsx!("")
} else {
    rsx!(button {
        class: "bg-red-500 m-1 w-3 h-3 rounded-full",
        onclick: move |_| { is_closed.set(true) }
    })
}))
```

**Comment by bingryan** [comment]
> You'll have something like this:
> 
> ```rust
> let is_closed = use_state(&cx, move || false);
> 
> cx.render(rsx!(if *is_closed {
>     rsx!("")
> } else {
>     rsx!(button {
>         class: "bg-red-500 m-1 w-3 h-3 rounded-full",
>         onclick: move |_| { is_closed.set(true) }
>     })
> }))
> ```

thankyou @t1m0t , but how to make current app exit when  the state `is_closed = true`

**Comment by mrxiaozhuox** [comment]
> thankyou @t1m0t , but how to make current app exit when the state `is_closed = true`

you can call the `exit` to exit your app.

**Comment by bingryan** [comment]
> > thankyou @t1m0t , but how to make current app exit when the state `is_closed = true`
> 
> you can call the `exit` to close your app.

i'm write the logic :`Dialog Box With Maximize, Minimize & Close Button`

```

div { class: "p-1 flex items-center justify-center",
    button { class: "bg-red-500 m-1 w-3 h-3 rounded-full",
        onclick: move |evt| {
             println!("Close:{:?}",evt);
        }
    }
    button { class: "bg-yellow-500 m-1 w-3 h-3 rounded-full",
        onclick: move |evt| {
             println!("Minimize:{:?}",evt);
        }
    }
    button { class: "bg-green-500 m-1 w-3 h-3 rounded-full",
        onclick: move |evt| {
             println!("Maximize:{:?}",evt);
        }
    }
}
```

can you give me some example or documents? i do not know how to  put `state(is_closed)` to the event handle, and make logic for `Maximize, Minimize & Close`

**Comment by t1m0t** [comment]
If you check [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/desktop_context.rs), it looks not to be implemented yet unfortunately. Dioxus is still in early dev :)

**Comment by mrxiaozhuox** [comment]
now you can use it like:
```
let window = dioxus::desktop::use_window(&cx);
window.minimize(true);
```
