### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: MissingField("char_code")

### ISSUE THREAD

**Issue by ndarilek** [DioxusLabs/dioxus#1600]
**Problem**

Using dioxus_desktop on Windows 11. If I type into a text field with completions, webview prompts me to press tab to accept the suggestion. If I do, I almost always get a panic. It doesn't happen in some instances, but seems to about 90% of the time. The panic is as follows:

thread 'main' panicked at C:\Users\nolan\.cargo\git\checkouts\dioxus-1e619ce595d3799d\bf36fc6\packages\html\src\transit.rs:36:41:                                                                                                     
called `Result::unwrap()` on an `Err` value: MissingField("char_code")                                             
stack backtrace:                                                                                                   
   0: std::panicking::begin_panic_handler                                                                          
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595                   
   1: core::panicking::panic_fmt                                                                                   
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67                   
   2: core::result::unwrap_failed                                                                                  
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\result.rs:1652                    
   3: enum2$<core::result::Result<enum2$<dioxus_html::transit::EventData>,enum2$<serde_value::de::DeserializerError> > >::unwrap<enum2$<dioxus_html::transit::EventData>,enum2$<serde_value::de::DeserializerError> >                 
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\result.rs:1077                    
   4: dioxus_html::transit::impl$0::deserialize<enum2$<serde_json::value::Value> >                                 
             at C:\Users\nolan\.cargo\git\checkouts\dioxus-1e619ce595d3799d\bf36fc6\packages\html\src\transit.rs:36
   5: serde_json::value::from_value<dioxus_html::transit::HtmlEvent>                                               
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\serde_json-1.0.108\src\value\mod.rs:1007                                                                                                          
   6: dioxus_desktop::launch_with_props::closure$1<tuple$<> >                                                      
             at C:\Users\nolan\.cargo\git\checkouts\dioxus-1e619ce595d3799d\bf36fc6\packages\desktop\src\lib.rs:271
   7: tao::platform_impl::platform::event_loop::impl$2::run_return::closure$0<dioxus_desktop::desktop_context::UserWindowEvent,dioxus_desktop::launch_with_props::closure_env$1<tuple$<> > >                                          
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop.rs:235                                                                                            
   8: alloc::boxed::impl$48::call_mut<tuple$<enum2$<tao::event::Event<dioxus_desktop::desktop_context::UserWindowEvent> >,ref_mut$<enum2$<tao::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<tao::event::Event<dioxus_desktop::desktop_c                                                                                    
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\alloc\src\boxed.rs:2014                    
   9: tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<dioxus_desktop::desktop_context::UserWindowEvent>                                                                                       
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop\runner.rs:250                                                                                     
  10: core::panic::unwind_safe::impl$23::call_once<tuple$<>,tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> >                           
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\panic\unwind_safe.rs:271          
  11: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> >,tuple$<> >                                                                                                                 
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:502                   
  12: windows::Windows::Win32::UI::Input::Pointer::impl$68::eq                                                     
  13: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> > >       
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:466                   
  14: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> >,tuple$<> >  
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panic.rs:142                       
  15: tao::platform_impl::platform::event_loop::runner::EventLoopRunner<dioxus_desktop::desktop_context::UserWindowEvent>::catch_unwind<dioxus_desktop::desktop_context::UserWindowEvent,tuple$<>,tao::platform_impl::platform::event_loop::runner::impl$3::call_even                                                                                    
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop\runner.rs:156                                                                                     
  16: tao::platform_impl::platform::event_loop::runner::EventLoopRunner<dioxus_desktop::desktop_context::UserWindowEvent>::call_event_handler<dioxus_desktop::desktop_context::UserWindowEvent>                                       
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop\runner.rs:242                                                                                     
  17: tao::platform_impl::platform::event_loop::runner::EventLoopRunner<dioxus_desktop::desktop_context::UserWindowEvent>::send_event<dioxus_desktop::desktop_context::UserWindowEvent>                                               
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop\runner.rs:224                                                                                     
  18: tao::platform_impl::platform::event_loop::ThreadMsgTargetSubclassInput<dioxus_desktop::desktop_context::UserWindowEvent>::send_event<dioxus_desktop::desktop_context::UserWindowEvent>                                          
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop.rs:128                                                                                            
  19: tao::platform_impl::platform::event_loop::thread_event_target_callback::closure$0<dioxus_desktop::desktop_context::UserWindowEvent>                                                                                             
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop.rs:2232                                                                                           
  20: core::ops::function::FnOnce::call_once<tao::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent>,tuple$<> >                                       
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250               
  21: core::panic::unwind_safe::impl$23::call_once<windows::Windows::Win32::Foundation::LRESULT,tao::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> >                                                                                                                
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\panic\unwind_safe.rs:271          
  22: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> >,windows::Windows::Win32::Foundation::LRESULT>                                                                                    
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:502                   
  23: windows::Windows::Win32::UI::Input::Pointer::impl$68::eq                                                     
  24: std::panicking::try<windows::Windows::Win32::Foundation::LRESULT,core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> > >                                                                                            
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:466                   
  25: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<dioxus_desktop::desktop_context::UserWindowEvent> >,windows::Windows::Win32::Foundation::LRESULT>                                                                                        
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panic.rs:142                       
  26: tao::platform_impl::platform::event_loop::runner::EventLoopRunner<dioxus_desktop::desktop_context::UserWindowEvent>::catch_unwind<dioxus_desktop::desktop_context::UserWindowEvent,windows::Windows::Win32::Foundation::LRESULT,tao::platform_impl::platform::e                                                                                    
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop\runner.rs:156                                                                                     
  27: tao::platform_impl::platform::event_loop::thread_event_target_callback<dioxus_desktop::desktop_context::UserWindowEvent>                                                                                                        
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop.rs:2281                                                                                           
  28: DefSubclassProc                                                                                              
  29: DefSubclassProc                                                                                              
  30: DispatchMessageW                                                                                             
  31: DispatchMessageW                                                                                             
  32: windows::Windows::Win32::UI::WindowsAndMessaging::DispatchMessageW                                           
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.44.0\src\Windows\Win32\UI\WindowsAndMessaging\mod.rs:925                                                                                
  33: tao::platform_impl::platform::event_loop::EventLoop<dioxus_desktop::desktop_context::UserWindowEvent>::run_return<dioxus_desktop::desktop_context::UserWindowEvent,dioxus_desktop::launch_with_props::closure_env$1<tuple$<> > >
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop.rs:265                                                                                            
  34: tao::platform_impl::platform::event_loop::EventLoop<dioxus_desktop::desktop_context::UserWindowEvent>::run<dioxus_desktop::desktop_context::UserWindowEvent,dioxus_desktop::launch_with_props::closure_env$1<tuple$<> > >       
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\platform_impl\windows\event_loop.rs:219                                                                                            
  35: tao::event_loop::EventLoop<dioxus_desktop::desktop_context::UserWindowEvent>::run<dioxus_desktop::desktop_context::UserWindowEvent,dioxus_desktop::launch_with_props::closure_env$1<tuple$<> > >                                
             at C:\Users\nolan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.19.1\src\event_loop.rs:181                                                                                                                  
  36: dioxus_desktop::launch_with_props<tuple$<> >                                                                 
             at C:\Users\nolan\.cargo\git\checkouts\dioxus-1e619ce595d3799d\bf36fc6\packages\desktop\src\lib.rs:166
  37: dioxus_desktop::launch_cfg                                                                                   
             at C:\Users\nolan\.cargo\git\checkouts\dioxus-1e619ce595d3799d\bf36fc6\packages\desktop\src\lib.rs:94 
  38: buff::main                                                                                                   
             at .\src\main.rs:29                                                                                   
  39: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >                                                 
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250               
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                            
error: process didn't exit successfully: `target\debug\buff.exe` (exit code: 101)                                  

**Steps To Reproduce**

- Create a Windows desktop app with a text input and form.
- Do whatever is needed for the text input to get a suggested completion--submit the form once, maybe?
- Probably on a subsequent run of the app you'll be given a suggestion. Press tab to accept it.

**Expected behavior**

Microsoft being Microsoft, I'd expect just about anything from their end, but I'd expect the app not to crash with a Dioxus-related panic at least. :)

**Environment:**
 - Dioxus version: master as of 5 minutes ago
 - Rust version: 1.73.0
 - OS info: Windows 11
 - App platform: Desktop

Thanks!

**Comment by ealmloff** [comment]
Can you provide the code that caused this error? The error is related to decoding an event sent from the browser. It would be very helpful to narrow down what event Dioxus is failing to decode
