### ISSUE TITLE
warning: `&` without an explicit lifetime name cannot be used here

### ISSUE THREAD

**Issue by WolfeCub** [DioxusLabs/dioxus#1619]
**Problem**

When using server functions (as in the fullstack axum-router example) calls to the `server` macro have the following warning:

```rust
warning: `&` without an explicit lifetime name cannot be used here
  --> packages/fullstack/examples/axum-router/src/main.rs:86:1
   |
86 | #[server(PostServerData)]
   | ^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
   = note: `#[warn(elided_lifetimes_in_associated_constant)]` on by default
   = note: this warning originates in the attribute macro `server` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Steps To Reproduce**

```bash
git clone https://github.com/DioxusLabs/dioxus.git
cd dioxus/packages/fullstack/examples/axum-router
dx build --features web --release
cargo run --features ssr --release
```

**Expected behavior**

Macro shouldn't create warnings.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/1369773/fc012214-bc35-45b7-985d-3bc1cd0c889d)

**Environment:**
 - Dioxus version: 0.4 and master
 - Rust version:
```bash
$ rustup show

Default host: x86_64-unknown-linux-gnu
rustup home:  /home/wolfe/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.75.0-nightly (7adc89b69 2023-11-07)
```
 - OS info: arch
 - App platform: web

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [X] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by WolfeCub** [comment]
Doing a bit more investigation: I found that dioxus makes use of the `server_fn` package. Checking for issues there I stumbled across this: https://github.com/leptos-rs/leptos/pull/1580. Looking at the commit it seems it was only in 0.5.x releases and `dioxus-fullstack` is still on 0.4.6. I tried the simple thing of just updating the version but that gave the following error: 

```
error[E0407]: method `register` is not a member of trait `server_fn::ServerFunctionRegistry`
   --> packages/fullstack/src/server_fn.rs:128:5
    |
128 | /     fn register(
129 | |         url: &'static str,
130 | |         server_function: ServerFunction,
131 | |         encoding: server_fn::Encoding,
132 | |     ) -> Result<(), Self::Error> {
133 | |         Self::register_explicit("", url, server_function, encoding)
134 | |     }
    | |_____^ not a member of trait `server_fn::ServerFunctionRegistry`
```

So unfortunately it's not a dead simple fix.

**Comment by ealmloff** [comment]
Fixed in https://github.com/DioxusLabs/dioxus/pull/1620
