### ISSUE TITLE
Lifetime issue when using async methods in callbacks

### ISSUE THREAD

**Issue by EMUNES** [DioxusLabs/dioxus#1625]
**Problem**

In the *file explorer* example, I have changed methods in `Files` structure to all be async. And I use those async functions in those `on_click` callbacks like:

```
i { class: "material-icons", onclick: move |_| async {files.write().go_up().await}, "logout" }
```
It will report following error:

```
fn app(cx: Scope) -> Element {
   |        -- has type `&'1 Scoped<'1>`
...
40 |                                 onclick: move |_| async {files.write().go_up().await},
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ returning this value requires that `'1` must outlive `'static`        
```

So I'm not sure how to safely use `async` methods according to above issue.

**Steps To Reproduce**

- Clone *file explorer* example.
- Change methods in `Files` structure to async like: 
```  
async fn go_up(&mut self) {
        if self.path_stack.len() > 1 {
            self.path_stack.pop();
        }
        self.reload_path_list().await;
    }
```
- Use those methods in `on_click`.

**Expected behavior**

As the async example in dioxus documentation, async functions should work normally.

When it comes to async methods, lifetime issue will occur.

**Screenshots**

**Environment:**
 - Dioxus version: 0.4
 - Rust version:1.73
 - OS info: Windows11
 - App platform: `desktop`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
👋 If you want to use state in a `'static` future in dioxus, you will need to clone the state first (this is cloning an `Rc`, not the underlying data so it is cheap) and then move it into the closure.

```rust
onclick: move |_| {
    // This clones files to make it 'static
    to_owned![files];
    async move {
        files.write().go_up().await
    }
}
```

In the 0.5 release, we are introducing [signals](https://github.com/DioxusLabs/dioxus/tree/master/packages/signals#copy-data) which will automatically copy into the future. If you use signals, the example code you posted will just work automatically

**Comment by EMUNES** [comment]
Wow, thank you for solutions, very looking forward for the 0.5 release.
