### ISSUE TITLE
Allow dynamic routes in static generation

### ISSUE THREAD

**Issue by onichandame** [DioxusLabs/dioxus#1640]
## Specific Demand

[The SSG example](https://github.com/DioxusLabs/dioxus/tree/master/packages/fullstack/examples/static-hydrated) presents a way to cache static routes, but not dynamic ones. The reason this feature is demanded is that when writing blogs, a common approach is to write one source file templating all blog pages, and hydrate it with different blog content. For example a dynamic route with path `/:slug` may serve as the template, and markdowns living in a different place serve as blog content.

**Comment by ealmloff** [comment]
If you want to write a blog with static site generation, you can use static segments like the official Dioxus blog does [here](https://github.com/DioxusLabs/docsite/blob/master/src/lib.rs#L88-L103). Or you can use the include-markdown crate to generate those routes for you. 

If you want the segment to be dynamic at runtime, you can use [incremental site generation](https://github.com/DioxusLabs/dioxus/blob/62719c309a26e5320b0bc9dde04a9d1689e351e4/packages/fullstack/src/launch.rs#L76) (combined with any of the [framework examples](https://github.com/DioxusLabs/dioxus/tree/62719c309a26e5320b0bc9dde04a9d1689e351e4/packages/fullstack/examples)) which renders static pages lazily when you first request the page and then caches the result.

**Comment by onichandame** [comment]
Thanks
