### ISSUE TITLE
Cannot compile dependency: could not find `Library` in `libloading`

### ISSUE THREAD

**Issue by Tartopoms** [DioxusLabs/dioxus#1641]
**Could not compile a lib with `dx serve`**

When I run `dx serve`, I get an error because the library `cryptoki-sys` cannot compile.
[`cryptoki-sys`](https://github.com/parallaxsecond/rust-cryptoki/tree/main/cryptoki-sys) is a dependency of [`cryptoki`](https://github.com/parallaxsecond/rust-cryptoki/tree/main/cryptoki).

The **error** is:
```
# dx serve
[INFO] 🚅 Running build command...
Error: 🚫 Serving project failed: error[E0433]: failed to resolve: could not find `Library` in `libloading`
    --> /root/.cargo/registry/src/custom-registry/cryptoki-sys-0.1.7/src/bindings/generic.rs:2164:37
     |
2164 |         let library = ::libloading::Library::new(path)?;
     |                                     ^^^^^^^ could not find `Library` in `libloading`


error: Broken pipe (os error 32)
root@aa412bc2bbf8:/free/projects/rust-projects/axum_ws_dx/test# error: could not compile `cryptoki-sys` (lib) due to 4 previous errors
```
Whithout the `cryptoki` lib added, I can `dx serve` correctly.
I also can `cargo run` a projet with `cryptoki` (without wasm).

**Steps To Reproduce**

I'm working on a Docker Container, offline, with a custom Rust toolchain and a custom registry. I've been working with them for 3 months and have never had a problem so far, so I want to remove these two from the possible error case.

_With my toolchain and registry: I have two full Rust app working. One with an Axum server and Dioxus client, communicating with REST and WebSockets. Another with cryptoki (RSA PKCS#11), without any issue._

- download the [dioxus-template](https://github.com/DioxusLabs/dioxus-template/)
- I had to `export USER=random` because I had none on my container. _It was required but it worked whatever the value was_ 🤷‍♀️
- `dx create --template dioxus-template-main`
```
# dx create --template dioxus-template-main
[WARN] You appear to be creating a Dioxus project from scratch; we will use the default config
[WARN] Favorite `.dioxus-template` not found in config, using it as a local path: .dioxus-template
 Project Name: test2
[INFO]  Destination: /free/projects/rust-projects/axum_ws_dx/test ...
[INFO]  project-name: test ...
[INFO]  Generating template ...
✔  What platform are you targeting? · web
✔  Should the application use the dioxus router? · true
✔  How do you want to create CSS? · Vanilla
[INFO]  Moving generated files into: `/free/projects/rust-projects/axum_ws_dx/test`...
[INFO]  Initializing a fresh Git repository
[INFO]  Done! New project created /free/projects/rust-projects/axum_ws_dx/test
[INFO] Generated project at /free/projects/rust-projects/axum_ws_dx/test
```

**Expected behavior**

Being able to compile:
```
Project Reloaded: Changed 1 files. [xx:xx:xx]

        > Local : http://localhost:8080/
        > Network : http://<IP>:8080/
        > HTTPS : Disabled

        > Profile : Debug
        > Hot Reload : Normal
        > Index Template : Default
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 1190 millis

[INFO] A perfect compilation!
```

**Environment:**

 - Dioxus version: v0.4.0
 - Rust version: 1.70.0, `stable`
 - OS info: Docker container: Debian GNU/Linux 11 (bullseye)
 - App platform: `web`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start

When I run `dx serve --verbose` I get:
```
[INFO] 🚅 Running build command...
| 💼 Waiting to start build the project...
error: cannot set both --verbose and --quiet
```

**Comment by ealmloff** [comment]
It sounds like `cryptoki-sys` doesn't support WASM. You could open an issue on that repo about WASM support.

If you want to get the full error you can run:
```
cargo check --target wasm32-unknown-unknown
```

If you are interesting in fixing the error related to quiet in dioxus, we need to only enable the quiet flag [here](https://github.com/search?q=repo%3ADioxusLabs%2Fdioxus+--quiet&type=code) when the dioxus-cli `--verbose` flag is false

**Comment by ealmloff** [comment]
Closing this issue because it looks like it is not related to dioxus
