### ISSUE TITLE
dioxus-desktop 0.4.0 failed to build on docs.rs

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#1644]
I don't know if this is a bug with docs.rs, because I can build the docs locally and the IDE has no problem either, but both of those options are quite unwieldy. Can someone look into this? [build log](https://docs.rs/crate/dioxus-desktop/0.4.0/builds/874830)

**Comment by ealmloff** [comment]
This is fixed in https://github.com/DioxusLabs/dioxus/pull/1412. Wry broke docs.rs without a specific flag which we now forward. Whenever the next release goes out the docs will be fixed
