### ISSUE TITLE
Documentation on using other data than the dioxus_html::events for EventHandlers

### ISSUE THREAD

**Issue by Exotik850** [DioxusLabs/dioxus#1656]
On the website it mentions at the very bottom of the [Event Handlers](https://dioxuslabs.com/learn/0.4/reference/event_handlers) page:

> You can also put custom data in the event, rather than e.g. MouseData

However I can not find any documentation regarding how I would use this, as it seems like a very useful feature to have

If I'm simply missing where it is maybe a link to the documentation in the page would be helpful as well

**Comment by ealmloff** [comment]
There isn't anything special about *Event types. You can use any type you want.

Eg instead of:
```rust
#[derive(Props)]
pub struct FancyButtonProps<'a> {
    on_click: EventHandler<'a, MouseEvent>,
}

pub fn FancyButton<'a>(cx: Scope<'a, FancyButtonProps<'a>>) -> Element<'a> {
    cx.render(rsx!(button {
        class: "fancy-button",
        onclick: move |evt| cx.props.on_click.call(evt),
        "click me pls."
    }))
}
```
You could use:
```rust
#[derive(Props)]
pub struct FancyButtonProps<'a> {
    on_click: EventHandler<'a, i32>,
}

pub fn FancyButton<'a>(cx: Scope<'a, FancyButtonProps<'a>>) -> Element<'a> {
    cx.render(rsx!(button {
        class: "fancy-button",
        onclick: move |_| cx.props.on_click.call(0),
        "click me pls."
    }))
}
```

**Comment by Exotik850** [comment]
Ah ok great! I'll make a PR to add that to the docs, as it isn't really made clear
