### ISSUE TITLE
dx cpu load is high

### ISSUE THREAD

**Issue by felixf4xu** [DioxusLabs/dioxus#1677]
**Problem**

when I run `dx serve`, I see the `dx` process use up to 30% of all cpu.

**Steps To Reproduce**

- create a simple test programme of dioxus, 
- run `dx server --hot-reload --platform desktop`
- check the cpu load of dx process

**Expected behavior**

normal cpu load, like any other program like vscode, Edge, word. (< 10%)

**Screenshots**

**Environment:**
 - Dioxus version: branch v0.5
 - Rust version: 1.73
 - OS info: Windows
 - App platform: `desktop`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

I checked the code, 
https://github.com/DioxusLabs/dioxus/blob/0.5/packages/cli/src/server/desktop/mod.rs#L126-L129
```rust
                let _ = local_socket_stream.set_nonblocking(true);
                move || {
                    loop {
                        match local_socket_stream.accept() {
```
the `nonblocking` and the infinite `loop` (without sleep inside) should be the root cause. I would suggest to use **blocking** mode of interprocess.

**Comment by ealmloff** [comment]
I saw you opened https://github.com/DioxusLabs/dioxus/pull/1582 which looks like it would fix this. Whenever you are done with it, you can change from a draft PR to a normal PR and I would happy to review it

**Comment by felixf4xu** [comment]
#1582 is another way to fix it, which uses `sleep`, but now I think it's better to use _blocking_, what's your thought?

**Comment by ealmloff** [comment]
> #1582 is another way to fix it, which uses `sleep`, but now I think it's better to use _blocking_, what's your thought?

I agree, that seems like a better solution
