### ISSUE TITLE
[bug/help] examples not working whatsoever

### ISSUE THREAD

**Issue by philiparvidsson** [DioxusLabs/dioxus#1690]
I'm trying the examples but I can't really get anything to work right now.

It seems axum::Server has been replaced with axum::serve (using a TcpListener). I think I got this one figured out.

The next one is serve_dioxus_application which basically does not seem to exist (anymore?).

In particular, I'm following this guide: https://dioxuslabs.com/docs/nightly/guide/en/fullstack/getting_started.html

Help appreciated.

**Comment by ealmloff** [comment]
That guide is for an older version of Dioxus (0.3). Here is the guide for 0.4: https://dioxuslabs.com/learn/0.4/getting_started

**Comment by philiparvidsson** [comment]
Thank you. I got confused because the URL said nightly.
