### ISSUE TITLE
Some macOS keybindings do not work (Copy, Paste, Select all)

### ISSUE THREAD

**Issue by Natrocx** [DioxusLabs/dioxus#1691]
**Problem**
Some keybindings like Cmd+A for select all, Cmd+c for copy or Cmd+v for paste, Cmd+x, Cmd+Z (and potentially others? im no macOS expert) do not work/do nothing. Other macOS specific keybindings like Cmd+backspace and Cmd+shift+left do work

**Steps To Reproduce**

Try to use the following code: 
```rust
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

pub fn app(cx: Scope) -> Element {
    render! {
      input {
        style: "width:100%;",
        value: "A lot of text to remove. Maybe you wish to select all to remove it?"
      }
    }
}
```

**Expected behavior**

Standard keybindings work the same as in Safari,

**Environment:**
 - Dioxus version: 0.4.0/git main
 - Rust version: 1.76.0-nightly
 - OS info: macOS 14.1
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
On macOS, these keybindings need to be mapped to some action in the menu bar/context menu. This is how I set this up in my project: https://github.com/esimkowitz/dev-widgets/blob/main/src/environment/desktop.rs

**Comment by ealmloff** [comment]
> I encountered this issue too and would like implement it as standard behaviour.

I agree, this should be default behavior with a way to opt out in the window builder. If you are interested in adding this, we need to add a new option to the builder [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/cfg.rs#L26) and then apply the default window items [here](https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/webview.rs#L10)
