### ISSUE TITLE
Move dioxus-logger to dioxus-std

### ISSUE THREAD

**Issue by esimkowitz** [DioxusLabs/dioxus#1692]
## Specific Demand

The [dioxus-logger](https://crates.io/crates/dioxus-logger) crate is falling out of sync with the rest of the Dioxus project, which is moving to use the tracing crate instead of the log crate. To ensure that this critical library receives the same support as the rest of Dioxus, it should be moved into the dioxus-std repository.

## Implement Suggestion

Copy the existing code into the dioxus-std repo and maintain it there. Also update it to capture logs from both the log crate and the tracing crate.

**Comment by ealmloff** [comment]
If you want to log traces within dioxus you can use https://crates.io/crates/tracing-wasm.

dioxus-logger is @DogeDark's library. He is also the maintainer of dioxus-std. It would be great if dioxus-logger supported tracing, but where the library lives doesn't effect what it does or dosen't support

**Comment by esimkowitz** [comment]
I was thinking that by moving it, we could enforce the same set of dependency upgrade policies, checkin validation, etc. if it was in the same repo.

**Comment by ealmloff** [comment]
That would have been useful when upgrading to tracing, but I don't think there will be a lot of API changes for logging in the future. This is the only "breaking" change to logging that Dioxus has made since the `0.1` release. The tracing crate seems very stable

**Comment by DogeDark** [comment]
I have talked previously about moving dioxus-logger to the Dioxus organization, and part of that was the possibility of using it with a future profiling/dev tool system. I'd love to get it updated and better integrated with Dioxus, but it's hard to find the time.

Additionally, I think it should stay as a standalone crate. The original idea for it was to become a type of framework with a multitude of logging capabilities, and if it does become integrated with a dev tool, it'd be ideal.
