### ISSUE TITLE
Allow specifying path to Cargo.toml in dioxus-CLI

### ISSUE THREAD

**Issue by ItsDoot** [DioxusLabs/dioxus#1694]
## Specific Demand

Cargo has a [`--manifest-path`](https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options) argument to manually specify the path to the `Cargo.toml` file. `dx` commands should also support this parameter.

## Implement Suggestion

Add an argument like `--manifest-path` to allow specifying the path to the `Cargo.toml`.

**Comment by ItsDoot** [comment]
@ealmloff Does #1777 cover this issue as well?

**Comment by ealmloff** [comment]
https://github.com/DioxusLabs/dioxus/pull/1777 lets you pass arbitrary arguments after `-- `. You can use `dx serve -- --manifest-path your/path`.

**Comment by ItsDoot** [comment]
Resolved by #1777
