### ISSUE TITLE
Links in Dioxus Fullstack are broken

### ISSUE THREAD

**Issue by ValorZard** [DioxusLabs/dioxus#1702]
**Problem**

The links here are broken: https://github.com/DioxusLabs/dioxus/tree/master/packages/fullstack

**Steps To Reproduce**

-  Click on the links for ``Axum``, ``Salvo``, ``Warp``, and  ``Server functions``

**Expected behavior**

Those pages should exist

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/7539214/c601a98c-beff-456a-a82d-c2b848336fda)

**Environment:**
Github

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [x ] I would like to fix and I have a solution (add the webpages)
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Currently the features for Axum, Salvo, and Warp are not enabled in docs.rs. We should add those features to the [docs.rs metadata](https://docs.rs/about/metadata) in the [fullstack cargo.toml](https://github.com/DioxusLabs/dioxus/blob/master/packages/fullstack/Cargo.toml)
