### ISSUE TITLE
Support dynamically-generated assets

### ISSUE THREAD

**Issue by willcrichton** [DioxusLabs/dioxus#1718]
## Specific Demand

A webview may have dynamically generated content. My use case is an EPUB reader where the user provides a ZIP file containing web files with assets. I can dynamically load the web file (e.g. using `dangerous_inner_html`), but if that HTML contains an `<img src="custom.jpg" />`, then I have no easy way to intercept that request and redirect it to the ZIP file.

## Implement Suggestion

Something around `WebViewBuilder::with_custom_protocol` is probably the way to go. I'll mess around with this and post here if I make progress.

**Comment by willcrichton** [comment]
One possible solution is to have the user provide a custom asset handler in the `Config` structure. I prototyped one such interface here: https://github.com/willcrichton/dioxus/commit/deded8063da08244df661a0886f046af1f009311

**Comment by ealmloff** [comment]
closed by https://github.com/DioxusLabs/dioxus/pull/1719
