### ISSUE TITLE
todomvc.rs checkbox didn't work

### ISSUE THREAD

**Issue by c5soft** [DioxusLabs/dioxus#173]
Hi there, have you noticed the examples/todomvc.rs seemed not to function, each item could not be checked, thus there is no way to make a item to be completed.

**Comment by mrxiaozhuox** [comment]
oh, right. In the latest version (master), I can't type anything.

**Comment by mrxiaozhuox** [comment]
I think because some api have been changed.

**Comment by jkelleyrtp** [comment]
This should be fixed in #200 , sorry about that, we got too aggressive with prevent default
