### ISSUE TITLE
Router on Liveview Doesn’t Respect or Alter URL

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/dioxus#1733]
**Problem**

On Liveview, the router does not respect the URL when directly accessing a route. E.g. trying the ``/tools`` route. Additionally, the links do not update the URL with the new route.

**Steps To Reproduce**

[Reproducible Code Sample](https://gist.github.com/DogeDark/cc811881cf791817c08749d29cbaaf72)

- Run the code sample provided.
- Try out the links and go to the ``/tools`` route directly.

**Expected behavior**

The browser URL to update accordingly with the router and on fresh load the router respects the targetted URL.

**Screenshots**

https://github.com/DioxusLabs/dioxus/assets/30190859/2add385c-6ddf-4ffc-9a38-c2e09e8e19a0

**Environment:**
 - Dioxus version: 0.4.3
 - Rust version: 1.73.0
 - OS info: Windows 10
 - App platform: Liveview

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
That code sample is missing the code to start the liveview history:
```rust
let history = LiveviewHistory::new(cx);
render! { Router::<Route> {
    config: || RouterConfig::default().history(history),
} }
```

https://github.com/DioxusLabs/dioxus/pull/1736 changes the router to automatically enable the liveview history when the liveview feature is enabled

**Comment by bluebear94** [comment]
I am also experiencing this issue, but on fullstack instead of liveview. Is there a solution for fullstack?

**Comment by nxy7** [comment]
> I am also experiencing this issue, but on fullstack instead of liveview. Is there a solution for fullstack?

You probably figured it out by now, but I'll leave answer in case someone like me will be looking for it. To fix it you need to add features to `dioxus`. I've change Cargo.toml to include `dioxus = { features = ["fullstack", "router", "web"], workspace = true }
dioxus-router = { workspace = true }`. Idk which one (probably 'web'), but one of those provides History implementation that then becomes router default.
