### ISSUE TITLE
`prevent_default` does not stop stealing of foucs

### ISSUE THREAD

**Issue by lukasturcani** [DioxusLabs/dioxus#1734]
**Problem**

use of `prevent_default` does not stop a button from stealing focus from an input element.

**Steps To Reproduce**

The repo https://github.com/lukasturcani/dioxus-focus-issue has a runnable minimum reproducible
example as well as a working HTML example.

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Prevent default only does something if you add an event listener to the element. If you render a button like this, it will not take the focus from the form:

```rust
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(App)
}

#[component]
fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        input {
            r#type: "search",
        },
        button {
            prevent_default: "onmousedown",
            onmousedown: move |_| {},
            r#type: "button",
            "click",
        }
    })
}
```

**Comment by lukasturcani** [comment]
Thank you!! This fixed my issue :pray:
