### ISSUE TITLE
2 different versions in the same dioxus-cli binary

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#1739]
**Problem**

I have noticed that `dx -V` shows `dioxus 0.4.3` and `dx version` shows `0.0.0 (cd019db9 2023-12-18)`.

```
version    Print the version of this extension
-V, --version    Print version
```

**Steps To Reproduce**

- get `dx` binary
- `dx -V`
- `dx version`

**Expected behavior**

I expect them to be the same, or at least not `0.0.0`. But having 3 ways to check version is probably overkill, you can only leave `-V|--version` or `version`. But having a full subcomand just to show a version...

**Environment:**
 - Dioxus version: 0.4.1 or 0.4.3
 - Rust version: 1.76.0, nightly
 - OS info: Pop!_OS 22.04
 - App platform: `none`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by Andrew15-5** [comment]
When I try to use `dx version` outside a cargo project I get:

```
Error: Couldn't retrieve cargo metadata

Caused by:
    `cargo metadata` exited with an error: error: could not find `Cargo.toml` in `/home/user/.cargo/bin` or any parent directory
```

But in any cargo project it shows v0.0.0.

**Comment by hem1t** [comment]
I compiled it straight from the repository ( not using the cargo install ) and now it doesn't have the same issues.

Like, complaining about not finding `Cargo.toml`

**Comment by Andrew15-5** [comment]
Yep, I guess the error message has gone away. But it wasn't the main problem anyway.

**Comment by ealmloff** [comment]
Closed by https://github.com/DioxusLabs/dioxus/pull/1813
