### ISSUE TITLE
 `dx fmt` command inserts extra space before comma in tuple patterns within for loops

### ISSUE THREAD

**Issue by sh1nduu** [DioxusLabs/dioxus#1744]
**Problem**

When using the `dx fmt`, an extra space is inserted before the comma in tuple patterns within a `for` loop.

**Steps To Reproduce**

1. Create a Rust file with a function that includes a `for` loop iterating over tuples, as shown in the example below.
2. Run the `dx fmt` command on the file.
3. Observe that the formatted code includes an extra space before the comma in the tuple pattern.

**Expected behavior**

The `dx fmt` command should format the tuple pattern in the `for` loop without inserting an extra space before the comma. The expected formatted code should look like this:

```rust
fn App(cx: Scope) -> Element {
    let tuples = vec![(1, 1), (2, 2), (3, 3)];
    let triples = vec![(1, 1, 1), (2, 2, 2), (3, 3, 3)];
    cx.render(rsx! (
        for (first, second) in tuples {
            p { "{first}, {second}" }
        }
        for (first, second, third) in triples {
            p { "{first}, {second}, {third}" }
        }
    ))
}
```

**Environment:**
 - Dioxus version: v0.4.3
 - Rust version: 1.74.1
 - OS info: MacOS
 - App platform: `web`, `fullstack`

**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This looks similar to https://github.com/DioxusLabs/dioxus/issues/1419. You may need to reinstall the dioxus cli. After installing the `0.4.3` version of the CLI, the example you posted is formatted correctly on my computer

**Comment by sh1nduu** [comment]
Thank you for the suggestion. I've tried reinstalling the `dioxus-cli` version `0.4.3` from crates.io, but unfortunately, the issue persisted. However, when I installed the git version `dioxus-cli v0.4.3 (https://github.com/DioxusLabs/dioxus#1880bdb3)`, the formatting issue was resolved.
