### ISSUE TITLE
default prop values

### ISSUE THREAD

**Issue by nilsmartel** [DioxusLabs/dioxus#175]
Having props like this, I'd love to not specify `width: None` every time.
I think it's best to use a form of default values for `Option` especially.

<img width="327" alt="grafik" src="https://user-images.githubusercontent.com/28377948/151656148-4b554ea2-3834-48ff-ac9d-441206898c14.png">

Maybe for other cases one can explicitly define defaults

<img width="529" alt="grafik" src="https://user-images.githubusercontent.com/28377948/151656217-3ff7aa93-acc1-46e2-8f47-ecea273dccc6.png">

**Comment by mrxiaozhuox** [comment]
oh, you can set the default value like this:
```
struct ButtonProps {
    #[props(optional)]
    width: Option<u32>,
}
```
then this props will have default-value.

**Comment by mrxiaozhuox** [comment]
Document: https://dioxuslabs.com/guide/elements/propsmacro.html?highlight=defa#optional-fields

**Comment by jkelleyrtp** [comment]
> Having props like this, I'd love to not specify `width: None` every time. I think it's best to use a form of default values for `Option` especially.
> 
> <img alt="grafik" width="327" src="https://user-images.githubusercontent.com/28377948/151656148-4b554ea2-3834-48ff-ac9d-441206898c14.png">
> 
> Maybe for other cases one can explicitly define defaults
> 
> <img alt="grafik" width="529" src="https://user-images.githubusercontent.com/28377948/151656217-3ff7aa93-acc1-46e2-8f47-ecea273dccc6.png">

You're *almost* there. We namespace attributes to not clash with other crates.

Try 

```
#[props(default = 64)]
```

**Comment by nilsmartel** [comment]
<3 
this is beautiful.
thanks for the quick answers
