### ISSUE TITLE
Add a note about incompatibility between `--hot-reload` and `--release` options

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#1757]
If `--hot-reload` doesn't work with `--release` option (according to @ealmloff, it doesn't work), then there is probably should be a note in either one of the options addressing this issue.

```
      --release
          Build in release mode [default: false]
      --hot-reload
          Build with hot reloading rsx (doesn't work in release mode) [default: false]
```

@ealmloff suggested a warning log instead (which I can agree with).

**Comment by rohilvarma11** [comment]
Hey @ealmloff, I am new to open source and I would love if you could give me some pointers on how I can get started with this.

**Comment by ealmloff** [comment]
> Hey @ealmloff, I am new to open source and I would love if you could give me some pointers on how I can get started with this.

Of course! Here is an outline of the steps you can use to fix this issue:

1) Clone the repo
2) Change the documentation for the hot reload flag on the serve command here:

https://github.com/DioxusLabs/dioxus/blob/6126e02143932ed08fecdc43c99e277babb1c0e7/packages/cli/src/cli/cfg.rs#L119

3) Add a command group that includes `hot-reload` that [conflicts with](https://docs.rs/clap/4.2.7/clap/struct.ArgGroup.html#method.conflicts_with) the `release` arg kind of like this example from clap: https://github.com/clap-rs/clap/blob/e648e086f3934afb40b121b5999b9e23657ddc28/clap_complete/src/dynamic/shells/mod.rs#L32C22-L32C22

4) install your new local version of the CLI with `cargo install --path /path/to/your/cli/package` and test that the two flags conflict when you run `dx serve --hot-reload --release`
5) Open a PR: https://github.com/DioxusLabs/dioxus/compare with a brief description of your changes
6) If any checks fail, you may need to format your code or fix clippy. The automatic checks we run against PRs is explained [here](https://dioxuslabs.com/learn/0.4/contributing#before-you-contribute)

Let me know if you run into any issues/need more information!
