### ISSUE TITLE
routing not working except base url

### ISSUE THREAD

**Issue by abhijeetbhagat** [DioxusLabs/dioxus#1760]
**Problem**
with this router:
```
#[derive(Routable, PartialEq, Clone)]
pub enum Route {
    #[route("/groups")]
    GroupsView {},

    #[route("/")]
    Login {},

    #[route("/:..route")]
    NotFound { route: Vec<String> },
}
```
i am unable to route to `/groups` - get a 404.
`/` works fine. `NotFound` doesn't work.

**Expected behavior**
configured routes should work properly.

**Environment:**

 - Dioxus version:  0.4.3
 - dioxus-router = "0.4.3"
 - Rust version: 1.77 nightly
 - OS info: macos
 - App platform: web
 
**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by baxterjo** [comment]
Adding onto this in hopes it will get picked up soon. I did some testing using the [router example project](https://dioxuslabs.com/learn/0.4/router/example/first-route). I changed the `/` route to `/home` and it hit the catchall route at the end and displayed the PageNotFound component. Then when I tried to manually navigate to home by typing it into the URL, the routing failed. I'm wondering if maybe the "needs_update" function is not being called under the hood when a new route is typed in?

**Comment by ealmloff** [comment]
Do you have this section in your `dioxus.toml` (from the [router guide](https://dioxuslabs.com/learn/0.4/router#introduction))?

```
[web.watcher]
index_on_404 = true
```

**Comment by baxterjo** [comment]
@ealmloff Thanks for pointing out the router guide. Since some of your deployment docs are gauged toward github pages, it might be helpful to provide a hint on how to create the `404.html` file (I opted to use a `make` job triggered by a pre commit hook) or maybe even get really fancy and allow users to config the Dioxus.toml to create a copy of `index.html` at a location of their choosing.

**Comment by abhijeetbhagat** [comment]
> [web.watcher]
> index_on_404 = true

yeah that worked. sorry, i missed that part in the guide. thank you!
