### ISSUE TITLE
Passing Props to Layout Components?

### ISSUE THREAD

**Issue by baxterjo** [DioxusLabs/dioxus#1765]
## Specific Demand

Is there a way to pass props to layout components? I would like my layout to render dynamically based on the route that is being taken. (e.g.: Highlight the page I'm currently on in the navbar)

If this does exist, could you provide some docs in the layout section for it?

**Comment by ealmloff** [comment]
https://github.com/DioxusLabs/docsite/pull/190 adds documentation about dynamic parameters in layouts

**Comment by baxterjo** [comment]
@ealmloff Thanks for the quick response, but to solve my specific problem I used the `use_route()` function. Maybe point that out in the docs as well?
