### ISSUE TITLE
Add Route Variant to Site Map Segment

### ISSUE THREAD

**Issue by baxterjo** [DioxusLabs/dioxus#1767]
## Specific Demand

It would be nice to be able to dynamically create a navbar based on the contents of my router. The best way I can figure on how to do this is by traversing the site map when rendering the nav bar. Some good path naming and clever string manipulation gets me part of the way to filling out a navbar, but this strategy falls apart when I try to make links to the routes. The obvious place to look for these routes is the site map, but it does not seem like it would be clean to have an enum variant contain a list of all of the possible variants of its type. Deserializing variants from strings of their paths might work though.

## Implement Suggestion

Either add a route member to the SiteMapSegment struct, or get some kind of serialization for routes where users could use a try_from on a str that is the path of the route and get a variant of the route. So something like this could work:

```rust
for segment in Route::SITE_MAP {
  let route = match segment.segment_type {
    Static(path) => Route::try_from(path).unwrap(),
    _ => continue;
  }
}
```

**Comment by ealmloff** [comment]
Routes implement [FromStr](https://doc.rust-lang.org/std/str/trait.FromStr.html) which has a from_str method that tries to parse the route.

If you just want a list of static routes, you can use the built in [static_routes](https://docs.rs/dioxus-router/latest/dioxus_router/routable/trait.Routable.html#method.static_routes) method on the router trait

**Comment by baxterjo** [comment]
@ealmloff Perfect! Thanks so much, the generated docs and rust docs are not in a format that I am used to so they have been weird to navigate for me.
