### ISSUE TITLE
render macro panics with index out of bounds error

### ISSUE THREAD

**Issue by abhijeetbhagat** [DioxusLabs/dioxus#1769]
**Problem**

i am trying to do this:
```
...
div {
        class: "flex flex-col",
        for group in my_vec.iter().as_slice().group_by(|a, b| a.from_id == b.from_id) {

         }
}
...
```
with `#![feature(slice_group_by)]` add to the top in a `mod.rs` file and i get this:
```
message: index out of bounds: the len is 0 but the index is 0
```
removing the for loop doesn't cause panic.
the for loop works fine on the rust playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e8878294d72f9a525a8ed2cf2291ed28

**Expected behavior**

should not panic

**Environment:**
- dioxus = "0.4.3"
- dioxus-web = "0.4.3"
 - Rust version: 1.77 nightly
 - OS info: MacOS
 - App platform: web

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
The body of the for loop is rsx. You run into the same error if you try to use an empty rsx macro: `rsx!{}`

If you are interested in fixing this issue, I would start in the rsx macro. We are indexing into an empty array somewhere. Maybe here? https://github.com/DioxusLabs/dioxus/blob/0166eafafb20eaf7acdbdd67bae44d037c3870b1/packages/rsx/src/lib.rs#L207

**Comment by abhijeetbhagat** [comment]
@ealmloff thanks for pointing out the source location. i shall look into this.
