### ISSUE TITLE
Can I use flex grow in TUI 

### ISSUE THREAD

**Issue by JunYang-tes** [DioxusLabs/dioxus#1780]
Hi,
I expect the "Content" div take remained space since it has `flex_grow:1`, but it's not. What's wrong here ?
![image](https://github.com/DioxusLabs/dioxus/assets/17270099/d9cc5538-bccd-4462-9a86-97c5c755b4e3)

**Comment by ealmloff** [comment]
Currently, layout attributes are only applied if they are a string literal (`flex_grow: "1"`). #1781 fixes that issue
