### ISSUE TITLE
Change Webpage Title at Runtime?

### ISSUE THREAD

**Issue by baxterjo** [DioxusLabs/dioxus#1788]
## Specific Demand

This might be a front end newbie question. But is there a way to change the title of the webpage at runtime? It would be nice to add some info to what shows up in the tab of the browser.

**Comment by ealmloff** [comment]
You can use web sys to change the title. The [set_title](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Document.html#method.set_title) method on the document sets the title to a string

**Comment by baxterjo** [comment]
Awesome, thanks!
