### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value' > `/packages/core/src/scopes.rs:172:48`

### ISSUE THREAD

**Issue by t1m0t** [DioxusLabs/dioxus#179]
After clicking to trigger `push_route`, I get this runtime error.

panicked at 'called `Option::unwrap()` on a `None` value', /home/user/packages/core/src/scopes.rs:172:48

Looks like we should handle the `None` variant here.

**Environment:**
 - Dioxus version: master
 - Rust version: 1.58.1
 - OS info: Debian 11
 - App platform: web
 - On: runtime

**Comment by autarch** [comment]
@jkelleyrtp I think this is the error I was seeing yesterday.

@t1m0t Can you try the latest HEAD? I think this may already be fixed.

**Comment by t1m0t** [comment]
@autarch I'm on the master branch and did `cargo update`. Same error here.

**Comment by jkelleyrtp** [comment]
Can you save the code that triggered this in a branch somewhere? Getting an error with unwrap here means the diffing algorithm scheduled a node for deletion even if it was still active, which shouldn't be happening.

**Comment by t1m0t** [comment]
> Can you save the code that triggered this in a branch somewhere? Getting an error with unwrap here means the diffing algorithm scheduled a node for deletion even if it was still active, which shouldn't be happening.

I'll have to figure it out.
Could it relates to this kind error log I get before?
```
ERROR /home/user/packages/core/src/nodes.rs:626 
                Warning: Each child in an array or iterator should have a unique "key" prop.
                Not providing a key will lead to poor performance with lists.
                See docs.rs/dioxus for more information.
                -------------
```

**Comment by jkelleyrtp** [comment]
> > Can you save the code that triggered this in a branch somewhere? Getting an error with unwrap here means the diffing algorithm scheduled a node for deletion even if it was still active, which shouldn't be happening.
> 
> I'll have to figure it out. Could it relates to this kind error log I get before?
> 
> ```
> ERROR /home/user/packages/core/src/nodes.rs:626 
>                 Warning: Each child in an array or iterator should have a unique "key" prop.
>                 Not providing a key will lead to poor performance with lists.
>                 See docs.rs/dioxus for more information.
>                 -------------
> ```

Perhaps? It's always a good idea to put your keys in anyways, and I think the traceback (if you hunt for it) should tell you which line of code is causing the error.

The Router pushes the diffing algorithm in a weird way since it sees nodes but can't distinguish if the current scope created them, or some parent.

**Comment by t1m0t** [comment]
My issue is that I pass several children in a parent Element (`&cx.props.children`), in a children `Prop`, so the issue lies here I think. 
I believe we should disallow passing several children because actually Dioxus doesn't handle that properly. Instead of having your app to certainly crash using this anti pattern, it would be better to simply disallow it. A log error is not enough imo.

This would force us to find another way. Avoid children for a complex structure is doable, ain't it? What would be the pattern then? In vuejs, this kind of children pattern is named `slot`. In React, idk.

**Comment by jkelleyrtp** [comment]
> My issue is that I pass several children in a parent Element (`&cx.props.children`) I think. I believe we should disallow passing several children because actually Dioxus doesn't handle that properly. Instead of having your app to certainly crash using this anti pattern, it would be better to simply disallow it. A log error is not enough imo.
> 
> This would force us to find another way. Avoid using children anti pattern for a complex structure is doable, ain't it? What would be the alternative pattern then? In vuejs, this kind of children pattern is named `slot`. In React, idk.

The intention is that this feature works :) Getting it right is somewhat difficult because everything is a self-referential structure. If you have a minimal repro I could start there and add some more test coverage to fix the issue. We have a few tests covering children elements already, but I guess they're not complex enough to catch the failing cases.
