### ISSUE TITLE
Some of elements lost their's responsiveness

### ISSUE THREAD

**Issue by serzhiio** [DioxusLabs/dioxus#1811]
After latest update i've discovered that some of my elements with `onlick` and `oninput` events, stopped producing events. Really can't understand what happened?
Any significant changes?

**Comment by ealmloff** [comment]
There have been a lot of recent changes to the git version of dioxus. This could be related to https://github.com/DioxusLabs/dioxus/pull/1402 or https://github.com/DioxusLabs/dioxus/pull/1534. Can you provide more information about your platform, the component that no longer works and the version of dioxus you are using?

**Comment by serzhiio** [comment]
Here is what i found:
```
pub fn Form(cx: Scope) -> Form {
   let dynamic_class = if true {"first"} else {"second"};
   cx.render(rsx!(
      input{class:"flex-col w-full text-sm px-2 text-white border rounded-r-none",
          class: dynamic_class,
          oninput: |_| log::debug!("input event"),
      }
   ))
}
```
if i put `dynamic_class` to input element's classes, it stops producing event, if i remove it everything is OK.

**Comment by serzhiio** [comment]
My deps:
```
dioxus = {git="https://github.com/DioxusLabs/dioxus"}
dioxus-web = {git="https://github.com/DioxusLabs/dioxus"}
fermi = {git="https://github.com/DioxusLabs/dioxus"}
```
