### ISSUE TITLE
Cloudflare Pages / Workers integration

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/dioxus#1829]
## Specific Demand

It's easy to build static sites and CSR with Dioxus and have it built ready to go on multiple platforms including Cloudflare Pages, however this is not easily possible with SSR, as Cloudflare uses workerd, a custom JS runtime, which also supports Rust. 

It'd be great if fullstack applications with Dioxus can run on CF pages / workers runtimes. Cloudflare is currently the largest runtime platform behind AWS Lambda, with it continuously growing thanks to its amazing pricing.

## Implement Suggestion

Perhaps the internal macros for SSR could also generate the necessary code to turn it with workers-rs.

Reference: https://github.com/cloudflare/workers-rs

**Comment by ealmloff** [comment]
> It's easy to build static sites and CSR with Dioxus and have it built ready to go on multiple platforms including Cloudflare Pages, however this is not easily possible with SSR, as Cloudflare uses workerd, a custom JS runtime, which also supports Rust.

Dioxus ssr doesn't assume anything about your runtime. It just takes a component, or a block of rsx and renders it to a string. You can hook up dioxus-ssr to a framework of your choice with [this guide](https://dioxuslabs.com/learn/0.4/reference/ssr).

Dioxus fullstack doesn't assume much about your runtime, but it does includes adapters for different frameworks. Worker-rs could be supported through a new adapter or just through an agnostic adapter that takes a generic hyper request and returns a generic hyper response without a router

**Comment by itsezc** [comment]
> > It's easy to build static sites and CSR with Dioxus and have it built ready to go on multiple platforms including Cloudflare Pages, however this is not easily possible with SSR, as Cloudflare uses workerd, a custom JS runtime, which also supports Rust.
> 
> Dioxus ssr doesn't assume anything about your runtime. It just takes a component, or a block of rsx and renders it to a string. You can hook up dioxus-ssr to a framework of your choice with [this guide](https://dioxuslabs.com/learn/0.4/reference/ssr).
> 
> Dioxus fullstack doesn't assume much about your runtime, but it does includes adapters for different frameworks. Worker-rs could be supported through a new adapter or just through an agnostic adapter that takes a generic hyper request and returns a generic hyper response without a router

Good to hear this, however where Cloudflare Pages are concerned I believe there might be some additional overhead as can be seen on here: 

- https://developers.cloudflare.com/pages/functions/
- https://blog.cloudflare.com/pages-functions-with-webassembly

**Comment by katopz** [comment]
So i assume this is possible am I right?
I'm asking because `leptos` just made it to the [templates](https://github.com/cloudflare/workers-rs/blob/main/templates/leptos/README.md)

And I curious that we can do this before I try. 🤔

**Comment by ealmloff** [comment]
> So i assume this is possible am I right? I'm asking because `leptos` just made it to the [templates](https://github.com/cloudflare/workers-rs/blob/main/templates/leptos/README.md)
> 
> And I curious that we can do this before I try. 🤔

Yes, this should be possible now. We don't have an official integration, but you can make it work through the axum router like the Leptos example
