### ISSUE TITLE
prerendered on desktop should persist the dom between pre-rendering and mount

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#1838]
## Specific Demand

I'm not sure if this is *actually* useful (but could be!) but right now our pre-rendering setup in desktop requires you to create a virtualdom, pre-render it, and then immediately get rid of it.

This API seems just... weird. Pre-rendering is useful (maybe?) but we have no stats on if it's actually being used and why anyone would use it. We should either just get rid of it completely or tweak it so it's a bool and we do the pre-rendering and dom saving automatically.

**Comment by ealmloff** [comment]
It used to be useful to midigate https://github.com/DioxusLabs/dioxus/issues/1120 but now that we wait until after the first render to show the window (https://github.com/DioxusLabs/dioxus/pull/1588), it should be less of an issue
