### ISSUE TITLE
Props spreading causes an infinite loop

### ISSUE THREAD

**Issue by atty303** [DioxusLabs/dioxus#1843]
**Problem**

https://github.com/DioxusLabs/dioxus/blob/5b6f9d6b80ef06c83a55a5399d3ddcd7e29479df/packages/core/src/diff.rs#L144-L163

It appears that the iterator is not consumed when it enters this case.
I tried calling left_iter.next() right_iter.next() and the infinite loop was resolved.
Is this the right way to fix it?

**Environment:**
 - Dioxus version: master
 - Rust version: 1.75.0]
 - OS info: Windows
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution, but I don't know how to test it.
- [ ] I don't have time to fix this right now, but maybe later

**Comment by atty303** [comment]
Component definitions are here:
https://github.com/atty303/bb2-building/blob/63d99f345f604020143ede9b9cda4f5f93106c61/src/components/tabs.rs

Here is what we use:
https://github.com/atty303/bb2-building/blob/63d99f345f604020143ede9b9cda4f5f93106c61/src/components/skill_view.rs#L71-L128

**Comment by ealmloff** [comment]
Yes, the item should be consumed in each of those branches.

You can test the fix by trying to diff two spread attributes with a different number of attributes (both small -> large and large -> small)
