### ISSUE TITLE
web renderer: Allow passing a `web_sys::Element` to `launch_cfg`

### ISSUE THREAD

**Issue by mirkootter** [DioxusLabs/dioxus#1848]
## Specific Demand

To use the web renderer, we have to use `dioxus_web::launch` or `dioxus_web::launch_cfg`. While it is possible to specify the root element by its html id, it is not possible to directly specify a `web_sys::Element`. Dioxus will always use `window.document.get_element_by_id` to find the root element.

This makes it very hard to use more complex roots, i.e. roots in a popup window or in a shadow-root.

It should be possible to directly specify an element if we have one

## Implement Suggestion
`dioxus_web::Config` could be easily modified to support both rootnames and root elements. Since the implementation details for `Config` are private, it's no breaking change.

Only a new method would be added: `Config::rootelement()`.

I'd be happy to create a quick PR for this if there are no objections

**Comment by ealmloff** [comment]
> I'd be happy to create a quick PR for this if there are no objections

That would be great! Exposing the root id is useful as a utility, but directly passing in a `web_sys::Element` is more useful if the element is dynamically created/found
