### ISSUE TITLE
Switch to tracing everywhere

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#1856]
## Specific Demand

We have a number of crates that are not updated to use tracing and instead still use log + fern/env_logger/simple_logger. The ecosystem seems to have moved to tracing. The CLI specifically needs to be updated, among others.

**Comment by DogeDark** [comment]
I imagine the documentation [here](https://dioxuslabs.com/learn/0.4/cookbook/integrations/logging) needs updating too?
