### ISSUE TITLE
Improved CI

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#186]
## Specific Demand

CI should be doing a lot more heavy lifting. bors might be too heavy for us right now, but we should at least configure things like

- [x] better test suite
- [ ] visual CI
- [ ] performance tracking
- [ ] automatic app screenshots
- [ ] automatic example deployments
- [x] automatic docsite deployments
- [x] run all examples

**Comment by t1m0t** [comment]
I believe we should distinguish between build and runtime tests. Build tests is easily catchable whereas runtime tests should be run in a browser environment.
In this [doc](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/browsers.html) we have some hints on how to perform these. 

disclaimer: inspired by yew ci/di pipeline

I would then propose this example for testing runtime:
```rust
use wasm_bindgen_test::{wasm_bindgen_test as test, wasm_bindgen_test_configure};
// import necessary dioxus libs
use dioxus_core::prelude::*;
use dioxus_core_macro::*;
use serde::{Deserialize, Serialize};

wasm_bindgen_test_configure!(run_in_browser);

// for each test case
#[wasm_bindgen_test]
fn some_desc_of_the_test() {
    fn main() {
        console_error_panic_hook::set_once();
        wasm_logger::init(wasm_logger::Config::new(log::Level::Debug));
        dioxus_web::launch(APP);
    }

    static APP: Component = |cx| {
        cx.render(rsx! {
           // some code
        })
    };

    // defining some components

    main();
    // perform some tests with gloo_utils or other for instance in this section:
    // assert(...);
}
```
The tests should be located in a test folder in each packages along with a `Makefile.toml` with this for instance:
```
[tasks.test]
extend = "core::wasm-pack-base"
command = "wasm-pack"
args = [
    "test",
    "@@split(DIOXUS_TEST_FLAGS, )",
    "--",
    "--features",
    "${DIOXUS_TEST_FEATURES}",
]
```

In the `Cargo.toml` of the package, we should include at minima:
```
[dev-dependencies]
wasm-bindgen-test = "0.3"
```

In the root repo, we should have a `Makefile.toml` with for instance:
```
[config]
min_version = "0.32.4"
default_to_workspace = false

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CLIPPY_ARGS = "-- --deny=warnings"

[config.modify_core_tasks]
private = true
namespace = "core"

[tasks.tests]
category = "Testing"
description = "Run all tests"
dependencies = ["tests-setup"]
env = { CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["**/examples/*", "**/packages/changelog"] }
run_task = { name = ["test-flow", "doc-test-flow", "ssr-test", "website-test"], fork = true }

[tasks.tests-setup]
private = true
script_runner = "@duckscript"
script = [
    """
    test_flags = array --headless --firefox
    dioxus_test_features = set wasm_test
    dioxus_test_flags = array_join ${test_flags} " "
    echo "running tests with flags: ${dioxus_test_flags} and features: ${dioxus_test_features}"
    set_env DIOXUS_TEST_FLAGS ${dioxus_test_flags}
    set_env DIOXUS_TEST_FEATURES ${dioxus_test_features}
    """,
]
```

I would also note that examples should at least compile, and that runtime should be tested inside packages.

I'll try to do some PR regarding that.

**Comment by t1m0t** [comment]
#190
