### ISSUE TITLE
need a paginator just like zola

### ISSUE THREAD

**Issue by silverfox-soft** [DioxusLabs/dioxus#1865]

**Comment by ealmloff** [comment]
There are a few different projects that have component libraries for dioxus, but I don't know of any that have a paginator component yet. It looks like [primer-rsx has an incomplete implementation](https://github.com/purton-tech/cloak/blob/main/crates/primer-rsx/pagination.rs). If you would like discuss or contribute to the development of a UI component library for dioxus, you can [join this issue](https://github.com/DioxusLabs/dioxus/issues/1483).

Existing component libraries:
- https://github.com/matthunz/dioxus-material
- https://github.com/DioxusLabs/dioxus/discussions/1114

(Closing this issue to fold it into the larger component library discussion)
