### ISSUE TITLE
Add `dx create` options to skip user interaction

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#1871]
## Specific Demand

Right now, when creating a Dioxus project with `dx create` you can only specify the template that will be used or use the default one if the option is omitted. For more convenience and easier reproduction examples, a way to skip the user interaction would be great (using `echo | dx create` doesn't work, and it's more of a hack). So something like `--yes` to "answer yes" for all questions when creating a cargo project (to use the default values for all questions/variables).

## Implement Suggestion

The specifics of the implementation are discussed here: https://discord.com/channels/899851952891002890/1200469217884000288.

**Comment by mrxiaozhuox** [comment]
make a new option that can create template without cargo-generator ?

**Comment by Andrew15-5** [comment]
This isn't planned in the linked PR. It also would probably be much harder to do it manually, though it will reduce total number of dependencies a little bit.

**Comment by Andrew15-5** [comment]
> Some of template want adapt is difficult

I don't understand this part at all. Maybe you can rephrase that? Or say what you want to do.

> and you don't need input any option from cargo-generator.

With that PR you only will have to provide:
- `--name` and `--yes` to create the project using the default template (with default values)
- `--name`, `--yes`, `--template` for other templates

You can also then provide `--option` to override the default values in the `cargo-generate.toml` (in the selected template).

**Comment by Andrew15-5** [comment]
Right now `cargo-generate` can't get the default values: https://github.com/cargo-generate/cargo-generate/issues/1114. So I will implement the "get default values" only for the default template as a temporary fix.

**Comment by Andrew15-5** [comment]
I will copy it here, just in case: https://github.com/DioxusLabs/dioxus/pull/1872#issuecomment-2083819160.
