### ISSUE TITLE
Blank page when running mobile application on android

### ISSUE THREAD

**Issue by Rextens** [DioxusLabs/dioxus#1875]
When running **cargo android run** with newest(**b7b5f5c** in this case) commit, application is showing just blank page with the app title above. It is also not accessible by webview testing tools like **chrome://inspect/#devices**

**Steps To Reproduce**

1. Create mobile application following the tutorial
2. Use following dependencies inside Cargo.toml instead of ones provided by the tutorial:
`[dependencies]
anyhow = "1.0.56"
log = "0.4.11"
dioxus = { git = "https://github.com/dioxuslabs/dioxus", version = "0.4.2" }
dioxus-desktop = { git = "https://github.com/dioxuslabs/dioxus", version = "0.4.2", default-features = false, features = ["tokio_runtime"] }
wry = "0.34.0"`
3. Connect phone, or run virtual device via android studio
4. Run **cargo android run** to deploy the application
5. Open the application

**Expected behavior**

Application should show what is coded. In case of the tutorial code, it should show the button, that upon clicking is adding numbers below, like here(Screenshot taken from **chrome://inspect/#devices**):
![image](https://github.com/DioxusLabs/dioxus/assets/19731974/42882248-0ebb-4fe9-b7af-5369f7477c11)

Instead, this is what is showing up:
![image](https://github.com/DioxusLabs/dioxus/assets/19731974/313692e2-edff-4ad3-861b-640b71818824)

**Environment:**
 - Dioxus version: [v0.4.2, github `master`]
 - Rust version: [1.75.0, `stable`]
 - OS info: [Windows]
 - App platform: [`mobile`, `android`]

**Comment by jkelleyrtp** [comment]
Should be fixed now - make sure you select the right debug target.

See this issue for more details:
https://github.com/tauri-apps/cargo-mobile2/issues/290
