### ISSUE TITLE
I'm getting "get_native_file"  for the fullstack code implementation (from example)

### ISSUE THREAD

**Issue by bunnyBites** [DioxusLabs/dioxus#1878]
**Problem**
I have recently started to build something (full-stack) using a Dioxus full-stack renderer. I have followed the documentation provided [here](https://dioxuslabs.com/learn/0.4/reference/fullstack/server_functions),  But I'm getting an error while running this code(to run on the web);

```sh
dx build --features web
```

Error:
```sh
Error: 🚫 Building project failed: error[E0046]: not all trait items implemented, missing: `get_native_file`
  --> /home/bunny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-web-0.4.0/src/file_engine.rs:36:1
   |
36 | impl FileEngine for WebFileEngine {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `get_native_file` in implementation
   |
   = help: implement the missing item: `fn get_native_file(&'life0 self, _: &'life1 str) -> Pin<std::boxed::Box<(dyn futures_util::Future<Output = std::option::Option<std::boxed::Box<(dyn std::any::Any + 'static)>>> + 'async_trait)>> { todo!() }`
```

**Environment:**
 - Dioxus version: 0.4.3
 - Dioxus-fullstack: 0.4.3
 - Rust version: 1.75.0 (stable)
 - OS info: Linux (Opensuse)
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Another user ran into this issue earlier on the discord server. Running `cargo update` fixed this issue for that user. `dioxus-html` accidentally had some mostly internal breaking changes in a minor release.

**Comment by bunnyBites** [comment]
> Another user ran into this issue earlier on the discord server. Running `cargo update` fixed this issue for that user. `dioxus-html` accidentally had some mostly internal breaking changes in a minor release.

Ohh that's great I'll try that and close the issue if it got fixed. Thanks🤓

**Comment by bunnyBites** [comment]
It got fixed by running ```cargo update```. Thanks !!

I am closing the issue.
