### ISSUE TITLE
Github icon in upper right corner of documentation doesn't lead to dioxus docs as expected

### ISSUE THREAD

**Issue by urcades** [DioxusLabs/dioxus#188]
**Problem**

Currently, the button located here:

<img width="1179" alt="Screen Shot 2022-02-01 at 1 27 25 AM" src="https://user-images.githubusercontent.com/1195363/151922560-98e58cda-4228-47e4-8ae1-642f14c3e149.png">

Links to the source of the `rust-lang/mdBook` [repo](https://github.com/rust-lang/mdBook/tree/master/guide), which has nothing to do with dioxus. I'd expect this github icon to link to the [docs repo](https://github.com/DioxusLabs/docsite).

**Comment by t1m0t** [comment]
It has been corrected in the master branch https://github.com/DioxusLabs/dioxus/blob/e02dfc3324fdb808f6390d2d6942fb727220a329/docs/guide/book.toml#L13-L14

**Comment by jkelleyrtp** [comment]
Should be fixed!
