### ISSUE TITLE
Custom index.html extensions

### ISSUE THREAD

**Issue by aellwein** [DioxusLabs/dioxus#1883]
## Specific Demand

Hi community,

what i want to achieve: customize the ``index.html`` of my dioxus-web application while still be able to use dioxus-cli
(in particular, i want set meta information, stuff like &lt;meta&gt; tags in &lt;head&gt; and so on.)

The problem is that currently ``index.html`` gets generated by dioxus, i have no influence there.

## Implement Suggestion

Like i see it, there is the [trunk](https://trunkrs.dev/) way -- to provide a base ``index.html``, extend it via custom tags only Trunk understands (these could also be hbs or mustache-like templates btw). Would be nice to have the same functionality in dioxus.

**Comment by ealmloff** [comment]
You can include a `index.html` with div with the id of `"main"` for dioxus to render into and the dioxus CLI will use it instead of the default index. It will still inject the code needed to load your wasm and perform hot reloading automatically.

We should document this in the dioxus `web` references [here](https://github.com/DioxusLabs/docsite/blob/master/docs-src/0.4/en/reference/web/index.md)

**Comment by aellwein** [comment]
Ok, good to know, thanks! This should be indeed documented somewhere.

**Comment by fabianboesiger** [comment]
I tested this but it does not seem to work. I inserted the script in my custom index.html, but a second script is still added.

**Comment by ealmloff** [comment]
Can you share your script and dioxus-cli version? Inserting something into the script with the literals `{base_path}` and `{app_name}` don't cause a duplicate loading script in the 0.5 version of the CLI.

index.html input:
```html
<!DOCTYPE html>
<html>
<head>
  <title>{app_title}</title>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="UTF-8" />
  {style_include}
</head>
<body>
  <div id="main"></div>
  <script type="module">
    <--! Note {base_path} and {app_name} need to be directly in the index.html -->
    console.log("/{base_path}/assets/dioxus/{app_name}.js");
  </script>
  {script_include}
</body>
</html>
```

index.html output in the dist folder:
```html
<!DOCTYPE html>
<html>
<head>
  <title>dioxus | ⛺</title>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="UTF-8" />
  
</head>
<body>
  <div id="main"></div>
  <script type="module">
    console.log("/./assets/dioxus/name.js");
  </script>
  
</body>
</html>
```

**Comment by fabianboesiger** [comment]
Ah, I was thinking I need to replace `{base_path}` and `{app_name}` manually, which is not the case. Now everything works fine. Thank you!
