### ISSUE TITLE
dioxus_desktop cmd/ctrl + w close window

### ISSUE THREAD

**Issue by kzhui125** [DioxusLabs/dioxus#1887]
By default, tauri will close window with `cmd/ctrl + w`

dioxus can make this as default behavior.

Or how can I implement this manually?

Thanks,

**Comment by ealmloff** [comment]
This was added in https://github.com/DioxusLabs/dioxus/pull/1696. The git version of dioxus automatically includes some default menu items with shortcuts including the close window shortcut

**Comment by kzhui125** [comment]
thanks
