### ISSUE TITLE
Seeing `Error: could not compile 'dioxus-desktop'` while attempting to compile first example

### ISSUE THREAD

**Issue by urcades** [DioxusLabs/dioxus#189]
**Problem**

Attempting to run [the very first app](https://dioxuslabs.com/guide/hello_world.html#our-first-app) listed in the official documentation results in the following error after compiling:

```
error: there is no argument named `mime`
   --> /Users/edouard/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-desktop-0.1.6/src/lib.rs:247:49
    |
247 | ...                   let meta = format!("{mime}");
    |                                           ^^^^^^

error: could not compile `dioxus-desktop` due to previous error
```

**Steps To Reproduce**

- Follow the instructions listed here: https://dioxuslabs.com/guide/hello_world.html#our-first-app
- Attempt to build the project with `cargo run`
- See error listed above

**Expected behavior**

After running `cargo run`, I'd expect for the example to build successfully.

**Environment:**

 - Dioxus version: `dioxus = { version = "0.1.8", features = ["desktop"] }`
   - Rust version: [e.g. 1.43.0, `nightly`]
 - OS info: MacOS 12.1 (21C52)
 - App platform: Safari Version 15.2 (17612.3.6.1.6)

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
I think this is because that format type is an edition=2022 feature but you're using rust 1.43. We either need to use classic format syntax or make our MSRV edition 2022.

**Comment by urcades** [comment]
@jkelleyrtp I can confirm that running `rustup update` cleared the issue I observed!
