### ISSUE TITLE
`dx build --release  --platform desktop` fails due to HotReloadEvent

### ISSUE THREAD

**Issue by tirithen** [DioxusLabs/dioxus#1890]
**Problem**

Running `dx build --release --platform desktop` fails as it tries to include hot reload features into the release build:

```
Error: 🚫 Building project failed: error[E0599]: no variant or associated item named `HotReloadEvent` found for enum `ipc::EventData` in the current scope
   --> /home/user/.cargo/git/checkouts/dioxus-ae1515ee984f3b14/821653e/packages/desktop/src/launch.rs:117:28
    |
117 |                 EventData::HotReloadEvent(msg) => app.handle_hot_reload_msg(msg),
    |                            ^^^^^^^^^^^^^^ variant or associated item not found in `EventData`
    |
   ::: /home/user/.cargo/git/checkouts/dioxus-ae1515ee984f3b14/821653e/packages/desktop/src/ipc.rs:10:1
    |
10  | pub enum EventData {
    | ------------------ variant or associated item `HotReloadEvent` not found for this enum
```

Editing the two files removing the HotReloadEvent enum variant and match block fixes the build and I get a working binary.

It looks like there is a feature toggle for these launch.rs: `#[cfg(feature = "hot-reload")]` and ipc.rs `#[cfg(all(feature = "hot-reload", debug_assertions))] ` but even as I assume there are development features they seem to be active even during the release build and I cannot find a way to manually disable them. I tried adding `default-features = false` in my `Cargo.toml` but that does not seem to help.

**Steps To Reproduce**

- Create a new dioxus project
- Setup dioxus dependencies to point to latest master branch
- Run `dx build --release --platform desktop`

**Expected behavior**

1. Running `dx build --release --platform desktop`, or even better the standard `cargo build --release` should create a single release optimized binary should in the target/release directory.
 2. The release build should not have hot reload capabilities? At least not by default?

**Environment:**
 - Dioxus version: [`master`]
 - Rust version: [1.75.0]
 - OS info: [Arch Linux latest updates]
 - App platform: [`desktop`]

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
The code for hot reloading in the desktop renderer should be gated both under the hot-reload feature and debug assertions.

This line: https://github.com/DioxusLabs/dioxus/blob/dc5e4e3738ac80cb3e333a10340674b575c95abd/packages/desktop/src/launch.rs#L116
Is missing the `debug_assertions` part of the config which is causing the issue. 

> I tried adding default-features = false in my Cargo.toml but that does not seem to help.

I think you need an async runtime like the tokio runtime to make your app work as expected:

```toml
dioxus-desktop = { version = "0.4", default-features = false, features = ["tokio-runtime"] }
```

**Comment by jkelleyrtp** [comment]
Just fixed this - master is updated.

**Comment by tirithen** [comment]
Great! Thanks for the fix!
