### ISSUE TITLE
formatter read from stdin and print to stdout

### ISSUE THREAD

**Issue by Dangerise** [DioxusLabs/dioxus#1891]
## Specific Demand

I'm using helix editor which require formatter to read the source file from stdin and print the result to stdout

My discussion on [Helix Editor](https://github.com/helix-editor/helix/discussions/9501)

**Comment by ealmloff** [comment]
That was added in https://github.com/DioxusLabs/dioxus/pull/1529. You can use `dx fmt -f -` to format code from stdin

**Comment by Dangerised** [comment]
@ealmloff log will be printed to stdout, how to disable it ?
