### ISSUE TITLE
open multiple window and close one of them cause crash

### ISSUE THREAD

**Issue by kzhui125** [DioxusLabs/dioxus#1892]
for `dioxus/examples/compose.rs`

<img width="887" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/11925432/2683d529-f027-46cf-a04d-8f94f1ab6908">

open multiple window and close one of them, will crash

**Environment:**
 - Dioxus version: master
 - Rust version: 1.75
 - OS info: MacOS
 - App platform: desktop

**Comment by ealmloff** [comment]
I can reproduce this issue on the master branch, but not in https://github.com/DioxusLabs/dioxus/pull/1791 which is interesting. Could be a dioxus core issue that is fixed in #1791 or a muda/wry issue like https://github.com/DioxusLabs/dioxus/pull/1819/files

**Comment by kzhui125** [comment]
@ealmloff  thanks, works now in master.
