### ISSUE TITLE
`dx create` requires `Cargo.toml` but does nothing to it

### ISSUE THREAD

**Issue by alimulap** [DioxusLabs/dioxus#1894]
**Problem**

From [here](https://github.com/DioxusLabs/dioxus/tree/master/packages/cli) and [here](https://dioxuslabs.com/learn/0.4/CLI/creating#initializing-a-project), it says that i only have to do `dx create` to make a new project. But when i try it, it search for `Cargo.toml` in current directory or parents directories. And because it found none, it gave me error

```
❯ dx create --template gh:dioxuslabs/dioxus-template
Error: Couldn't retrieve cargo metadata

Caused by:
    `cargo metadata` exited with an error: error: could not find `Cargo.toml` in `/mnt/hdp1/web/ikan` or any parent directory
```

But when i do `cargo init` and then `dx create` it will create the project but it makes another directory and it does nothing to `Cargo.toml`.

Am I missing something?

**Steps To Reproduce**

- Install `dioxus-cli`
- Type `dx create` in terminal

**Expected behavior**

Create a project without `Cargo.toml` when running `dx create`.

**Screenshots**

**Environment:**
 - Dioxus(cli) version: 0.4.3
 - Rust version: rustc 1.75.0 (82e1608df 2023-12-21)
 - OS info: Linux
 - App platform: `web`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This was fixed in https://github.com/DioxusLabs/dioxus/pull/1709
