### ISSUE TITLE
link example will crash

### ISSUE THREAD

**Issue by kzhui125** [DioxusLabs/dioxus#1904]
for `examples/link.rs`

1. change first href to `http://dioxuslabs123456.com/`

<img width="844" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/11925432/265ad266-22cf-41ba-a128-3f371862ccd1">

2. click first link, then click second link

<img width="400" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/11925432/23efc96a-6449-49e5-a8a9-fc345cf2a33e">

this may also reproduce if the first link is normal but have slow network connections or the website load time is long.

**Environment:**
 - Dioxus version: master
 - Rust version: 1.75
 - OS info: MacOS
 - App platform: desktop

**Comment by DogeDark** [comment]
I think this behavior should be changed so that the link opens in the default browser and not the app.

Result on Windows: 
![image](https://github.com/DioxusLabs/dioxus/assets/30190859/1760c527-7886-4d51-8276-d68e91e42977)

**Comment by kzhui125** [comment]
so it only crash on mac..
