### ISSUE TITLE
dioxus_web::launch_cfg cannot be called multiple times on different root elements.

### ISSUE THREAD

**Issue by JJJHolscher** [DioxusLabs/dioxus#1907]
**Problem**

When trying to have multiple dioxus widgets on different pre-existing elements, the browser console will tell about the fact that `null has no property X`, where X can be `listeners` or `nodeType` when calling `dioxus_web::launch_cfg` for the second time using either a `Config::rootname` or `Config::rootelement` on an element that is not a child of first root element.

**Steps To Reproduce**

- Clone my [repo](https://github.com/JJJHolscher/jupyter-and-dioxus) and cd into it.
- Checkout to 3f5abc55ba1981a8fcb0e2d13915834f238ba0bb
- Make sure you have wasm-pack.
- `cmd/build`
- `python -m http.server 8080`
- `$BROWSER http://localhost:8080`

My repo works with custom elements, but my exposed `change` function can also be used to launch dioxus on an element given its id, and you will again notice that this function errors when dioxus was already launched, either because there was already a rendered custom element or because the function was called before on a different id.

**Expected behavior**

When pointing the browser to index.html, you only see a single group of 2 buttons + 1 header. I expect there to be two groups, since there are two custom elements in index.html. Instead, there is the aforementioned error in the console.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/25668596/8b1e50de-1764-4922-8aa5-d587ad2deb51)

**Environment:**
 - Dioxus version: commit dc5e4e3738ac80cb3e333a10340674b575c95abd (<2 weeks old)
 - Rust version: 1.76.0-nightly
 - OS info: ArchLinux
 - App platform: web

**Willingness to solve this myself**
I'm interested in fixing this myself but don't know where to start.
If there is a way to solve this without using dioxus_web, that's also fine by me. I just want multiple dioxus widgets without all those widgets necessarily having to share the same root element, since I'm using dioxus inside a pre-existing html that sometimes adds new elements itself (I want dioxus widgets inside a jupyter notebook's cell output). If my goal is doable with a single dioxus root, then that's _also_ fine (I did not try this yet), but my gut tells me dioxus won't play nice with external sources adding (complex) elements.

**Bug or Feature**
I've seen no mention or examples of multiple `dioxus_*::launch` calls, maybe I am merely mistaken in thinking this is possible to do, in which case this issue is moreso a combination of a feature request; a call for help; and a mention that the documentation has not been clear to me about the role of `launch` calls. If Dioxus is not the right tool for my job, then this might deserve mention, for example here https://github.com/DioxusLabs/dioxus/issues/1359.

**Links**
- [discord discussion](https://discord.com/channels/899851952891002890/1202242748741328896/1204060510060937317)
- [my repo](https://github.com/JJJHolscher/jupyter-and-dioxus)
- [custom elements with yew](https://github.com/gbj/custom-elements/tree/main/examples/yew)

**Comment by JJJHolscher** [comment]
Here is the complete error message with debug flags enabled.
![image](https://github.com/DioxusLabs/dioxus/assets/25668596/569dee5a-aeed-4284-8666-21ba9cf66372)
Those websocket errors only occur with the debug flags.

**Comment by JJJHolscher** [comment]
Using iframes works...
You can have 1 dioxus_web::launch in another html file, which you look at through an iframe, that way you can have multiple interactive dioxus widgets accessible from a single window.
That's an ugly workaround, but at least I'm no longer stuck.

index.html
![image](https://github.com/DioxusLabs/dioxus/assets/25668596/a7bb0214-ba99-4f87-87c1-20466afef017)

other.html
![image](https://github.com/DioxusLabs/dioxus/assets/25668596/6955a8f8-4857-45ca-860a-86f13da15bde)

browser
![image](https://github.com/DioxusLabs/dioxus/assets/25668596/bda2c34c-a91d-4ae2-87b1-f2083924c2d0)

**Comment by jkelleyrtp** [comment]
This should definitely be possible and might be a side effect of how we do event delegation actually. I'll take a look soon - should be simple to fix.

**Comment by jkelleyrtp** [comment]
Revisiting this - it's likely because we use the same interpreter for all virtualdom instances and there's a data race happening.

Going to be fixed in #1974

**Comment by JJJHolscher** [comment]
I got around to testing this and the problem is resolved. Thank you

**Comment by jkelleyrtp** [comment]
> I got around to testing this and the problem is resolved. Thank you

0.5.0-alpha.2 is out now with this fixed if you want a released version to work from :)
