### ISSUE TITLE
Use of gzip compression slows down asset downloads considerably

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#1947]
**Problem**

When doing debug builds of fullstack Dioxus apps, the WASM file tends to be around 30MB for a small test app. The server then goes ahead and performs real time Gzip compression on this, reducing the file to 9MB but it takes a whopping 7 seconds of time to do so! This adds up to the edit-compile-run cycle considerably.

With a release build, the gzip still takes about 1sec for the 30MB file.

**Steps To Reproduce**

- build and run the doc example app from https://dioxuslabs.com/learn/0.4/getting_started/fullstack
- run curl to test the download speed (or use browser tools with caching disabled)
```
$ time curl -o test -H "Accept-Encoding: gzip, deflate, br" http://127.0.0.1:8080/assets/dioxus/dio-test_bg.wasm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed
100 8496k    0 8496k    0     0  1166k      0 --:--:--  0:00:07 --:--:-- 1092k

real    0m7.310s
user    0m0.000s
sys     0m0.000s
```

**Expected behavior**

As gzip is very slow with a debug build, it should be disabled altogether. Generally, doing real-time gzip compression on static assets is not desired in any case and the assets should be compressed at build time and served as-is.

**Screenshots**

**Environment:**
 - Dioxus version: 0.4.3
 - Rust version: 1.76.0
 - OS info: Windows (both native and WSL2)
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
We can use [this method](https://docs.rs/tower-http/latest/tower_http/services/struct.ServeDir.html#method.precompressed_gzip) on ServeDir to pre-compress static assets in axum in release mode and disable compression in debug mode.
