### ISSUE TITLE
Doesn't work in Debian 11 (missing libappindicator3-dev)

### ISSUE THREAD

**Issue by malaire** [DioxusLabs/dioxus#196]
## Specific Demand

I want to make dioxus desktop apps in Debian 11 but currently even simple examples fail to build with `libappindicator3 library not found!` error.

## Implement Suggestion

Looks like Debian 11 is using `libayatana-appindicator` instead.
I don't know what needs to be changed to use this in dioxus.

**Comment by malaire** [comment]
Looks like crate `tao` has feature `ayatana` for this (dependency chain is dioxus > dioxus-desktop > wry > tao) but just adding this to Cargo.toml doesn't work for some reason:

```
[dependencies]
dioxus = { version = "0.1.8", features = [ "desktop" ] }
tao = { version = "0.5.2", features = [ "ayatana" ] }
```

**Comment by t1m0t** [comment]
This is related to tauri I believe: https://github.com/tauri-apps/tauri/issues/2647
Still pending though.

**Comment by jkelleyrtp** [comment]
If you modify Dioxus desktop Tao dependency to use the tayana feature, can you get a compile working? They recently added a new feature to tao that doesn't use libappindicator.

**Comment by malaire** [comment]
But `dioxus-desktop` depends on `wry` which depends on `tao` - there is no `tao` dependency in `dioxus-desktop`.

**Comment by jkelleyrtp** [comment]
<img width="350" alt="Screen Shot 2022-02-03 at 10 27 42 AM" src="https://user-images.githubusercontent.com/10237910/152373457-b3f08e93-47d8-4607-869c-9f658f771de1.png">

On the most recent version of wry, there is a feature flag for "ayatana". Can you try enabling that and see if things work?

**Comment by jkelleyrtp** [comment]
I believe ayatana is a feature on 0.5.2 tao? It seems it just hasn't propagated into wry yet :(

**Comment by Nykseli** [comment]
> Cloning this repository and changing `wry` dependency in `packages/desktop/Cargo.toml`to following makes examples compile:
> 
> ```
> wry = { git = "https://github.com/tauri-apps/wry", branch = "next", features = [ "ayatana" ] }
> ```

This didn't work for me. Looks like `wry` removed `webview::RpcRequest`,  `with_rpc_handler` and other rpc functionality. (See https://github.com/tauri-apps/wry/commit/c2c26b028278c333ce0408327a5bde6062eb26d1) 

I didn't quite understand how the new `with_ipc_handler` function could used in https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/lib.rs so I just forked `wry` and reverted the rpc refactor commit.

I can now compile the examples by changing the  changing `wry` dependency in `packages/desktop/Cargo.toml` to following:
```
wry = { git = "https://github.com/Nykseli/wry", branch = "dev", features = [ "ayatana" ] }
```

**Comment by jkelleyrtp** [comment]
Whenever wry releases their new version we'll updated it to include ayatana.

If anyone else is trying to build dioxus desktop on Deb 11 and runs into this issue, patch your `wry` version manually:


```
[patch.crates-io]
wry = { git = "https://github.com/Nykseli/wry", branch = "dev", features = [ "ayatana" ] }
```

**Comment by jkelleyrtp** [comment]
PR up that upgrades wry to the recent version that supports ayatana. LMK if it works for you, and if there's any suggestions on how to best expose it to config flags at the top of our repo.

**Comment by malaire** [comment]
I don't completely understand how features interact, but wouldn't you need to somehow enable `ayatana` at top level?

i.e. instead of this (from the PR):
```
dioxus = { version = "*", features = [ "desktop" ] }
dioxus-desktop = { version = "*", features = [ "ayatana" ] }
```
wouldn't this require something like this instead since `dioxus` depends on `dioxus-desktop`
```
dioxus = { version = "*", features = [ "desktop-ayatana" ] }
```
I'll see if I can somehow test the PR, but I don't really know how to set that up.

**Comment by jkelleyrtp** [comment]
Can you see if it's possible to simplify your dependency declaration for Dioxus using nested feature flags and not manually roping in dioxus-desktop?

```
dioxus = {  git = "https://github.com/DioxusLabs/dioxus", branch = "jk/wry-upgrade", features = [ "desktop", "dioxus-desktop/ayatana" ] }
```

**Comment by malaire** [comment]
That fails with following error:
```
error: failed to parse manifest at `/path/to/Cargo.toml`

Caused by:
  feature `dioxus-desktop/ayatana` in dependency `dioxus` is not allowed to contain slashes
  If you want to enable features of a transitive dependency, the direct dependency needs to re-export those features from the `[features]` table.
```

**Comment by jkelleyrtp** [comment]
This is now fixed in master through the ayatana feature flag if you manually bring in `dioxus-desktop`.
