### ISSUE TITLE
Support `prevent_default` on `svg` elements

### ISSUE THREAD

**Issue by japsu** [DioxusLabs/dioxus#197]
Consider [this code](https://github.com/japsu/jatsi/blob/a9407b30ab9d0fa02b89a26b346067669464be41/src/components/die.rs#L50-L68).

Here the `prevent_default` attribute on an `svg` element is not supported. Hence clicking on the rendered SVG dice will cause unwanted side effects, such as double click selecting text on the button below etc.

`dioxus-html` 0.1.6

**Comment by jkelleyrtp** [comment]
Does this still break for you if you use Dioxus master? We don't distinguish on namespace, but we did have issues with prevent default not propagating through nested elements, which has been fixed in master but not released yet.

**Comment by japsu** [comment]
@jkelleyrtp yes, the error is still the same with

```
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "master", features = ["web"] }
```

```rust
error[E0599]: no method named `prevent_default` found for struct `svg` in the current scope
  --> src/components/die.rs:53:7
   |
53 |       prevent_default: "onclick",
   |       ^^^^^^^^^^^^^^^ method not found in `svg`

error[E0277]: the size for values of type `[Attribute<'_>]` cannot be known at compilation time
   --> src/components/die.rs:50:3
    |
50  | /   rsx!(cx,
51  | |     svg {
52  | |       onclick: |e| onclick.call(e),
53  | |       prevent_default: "onclick",
...   |
67  | |     }
68  | |   )
    | |___^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[Attribute<'_>]`
note: required by a bound in `Bump::alloc`
   --> /Users/japsu/.cargo/registry/src/github.com-1ecc6299db9ec823/bumpalo-3.9.1/src/lib.rs:579:18
    |
579 |     pub fn alloc<T>(&self, val: T) -> &mut T {
    |                  ^ required by this bound in `Bump::alloc`
    = note: this error originates in the macro `rsx` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by jkelleyrtp** [comment]
Oh! That makes sense. Yes, that should be enabled, I guess we just missed applying those global attributes to svg.

In the meantime, you can place any arbitrary attribute in through quotes:

'''
"dioxus-prevent-default": "onclick"
'''

**Comment by jkelleyrtp** [comment]
Fix is up in #199. I also added an SVG example that borrows your dice SVG example, if that's okay with you.

**Comment by jkelleyrtp** [comment]
On mac, though, I can't figure out why I'm still getting text selection outside the svg on double click.

**Comment by japsu** [comment]
Feel free to use the `Die` example!

I did some digging and it seems the double click selects problem exists on the previous Yew version of my code as well. Haven't yet gotten around to trying it on plain vanilla JavaScript.

Might just be Stuff Browsers Do(TM), in which case having `prevent_default` on SVG might not be that useful, but should probably still be included for completeness.

Perhaps I should wrap the `Die` in a button for accessibility etc. Might fix the selection problem too.
