### ISSUE TITLE
Warn when Signal::global is used in a const global

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#1976]
## Specific Demand

If `Signal::global` is used in const global instead of a static global, multiple states will be created. Consts effectively copy the const value into every place where the const is used.

```rust
const SIGNAL: GlobalSignal<u32> = Signal::global(|| 0);

// This will create a signal
SIGNAL.read(); // -> Signal::global(|| 0).read()

// This will create a completely different signal
SIGNAL.read(); // -> Signal::global(|| 0).read()

static STATIC_SIGNAL: GlobalSignal<u32> = Signal::global(|| 0);

// This just references the existing signal if a signal already exists in the global context
STATIC_SIGNAL.read();
```

## Implement Suggestion

We should try to prevent this at compile time or if we cannot prevent it at compile time, warn the user with tracing. 

OnceCell faces a similar issue. It might be worth looking into their discussions/issues: https://github.com/matklad/once_cell/issues/224, https://github.com/rust-lang/rust/issues/40543

**Comment by jkelleyrtp** [comment]
I believe this was fixed in #2258 since we now use panic locations as keys which are more resilient to merging even in const contexts.

Despite this being fixed, when you try to use mutative methods on const signals, rust will warn you and tell you to swap it to static.
