### ISSUE TITLE
Hot reload not working when Dioxus project is under a Cargo workspace

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#1990]
**Problem**

I have a very simple test fullstack app that works just fine when it's a standalone project. However if I make it a part of a workspace, the hot-reloading functionality no longer works. Basically everything looks to be fine, but the `hot_reload` websocket gets immediately closed. The other `disconnect` websocket stays open. When the project is standalone, the hot_reload websocket stays open.

**Steps To Reproduce**

Reproducible repo at https://github.com/ochrons/dioxus-reload-bug

```
cd web
dx serve --hot-reload
```
launch browser at `127.0.0.1:8080`
make a change in `main.rs`
see how it changes in the browser

If you check browser web dev tools, you can see that the `hot_reload` socket is in pending state and messages have been received.

then

```
cd packages/web
dx serve --hot-reload
```

launch browser at `127.0.0.1:8080`
make a change in `main.rs`
nothing happens in the browser

If you check browser web dev tools, you can see that the `hot_reload` socket is not in pending state but has been closed.

**Expected behavior**

Both cases should work identically

**Screenshots**

**Environment:**
 - Dioxus version: 0.5.0-alpha.0
 - Rust version: 1.76
 - OS info: Windows 11, WSL2
 - App platform: fullstack

**Comment by ochrons** [comment]
Further findings, excluding the `packages/web` from workspace makes hot-reload work again just fine

```toml
[workspace]
resolver = "2"
members = [
    
]
exclude = [
    "web",
    "packages/web"
]
```

Same thing if the top level `Cargo.toml` is renamed to something else.

So for some reason if `dx` finds that the project is indeed a member of a workspace, the hot-reload websocket gets closed early.

**Comment by ochrons** [comment]
This problem also occurs if the `packages/web` project is excluded from the workspace, but it depends on a crate that is in a workspace e.g.

```
[dependencies]
data = { path = "../data" }
````

**Comment by emk** [comment]
I can confirm that hot reloading is failing in a workspace. This is an obstacle to adding a Dioxus UI to a larger, existing project containing multiple crates.
