### ISSUE TITLE
cargo install dioxus-cli fails on macos

### ISSUE THREAD

**Issue by Kllngii** [DioxusLabs/dioxus#2000]
**Problem**

`cargo install dioxus-cli` fails on macos giving the following error:

```
   Compiling toml v0.5.11
   Compiling colored v2.1.0
   Compiling subprocess v0.2.9
   Compiling fs_extra v1.3.0
error: linking with `cc` failed: exit status: 1

ld: warning: object file (/private/var/folders/_3/cnmmf98d4sd38l6qftdvqvmm0000gq/T/cargo-install1J3FLX/release/deps/libring-91e776d54e9661a8.rlib[42](b0fc24a25852a580-sha256-armv8-ios64.o)) was built for newer 'macOS' version (14.2) than being linked (14.0)
[*** a few dozen more of these lines, cut for the sake of clarity ***]

ld: Undefined symbols:
            _iconv, referenced from:
                _git_fs_path_iconv in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_iconv in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_iconv in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_iconv in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_iconv in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
            _iconv_close, referenced from:
                _git_fs_path_direach in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_iconv_clear in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_diriter_free in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_dirload in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
            _iconv_open, referenced from:
                _git_fs_path_direach in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_iconv_init_precompose in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
                _git_fs_path_diriter_init in liblibgit2_sys-c19d5e5d1018ef75.rlib[114](f0f7908ee800b4e1-fs_path.o)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

The following warnings were emitted during compilation:

warning: dioxus-cli@0.4.3: Could not find `.git/HEAD` from manifest dir!

error: could not compile `dioxus-cli` (bin "dx") due to 1 previous error
error: failed to compile `dioxus-cli v0.4.3`, intermediate artifacts can be found at `/var/folders/_3/cnmmf98d4sd38l6qftdvqvmm0000gq/T/cargo-install1J3FLX`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

```

The error still persists if I try to install the cli from git using `cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli`
and even when I use an older version by specifying a branch like `cargo install --git https://github.com/DioxusLabs/dioxus --branch v0.4 dioxus-cli`. This seems weird and like there might be an error on my end, because surely I'm not the first person building the cli for macOS since December.

**Steps To Reproduce**

- try to install the dioxus-cli with `cargo install dioxus-cli`

**Expected behavior**

A clean install without any error. Afterwards a command like `dx serve` should run without problems.

**Screenshots**
<img width="1506" alt="build with reused artifacts 1" src="https://github.com/DioxusLabs/dioxus/assets/34012522/7cc8b636-7e5b-443c-8a46-b6c2df85e92e">
<img width="1507" alt="build with reused artifacts 2" src="https://github.com/DioxusLabs/dioxus/assets/34012522/20e90b76-3b65-4d88-82d1-1739710c0eff">

**Environment:**
 - Dioxus version: `main`
 - Rust version: `stable` (1.76.0 (07dca489a 2024-02-04))
 - OS info: macOS 14.3.1 (23D60); aarch64
 - Cargo version: 1.76.0 (c84b36747 2024-01-18)
 - App platform: N/A

**Questionnaire**
- [x ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Kllngii** [comment]
> In your screenshots you're exporting a CARGO_TARGET_DIR - maybe the artifact caching is not working with that setup?

Thats because I did a rebuild for the screenshot reusing the old partially build artifacts to keep the error message more compact.

It also does not work when building it freshly.

**Comment by rtretter** [comment]
I have difficulties reproducing this behavior (M2 Chip, Cargo/Rust 1.76.0).
You could try reinstalling the rust toolchain using something like: `rustup toolchain uninstall stable && rustup toolchain install stable`

**Comment by jkelleyrtp** [comment]
https://github.com/rust-lang/git2-rs?tab=readme-ov-file#building-on-macos-1010

Looks like it's failing on libgit. Do you not have openssl installed?

Try installing openssl:

```
brew install openssl@3
```

**Comment by Kllngii** [comment]
> https://github.com/rust-lang/git2-rs?tab=readme-ov-file#building-on-macos-1010
> 
> Looks like it's failing on libgit. Do you not have openssl installed?
> 
> Try installing openssl:
> 
> ```
> brew install openssl@3
> ```
> 
> Also libring is compiled for iOS on your machine - `b0fc24a25852a580-sha256-armv8-ios64`. Maybe try clearing your global cache and trying again.

I had `openssl@3` already installed, however I tried to reinstall it with brew just to be sure. However I am still getting the same error.



> I have difficulties reproducing this behavior (M2 Chip, Cargo/Rust 1.76.0). You could try reinstalling the rust toolchain using something like: `rustup toolchain uninstall stable && rustup toolchain install stable`

I also tried this, sadly it also doesn't fix my problem.

**Comment by kunalomizer** [comment]
Similarly, I am unable to install dioxus-cli. Tried the above mentioned solutions but did not work. 
Running on M1 Chip MacOs 14.4 Cargo/Rust 1.76.0.

Error Summary:
For more information about this error, try `rustc --explain E0308`.
error: could not compile `ctrlc` (lib) due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dioxus-cli v0.4.3`, intermediate artifacts can be found at `/var/folders/8_/lr86571j2_s483v2knvcgsdh0000gn/T/cargo-installBPVdLY`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by jkelleyrtp** [comment]
Looks like some configurations of some macs are having issues finding the iconv library.

https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx

Perhaps you upgraded from an x86 mac to an aarch64 mac and the old iconv is being linked in (via rosetta) but is not working.

I don't think there's anything we can do other than point users to this issue.
