### ISSUE TITLE
A static-site-generator platform target 

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#2006]
## Feature Request

My personal site, floneum's site, and the docsite all use dioxus in a mode with static-site-generation enabled.

However, we keep writing the same code to pre-render the site, hydrate it, etc.

With all the work in the new manifest system, we should make our tooling 1st class when used alongside static site generation. 

I imagine many folks would want to use dioxus for their statically-generated sites - and it's actually quite great at that. 

https://github.com/jkelleyrtp/jkelleyrtp.github.io

**Comment by wheregmis** [comment]
I also made a small portfolio using Dioxus getting inspiration from @jkelleyrtp's repo. 
Repo: https://github.com/wheregmis/wheregmis.github.io
Link: https://wheregmis.github.io/
It is really great indeed.
