### ISSUE TITLE
enhancement: Support manual drop of Signals

### ISSUE THREAD

**Issue by marc2332** [DioxusLabs/dioxus#2009]
## Feature Request

Currently, signals are only dropped when their assigned Scope is dropped, therefore creating Signals outside of the render component like event handlers or async tasks multiple times will end leaking memory, which is expected as you aren't really supposed to be creating signals in places like that, but, if you do, it would be very much helpful to have a way to drop these signals so they don't leak.

This would be useful for https://github.com/marc2332/freya/pull/533 where I have a registry map of signals that hold some assets bytes, therefore, when an asset cache duration expires, the signal is removed, but this is done in an async task, so the signal isn't really dropped, and instead it leaks memory. It would be nice to have some way to prevent this, so code like this could work:

```rs
fn app() -> Element {
    let mut data = use_signal(|| None);

    let onclick = move |_| {
        let value = Signal::new((0..999999).map(|_| 1f64).collect::<Vec<f64>>());
        *data.write() = Some(value);
    };

    rsx!(
        button {
            onclick,
            "the more you click the more it consumes"
        }
    )
}
```

**Comment by jkelleyrtp** [comment]
I believe you can call `take` on the signal/copyvalue and it will give you the original value, which would then be dropped.

After that, the signal container itself will be recycled.

@ealmloff can you verify? Also, maybe take() should give an option instead, so we don't accidentally panic if the value has already been taken.

**Comment by ealmloff** [comment]
Yes I thought we implemented this at some point, `take` does this currently. I think it should be renamed to/aliased as `drop`:
- We already have a `take` method on the writable trait that works like `std::mem::take`.
- Take isn't something I would search for when looking for something drops a value which seems to be the main use case of the method (I didn't find it when tagging this issue)

**Comment by marc2332** [comment]
Nice, this seems to work!:

```rs
fn app() -> Element {
    let mut data = use_signal::<Option<Signal<Vec<f64>>>>(|| None);

    let increase = move |_| {
        if let Some(signal) = data.write().take() {
            signal.take();
        }
        let value = Signal::new((0..999999).map(|_| 1f64).collect::<Vec<f64>>());
        *data.write() = Some(value);
    };

    rsx!(
        Button {
            onclick: increase,
            label { "make big" }
        }
    )
}
```

I agree that a better naming would be nice 😄
