### ISSUE TITLE
High cpu usage on resize

### ISSUE THREAD

**Issue by aqdd** [DioxusLabs/dioxus#2012]
resize window, do not release left mouse button, and repeat it. the mgr cpu up to 80%+.
same in wgpu lib.

**Comment by jkelleyrtp** [comment]
We can't fix this as it's an issue upstream. 

Reporting an issue with profanity in the title is not welcome. Please keep future issues high quality and appropriate.

**Comment by aqdd** [comment]
> We can't fix this as it's an issue upstream.
> 
> Reporting an issue with profanity in the title is not welcome. Please keep future issues high quality and appropriate.

Sorry
