### ISSUE TITLE
Error compiling desktop project on linux (`linking with 'cc' failed`)

### ISSUE THREAD

**Issue by jonnyandrew** [DioxusLabs/dioxus#2015]
**Problem**

Error compiling a desktop app on Ubuntu Linux:

```
error: linking with `cc` failed: exit status: 1
```

**Steps To Reproduce**

- Create an empty hello world project (based on [the getting started guide](https://dioxuslabs.com/learn/0.5/getting_started/desktop#creating-a-project))
- Run `cargo run` OR
- Run `dx serve --hot-reload --platform desktop`

Note that I already followed the [desktop getting started guide](https://dioxuslabs.com/learn/0.5/getting_started/desktop) to
- Install [Tauri prerequisites](https://beta.tauri.app/guides/prerequisites/#linux)
- Install WebkitGtk
  
**Expected behavior**

Sample project compiles and runs.

**Screenshots**

N/A

**Environment:**
 - Dioxus version: v0.5.0-alpha.0
 - Rust version: 1.76.0
 - OS info: Ubuntu Linux
 - App platform: `desktop`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Does the error you get with `cargo run` have any more information than `linking with `cc` failed: exit status: 1`? Generally link errors will have more specific information about what part of linking fails.

**Comment by Tahinli** [comment]
>sudo apt install gcc-multilib

this may fix.

**Comment by jonnyandrew** [comment]
> Does the error you get with `cargo run` have any more information than `` linking with `cc` failed: exit status: 1 ``? Generally link errors will have more specific information about what part of linking fails.

Ah sorry, I didn't spot it the first time round:

```
cannot find -lxdo: No such file or directory
```

I fixed the problem by installing `libxdo-dev` :) Thanks for your help!

**Comment by nully0x** [comment]
to fix on fedora, you should install 

`sudo dnf install libxdo-devel`

**Comment by bluenote10** [comment]
It should be noted that this currently leads to a somewhat rough experience for new users: Just checking out the repo and running `cargo run --example hello_world` results in an intimidating:

![image](https://github.com/DioxusLabs/dioxus/assets/3620703/f6aa20f8-7d2b-4df8-98da-b0c3307b5999)

I'm wondering if the hard dependency on `-ldxo` is actually intentional, or could it be made optional? Why does running the example depend on linking to an x11 automation tool?

**Comment by nully0x** [comment]
Yeah, I faced the same issue while following this [https://dioxuslabs.com/learn/0.5/getting_started](https://dioxuslabs.com/learn/0.5/getting_started). 

I had to also run `sudo dnf install perl` also to make it build on my machine

**Comment by 0Akise** [comment]
also encountered same issue on Arch Linux, and solved by doing
```
sudo pacman -S xdotool
```

it will install `libxdo` and fixes the issue for Arch :)
