### ISSUE TITLE
Tailwind CSS example: including stylesheets using the mg! not work.

### ISSUE THREAD

**Issue by alecthw** [DioxusLabs/dioxus#2019]
**including stylesheets using the mg! not work**

run the [TailwindCSS example](https://github.com/DioxusLabs/dioxus/tree/main/examples/tailwind) using `dx serve`, 
stylesheet does not take effect.

**Steps To Reproduce**

- run the [TailwindCSS example](https://github.com/DioxusLabs/dioxus/tree/main/examples/tailwind) using `dx serve`,

**Expected behavior**

stylesheet  take effect.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/22856212/620b0daf-402d-4df5-b21f-36ba74f6c658)

**Environment:**
 - Dioxus version: [`master`]
 - Rust version: [`1.76.0`]
 - OS info: [windows 11]
 - App platform: [`web`]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Fixed by https://github.com/DioxusLabs/collect-assets/pull/12
