### ISSUE TITLE
`dx serve` build fails when using cookies feature on reqwest crate

### ISSUE THREAD

**Issue by Harjun751** [DioxusLabs/dioxus#2099]
**Problem**

As per title. Everything works fine until using a method provided only in the cookies feature. The project builds fine using `cargo build`
```
Error: 🚫 Serving project failed: error[E0599]: no method named `cookie_store` found for struct `ClientBuilder` in the current scope
--> src\main.rs:21:42
   |
21 |     let cli = reqwest::Client::builder().cookie_store(true).build().unwrap();
   |                                          ^^^^^^^^^^^^ method not found in `ClientBuilder`
```

My main.rs:
```
#![allow(non_snake_case)]
// import the prelude to get access to the `rsx!` macro and the `Scope` and `Element` types
use dioxus::prelude::*;

fn main() {
    // launch the web app
    dioxus_web::launch(App);
}

// create a component that renders a div with the text "Hello, world!"
fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "Hello, world!"
        }
    })
}

async fn brokey(){
    let endpoint = format!("http://dinguswingus.com/dingus");
    let cli = reqwest::Client::builder().cookie_store(true).build().unwrap();

    cli.post(endpoint).send().await;
}
```

**Steps To Reproduce**

Create a new demo project as usual, then add reqwests with cookies
- cargo new --bin demo
- cargo add dioxus
- cargo add dioxus-web
- cargo add reqwest --features cookies
- Add some code that uses the cookies feature, like below:
```
async fn brokey(){
    let endpoint = format!("http://dinguswingus.com/dingus");
    let cli = reqwest::Client::builder().cookie_store(true).build().unwrap();

    cli.post(endpoint).send().await;
}
```

**Expected behavior**

The build doesn't fail :(

**Environment:**
 - Dioxus version: 0.4.3
 - dioxus-cli version: Tried 0.4.3, and 0.5.0-alpha.2
 - Rust version: 1.74.0
 - OS info: Windows
 - App platform: web

**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
`cargo build` will build an application that targets your current platform. `cargo build --target wasm32-unknown-unknown` will build an application that targets WASM (like dioxus web). reqwest. It looks like reqwest doesn't support cookies in wasm: https://github.com/seanmonstar/reqwest/pull/1449
