### ISSUE TITLE
Cannot use EventHandlers with `#[derive(Props)]`

### ISSUE THREAD

**Issue by marc2332** [DioxusLabs/dioxus#2120]
**Problem**

Example: 
```rs
#[derive(Props, PartialEq, Clone)]
pub struct SomeProps<T: 'static + PartialEq + Clone> {
    value: EventHandler<T>,
}
```

Probably caused by https://github.com/DioxusLabs/dioxus/pull/2119

**Expected behavior**

Compile

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/38158676/8d0d2c07-2681-40e1-a3bc-baa44c5918d6)

**Environment:**
 - Dioxus version: `main`
 - Rust version: latest
 - OS info: Windows
 - App platform: Freya

**Comment by ealmloff** [comment]
#2122 fixes the above code example, but we should probably not require the `Clone` and `PartialEq` bounds on `T`. The `Clone` and `PartialEq` derive macros automatically add a where clause that only implements the trait if `T: Clone + PartialEq`. The `Props` macro should do something similar
