### ISSUE TITLE
File Input on Desktop Not Displaying File Dialog When Clicked

### ISSUE THREAD

**Issue by matteron** [DioxusLabs/dioxus#2132]
**Problem**

Using `rsx! { input { r#type: "file" } }` to create a file input correctly inserts the element, but clicking on the input does not open up a file dialog for the user to pick a file.

**Steps To Reproduce**

- Create a new Dioxus desktop app on 0.5-alpha.2.
- Create an input control:
``` Rust
rsx! { input { r#type: "file" } }
```
- Run app and click input.

**Expected behavior**

A native file dialog opens up and allows the user to select files.

**Edit: More Info**
I should emphasize, I barely understand the codebase yet, but doing some preliminary investigation I seem to have found the problem might be related to the input element not having a `"data-dioxus-id"` attribute assigned to it causing the event to get ignored in the event listener in native.ts line 65 since `getTargetId` is returning null in this case.

**Environment:**
 - Dioxus version: 0.5-alpha.2
 - Rust version: 1.77
 - OS info: MacOS
 - App platform: Desktop
 
**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start

**Comment by jkelleyrtp** [comment]
Well........ if you attach an oninput listener to the input event the file dialog *does* show - it's just weird that without the listener we don't show the dialog. 

This works:
```rust
rsx! { input { r#type: "file", oninput: move |_| {} } }
```

Is there actually any utility for file inputs on desktop that don't handle the file?
