### ISSUE TITLE
Re-add SystemTray from Tauri

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#2138]
## Feature Request

Tauri made a refactor that pulled out muda, globalhotkey, and system tray into their own crates, which meant we lost that builtin functionality. We've added back muda and globalhotkey, but not tray yet.

Refactor:
https://github.com/tauri-apps/tao/pull/778/

The crate:
https://github.com/tauri-apps/tray-icon/

We should add tray back into the desktop renderer so users can build system trays with dioxus.

**Comment by cosmincatalin** [comment]
Would being able to close the main window but keeping the app running be part of this as well?

**Comment by emadbaqeri** [comment]
> Would being able to close the main window but keeping the app running be part of this as well?

Yeah, I think we should register a handler for `app_request_close` or something like this and run the app in the background. I think it works the way that `tauri` handles. I think having a tray icon without app running in the background does not have a point.

**Comment by GetPsyched** [comment]
Has there been any update on this since? I would love to have this feature!
