### ISSUE TITLE
"Choose Files" button in `file_upload` example causes app to hang for linux desktop

### ISSUE THREAD

**Issue by davidMcneil** [DioxusLabs/dioxus#2149]
**Problem**

Clicking "Choose Files" button in `file_upload` example causes app to hang on linux desktop ubuntu 22.04.

**Steps To Reproduce**

- `cargo run --example file_upload`
- push "Choose Files"
- app becomes stuck.

**Expected behavior**

Open file dialog. It hangs as if it is waiting for file selection but the file explorer is never opened. Works great on web so maybe some oddity of my OS.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/1497626/75414fb2-bf7a-428b-a29d-eb030e4df21d)

**Environment:**
 - Dioxus version: `master@9888d36`
 - Rust version: `1.77.0`
 - OS info: XFCE Ubuntu 22.04
 - App platform: `desktop`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
We use https://github.com/PolyMeilex/rfd to handle the file popup - can you check to see if these work for you?

**Comment by davidMcneil** [comment]
Interesting, rfd `cargo run --example simple` worked fine. It does not seem to make it to the handler:

```rust
fn app() -> Element {
    rsx! {
        input {
            r#type: "file",
            oninput: move |evt| {
                info!("file input {:?}", evt);
            }
        }
        input {
            r#type: "text",
            oninput: move |evt| {
                info!("text input {:?}", evt);
            }
        }
    }
}
```

**Comment by davidMcneil** [comment]
Looks like this line is blocking `dialog.pick_file().into_iter().collect()`. Replacing it with `vec![]` at least prevents the app from locking up.

**Comment by davidMcneil** [comment]
fix https://github.com/DioxusLabs/dioxus/pull/2161
