### ISSUE TITLE
why my screen is blank when I execute the  examples in dioxus

### ISSUE THREAD

**Issue by litieqq** [DioxusLabs/dioxus#215]
Hello, I encountered a problem that when i update the lastest source code(version: 1.0.8) and try to execute the examples(eg: calculator、hello_world) , all window shown is blank.

![image](https://user-images.githubusercontent.com/10518204/152770558-db2b5d53-f314-436d-b6f1-1fafde068654.png)

**Comment by jkelleyrtp** [comment]
Can you make sure you're on the latest master (git pull, git reset, clone afresh, etc whatever it takes to have the same source code as this github repo)?

If the issue persists, can you right-click the window, click Inspect Element, navigate to console, and report any errors that might have popped up while running the `hello_world` example?

**Comment by litieqq** [comment]
Yes, my version is the latest master. I operated as you saying and found the following error message.
![image](https://user-images.githubusercontent.com/10518204/152904210-56042f6d-5b17-4cfa-8438-8eaecceca45e.png)

Unhandled Promise Rejection: SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.
(anonymous function) — index.js:9
promiseReactionJob
Selected Element
<html>
<head>…</head>
<body>…</body>
</html>
![image](https://user-images.githubusercontent.com/10518204/152904472-9ff0eb4f-994d-479f-b473-2f31d60de330.png)

**Comment by jkelleyrtp** [comment]
> Yes, my version is the latest master. I operated as you saying and found the following error message. ![image](https://user-images.githubusercontent.com/10518204/152904210-56042f6d-5b17-4cfa-8438-8eaecceca45e.png)
> 
> Unhandled Promise Rejection: SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list. (anonymous function) — index.js:9 promiseReactionJob Selected Element
> 
> … … ![image](https://user-images.githubusercontent.com/10518204/152904472-9ff0eb4f-994d-479f-b473-2f31d60de330.png)

It looks like our javascript shim layer might be using too modern features for your javascript engine. I'll take a look and see if we can conform to an older standard.

**Comment by jkelleyrtp** [comment]
Can you try this github branch to see if the issue is fixed?

https://github.com/DioxusLabs/dioxus/pull/219

```
git clone https://github.com/DioxusLabs/dioxus.git
git checkout jk/js-ecma
```

And then run the examples.

The TypeScript compiler generated "too modern" of code and I don't think your WebKit version supports the most modern JS features.

**Comment by litieqq** [comment]
Yes, it works! 
![image](https://user-images.githubusercontent.com/10518204/152927424-157711aa-f42e-44d0-983f-fbf3adf88752.png)

**Comment by jkelleyrtp** [comment]
Awesome! Glad it works now!

**Comment by litieqq** [comment]
Thanks for your helping
