### ISSUE TITLE
dioxus-cli  does not proxy websocket connections

### ISSUE THREAD

**Issue by sjames** [DioxusLabs/dioxus#2155]
**Problem**

**Steps To Reproduce**

- Implement a websocket API endpoint using Axum.  Configure the development proxy to proxy calls to the API in Dioxus.toml using the [[web.proxy]] configuration option.

- serve the application using ```dx serve```

The UPGRADE request goes through and the upgrade request is sent back,  but the websocket connection drops as soon as it is established.

**Expected behavior**

The proxy should also allow websocket connections.

**Environment:**
 - Dioxus version: 0.4.3
 - Rust version: 1.77.0
 - OS info: Linux (Ubuntu 22.04)
 - App platform: Web

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by IgorLaborieV8** [comment]
I have the same issue with Dioxus v0.5.6

**Comment by cLazyZombie** [comment]
Has this issue been resolved? 

It seems the same problem is occurring in version 0.6.1. 

Are there any additional settings required?

**Comment by buxx** [comment]
I still have the problem with 0.6.3. See https://github.com/DioxusLabs/dioxus/issues/4080.
