### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by t1m0t** [DioxusLabs/dioxus#216]
## Specific Demand
Would be very nice to have internationalization support in Dioxus or at least a working example. This library could be integrated for this job: 
 - [cargo-i18n](https://github.com/kellpossible/cargo-i18n). Uses `fluent` or `gettext` and has support for `wasm`
 - [fluent-rs](https://github.com/projectfluent/fluent-rs)
 - [gettext](https://github.com/justinas/gettext)

## Suggested implementation
I think it is possible to integrate it through `use_provide_context` or building a hook. I could try to implement it myself.

**Comment by arkaitz-dev** [comment]
Any news on this issue?

**Comment by jkelleyrtp** [comment]
Hey! We've got something going here

https://github.com/DioxusLabs/dioxus-std/tree/master/examples/i18n

**Comment by jkelleyrtp** [comment]
Also, another library here
https://github.com/Zomatree/Dioxus-i18n
