### ISSUE TITLE
Linux下无法选择文件 (File picker not working in some Linux/WSL)

### ISSUE THREAD

**Issue by aidaodi** [DioxusLabs/dioxus#2163]
input {
                    r#type: "file",
                    multiple: true,
                    directory: true,
                    onchange: move |evt|{
                        info!("{}", evt.value());
                    },
                }
这是我的代码。在0.5.0-alpha.0下是可以选择文件的。升级到0.5.0后，无法选择文件。

**Comment by araraloren** [comment]
I faced same issue on WSL(Desktop, Vanilla). The terminal just print `Got values: []` when press `Choose file` button.

```rust
#![allow(non_snake_case)]

use dioxus::prelude::*;

fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        input {
            r#type: "file",
            directory: true,
            onchange: move |evt| {
                evt.files()
                    .map(|v| v.files())
                    .iter()
                    .for_each(|v| { println!("Got values: {v:?}") });
            }
        }
    }
}

```

The version information:

```
 ~/p/d/directory-bug (main)> rustc --version
rustc 1.79.0 (129f3b996 2024-06-10)
 ~/p/d/directory-bug (main)> dx --version
dioxus 0.5.4
 ~/p/d/directory-bug (main)> cat /etc/redhat-release
Fedora release 39 (Thirty Nine)
```

The screenshot: 
![Animation](https://github.com/DioxusLabs/dioxus/assets/15150618/dead20cb-617f-4cad-bee7-3efd68bed943)

**Comment by DogeDark** [comment]
I was able to get a file dialog to show and work correctly after installing `zenity`. For Debian-based: `sudo apt install zenity`
