### ISSUE TITLE
Broken behavior in TodoMVC example

### ISSUE THREAD

**Issue by bluenote10** [DioxusLabs/dioxus#2173]
**Problem**

Something doesn't seem to work quite right in the TodoMVC example.

**Steps To Reproduce**

- `cargo run --example todomvc`
- Add a few items
- Click on "Active" or "Completed"
- Then click on the upper left button that allows to select multiple todos

**Expected behavior**

The app should continue to work.

**Actual behavior**

The app seem to be stuck in a broken state. Clicking the "All", "Active", or "Completed" no longer works, and there are some floating elements.

**Screenshots**

[Screencast from 28.03.2024 23:45:09.webm](https://github.com/DioxusLabs/dioxus/assets/3620703/063ccbcd-97b6-4e62-80b9-a958d7d4e3c2)

**Environment:**
 - Dioxus version: master
 - Rust version: 1.77
 - OS info: Linux
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
Hmmmmm I can't repro this on mac, might be an issue related to the gtk renderer, similar to the issue in #2170 

https://github.com/DioxusLabs/dioxus/assets/10237910/843af7e6-102f-4076-913f-a590737cf0fb

**Comment by umnovI** [comment]
I've had the same issue, but now everything works fine on win11


https://github.com/DioxusLabs/dioxus/assets/30232564/afc4a2e4-3aeb-45a5-926e-35ea3ac868df

**Comment by bluenote10** [comment]
Yes I think that has fixed it, thanks!
