### ISSUE TITLE
`dioxus-cli` version on crates.io (0.5.4) is ahead of git (0.5.3) (or have a version mismatch)

### ISSUE THREAD

**Issue by foresterre** [DioxusLabs/dioxus#2175]
**Problem**

The latest [version](https://crates.io/crates/dioxus-cli/versions) published on crates.io is [v0.5.4](https://crates.io/crates/dioxus-cli/0.5.4).

The latest version on `main` (I couldn't find a more mainline branch), is `0.5.3` instead:

https://github.com/DioxusLabs/dioxus/blob/44471f4918529fd15a143854984ce3b3d58c07a9/packages/cli/Cargo.toml#L1-L4

The latest Dioxus [release on Github](https://github.com/DioxusLabs/dioxus/releases/tag/v0.5.0) has both `dx` artifacts with `0.5.3` (most of them) and some with `0.5.4`.

The currently last [Publish CI](https://github.com/DioxusLabs/dioxus/actions/workflows/publish.yml) github action built version [0.5.3](https://github.com/DioxusLabs/dioxus/actions/runs/8461660498/job/23181788958#step:7:570)

---

I originally discovered this because of another potential issue and went looking whether this may have been fixed on git, only to discover that at least the version number installed via git was less recent than the crates.io version 😅

**Comment by jkelleyrtp** [comment]
Fixed, I published a version but didn't push the commit
