### ISSUE TITLE
Broken link in the README of the GitHub organization to the roadmap

### ISSUE THREAD

**Issue by moretea** [DioxusLabs/dioxus#2179]
I noticed that the link "roadmap is public" points to a Notion page that I can not open.

It links to https://pointy-quokka-0c3.notion.site/Dioxus-Labs-Public-Roadmap-771939f47d13423abe2a2195b5617555?pvs=4

Not sure if this repo  is the right one to open the issue. Tell me if I should open it somewhere else.

**Comment by jkelleyrtp** [comment]
Fixed, should now point at github since we've moved things around https://github.com/orgs/DioxusLabs/projects/7
