### ISSUE TITLE
Tailwind classes are not hot reloaded

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#2180]
**Problem**

The blog post says that tailwind classes can now be hot reloaded, but they currently require a full recompile

**Steps To Reproduce**

- Clone the dioxus repo (rev 2461790baf302766f35861c3c85269ba90add247)
- Run:
```sh
cd examples/tailwind
dx serve
```
- Run in another terminal:
```sh
cd examples/tailwind
npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch
```
- Change a tailwind class
- Observe a normal rust recompile

**Expected behavior**

In the blog post we mention that tailwind hot reloading is supported:
![Screenshot 2024-03-29 at 8 32 45 AM](https://github.com/DioxusLabs/dioxus/assets/66571940/7cd1c680-c126-4eae-80e1-d9b8ec0ddeda)

**Environment:**
 - Dioxus version: `master`
 - Rust version: `nightly`
 - OS info: MacOS
 - App platform: `web`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
I get these working for me but I did have to play with it a bit

**Comment by bryant-video** [comment]
> I get these working for me but I did have to play with it a bit

what did you do, i cannot get tailwind class changes autoreloading

**Comment by fokklz** [comment]
I've read the source for hot-realoading, its nessescarry to include the file in your watcher. So you should have in your `Dioxus.toml`

```toml
[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets", "assets/tailwind.css"]
```

The file needs to be set in watch_path and it has to be inside the assets folder for this to work.
you may want to document this anywhere ^^

there is for example 0 mention of this in [tailwind guide](https://dioxuslabs.com/learn/0.5/cookbook/tailwind)

[discord message](https://discord.com/channels/899851952891002890/1226238123931996170/1242350762907013173)
