### ISSUE TITLE
Accessing bundled resources in android apps

### ISSUE THREAD

**Issue by LaurentMazare** [DioxusLabs/dioxus#2183]
**Problem**

I'm trying to bundle some data file in a dioxus app but when trying to access the file I get some file not found error. Not sure if this is supposed to be supported at the moment, also I might well be doing something pretty wrong here.

**Steps To Reproduce**

See this [gist](https://gist.github.com/LaurentMazare/a9531cca494db16768405a1d7ccc7f1c) for a small repro.

Basically I created a `test.txt` file in my project directory, added the following to my `Cargo.toml`:
```
[bundle]
resources = ["test.txt"]
```

And in the app code I'm trying to read the file via:
```rust
    let content = std::fs::read_to_string("test.txt");
    log::debug!("{:?}", content);
```

However when running the code on the android emulator, I get a `"No such file or directory"` error.

**Expected behavior**

Hopefully I would get the content of the file when reading it :)

**Screenshots**

N/A

**Environment:**
 - Dioxus version: 0.5.0
 - Rust version: 1.76.0
 - OS info: ubuntu 23.10 on x86_64, code is running via the emulator in Android Studio.
 - App platform: mobile

The `JAVA_HOME`, `ANDROID_HOME`, and `NDK_HOME` environment variables are hopefully properly set.

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This is an area where integrating mobile tooling with dioxus would be very helpful (#2091). We currently add any assets you use with manganis or in the bundle.resources section to the list of assets to bundle on desktop, but it looks like we are not doing this for mobile builds.

It looks like the config in cargo mobile2 [accepts an assets directory](https://github.com/tauri-apps/cargo-mobile2/blob/dev/src/config/app/mod.rs#L71) which may be helpful here.

We may also need to either add extra logic to read assets on android or use the existing `WebViewBuilderExtAndroid` trait in wry

Related issues:
- https://github.com/DioxusLabs/dioxus/issues/1560
- https://github.com/tauri-apps/wry/issues/846

**Comment by jkelleyrtp** [comment]
Closing since #1560 is basically the same thing - but thank you so much for the very detailed issue report.

We didn't have time for this in the 0.6 release but our plans for 0.7 involve a mobile overhaul, fixing this.
