### ISSUE TITLE
dioxus-cli generate old tailwind fullstack example with multipage bug

### ISSUE THREAD

**Issue by gusinacio** [DioxusLabs/dioxus#2186]
**Problem**

I created a fullstack project using the `dx` cli and selected to use Tailwind. The problem is that it uses the older configuration via `Dioxus.toml` style config in `[web.resource]`. The starter code contains a bug already mapped and fixed on #1292. 

**Steps To Reproduce**

- `dx new`
- Give a name
- Select fullstack
- Select to use the router
- Select tailwind
- Take a look on `Dioxus.toml` and see `style = ["tailwind.css"]`
**Expected behavior**

Create a starter code using the latest example from `examples/fullstack/tailwind` or create an example with the fixed version using `style = ["/tailwind.css"]`

**Screenshots**

**Environment:**
 - Dioxus version: 0.5.0
 - Rust version: 1.77
 - OS info: MacOS
 - App platform: fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Andrew15-5** [comment]
I've tested https://github.com/DioxusLabs/dioxus-template/pull/46, this should fix the issue.

You can test it now:

```sh
cargo install --git https://github.com/Andrew15-5/dioxus.git --branch rewrite-dx-init-new dioxus-cli
dx new -y --template https://github.com/Andrew15-5/dioxus-template --branch use-absolute-style-path --subtemplate Fullstack -o router=true -o styling=Tailwind name
cd name
rg 'style = '
```

**Comment by mrxiaozhuox** [comment]
@ealmloff @jkelleyrtp can you close this issue.
