### ISSUE TITLE
Dioxus fullstack livereload bugs out if using `use_server_future` with the automatic suspend functionality (i.e. ?) when sleeping

### ISSUE THREAD

**Issue by Silvea12** [DioxusLabs/dioxus#2193]
**Problem**

When refreshing your app with fullstack and a `use_server_future()` with a `?` to suspend as per the docs, when using tokio sleep, the page infinitely reloads.

**Steps To Reproduce**

- Create a fullstack app from the standard template
- Create a server fn:
```rs
#[server]
async fn my_server_fn() -> Result<(), ServerFnError> {
    use tokio::time::*;
    sleep(Duration::from_secs(1)).await;
    Ok(())
}
```
- Use said server fn via `use_server_future(my_server_fn)?;` in a component. No need to actually use the value.
- Load the page, all is normal.
- Hit F5. Watch the page go into an infinite reload loop.

See this in the server logs:
<details><summary>Logs</summary>

The blank line here is every time it pauses for the sleep.
```
[INFO] dioxus_fullstack::render - Suspense resolved
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_signals::signal - new_maybe_sync;
[INFO] dioxus_fullstack::hooks::server_future - First run of use_server_future

[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_signals::signal - new_maybe_sync;
[INFO] dioxus_fullstack::hooks::server_future - First run of use_server_future
[INFO] dioxus_fullstack::render - Suspense resolved

[INFO] dioxus_fullstack::render - Suspense resolved
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_signals::signal - new_maybe_sync;
[INFO] dioxus_fullstack::hooks::server_future - First run of use_server_future

[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_signals::signal - new_maybe_sync;
[INFO] dioxus_fullstack::hooks::server_future - First run of use_server_future
[INFO] dioxus_fullstack::render - Suspense resolved
```
</details>

**Expected behavior**

It should not infinitely reload

**Screenshots**

N/A

**Environment:**
 - Dioxus version: `0.5.0` release, dioxus git `9f280a8d84c183c74db3452d60a4601aa343813c` (main at time of project creation)
 - Rust version: `1.77.1`
 - OS info: `Linux 6.8.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC x86_64 GNU/Linux`
 - App platform: `fullstack`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
I cannot reproduce this issue with dioxus `0.5.0`: https://github.com/ealmloff/reproduce-dioxus-fullstack-2193

The page takes 1 second to reload, but does not reload in a loop

**Comment by Silvea12** [comment]
I can reproduce it with your demo. See the attached video.
[Screencast_20240402_021207.webm](https://github.com/DioxusLabs/dioxus/assets/3120639/db8f97cc-2780-403e-9f6b-e53991bd3095)
