### ISSUE TITLE
Accept RKYV archive for fullstack as answer?

### ISSUE THREAD

**Issue by XavDesbordes** [DioxusLabs/dioxus#2206]
Hi,
According to [https://dioxuslabs.com/learn/0.5/reference/fullstack/server_functions](https://dioxuslabs.com/learn/0.5/reference/fullstack/server_functions), an answer must be serializable by serde.

For people using binary protocols (Rkyv, others) it implies a Serialization/Deserialization first before, which may be costly.
`Alignedvec` would help at the very least to avoid this.

Any opinion?

**Comment by ealmloff** [comment]
That page is a bit out of date. Return values can now choose any of [these codecs](https://docs.rs/server_fn/0.6.9/server_fn/codec/index.html) including rkyv by setting the output encoding. Here is an example that uses the streaming text encoding: https://github.com/DioxusLabs/dioxus/blob/0850dcba5e91912ac9de1b02443cebd9b8ec2349/packages/fullstack/examples/axum-streaming/src/main.rs#L26

**Comment by XavDesbordes** [comment]
Nice, that's great! thanks!
