### ISSUE TITLE
Desktop quickstart demo cannot show in macos

### ISSUE THREAD

**Issue by qqke** [DioxusLabs/dioxus#2208]
Can not show any elements on my macos wih dioxus@0.5

**Comment by ealmloff** [comment]
I cannot reproduce it with that setup on macOS with the 0.5.0 version of the CLI. It might be an error that is specific to the version or your webview. If you are interested in debugging this issue, more information about the syntax error in your console would be useful. We might be compiling to a newer version of javascript for the [interpreter](https://github.com/DioxusLabs/dioxus/tree/main/packages/interpreter/src/ts) than what your browser supports

**Comment by qqke** [comment]
It is possible that my outdated macOS Catalina 10.15.7 installation was causing the issue. After switching to Windows 11, the problem no longer occurs.
