### ISSUE TITLE
bug: Bloated CLI rendering in certain terminal emulators

### ISSUE THREAD

**Issue by marc2332** [DioxusLabs/dioxus#2221]
Wezterm:

![image](https://github.com/DioxusLabs/dioxus/assets/38158676/c8ebc6fd-e65d-4d99-83bb-82d322b55afe)

every update causes a new line break

**Comment by neupsh** [comment]
same with KDE plasma console (I have plasma 6, not sure if it matters).

**Comment by tigerros** [comment]
Same issue in RustRover's integrated terminal with Dioxus CLI 0.5.4
