### ISSUE TITLE
Fail to Read `dist/__assets_head.html`

### ISSUE THREAD

**Issue by photino** [DioxusLabs/dioxus#2231]
**Problem**

We have upgraded to Dioxus 0.5 in our application framework [Zino](https://github.com/zino-rs/zino). The `dioxus-desktop` example outputs the following error:

```bash
ERROR dioxus_desktop::protocol: Failed to read "D:\\code\\git\\github\\zino\\examples\\dioxus-desktop\\dist\\__assets_head.html"
```
It is somewhat annoying. How can we fix it if the file does not exists?

**Steps To Reproduce**

- `git clone https://github.com/zino-rs/zino.git`
- `cd examples/dioxus-desktop`
- `cargo run`

**Expected behavior**

No errors.

**Screenshots**

**Environment:**
 - Dioxus version: `0.5`
 - Rust version: `1.77`
 - OS info: `Windows`
 - App platform: `desktop`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
That error will go away if you build your application with the dioxus cli with `dx serve`. Without the head file, [manganis](https://github.com/DioxusLabs/collect-assets) assets will not be preloaded and css files will not be injected into the head. We can downgrade [this error](https://github.com/DioxusLabs/dioxus/blob/main/packages/desktop/src/protocol.rs#L89) to a warning about assets not being preloaded if the application is not built with the dioxus cli
