### ISSUE TITLE
`dx`'s help message shows that the hot-reloading is disabled by default, which is false (no pun intended)

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#2233]
**Problem**

```
      --hot-reload
          Build with hot reloading rsx. Will not work with release builds. [default: false]
```

It should say `true`. But how would you disable it? Can you pass in true/false? Maybe there should be a `--no-hot-reload` option instead.

**Steps To Reproduce**

- `dx -h`
- see the thing

**Expected behavior**

The message should say `true`.

**Environment:**
 - Dioxus version: v0.5.4
 - Rust version: 1.79.0, nightly
 - OS info: Pop_!OS
 - App platform: fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by Apollo-Roboto** [comment]
I find this flag confusing too. When trying to disable hot-reload, it throws an error:

```
> dx serve --hot-reload false

error: unexpected argument 'false' found

Usage: dx.exe serve [OPTIONS] [-- <CARGO_ARGS>...]

For more information, try '--help'.
```

It seems impossible to disable hot reload.

**Comment by Yash-271120** [comment]
@ealmloff Hey there!
I have recently learnt about rust and would like to contribute to the issue.

**Comment by Andrew15-5** [comment]
`clap` already adds default value if value can be set and omitted:

![image](https://github.com/DioxusLabs/dioxus/assets/37143421/97419440-ed0e-41ce-a0e0-a436ae787965)

After compiling:

![image](https://github.com/DioxusLabs/dioxus/assets/37143421/fd7c3eac-164d-42a4-bbcc-b4c01b4b93b9)
