### ISSUE TITLE
ios mobile setup does not work

### ISSUE THREAD

**Issue by dignifiedquire** [DioxusLabs/dioxus#2241]
I was running through the mobile section for `0.5`, for ios

- compile fails like in #1512 , adding `desktop` to the `dioxus` features fixes this
- after running `cargo apple open` building fails with xcode
<img width="847" alt="Screenshot 2024-04-04 at 20 20 47" src="https://github.com/DioxusLabs/dioxus/assets/790842/da7a39ac-4bfb-4535-98af-0b3619ec0c65">

**Comment by jkelleyrtp** [comment]
We just added a template to cargo-mobile2 and fixed some bugs related to iOS setup. iOS setup also got updated on the docsite.
