### ISSUE TITLE
Dioxus desktop 0.5+ doc generation

### ISSUE THREAD

**Issue by jbousquie** [DioxusLabs/dioxus#2284]
Hi,
It would be nice if the dioxus-desktop crate documentation generation could be fixed for versions >= 0.5 : 

https://docs.rs/crate/dioxus-desktop/latest
https://docs.rs/crate/dioxus-desktop/0.5.1/builds

I'm trying to set correctly a deskop app window size and I guess the way to do it is somewhere in this crate :-)

Thanks for your incredible work so far !

**Comment by tigerros** [comment]
In the meantime you can use `cargo doc` to view the docs locally.
