### ISSUE TITLE
enable `grid` attributes

### ISSUE THREAD

**Issue by seanandyrush** [DioxusLabs/dioxus#229]
## Specific Demand

seems like there is not support of `grid` attributes, which are essentials to me.

no method named `grid_auto_flow` found for struct `div` in the current scope
method not found in `div`

**Comment by jkelleyrtp** [comment]
Do you know of a good list of *all* the css classes?

We don't really have a way of doing arbitrary style attributes right now so you can't even work around missing CSS attributes.
