### ISSUE TITLE
unable to run desktop app on ubuntu22.04 LTS

### ISSUE THREAD

**Issue by learncodingforweb** [DioxusLabs/dioxus#2317]
**Problem**
if try to app app using **dx serve --hot-reload --platform desktop** getting error on ubuntu22.04LTS
note: /usr/bin/ld: cannot find -lxdo: No such file or directory
          collect2: error: ld returned 1 exit status

```
uname -a
Linux notebook 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```
**Steps To Reproduce**

dx new
✔ 🤷   Which sub-template should be expanded? · Desktop
🤷   Project Name: myapp
✔ 🤷   How do you want to create CSS? · Tailwind
✔ 🤷   Should the application use the Dioxus router? · false

dx serve --hot-reload --platform desktop

**Expected behavior**

App should run ubuntu22.04

**Environment:**
 - Dioxus version: dioxus 0.5.0
 - Rust version: 
 ```
rustc --version 
rustc 1.77.2 (25ef9e3d8 2024-04-09)

rustup --version
rustup 1.27.0 (bbb9276d2 2024-03-08)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.77.2 (25ef9e3d8 2024-04-09)
```

 - OS info: ubuntu22.04
 - App platform: desktop

**Comment by learncodingforweb** [comment]
resolve issue by installing **sudo apt install libxdo-dev**. please mention Prerequisites

**Comment by smirzaei** [comment]
For Arch Linux users, you need to install the [xdotool](https://archlinux.org/packages/extra/x86_64/xdotool/) package.
