### ISSUE TITLE
dx build recompiles everything every time when using a cargo workspace

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#2326]
**Problem**

When having a Dioxus fullstack app as part of cargo workspace, running `dx build` always recompiles everything. The same doesn't happen with `dx serve` though.

**Steps To Reproduce**

Create a new Rust project using cargo workspace. 
Add a Dioxus fullstack project as a workspace member.
Run `dx build` in the fullstack project dir.
Run it again.

**Expected behavior**

It should not recompile anything, when nothing is changed.

This problem does not happen when having a standalone Dioxus fullstack or desktop app that is not part of a workspace.

**Environment:**
 - Dioxus version: 0.5.1 (CLI version 0.5.4)
 - Rust version: 1.76
 - OS info: Win11 WSL2 Ubuntu 22.04
 - App platform: fullstack

**Comment by hampuslidin** [comment]
I can reproduce this everytime on a non-workspace project as well:

1. Run `dx new`.
2. Select `Fullstack`.
3. Give it any project name.
4. Choose either `true` or `false` for using the Dioxus router.
5. Choose Vanilla CSS.
6. Go into the project directory.
7. Run `dx build --platform fullstack`.
8. Run `dx build --platform fullstack` again and observe it being recompiled.
 
dioxus-cli version: 0.5.4

**Comment by jkelleyrtp** [comment]
This is due to 1) how we handle rustflags for optimizations and 2) where we place out artifacts for parallel builds - this should be mostly fixed when we move to profiles instead of implicit rustargs #2780

**Comment by jkelleyrtp** [comment]
We use profiles now in #2862 but this bug issues in a secondary form which is getting fixed in #2779
