### ISSUE TITLE
Collect data about builds with dx and output it somewhere

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#2333]
## Feature Request

While working on the status/health page, I realized we have no simple way of getting all the important stats that someone might care about when building dioxus apps.

This includes:
- build timings
- size of wasm
- size of assets and compression stats
- performance metrics / benchmarks (ie cargo bench)
- passed tests (ie cargo test)
- time to compile, time to optimize, and time spent generating llvm-ir so we can better diagnose compile times

And more.

This would just let us run the dioxus-cli as a library and get the outputs we need for the status page.

We would also be able to log it into the `dx serve` status page so folks have a good sense of how big their builds are.

**Comment by DogeDark** [comment]
Is this meant to be telemetry uploaded to a database?

**Comment by jkelleyrtp** [comment]
> Is this meant to be telemetry uploaded to a database?

It could be used for telemetry but I mostly want 1) folks to know how big their apps are and 2) benchmark open PRs against `main` to see if they cause regressions or improvemenets.

**Comment by DogeDark** [comment]
There has been the occasional time when I've thought that having a database could be handy. For example the Dioxus Awesome page could be more interactive with one and we could have liveops on the website.

**Comment by jkelleyrtp** [comment]
With the structured logging and the dx-wire-format, this is mostly done - we just need to start expanding what we output.
