### ISSUE TITLE
dx fmt deletes comments in non-expression postion

### ISSUE THREAD

**Issue by magikmw** [DioxusLabs/dioxus#2341]
**Problem**

Using `dx fmt` on source files is deleting comments, both in rsx macros and standard rust when using `--all-code`.  
This is especially egregious because standard `rustfmt` formatter is really messing up any files with rsx in them, so `dx fmt` is the only viable alternative.

**Steps To Reproduce**

- Put any comments into a file - either inside rsx or elsewhere
- Run `dx fmt -f yourfile.rs`
- Comments deleted

**Expected behavior**

Comments should be left alone.  
I'm not entirely sure how `rustfmt` does it, but with my limited experience with it, it seems to keep comments intact and relatively in the relevelant place after formatting.

**Screenshots**

n/a

**Environment:**
 - Dioxus version: 0.5.1
 - Rust version: rustc 1.77.2 (25ef9e3d8 2024-04-09)
 - OS info: Fedora 40 beta
 - App platform: n/a (but I'm making a fullstack app)

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by DogeDark** [comment]
I am unable to reproduce this using the git version of the CLI. Can you test the git version of the CLI on your end?

You can install the git version with:
```
cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
```

**Comment by magikmw** [comment]
I did run the command to install git version and checked again:

```diff
-                // TODO: Implement event handling here -> listen to eve
nts in child
                 let accept_keys = [Key::Enter, Key::Character(" ".to_string())];
-                if accept_keys.contains(&evt.key()){
+                if accept_keys.contains(&evt.key()) {
                     log::info!("{} pressed in {}", evt.key(), "{props.labelText}");
                     log::info!("{} pressed in {}", evt.key(), "{props.labelText}");
                 }
             },
             class: "flex flex-1 h-full w-3/4 items-center justify-center btn btn-outline my-1 py-1",
-            div { class: "flex-none py-1", // TODO: Refactor into separate component
+            div { class: "flex-none py-1",
                 Icon { width: 24, height: 24, icon: props.icon, title: "{props.iconTitle}" }
-            },
+            }
             "{props.labelText}"
-            input { // TODO: Refactor into separate component
+            input {

```

dx -V says:

`dioxus 0.5.2`

**Comment by DogeDark** [comment]
I can reproduce it now. The formatter doesn't like inline comments and removes them completely:
```rs
rsx! {
    div {   // this comment will be removed
        "hi",
    }
}
```

**Comment by spookyvision** [comment]
this also seems to affect the VSCode Dioxus extension. Block-level comments (`/* .. */`) are also affected; doc comments (`///`) however are not.

**Comment by DogeDark** [comment]
Adding to the list.

All comments are removed in event handlers:
```rust
rsx! {
    div {
        // also occurs in move || async move
        onclick: move |_| {
            // is removed
            /* is removed */
        }
    }
}
```

**Comment by OlivierLemoine** [comment]
I think it comes from here:
https://github.com/DioxusLabs/dioxus/blob/472031d1f51557601797d1cb469f09e4f3e0ca71/packages/cli/src/cli/autoformat.rs#L249-L253

syn does not keep comments.

https://crates.io/crates/rustfmt-wrapper (or spawning `rustfmt` directly) could be used instead.
This won't help in non-rust code, but I think it's a start.

I don't know if Dioxus developers would agree with this solution, but if they do, I would be happy to do it.

**Comment by OlivierLemoine** [comment]
What if it was behind a target cfg? Wasi support spawning new tasks, so rustfmt would work.
But it's true it's not an ideal solution.
