### ISSUE TITLE
Add ability to configure "always on/pin to top" option for the Dioxus Desktop

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#2354]
## Feature Request

The "always on top" feature is blocking the file choose window (`<input type="file">`), which is supposed to be a part of the app. So not only it blocks other dev windows (editor, `dx` and `tailwind` commands), but also itself. And when moving to the virtual desktop with that window and an editor, it will always refocus on that window, instead of the previously focused editor, which is just not a great DX, to put it mildly.

## Implement Suggestion

Probably a toggle either in the `Dioxus.toml` file or in the `dioxus::desktop::Config::new()`.

**Comment by SophieSilver** [comment]
You can pass a `WindowBuilder` to the config using `Config::with_window()`. 

The `WindowBuilder` lets you configure whether you want the window to always be on top (https://docs.rs/tao/latest/tao/window/struct.WindowBuilder.html#method.with_always_on_top).

**Comment by DogeDark** [comment]
They mean for the CLI. It had a new feature that keeps the desktop window always on top while running in dev mode.

**Comment by Andrew15-5** [comment]
I think it's a new version of Dioxus and not `dx`.

The `WindowBuilder` method can serve as a workaround.

**Comment by DogeDark** [comment]
I tested the file input issue mentioned here, and it looks to be resolved (let me know if this isn't the case for you!). I linked a PR for the always-on-top setting request.
