### ISSUE TITLE
Dioxus CLI MSRV

### ISSUE THREAD

**Issue by hilpara** [DioxusLabs/dioxus#2378]
**Problem**

Can't compile dioxus-cli v0.5.4. What is the MSRV for cli? I can't find any information about it. What is the MSRV for Dioxus itself?

`Updating crates.io index
  Downloaded dioxus-cli v0.5.4
  Downloaded 1 crate (144.1 KB) in 0.18s
  Installing dioxus-cli v0.5.4
error: failed to compile `dioxus-cli v0.5.4`, intermediate artifacts can be found at `/tmp/cargo-installLEyIVT`

Caused by:
  failed to select a version for `env_logger`.
      ... required by package `dioxus-cli v0.5.4`
  versions that meet the requirements `^0.11.3` are: 0.11.3

  the package `dioxus-cli` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
   It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

  failed to select a version for `env_logger` which could resolve this conflict`

**Steps To Reproduce**

- cargo install dioxus-cli 

**Expected behavior**

Compile successful.

**Environment:**
 - cargo 1.67.1 - can't update it for embedded target

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by nitesik** [comment]
Try updating your compiler.

```
rustup update
```
