### ISSUE TITLE
Dioxus-cli ignores env variables in `.cargo/config.toml`

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#2384]
**Problem**

In my project I have defined env variables for the server (database URL etc) in `.cargo/config.toml` file and if I run the fullstack app with `cargo run --features server` the environment is correctly set up. However, if running it with `dx serve`, none of the env variables are set.

**Steps To Reproduce**

- create a `.cargo/config.toml` with an `[env]` section and define some environment variables
- run the project wth `dx serve`
- the env variables are not set for the server executable

**Expected behavior**

Should work the same as `cargo run`

**Environment:**
 - Dioxus version: 0.5.4 (cli)
 - Rust version: 1.76
 - OS info: Win11 WSL2 Ubuntu
 - App platform: fullstack

**Comment by ochrons** [comment]
#2259 might be related

**Comment by DogeDark** [comment]
Yes, it looks like the same issue. I'm going to close this in favor of #2259 and PR #2372. Thanks for the report!
