### ISSUE TITLE
[Desktop] Hot reloading does not work in the "tailwind" sample

### ISSUE THREAD

**Issue by thurn** [DioxusLabs/dioxus#2386]
**Problem**

Hot reloading does not work on "desktop" platform on current master (472031d1f51557601797d1cb469f09e4f3e0ca71) for the "tailwind" sample. It works correctly with the "web" platform.

OSX 14.2
rustc 1.77.2

**Steps To Reproduce**

- Clone dioxus from github
- Run "dx serve --platform desktop" in the "dioxus/examples/tailwind" directory
- Change any text in main.rs
- Observe that the text is not changed

**Comment by jkelleyrtp** [comment]
Fixed in #2779
