### ISSUE TITLE
Lifetime issue for Auto Conversion of the Children Field

### ISSUE THREAD

**Issue by cryptoquick** [DioxusLabs/dioxus#239]
**Problem**

Trying to follow the guide here for Auto Conversion of the Children Field:
https://dioxuslabs.com/nightly/guide/components/component_children.html#auto-conversion-of-the-children-field

There's some kind of lifetime issue when returning Element:

```
missing lifetime specifier
this function's return type contains a borrowed value, but the signature does not say which one of `cx`'s 2 lifetimes it is borrowed fromrustc[E0106](https://doc.rust-lang.org/error-index.html#E0106)
[text_field.rs(14, 22):]()
[text_field.rs(14, 17): ]()consider introducing a named lifetime parameter: `<'a>`, `Element<'a>`
```

**Steps To Reproduce**

```rust
use dioxus::prelude::*;

#[derive(Props)]
pub struct TextFieldProps<'a> {
    #[props(optional)]
    label: Option<&'a str>,

    #[props(optional)]
    darkest: Option<bool>,

    children: Element<'a>,
}

pub fn TextField(cx: Scope<TextFieldProps>) -> Element {
    cx.render(rsx! {
        div {
            cx.props.label.clone().map(|label| rsx!(
                h3 {
                    "{label}"
                }
            )),
            &cx.props.children
        }
    })
}
```

**Expected behavior**

Was hoping to use this here without an error:

```
TextField {
    input {
        r#type: "password",
        placeholder: "Enter Password",
    }
}
```

**Screenshots**

N/A

**Environment:**
 - Dioxus version: `master` / rev = `cc79287e868b69be206125cc823bdb9b7cc6ffb2`
 - Rust version: 1.58.1
 - OS info: Arch Linux
 - App platform: `web`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by mrxiaozhuox** [comment]
You need add the lifetime in component function:
```rust
pub fn TextField<'a>(cx: Scope<'a, TextFieldProps<'a>>) -> Element<'a> {
    cx.render(rsx! {
        div {
            cx.props.label.clone().map(|label| rsx!(
                h3 {
                    "{label}"
                }
            )),
            &cx.props.children
        }
    })
}

```

**Comment by jkelleyrtp** [comment]
Yeah the docs are wrong/misleading about the lifetime. I think this issue can only be resolved when we update the docs to reflect the required lifetime and/or it's verified that it solves your issue.

**Comment by jkelleyrtp** [comment]
The docs are fixed and this code compiles, so I'm going to close this :)
