### ISSUE TITLE
how to spawn a thread in main or other place only once

### ISSUE THREAD

**Issue by jiker-burce** [DioxusLabs/dioxus#2391]
**Problem**

**Steps To Reproduce**

```rust
fn main() {
launch(client_mod::client_lib::Client);
}

pub fn Client() -> Element {
    println!("Client");

  spawn(async move {
  // do some async things here
  }
}
```
- I found that if something changed, the `Client(main App component)` will be rendered again, so the `Client` will be printed many times. So that the spawn will generate many times.

**Expected behavior**
Is there a way could spawn new thread in `fn main` or other places, so I could just spawn a new thread once just like launch().

**Screenshots**

**Environment:**
 - Dioxus version: 0.5.1
 - Rust version: 1.7.75
 - OS info: MacOS
 - App platform: `desktop`

**Comment by jkelleyrtp** [comment]
> **Problem**
> 
> **Steps To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> ```rust
> fn main() {
> launch(client_mod::client_lib::Client);
> }
> 
> pub fn Client() -> Element {
>     println!("Client");
> 
>   spawn(async move {
>   // do some async things here
>   }
> }
> ```
> 
>  * I found that if something changed, the `Client(main App component)` will be rendered again, so the `Client` will be printed many times. So that the spawn will generate many times.
> 
> **Expected behavior** Is there a way could spawn new thread in `fn main` or other places, so I could just spawn a new thread once just like launch().
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> **Environment:**
> 
> * Dioxus version: 0.5.1
> * Rust version: 1.7.75
> * OS info: MacOS
> * App platform: `desktop`

We have use_future, use_effect, and use_hook depending on how much abstraction you need.

https://docs.rs/dioxus-hooks/latest/dioxus_hooks/fn.use_future.html
https://docs.rs/dioxus-hooks/latest/dioxus_hooks/fn.use_effect.html
https://docs.rs/dioxus-core/0.5.1/dioxus_core/fn.use_hook.html
