### ISSUE TITLE
HTML String into rsx!

### ISSUE THREAD

**Issue by jing-951** [DioxusLabs/dioxus#2400]
How to map HTML strings to RSX!
I searched for everything about Dioxus but couldn't find it.
For example, converting 
`"<p>abc</p><h1>123</h1>" `
into:
```
Rsx! {
P {"abc"},
H1 {"123"},
}
```

**Comment by wheregmis** [comment]
You can use something like this
let contents = "live <b>dangerously</b>";

rsx! { div { dangerous_inner_html: "{contents}" } }

For more detail Check https://dioxuslabs.com/learn/0.5/reference/rsx

**Comment by jing-951** [comment]
> You can use something like this
> 
> `let contents = "live <b>dangerously</b>"; rsx! { div { dangerous_inner_html: "{contents}" } }`
> 
> For more detail Check https://dioxuslabs.com/learn/0.5/reference/rsx

**Thank you very much. I have solved this problem using your method**

**Comment by jkelleyrtp** [comment]
We also have the ability to translate HTML into RSX using the CLI.
