### ISSUE TITLE
Update TailwindCSS Example Project

### ISSUE THREAD

**Issue by DickyChengg** [DioxusLabs/dioxus#2402]
## Contribute

Is there something that I can do to update the [Tailwind Example Project](https://github.com/DioxusLabs/dioxus/tree/main/examples/tailwind)?

I'm having hard time to figure out how to include the tailwind css even I had followed this example.
But it turns out there is something missing. (Or maybe I miss something else 🤔)

I have to add the css_url to the virtual_dom config on launch to make it worked as expected:

```rust
let css_url = format!(
  r#"<link rel="stylesheet" href="{}">"#,
  mg!(file("public/tailwind.css"))
);
let config = dioxus_desktop::Config::new()
  .with_custom_head(css_url);

let dom = VirtualDom::new(app);
dioxus_desktop::launch::launch_virtual_dom(dom, config);
```

I haven't tried to configure it on mobile apps because I'm still a lil bit confuse on how to setup the Cargo and checking the platform.
ps: I'm really new to Rust 😅.

## Result:

<img width="1277" alt="Screenshot 2024-05-10 at 15 40 33" src="https://github.com/DioxusLabs/dioxus/assets/44596153/b4fe092a-2bf6-4afa-876e-4cfac2d94060">

I hope the next person can save a lot of time to configure TailwindCss plus they don't have to explain everything to ChatGP, Codiumate and Bard on "how to fix this" kekw.

Thanks to Bard.

**Comment by DogeDark** [comment]
The [manganis](https://github.com/DioxusLabs/dioxus/blob/40df088b7dd355c781b827df17d36b2ec40b3469/examples/tailwind/src/main.rs#L5C1-L5C65) `_STYLE` line that includes the stylesheet should be linking it, however, it requires the app to be built with the Dioxus CLI to work. Perhaps you weren't running it with the CLI? If not, you can install it with ``cargo install dioxus-cli``

**Comment by DickyChengg** [comment]
Haa I see, I missed this one.
Thanks for the explanation, I'm using VS Code terminal and almost give up to resolve this issue 🙈
