### ISSUE TITLE
Assets in Dioxus build are "unpacked" from the original directory

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/dioxus#2407]
**Problem**

If I have a directory called `assets` and a file `assets/foo.txt` and I set the `asset_dir` in `Dioxus.toml` to `"assets"`, the resulting bundle (`dist`) will contain `foo.txt`, removing the original `assets` directory. I know Dioxus has it's own `assets` directory, but that can just be renamed to some unique name.

**Steps To Reproduce**

- Create a new app that reads from `assets/foo.txt`.
- Set `asset_dir` to `"assets"` in `Dioxus.toml`.
- Run `dx build`.
- Run the executable in `dist`.
- Program errors because the file could not be found, but it works with `dx serve` or `cargo run`.

**Expected behavior**

The path should be preserved and behavior kept consistent with `dx build`, `dx serve` and `cargo run`.

**Screenshots**

**Environment:**
 - Dioxus version: 0.5.1 crate, latest git CLI
 - Rust version: 1.78.0
 - OS info: Windows 10
 - App platform: desktop

**Comment by jkelleyrtp** [comment]
In 0.6 we're moving away from the "assets" dir via Dioxus.toml and entirely to a code-based include system using macros (manganis now provides an asset!() macro).

We're still going to keep the "assets dir" behavior for 0.6 (deprecating it for one release) and then in the future to include arbitrary folders of assets, you'll want to use the `manganis::dir!()` macro (or whatever we name it...) to include arbitrary directories for runtime loading.

Anyways, the asset system has been greatly overhauled and the original bug here has been fixed, so I'm going to close this.
