### ISSUE TITLE
Support the new Popover API natively

### ISSUE THREAD

**Issue by Exotik850** [DioxusLabs/dioxus#2413]
## Feature Request

The new [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) has just been released and it works in every browser, using this in dioxus would greatly improve the look and feel of a lot of apps 

## Implement Suggestion

Adding the necessary attributes in the [GlobalAttributes](https://docs.rs/dioxus-html/0.5.1/dioxus_html/trait.GlobalAttributes.html) to utilize the Popover API declaratively

> Declaratively, via a set of new HTML attributes. A simple popover with a toggle button can be created using the following code:
```html
<button popovertarget="mypopover">Toggle the popover</button>
<div id="mypopover" popover>Popover content</div>
```

**Comment by ealmloff** [comment]
Closed by https://github.com/DioxusLabs/dioxus/pull/2498
