### ISSUE TITLE
Renaming value doesn't change in rsx macro

### ISSUE THREAD

**Issue by mrgzi** [DioxusLabs/dioxus#2422]
When we rename the value, it doesn't change the value if its inside a string. but it changes in rust code.

```rs
pub fn component() -> Element {
    let mut username = use_signal(|| "".to_string());

    rsx! {
        input {
            r#type: "text",
            value: "{username}",
        }
    }
}
```

**Comment by ealmloff** [comment]
I think this is caused by assigning the wrong span to variables inside rsx. We parse the rsx macro using syn which is really meant to parse rust-like things, not raw text which makes things like the format macro in dioxus difficult
