### ISSUE TITLE
Manganis CSS Hot Reloading

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/dioxus#2429]
#### Feature Request

Add CSS hot reloading for manganis.

#### Implement Suggestion

The `manganis-cli-support` crate could include a watcher that notifies the CLI hot reload loop of changes. The hot reload loop could then diff the CSS and apply changes.

**Comment by FragrantArmpit** [comment]
We already have a watcher in CLI. Perhaps just expose the asset file paths from mangalis for the dioxus CLI watcher to watch?

**Comment by jkelleyrtp** [comment]
Implemented in #2779

Works for all platforms, but android simulator is a little shaky right now
