### ISSUE TITLE
Can't match Resource.value() as shown in documentation.

### ISSUE THREAD

**Issue by DefinitelyNotSimon13** [DioxusLabs/dioxus#2442]
**Problem**

I am just getting into dioxus and wanted to use  "use_resource" to retrieve a value similiar to the [documentation](https://docs.rs/dioxus-hooks/latest/dioxus_hooks/fn.use_resource.html).

```rust
let stories = use_resource(move || async move { get_stories(10).await });

rsx! {
    match stories.value() {
        Some(Ok(list)) => rsx! { "test"},
        Some(Err(e)) => rsx! { "test err"},
        None => rsx! { "none"},
    }
}
```
However I now get the following compile time error:
```rust
error[E0308]: mismatched types
   --> src/main.rs:184:13
    |
181 |         match stories.value() {
    |               --------------- this expression has type `dioxus::prelude::ReadOnlySignal<std::option::Option<Result<Vec<StoryItem>, reqwest::Error>>>`
...
184 |             None => rsx! { "none"},
    |             ^^^^ expected `ReadOnlySignal<Option<Result<..., ...>>>`, found `Option<_>`
    |
    = note: expected struct `dioxus::prelude::ReadOnlySignal<std::option::Option<Result<Vec<StoryItem>, reqwest::Error>>>`
                 found enum `std::option::Option<_>`
```

Looking at the documentation I can't seem to find a way to get it working.

**Steps To Reproduce**

-  try to match a Resource as shown in documentation
- 
- 

**Expected behavior**

Match the same way as is shown in the documentation

**Environment:**
 - Dioxus version: v0.5.1, `master`
 - Rust version: 1.77.2.0,  `stable`
 - OS info: Linux
 - App platform: `web`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by DefinitelyNotSimon13** [comment]
Update:
Actually just saw that I was on the wrong version of the quick start guide - dont really now how that happened? 

Here I found a way to do it, however as far as I can tell that still means that the Documentation is outdated.

**Comment by DefinitelyNotSimon13** [comment]
Okay so while looking into the soure files, it seems that the documentation here is already correct and the error is only on the docs site?

**Comment by Yohe-Am** [comment]
Hey, I just run into this. How did you resolve this?

**Comment by Yohe-Am** [comment]
The `read_unchecked` approach used in the [guide](https://dioxuslabs.com/learn/0.5/guide/data_fetching) did also prove erroneous.

**Comment by DefinitelyNotSimon13** [comment]
Pretty sure, I was on the wrong version for the document IIRC.

Maybe try n check your URL

**Comment by DefinitelyNotSimon13** [comment]
@Yohe-Am 
Pretty sure I was on the wrong version of the documentation IIRC.
Maybe try and check your URL/change the version there

**Comment by Yohe-Am** [comment]
Thanks, this indeed seems to be case of #2284
