### ISSUE TITLE
Opinion: `Signal` should not be callable

### ISSUE THREAD

**Issue by jprider63** [DioxusLabs/dioxus#2447]
## Feature Request

Currently, to retrieve the contents of a [`Signal`](https://docs.rs/dioxus/0.5.1/dioxus/prelude/struct.Signal.html), you need to *call* the `Signal` struct. For example:
```
    let signal: Signal<Option<String>> = use_signal(|| None);
    if let Some(s) = signal() {
        rsx!(
            p {
                s
            }
        )
    }
```
This seems impossible at first since `Signal` has kind `*`, but calling something requires kind `* -> *` in order to typecheck. If I understand correctly, this is possible by abusing the auto dereferencing rules of Rust and implementing `Deref` with `type Target = dyn Fn() -> T`. I believe this is an anti-pattern that should not be used by a popular library. I found this extremely confusing and spent significant time 1) figuring out how to retrieve a `T` (the only mention in [`Signal`](https://docs.rs/dioxus/0.5.1/dioxus/prelude/struct.Signal.html)'s documentation is hidden in the `Deref` impl) and 2) understanding how this works. 

## Implement Suggestion

Remove the `Deref` implementation and implement a separate method (maybe `get`?) that retrieves the content of a `Signal`.

**Comment by ealmloff** [comment]
The majority of methods for `Signal` are implemented on the [`Readable`](https://docs.rs/dioxus/0.5.1/dioxus/prelude/trait.Readable.html) and [`Writable`](https://docs.rs/dioxus/0.5.1/dioxus/prelude/trait.Writable.html) trait. One of the methods on the Readable trait is `cloned` which clones the value out of the signal.

This seems more like a docs/discoverability issue than anything else. I agree looking at the docs of `Signal`, it isn't clear that you can call the struct or use methods from readable and writable. It would be more clear if we included more examples in the signal docs (including calling the signal like a function) and links to the relevant traits (`Readable` and `Writable`)

Implementing the `Fn` trait itself would also be much more clear than `Deref`, but unfortunately `fn_traits` has not landed in stable yet.

**Comment by jprider63** [comment]
Thanks, that's good to know about `cloned`. I tried using `read`, but that returned a `GenerationalRef` which I wasn't sure what to do with. 

I was unaware of [`fn_traits`](https://github.com/rust-lang/rust/issues/29625). That also seems like a bad idea in my opinion, but that's a separate issue.

**Comment by ealmloff** [comment]
The docs were improved in https://github.com/DioxusLabs/dioxus/pull/2460 to reference the readable and writable traits and include more examples
