### ISSUE TITLE
I can't run the code generated by `dx new`

### ISSUE THREAD

**Issue by Bear-V** [DioxusLabs/dioxus#2448]
**Problem**

I can't run the code generated by `dx new`

**Steps To Reproduce**

- `dx new` 
- `web`
-  `dx serve --hot-reload`

**Expected behavior**

**Screenshots**
<img width="1391" alt="image" src="https://github.com/DioxusLabs/dioxus/assets/38470946/38bbb0e3-707b-4687-921c-c34a9d554d7f">

**Environment:**
 - Dioxus version: 0.5
 - Rust version:1.78 
 - OS info: MacOS intel 
 - App platform: web

**Comment by ealmloff** [comment]
What error message do you get when you run `cargo build --target wasm32-unknown-unknown`? You may need to install a missing rust component

**Comment by Bear-V** [comment]
@ealmloff 
when i run this , is error  and I don't know how to solve it
please help , i try many methods , but not result
![image](https://github.com/DioxusLabs/dioxus/assets/38470946/66d88b84-93e2-403e-9d64-546a2afedf08)

**Comment by Bear-V** [comment]
ok
i get it
thank you
