### ISSUE TITLE
Unable to do 'dx serve' on nixos if mio is a dependency

### ISSUE THREAD

**Issue by TBS1996** [DioxusLabs/dioxus#2453]
**Problem**

when following the introduction, 'dx serve' only works when mio is not a dependency, when using nixos

**Steps To Reproduce**

* use nixos
* follow quickstart and use for example fullstack renderer
* do 'dx serve'

**Expected behavior**

the example program should run as expected

excerpt from the errors:

```
[nix-shell:~/prog/ocean/web]$ dx serve
\ ⚙️ Compiling registry+https://github.com/rust-lang/crates.io-index#dioxus-logger@0.5.1       error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /home/tor/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.11/src/io_source.rs:12:5
   |
12 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /home/tor/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.11/src/net/tcp/listener.rs:15:17
   |
15 | use crate::sys::tcp::{bind, listen, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /home/tor/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.11/src/net/tcp/stream.rs:13:17
   |
13 | use crate::sys::tcp::{connect, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0433]: failed to resolve: could not find `Selector` in `sys`
   --> /home/tor/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.11/src/poll.rs:312:18
    |
312 |             sys::Selector::new().map(|selector| Poll {
    |                  ^^^^^^^^ could not find
```

**Environment:**
 - Dioxus version: 0.5.4
 - Rust version: 1.7.8, stable
 - OS info:NixOs (with wayland if that matters)
 - App platform: liveview (or any other if mio becomes a dependency, like on web)

seems related: https://github.com/tokio-rs/mio/issues/1782

**Comment by ealmloff** [comment]
The CLI defaults to a web build that targets wasm, but Mio doesn't support wasm. You can build for your current architecture with `dx serve --platform desktop`

**Comment by ealmloff** [comment]
If you are targeting fullstack, you need to make tokio/mio an optional dependency that is only active when the server feature is enabled. Dioxus will automatically run two builds with `dx serve`: one with the web feature that targets wasm, and one with the server build that targets your current architecture

**Comment by LuckyTurtleDev** [comment]
You can also change `default_platform` to `"desktop"` at the `Dioxus.toml`
