### ISSUE TITLE
use_effect with value 

### ISSUE THREAD

**Issue by ThomasCartier** [DioxusLabs/dioxus#2457]
## Feature Request

Hi,
Could we have a hook that captures the variable that is about to change to store its state in another signal ?

My goal is to manage a page that has a selector which enable to load text in a Vec of structures.

But use_effect get the new value of the reactive value after it has changed.
Some thing like:

```rust
 use_effect(move || {

           let _ = my_var.read();

            // do things with the new my_var value, after the update
});
 use_effect_before(move || {

           let _ = my_var.read();

            // do things with the my_var value, before it updates
});
```

That would be handy and avoid a myriad of signals down the components. Cleaner API.

Any opinion on this?

Thanks

**Comment by ThomasCartier** [comment]
A way to filter the signals that trigger a re loop would be nice:

```
 use_effect(move || {

           let _ = my_var.read();
           let _ = another_signal_that_should_not_retrigger.read()
});
```
That would avoid infinite loop management when some effect have signals useful in the callback but that mess up the logic when they are "active" otherwise.

**Comment by ealmloff** [comment]
> That would be handy and avoid a myriad of signals down the components. Cleaner API.

What use case would `use_effect_before` simplify? Could you show how you would approach your problem now vs with `use_effect_before`

> A way to filter the signals that trigger a re loop would be nice:

You can use the `peek` method on signals to read a value without subscribing to the signal
