### ISSUE TITLE
Error compiling dioxus-desktop: no argument named `mime`

### ISSUE THREAD

**Issue by davisuga** [DioxusLabs/dioxus#246]
**Problem**

Could not run "Our first app" due to compilation error
**Steps To Reproduce**

- Basically follow the documentation until [Our first app](https://dioxuslabs.com/guide/hello_world.html#our-first-app)

**Expected behavior**

Run the app

**Screenshots**

![image](https://user-images.githubusercontent.com/33470530/153858104-ba03522b-5f3d-4b87-a63a-8b4b0e8dc47d.png)

**Environment:**
 - Dioxus version: 0.1.6
 - Rust version: `rustc 1.56.0` `rustup 1.24.3`
 - OS info: Linux Mint 20.2 uma
 - App platform: Desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by mrxiaozhuox** [comment]
can you try to upgrade your rust version. I think maybe is compiler version problem.

**Comment by jkelleyrtp** [comment]
Oh, and make sure to update your Dioxus version. 0.1.6 is pretty old and we actually support 2018 edition now.
