### ISSUE TITLE
no `use_muda_event_handler` in the root

### ISSUE THREAD

**Issue by roxiga** [DioxusLabs/dioxus#2462]
**Problem**

I cannot build Menu Event Handler `use_muda_event_handler`.

**Steps To Reproduce**
```rust
use dioxus::desktop::{muda::*, use_muda_event_handler}; // Error

let menu = Menu::new();
let edit_menu = Submenu::new("Edit", true);
edit_menu
  .append_items(&[&MenuItem::with_id("switch-text", "Switch text", true, None),])
  .unwrap();
menu.append(&edit_menu).unwrap();
let config = dioxus::desktop::Config::new().with_menu(menu);
LaunchBuilder::new().with_cfg(config).launch(app)

use_muda_event_handler(move |muda_event| {
  if muda_event.id() == "switch-text" {
    text.set("Switched to text".to_string());
  }
});
```
**Expected behavior**

I want get Menu Event Handler on my original project.

'cargo run --example custom_menu' is OK.

**Environment:**
 - Dioxus version: [v0.5.1, v0.5.0]
 - Rust version: [1.78.0]
 - OS info: [Windows10]
 - App platform: [`desktop`]

**Questionnaire**
I'm interested in fixing this myself but don't know where to start

Your crate is good job.

**Comment by ealmloff** [comment]
The `use_muda_event_handler` hook is only available on the git version of dioxus. If you want to see only examples that are compatible with the published version of 0.5, you can look at [this tag](https://github.com/DioxusLabs/dioxus/tree/v0.5.2)

Or you can switch to the git version of dioxus 0.5 with:
```toml
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "0.5" }
```
