### ISSUE TITLE
Support for Web API / WebRTC

### ISSUE THREAD

**Issue by anatoli26** [DioxusLabs/dioxus#2469]
Hi!

Does Dioxus support Web APIs like Web Audio etc. or WebRTC to capture audio, video and take photos?

Thanks for your great work!

**Comment by jkelleyrtp** [comment]
This is not a dioxus thing - but rather an ecosystem issue.

Check this out:
https://github.com/wasm-peers/wasm-peers

That being said, we probably won't support this natively, and if we do, it'll be part of 
https://github.com/dioxusLabs/sdk
