### ISSUE TITLE
Expired example

### ISSUE THREAD

**Issue by YangFong** [DioxusLabs/dioxus#247]
Hi, I found that the examples in the documentation are not available in the current version, would you consider replacing them with examples that are available?

invalid：

![image](https://user-images.githubusercontent.com/70502828/153870132-fbcf1814-0b53-4e5a-9716-cfcc9f06acba.png)

effective：

![image](https://user-images.githubusercontent.com/70502828/153870215-d2968b19-ef78-4dd0-a42e-3326d0a9d05a.png)

**Comment by YangFong** [comment]
I see #218, just the site hasn't been updated yet。

**Comment by jkelleyrtp** [comment]
The nightly guide is right

https://dioxuslabs.com/nightly/guide/

But the stable docs are wrong. We'll bump to 0.1.9 very soon and this should be fixed.
