### ISSUE TITLE
Route URL is change can't Listening

### ISSUE THREAD

**Issue by exten** [DioxusLabs/dioxus#2476]
## Feature Request

When I change the URL path in the address bar, the system can't monitor the change. At this point, I can't take advantage of the route's update function for permission control.
```rust
rsx! {Router::<Route> {
        config: || RouterConfig::default().initial_route(Route::SignIn {}).on_update(|state|{
            info!("--- rule check in there route change! --- path: {} ", state.current());
            let glob_user = consume_context::<Signal<User>>();
            if let Some(permis) = glob_user.read().role.curr_permis(format!("{}", state.current())) {
                info!("--- rule curr path permis:{} ---", permis);
                // NavigationTarget::Internal(state.current())
            } else {
                // NavigationTarget::Internal(Route::BlogList {}),
            }
            (state.current() == Route::Home {}).then_some(
                // NavigationTarget::Internal(Route::BlogList {}),
                // NavigationTarget::<Route>::External(String::from("https://dioxuslabs.com/"))
                NavigationTarget::Internal(state.current())
            )
        })
    }}
```

## Implement Suggestion

1. How do I monitor address bar path changes? 
2. Whether path change monitoring can be implemented in Route.

**Comment by ealmloff** [comment]
The [`popstate` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event#when_popstate_is_sent) the browser exposes to watch history changes doesn't trigger when you manually type in a new url

**Comment by exten** [comment]
> The [`popstate` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event#when_popstate_is_sent) the browser exposes to watch history changes doesn't trigger when you manually type in a new url

What can I do to fix this? Is there a better suggestion?

**Comment by ealmloff** [comment]
As far as I know, you can't watch for manual url changes in the browser. I imagine this is intentional for security reasons. Why do you need to monitor manual URL changes?

**Comment by exten** [comment]
> As far as I know, you can't watch for manual url changes in the browser. I imagine this is intentional for security reasons. Can you provide more information about why you would like to monitor manual url changes? You might be able to implement it in a way that doesn't require listening to manual updates

I want to illustrate why you should monitor manual URL changes. 
---
Because I want to control and verify whether the current user can access the current web resource on the front end. Through the 'DIOXUS' framework, it is possible to listen to the route change and detect whether the current user has access to the resource. However, when the user manually modifies the URL address in the address bar, the framework route cannot detect the URL change and cannot start the user permission verification. 
---
Of course, the safest way is to do permission verification on the server side, then I will add a permission verification request to the component page corresponding to each route.
I imagine if the framework could provide a component render filter that provides a hook function before rendering the component.
---

**Comment by ealmloff** [comment]
If you just need to read the current route, you can use the [`use_route`](https://docs.rs/dioxus-router/latest/dioxus_router/hooks/fn.use_route.html) hook inside of a [layout](https://dioxuslabs.com/learn/0.5/router/reference/layouts) to read the current route. use_route will make your layout rerun whenever the route changes and it will run initially when you render the page. You can use the [navigator](https://dioxuslabs.com/learn/0.5/router/reference/navigation/programmatic) to move between routes in the layout if you need to redirect the user

When you manually change the url, the state of your app will be reset as the page reloads. If you need to keep state through that rerender, you will need to put your state in local storage or cookies (or use [a hook that does that for you](https://github.com/DioxusLabs/sdk/tree/master/examples/storage))

**Comment by exten** [comment]
> If you just need to read the current route, you can use the [`use_route`](https://docs.rs/dioxus-router/latest/dioxus_router/hooks/fn.use_route.html) hook inside of a [layout](https://dioxuslabs.com/learn/0.5/router/reference/layouts) to read the current route. use_route will make your layout rerun whenever the route changes and it will run initially when you render the page. You can use the [navigator](https://dioxuslabs.com/learn/0.5/router/reference/navigation/programmatic) to move between routes in the layout if you need to redirect the user
> 
> When you manually change the url, the state of your app will be reset as the page reloads. If you need to keep state through that rerender, you will need to put your state in local storage or cookies (or use [a hook that does that for you](https://github.com/DioxusLabs/sdk/tree/master/examples/storage))

Thank you very much for your tips. Now I have some ideas for implementation. Thank you again for your guidance and explanation.

**Comment by qingkongxiaofeng** [comment]
```rust
  let mut a = use_signal(|| "".to_string());

    use_effect(move || {
        let router = use_route::<RootRoute>(); // 在这里()会追踪路由的内置 Signal
        a.set(router.to_string());
        error!("路由切换触发effect: {router:?}");
    });

 span {"current route {a}" }
```
