### ISSUE TITLE
Conditionally exclude value attribute with non-null types (e.g. f64) from rendered HTML

### ISSUE THREAD

**Issue by thorn132** [DioxusLabs/dioxus#2478]
The [daisyUI progress bar](https://daisyui.com/components/progress/#indeterminate-without-value) indeterminate animation only displays when the `<progress>` tag does not set the `value` attr. However, Dioxus' `progress` RSX element always sets `value` to some `f64` if `value` is declared in the RSX, defaulting to `0` for `None`. E.g. the following compiles but does not show the indeterminate animation:
```rust
let val: Option<f64> = None;
rsx! {
    progress { class: "progress", value: val } // renders as <progress class="progress" value="0" />
}
```
The desired behavior in this case is for `None` values to not set the attribute at all, i.e. render as `<progress class="progress">`, but that may break other uses, so it could be opt-in with some syntax, e.g.:
```rust
rsx! {
    progress { class: "progress", value: None }        // renders as <progress class="progress" value="0" />
    progress { class: "progress", value?: None }       // renders as <progress class="progress" />
}
```
My current workaround is conditionally rendering the `progress` element to remove the attribute:
```rust
rsx! {
    if let Some(value) = value {
        progress { class: "progress", value: val }
    } else {
        progress { class: "progress" }
    }
}
```

**Comment by thorn132** [comment]
Also tried setting `value: AttributeValue::None` which has the same issue, contradicting the [documentation](https://docs.rs/dioxus-core/0.5.1/dioxus_core/enum.AttributeValue.html):
> **None** A "none" value, resulting in the removal of an attribute from the dom

**Comment by ealmloff** [comment]
This bug is specific to the `value` attribute which is handled differently in dioxus
