### ISSUE TITLE
hot reload does not trigger rebuild when string is updated on files different than main.rs

### ISSUE THREAD

**Issue by gusinacio** [DioxusLabs/dioxus#2485]
**Problem**
If you create a project and create a component that is outside `main.rs`, for example, `login.rs`.
when you update any string, it doesn't get rebuilt by `dx serve`

**Steps To Reproduce**

- Create a dioxus project
- Create a login.rs file and add `mod login;`
- Create a component inside login.rs
- Import the component in your App in main.rs
- Inside rsx of login.rs, create a string like class or the HTML value
- Run `dx serve --hot-reload`
- Update the string inside login.rs
- dx serve won't rebuild

**Expected behavior**
It should rebuild on different files other than main.rs while hot reloading

**Screenshots**

https://github.com/DioxusLabs/dioxus/assets/4844547/ef06fe5a-3ebb-4bbb-b6cc-b93353f5d56c

**Environment:**
 - Dioxus version: master, dioxus-cli: 5.0.4
 - Rust version: 1.78
 - OS info: MacOS M1
 - App platform: fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
The dioxus CLI and renderers communicate over IPC + websockets to hot reload static parts of rsx that is not nested within component/other rsx in debug mode. The edit you make in `login.rs` is hot reloadable without recompiling, but we need to recompile. 

There have been some updates to hot reloading since the last release. You may need to update your CLI to the git version of dioxus to make the protocol compatible between your app and the CLI.

**Comment by gusinacio** [comment]
I just tried updating everything to main and it's still not able to reload.

https://github.com/DioxusLabs/dioxus/assets/4844547/dbaace8e-3b3b-47f5-ac43-28574b4e7ca0

**Comment by gusinacio** [comment]
I think I found the problem. The problem was not related to the file, but the content of the strings in the whole rsx!

I generated some code in v0, and there were some `\n` in the middle of the strings. The whole rsx stops reloading if one of  the strings contains `\n`.


https://github.com/DioxusLabs/dioxus/assets/4844547/b0327733-0373-4bfa-bf43-16a2b231c889

**Comment by gusinacio** [comment]
It's actually a different problem. Creating a separated issue.
