### ISSUE TITLE
hot reload does refresh rsx! if it contains \n

### ISSUE THREAD

**Issue by gusinacio** [DioxusLabs/dioxus#2486]
I think I found the problem. The problem was not related to the file, but the content of the strings in the whole rsx!

I generated some code in v0, and there were some `\n` in the middle of the strings. The whole rsx stops reloading if one of  the strings contains `\n`.

https://github.com/DioxusLabs/dioxus/assets/4844547/b0327733-0373-4bfa-bf43-16a2b231c889

_Originally posted by @gusinacio in https://github.com/DioxusLabs/dioxus/issues/2485#issuecomment-2155248154_

**Comment by ealmloff** [comment]
This seems similar to https://github.com/DioxusLabs/dioxus/issues/1586

**Comment by ealmloff** [comment]
fixed by #2725

**Comment by jkelleyrtp** [comment]
Did you test it locally? @ealmloff

**Comment by ealmloff** [comment]
> Did you test it locally? @ealmloff

Yes, hot reloading this snippet works on desktop:
```rust
pre {
     "hello\tworld"
     "hello\nworld"
}
```
