### ISSUE TITLE
bug: Cannot pass `Cow<'static, str>` to component props that accept String

### ISSUE THREAD

**Issue by marc2332** [DioxusLabs/dioxus#2497]
**Problem**

Cannot pass `Cow<'static, str>` to component props that accept String

![image](https://github.com/DioxusLabs/dioxus/assets/38158676/24d942da-26d7-4f48-930a-ffd670553989)

**Steps To Reproduce**

Pass a `Cow<'static, str>` to a prop that accepts a String with #[props(into)]

Fails:

![image](https://github.com/DioxusLabs/dioxus/assets/38158676/3026dcdd-5c87-4fc5-96d7-84c7eb2ae655)

Works:
![image](https://github.com/DioxusLabs/dioxus/assets/38158676/df9ab81c-d012-49b2-a538-cc611b6cbc74)

**Expected behavior**

Work

**Environment:**
 - Dioxus version: main branch
 - Rust version: latest stable
 - OS info: Windows
 - App platform: freya

**Comment by ealmloff** [comment]
This works in the current git version of dioxus if you remove the `#[props(into)]` attribute. #2501 makes `props(into)` a no-op on string properties

**Comment by marc2332** [comment]
hah! Nice
