### ISSUE TITLE
Desktop UI disappears when reloading

### ISSUE THREAD

**Issue by WilliamRagstad** [DioxusLabs/dioxus#2511]
**Problem**

When I reload the page in my desktop application, all UI disappears and cannot be restored.

**Steps To Reproduce**

- Initialize a new desktop project
- Run with `dx serve`
- F5 or CTRL+R to refresh the page

**Expected behavior**

The UI to instantly be re-rendered.

**Screenshots**

![image](https://github.com/DioxusLabs/dioxus/assets/41281398/d6203e6a-0626-4a60-8a84-a8c700921e50)

**Environment:**
 - Dioxus version: v0.5.4
 - Rust version: 1.78.0
 - OS info: Windows 11
 - App platform: `desktop`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This was fixed in https://github.com/DioxusLabs/dioxus/pull/939, but it looks like that change got reverted at some point. (Wry upgrades?)
