### ISSUE TITLE
Fullstack Desktop CLI support

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#2516]
## Feature Request

It is currently painful to create and run desktop applications that work with server functions. See [this example](https://github.com/DioxusLabs/dioxus/tree/main/packages/fullstack/examples/axum-desktop): You need to set up multiple binaries in your `cargo.toml` and build your application twice manually

## Implement Suggestion

The CLI should handle the configuration for you to make this as simple as fullstack web: a feature for the client and server with a single crate

**Comment by zacbre** [comment]
This would be a nice thing to have. +1 for this feature. I'm currently running into the same issue.
