### ISSUE TITLE
Version mismatch dioxus-cli

### ISSUE THREAD

**Issue by DieracDelta** [DioxusLabs/dioxus#2525]
**Problem**

The dioxus-cli on crates.io is v0.5.4, and the dioxus-cli on the github release is v0.5.1. However, the dioxus-cli release on github appears to be newer.

**Expected behavior**

I would expect the versions to match

**Comment by Andrew15-5** [comment]
https://crates.io/crates/dioxus has v0.5.1.

https://crates.io/crates/dioxus-cli has v0.5.4.

https://github.com/DioxusLabs/dioxus/releases does not contain CLI binaries, so it matches the version from the https://crates.io.

I'm also confused as to why the versions aren't synced.

AFAIU, everyone should either use the latest common version (i.e., 0.5.1) for the library and the CLI, or the latest git version (compile the CLI and patch the library version in the `Cargo.toml`).

**Comment by ealmloff** [comment]
The dioxus-cli and dioxus versions don't need to match exactly. Any `0.5.*` versions should work with each other or the git version of the CLI works with the git version of dioxus

**Comment by Andrew15-5** [comment]
> Any `0.5.*` versions should work with each other

Well then this should be fixed as it doesn't. And here is the proof: #2491.

It worked "overall", but not "fully" or "as expected". But syncing the versions by using the same commit fixed the issue. Initially, both versions were `0.5.*`.

So the question remains as to why CLI has more 0.5 versions than the library. This just doesn't make sense. And in practice introduces weird behavior.

**Comment by ealmloff** [comment]
If you use the git version of dioxus, you may need to align commits. There are breaking changes in the main branch for 0.6

**Comment by Andrew15-5** [comment]
This version matching/mismatch (confusion) should at least be mentioned somewhere in the docs. I don't see anything relatable to versions. There isn't even an FAQ section/chapter anywhere, although this shouldn't be mentioned so deep anyway.

https://dioxuslabs.com/learn/0.5/getting_started#dioxus-cli

https://dioxuslabs.com/learn/0.5/CLI
