### ISSUE TITLE
Cross-platform Project Documentation

### ISSUE THREAD

**Issue by WilliamRagstad** [DioxusLabs/dioxus#2531]
## Feature Request

If possible, it would be really nice to have comprehensive documentation for an example project that implements both web and desktop platforms, emphasizing the unique selling point of Dioxus. The documentation should cover the setup, configuration, and usage of Dioxus in both web and desktop environments. This will help users understand the capabilities and advantages of Dioxus in these different contexts.

## Implement Suggestion

The documentation can be organized into sections for web and desktop, and both platforms, with detailed examples and code snippets to demonstrate Dioxus in each environment.

Additionally, interactive tutorials and video demos should be included to provide users a more engaging learning experience. This will help users quickly grasp the concepts and benefits of using Dioxus in their projects. Effectively showcasing the features of a platform-agnostic library like Dioxus.

**Comment by ealmloff** [comment]
The [guide](https://dioxuslabs.com/learn/0.5/guide) works with the desktop, liveview, fullstack and web renderers. Platform specific information is covered in the [reference](https://dioxuslabs.com/learn/0.5/reference#platforms). Documentation for setting up multiple platforms at once is tracked in https://github.com/DioxusLabs/docsite/issues/263

**Comment by WilliamRagstad** [comment]
I cannot seem to find a way to run `dx serve --platform desktop` and `dx serve --platform fullstack` or `dx serve --platform web` on the same project...
