### ISSUE TITLE
Uncaught TypeError: The specifier “env” was a bare specifier, but was not remapped to anything.

### ISSUE THREAD

**Issue by uzytkownik** [DioxusLabs/dioxus#2550]
**Problem**

Suddenly today after 'random change' my page stopped working. I started getting error:

```
Uncaught TypeError: The specifier “env” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```

Reverting my changes did not fixed the problem

**Steps To Reproduce**

Unknown?

**Expected behavior**

WASM is loaded

**Screenshots**

**Environment:**
 - Dioxus version: 0.5.4
 - Rust version: 1.81.0-nightly (a70b2ae57 2024-06-09)
 - OS info: Nix
 - App platform: web

**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by uzytkownik** [comment]
The lines in question:

```
mport { RawInterpreter } from './snippets/dioxus-interpreter-js-7c1300c6684e1811/inline0.js';
import { setAttributeInner } from './snippets/dioxus-interpreter-js-7c1300c6684e1811/src/js/common.js';
import { get_form_data } from './snippets/dioxus-web-84af743b887ebc54/inline0.js';
import { get_select_data } from './snippets/dioxus-web-84af743b887ebc54/inline1.js';
import { Dioxus } from './snippets/dioxus-web-84af743b887ebc54/src/eval.js';
import * as __wbg_star0 from 'env';
```

**Comment by uzytkownik** [comment]
I created a new project and this line is absent:

```
import { RawInterpreter } from './snippets/dioxus-interpreter-js-7c1300c6684e1811/inline0.js';
import { setAttributeInner } from './snippets/dioxus-interpreter-js-7c1300c6684e1811/src/js/common.js';
import { get_form_data } from './snippets/dioxus-web-84af743b887ebc54/inline0.js';
import { get_select_data } from './snippets/dioxus-web-84af743b887ebc54/inline1.js';
import { Dioxus } from './snippets/dioxus-web-84af743b887ebc54/src/eval.js';
```

My Dioxus.toml:

```[application]

name = "ee-calculator"

default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "ee-calculator"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = [
      "/bootstrap.min.css",
      "/ee-calculator.css"
]

script = ["/bootstrap.bundle.min.js"]

[web.resource.dev]

```

I don't see `env` or `__wbg_star0` anywhere in my app by grepping the source code.

**Comment by ealmloff** [comment]
This might be an error with wasm bindgen or another library that uses wasm bindgen. `__wbg_star0` is wasm bindgen start and that script is code wasm bindgen sets up to make it possible to call javascript from rust code. Do you have any other code that may use wasm bindgen?

It looks like there is an upstream issue with the same error message: https://github.com/rustwasm/wasm-bindgen/issues/2570

**Comment by uzytkownik** [comment]
It looks like LTO was the issue.

**Comment by damccull** [comment]
What is LTO? I'm having this error as well and unsure how to fix it.

**Comment by ealmloff** [comment]
> What is LTO? I'm having this error as well and unsure how to fix it.

It is a rust compiler option: Link time optimization. More documentation [here](https://doc.rust-lang.org/cargo/reference/profiles.html#lto) in the cargo reference
