### ISSUE TITLE
hybrid web renderer

### ISSUE THREAD

**Issue by pratikpparikh** [DioxusLabs/dioxus#2563]
Is it possible to create a hybrid web renderers rather then combined web and liveview under one application?  This question might be because i am new here and I am trying to understand if this is possible.

**Comment by ealmloff** [comment]
There was some discussion of embedding web only components in liveview applications in https://github.com/DioxusLabs/dioxus/issues/1988. However, Dioxus will be moving support for liveview into a community maintained crate in the future in favor of [fullstack](https://dioxuslabs.com/learn/0.5/reference/choosing_a_web_renderer#dioxus-fullstack). Fullstack acts kind of like a hybrid between web and liveview. Ideally, you get all the offline support and web-sys compatibility of web while still interacting with the server inline in your application with server functions.

**Comment by pratikpparikh** [comment]
@ealmloff thank you for quick response it does make sense.  Ideally if you convert liveview and web as composite components it can maybe provide the architecture freedom for being utilized in fullstack or standalone.  Just a food for thought.  Not sure what is the feasibility of it, but i have seen that this kind of architecture can solve most requirements without consolidating purpose focused features.

**Comment by jkelleyrtp** [comment]
We eventually want to merge liveview into fullstack, but this particular issues feels much closer to #1988 than that.
