### ISSUE TITLE
AutoCompletion in rsx! is not working in WSL

### ISSUE THREAD

**Issue by araraloren** [DioxusLabs/dioxus#2564]
**Problem**

Can not get autocompletion working in macro rsx!.

**Steps To Reproduce**
dx new
Web
Vanilla
true

- 
- 
- 

**Expected behavior**

**Screenshots**

![Animation](https://github.com/DioxusLabs/dioxus/assets/15150618/d56b6a53-0434-431b-b710-3107997f5e24)

**Environment:**
 - Dioxus version:   dioxus 0.5.4
 - Rust version:     rustc 1.79.0 (129f3b996 2024-06-10)
 - OS info:          Fedora release 39 (Thirty Nine) (WSL)
 - App platform:     web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
Autocomplete support for rsx is very limited in the published version of dioxus. https://github.com/DioxusLabs/dioxus/pull/2421 improves autocomplete significantly and will be included in the `0.6` version of dioxus
