### ISSUE TITLE
use_memo breaks other write() calls to signals written to in the hook

### ISSUE THREAD

**Issue by bcorey** [DioxusLabs/dioxus#2565]
**Problem**

If you write to a signal inside a use_memo hook, you can't write to that signal elsewhere in the component. No errors are thrown.

**Steps To Reproduce**

- Create a mutable signal with some custom state datatype featuring a "render" method returning a string and a "update" method that mutates the state.
- Create a trigger signal that will update the other signal when written to
- set up use_memo so that it references the trigger signal and calls `write().update()` on the state signal
- add a button to the RSX that changes the trigger value on click
- `let render_data` equal the result of calling the state signal with `.read().render()`
- display `render_data` in RSX
- observe that the rendered data updates when the button is clicked
- `let render_data` instead equal the result of calling the state signal with `.write().render()`
- observe that the rendered data does not update when the button is clicked
- observe that there are no console or compile errors
- observe that moving the `.render()` call to before the `use_memo` hook does not affect the outcome

**Expected behavior**

`.write()` calls on signals also written to inside a `use_memo` hook should succeed like the `.read()` ones do, or if this is not possible, an error should be thrown at compile time or runtime.

**Code**
adapted from the web starter:
```
#[derive(Clone, Debug)]
struct MyDataType(i32);

impl MyDataType {
    fn increment(&mut self) {
        self.0 += 1;
    }

    fn render(&self) -> String {
        format!("{}", self.0 * 10)
    }
}

#[component]
fn App() -> Element {
    let mut my_signal = use_signal(|| MyDataType(0));

    let mut my_trigger: Signal<bool> = use_signal(|| false);

    use_memo(move || {
        let _trigger = my_trigger();
        my_signal.write().increment();
        tracing::info!("button click");
    });

    // use_memo runs on button click but does not affect the rendered state retrieved here
    let render_data = my_signal.write().render();

    // use_memo runs on button click and affects the rendered state retrieved here
    // let render = my_signal.read().render();

    rsx! {
        h1 {
            "{render_data}"
        }
        button {
            onclick: move |_| my_trigger.set(!my_trigger()),
            "increment with use_memo",
        }
    }
}
```

**Environment:**
 - Dioxus version: `master`, `0.5`
 - Rust version:    `1.77.1`
 - OS info:        `MacOS 14.4.1, Firefox`
 - App platform:   `web`

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
In the version where `let render_data = `.write().render();`, you never read the signal `my_signal` in the component so the component doesn't subscribe to `my_signal`.

When you change it to read `my_signal`, it starts working because the component subscribes to `my_signal` (reruns when `my_signal` changes)
