### ISSUE TITLE
Make hot reloaded desktop window remember position

### ISSUE THREAD

**Issue by Vacyyyy** [DioxusLabs/dioxus#2569]
On hot reload, the window for the desktop application closes, then re-opens. When it does that, it just plops up somewhere, not where I had it before. This kinda fucks with my workflow.

**Comment by ealmloff** [comment]
This was added in https://github.com/DioxusLabs/dioxus/pull/2116 and will be published in the next release of dioxus

**Comment by jkelleyrtp** [comment]
This should already be in Dioxus 0.5. Make sure you're using the latest of everything.

If it's it not working you might need to re-enable it via the task menu item. If it's still not working- what platform/version/etc are you using?

**Comment by Vacyyyy** [comment]
I am on Windows using Dioxus 0.5.2.Please clearify what you mean by task menu item. Do you mean this ![image](https://github.com/DioxusLabs/dioxus/assets/77296536/06c58c0f-22bc-4b3d-ad53-f91129b0fe6d)? If so, there's no option like that there.

**Comment by jkelleyrtp** [comment]
Looks like you might've been running into this bug - https://github.com/DioxusLabs/dioxus/pull/2730

Gonna close this since that should fix that particular edge case - will reopen this issue if you still run into the bug.
