### ISSUE TITLE
env_logger error on dioxus-cli cargo install

### ISSUE THREAD

**Issue by marad2001** [DioxusLabs/dioxus#2584]
**Problem**

Running though the getting started guide and the below popped up on install of the cli:

error: failed to compile dioxus-cli v0.5.4

Caused by:
failed to select a version for env_logger.
... required by package dioxus-cli v0.5.4
versions that meet the requirements ^0.11.3 are: 0.11.3

the package dioxus-cli depends on env_logger, with features: anstream but env_logger does not have these features.
It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

failed to select a version for env_logger which could resolve this conflict

Running on windows 10, via Powershell.

**Steps To Reproduce**

Run "cargo install dioxus-cli" in Powershell on Windows 10. 

**Expected behavior**

Installation of the dioxus cli.

**Environment:**
 - Dioxus version:  dioxus-cli v0.5.4
 - Rust version:    1.70
 - OS info:         Windows 10

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start and I'm pretty sure this is beyond my capabilities. 
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
We published a 0.5.6 of the CLI with updates as well as the binstall for 0.5.6 so you don't need to cargo install it yourself.

I can't replicate this, but it's very likely one of our dependencies changed how they do features for a period of time. We released 0.5.6 earlier this week and I've confirmed locally that this should be fixed.
