### ISSUE TITLE
Decoding issue with emojis using the web platform

### ISSUE THREAD

**Issue by HaHa421** [DioxusLabs/dioxus#2589]
**Problem**

I am using the latest version of Dioxus and I have encountered an issue when using emojis in the text. When an emoji is present in the text, I get the following error:

```
Uncaught (in promise) TypeError: Failed to execute 'decode' on 'TextDecoder': The provided ArrayBufferView value must not be shared.
    at RawInterpreter.run (inline0.js:130:37)
    at imports.wbg.__wbg_run_2ca7d9c27d6a5eb6 (app.js:612:25)
    at app.wasm.dioxus_interpreter_js::unified_bindings::Interpreter::flush::h009ba4a86f46ba0f (app_bg.wasm:0x4f1ec6)
```

This only occurs when the text contains emojis. If I remove the emojis from the text, everything works normally.

**Steps To Reproduce**

this occurs when I use ul { "😃" } but I suppose it will happen for any element with any emoji

- same as above

**Expected behavior**

emojis are displayed without error

**Environment:**
 - Dioxus version:  v0.5.1
 - Rust version:    1.81.0, `nightly`
 - OS info:         Windows Edge
 - App platform:    `web`

**Comment by HaHa421** [comment]
I ended up patching [sledgehammer_bindgen_macro/src/types/string.rs](https://github.com/ealmloff/sledgehammer_bindgen/blob/master/sledgehammer_bindgen_macro/src/types/string.rs#100)
with 
```js
let sharedView = new DataView(this.m.buffer, this.lsp, this.sl);
                    let arrayBuffer = new ArrayBuffer(sharedView.byteLength);
                    new Uint8Array(arrayBuffer).set(new Uint8Array(sharedView.buffer, sharedView.byteOffset, sharedView.byteLength));
                    this.s = this.c.decode(arrayBuffer);
                  
                    /*
                    this.s = this.c.decode(new DataView(this.m.buffer, this.lsp, this.sl));
                    */
```
it also lets Dynamic Attributes work smoothly with rsx! 
the main caveat is that the buffer gets copied every time this code is ran , I suppose the buffer could be checked against: 
```js
if (this.m.buffer instanceof SharedArrayBuffer) ...
```

**Comment by ealmloff** [comment]
To reproduce this issue, you need to:
1) Transfer large chunks of strings or non-ascii strings to hit that path of text decoding:
```rust
use dioxus::prelude::*;

fn main() {
    launch(|| rsx! { ul { {"😃".repeat(1000)} } })
}
```
2) Enable a bunch of rust nightly flags to make wasm multithreaded described here: https://rustwasm.github.io/wasm-bindgen/examples/raytrace.html
