### ISSUE TITLE
[DOCS] SSR example issues

### ISSUE THREAD

**Issue by malcolmrebughini** [DioxusLabs/dioxus#259]
## Specific Demand

(Filing this as a Feature Request because a bug seemed too harsh :grimacing: )

The docs for SSR that can be found [here](https://dioxuslabs.com/reference/ssr/index.html) have a some errors.

## Implement Suggestion

1. There's a line that prompts the user to "Add Dioxus with the desktop feature". This should be the `ssr` feature, the actual command is correct.
2. The line that prompts the user to add tokio is incorrect:
```
cargo add dioxus tokio --features full
```
This should be just `cargo add tokio --features full`
 
3. The code to start the server does not compile. `into_make_service()` needs to be called for Router:
```rust
Router::new().route("/", get(app_endpoint)).into_make_service() 
```

I couldn't find these docs in any of the repos in this org. If someone can point me to it I'll be happy to update

**Comment by DogeDark** [comment]
The page you found the issues on was recently moved to [/docs/reference/src/platforms/ssr.md](https://github.com/DioxusLabs/dioxus/blob/master/docs/reference/src/platforms/ssr.md) in this repository, but the published version hasn't been updated yet. I believe the issue still persists.
