### ISSUE TITLE
Get access to target clicked on 

### ISSUE THREAD

**Issue by caperaven** [DioxusLabs/dioxus#2590]
## Feature Request

In js you can use the event.target to see what the element is that you clicked on allowing you to have one click event but have more flexibility.

## Implement Suggestion

For example
```
#[component]
pub fn menu() -> Element {
    rsx! {
        div {
            class: "menu-left",
            ul {
                onclick: move |event| {
                    if event.target.tag_name == "li" { ... }
                },

                li { "Home" }
                li { "About" }
                li { "Contact" }
                li { "Blog" }
            }
        }
    }
}
```

**Comment by ealmloff** [comment]
It would be nice to support something like target in the future that returns a boxed platform independant element type (like the onmounted event today). As a workaround, if you are targeting the web, you can downcast events to their web-sys event counterpart with the `web_event` method:
```rust
#[component]
pub fn menu() -> Element {
    rsx! {
        div {
            class: "menu-left",
            ul {
                onclick: move |event| {
                    let raw_event = event.web_event();
                    // ...
                },

                li { "Home" }
                li { "About" }
                li { "Contact" }
                li { "Blog" }
            }
        }
    }
}
```
Then you can get the [target](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Event.html#method.target) of that web-sys event

**Comment by caperaven** [comment]
Ok, groovy, ty

**Comment by filips123** [comment]
How to do this when targeting desktop? Web events don't seem to be available in that case.
