### ISSUE TITLE
Dioxus v5 no longer hides window decorations when disabled (works in v4)

### ISSUE THREAD

**Issue by imgurbot12** [DioxusLabs/dioxus#2595]
**Problem**

Disabling Window Decorations for Dioxus Desktop using the latest release of `v0.5.1` does not actually hide the default decorations anymore.

**Steps To Reproduce**

Here's a simple script to replicate the issue

```rust
use dioxus::prelude::*;

fn app() -> Element {
    rsx! { "Hello World!" }
}

fn main() {
    let window = dioxus_desktop::WindowBuilder::default().with_decorations(false);
    let config = dioxus_desktop::Config::default().with_window(window);
    LaunchBuilder::desktop().with_cfg(config).launch(app);
}
```

**Expected behavior**

In Version `v0.4.3` the Decorations are hidden as intended
```rust
use dioxus::prelude::*;

fn app<'a>(cx: Scope<'a, ()>) -> Element<'a> {
    cx.render(rsx! { "Hello World!" })
}

fn main() {
    let builder = dioxus_desktop::WindowBuilder::new().with_decorations(false);
    let config = dioxus_desktop::Config::new().with_window(builder);
    dioxus_desktop::launch_cfg(app, config);
}
```

**Environment:**
 - Dioxus version:  `dioxus = { version = "0.5.1", features = ["desktop"] }`
 - Rust version:   `rustc 1.79.0 (129f3b996 2024-06-10)`
 - OS info:  Ubuntu 24.04 LTS
 - App platform:   Desktop

**Questionnaire**

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by imgurbot12** [comment]
I thought this might be an upstream issue related to wry/tao since that happens to be the library behind the actual window rendering and is the source of `WindowBuilder` but running the wry [simple example](https://github.com/tauri-apps/wry/blob/dev/examples/simple.rs) doesn't include any decorations even when including `with_decorations(true)`

```rust
let window = WindowBuilder::new()
        .with_decorations(false)
        .build(&event_loop)
        .unwrap();
```

Changing it from true/false doesn't effect decorations whatsoever and none appear so I have no idea where the decorations from dioxus are even coming from.

Running tao's [decorators example](https://github.com/tauri-apps/tao/blob/dev/examples/decorations.rs) has similar issues. Decorations neither appear or reappear as they are always missing no matter what I do.

Considering I want the decorations disabled this would be a preferred bugged behavior over the basically useless decorators that are there in dioxus lol.

**Comment by imgurbot12** [comment]
The issue still persists with the latest from master branch as well sadly.
![decorators](https://github.com/DioxusLabs/dioxus/assets/21094168/724e74d8-4763-40d1-8a5f-b9872ce33d39)

**Comment by imgurbot12** [comment]
Ayo, after trying random things I noticed an [existing PR](https://github.com/DioxusLabs/dioxus/pull/2518) related to custom decorations so I decided to poke around to see if I could find something related to the issue and turns out I found [a call](https://github.com/DioxusLabs/dioxus/pull/2518/files#diff-42711db5735666be8dee1e56d9029ac67cd7672e72328b8902b6c3efccd7d04fR39) that hides the decorators.

It appears you have to call `.with_menu(None)` onto `dioxus_desktop::Config` like the following:

```rust
use dioxus::prelude::*;

fn app() -> Element {
    rsx! { "Hello World!" }
}

fn main() {
    let window = dioxus_desktop::WindowBuilder::default()
        .with_title("ayy lmao")
        .with_decorations(false);
    let config = dioxus_desktop::Config::default()
        .with_window(window)
        .with_menu(None);
    LaunchBuilder::desktop().with_cfg(config).launch(app);
}
```

I'm not sure if `with_decorations(false)` is supposed to override `with_menu` which is how I assume it operates in previous versions or if this is intentional so without clarification from the devs I'm going to leave the issue open for the moment.

**Comment by ealmloff** [comment]
Tao moved menu related utilities into a separate crate between dioxus 0.4 and 0.5. We currently set a default menu bar if menu is unset. I would expect the default menu bar to not be added if you set decorations to false.

If you are interested in fixing this, we set the default menu bar [here](https://github.com/DioxusLabs/dioxus/blob/main/packages/desktop/src/config.rs#L64). When `with_menu` is called we can check if the menu is decorated with [is_decorated](https://docs.rs/tao/latest/tao/window/struct.Window.html#method.is_decorated)

**Comment by imgurbot12** [comment]
Sure, that sounds like a pretty simple fix. Thanks!
Just opened a PR https://github.com/DioxusLabs/dioxus/pull/2613 :)
