### ISSUE TITLE
Wheel event is missing keyboard modifiers

### ISSUE THREAD

**Issue by kikijiki** [DioxusLabs/dioxus#2597]
## Feature Request

To detect a pinch with the trackpad I think you need to check if the ctrl modifier is present during a wheel event.
Currently that information doesn't seem to be available in the event data.

## Implement Suggestion

Implement the `ModifiersInteraction` for `WheelEvent` too.

**Comment by ealmloff** [comment]
The [web WheelEvent](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event#event_properties) doesn't have that information about active modifiers. We generally try to stay pretty close to a rusty version of events that the browser gives us. Dioxus provides nicer types and traits on top of web-sys events, but we try not to change the structure significantly

You can combine information from onkeydown and your scroll event to achieve the same effect

**Comment by ealmloff** [comment]
The web `WheelEvent` inherits from `MouseEvent` which has information about modifiers and the position of the event. We should implement [PointerInteraction](https://docs.rs/dioxus/latest/dioxus/prelude/trait.PointerInteraction.html) for WheelEvent
