### ISSUE TITLE
route macro fails to compile with path separator `::` syntax

### ISSUE THREAD

**Issue by xpe** [DioxusLabs/dioxus#2599]
**Problem**

It seems that the Dioxus `route` macro fails to compile when presented with `::` syntax; e.g. for aliases. See below.

**Steps To Reproduce**

```rust
#![allow(non_snake_case)]

use dioxus::prelude::*;

use crate::components as c;

#[derive(Clone, Routable, Debug, PartialEq)]
pub enum Route {
    #[route("/")]
    c::Home {},
}
```

**Compilation Error**

```console
error: expected one of `(`, `,`, `=`, `{`, or `}`, found `::`
  --> src/route.rs:11:6
   |
11 |     c::Home {},
   |      ^^ expected one of `(`, `,`, `=`, `{`, or `}`
   |
   = help: enum variants can be `Variant`, `Variant = <integer>`, `Variant(Type, ..., TypeN)` or `Variant { fields: Types }`
```

**Expected behavior**

The file should compile.

**Environment:**

 - Dioxus version:  dioxus 0.5.4
 - Rust version: rustc 1.79.0 (129f3b996 2024-06-10)
 - OS info: macOS 4.5 (23F79)
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later
- [x] The above questionnaire could be improved, I think
- [x] I have some interest in helping conditional on it being a bug and a PR being welcomed
- [x] I have interest in helping, but I don't know the time investment involved

**Comment by ealmloff** [comment]
The routeable macro doesn't change the syntax of how enums are defined, but you can explicitly pass the path of the component the route can render as the second argument to `#[route]`:

```rust
mod other;

#[derive(Clone, Routable, Debug, PartialEq)]
pub enum Route {
    #[route("/", other::MyOtherComponent)]
    Home {},
}
fn main() {
    launch(|| rsx!{Router::<Route> {}});
}
```

**Comment by xpe** [comment]
Thanks. This is clear now. Looking back, the idea of a router DSL was first in my mind, not a Rust enum definition. But it is both.
