### ISSUE TITLE
Implement lifecycle component

### ISSUE THREAD

**Issue by mrgzi** [DioxusLabs/dioxus#2601]
## Feature Request

Dioxus uses hooks for component state and lifecycle, which is different from other frameworks that use clear lifecycle methods. This can be hard for developers who are used to those methods. I would like to propose a feature to help these developers by mimicking lifecycle methods using hooks.

```rs
pub fn App() -> Element {
    rsx! {
        Lifecycle {
            on_mount: move || println!("Component mounted")),
            on_update: move || println!("Component updated")),
            on_unmount: move || println!("Component unmounted")),
        }
}
```

**Benefits:**

* Makes it easier for developers from other frameworks to use Dioxus.
* Lowers the learning curve by using familiar concepts.
* Encourages more developers to try Dioxus.

### Where I am trying to get?

I would like to have the same experience like other frameworks. if https://github.com/DioxusLabs/dioxus/issues/2600 and this issue implemented, we can write the logic like this;

```rs
struct MyComponent {}

impl MyComponent {
    fn on_mount() {
        println!("Component has been mounted");
    }

    fn on_update(){
        println!("Component has been updated");
    }

    fn on_unmount() {
        println!("Component has been unmounted");
    }

    #[component]
    fn view(&self) -> Element {
        rsx! {
            Lifecycle {
                on_mount: on_mount,
                on_update: on_update,
                on_unmount: on_unmount,
                div {
                    "Hello!"
                }
            }
        }
    }
}
```

```rs
pub fn App() -> Element {
    rsx! {
        MyComponent::view {}
    }
}
```

I understand that many developers believe hooks are the best approach. However, this proposal would allow Dioxus to offer greater flexibility and diversity during the development phase.

**Comment by jkelleyrtp** [comment]
This isn't something we want to add today but if it becomes useful maybe we'll reconsider it. It's hard to support lots of variants of app architectures while also shipping other important things, so not planned as of today.
