### ISSUE TITLE
Provide intellisense and auto import for component names in `rsx` macro

### ISSUE THREAD

**Issue by mrgzi** [DioxusLabs/dioxus#2602]
## Feature Request

While working with the `rsx!` macro in Dioxus, I frequently find myself uncertain whether I'm typing the component name correctly. This often leads me to navigate back to the file containing the component's definition to copy the exact name, which disrupts the flow of development. Integrating intellisense and auto importing for component names directly within the `rsx!` macro would significantly improve productivity.

**Comment by ealmloff** [comment]
Autocomplete was fixed in https://github.com/DioxusLabs/dioxus/pull/2421 which also lets RA import items as you type

**Comment by mrgzi** [comment]
@ealmloff It doesn't work for me and I use dioxus main branch.

**Comment by ealmloff** [comment]
> @ealmloff It doesn't work for me and I use dioxus main branch.

Do you use rust analyzer?

**Comment by mrgzi** [comment]
Yes, I think it does work if you use component in the same file. If component is in another file, it doesn't work.
