### ISSUE TITLE
Auto-fill crashes desktop app

### ISSUE THREAD

**Issue by rhaskia** [DioxusLabs/dioxus#2615]
**Problem**
When clicking on the edge autofill for an input, I get the following panic message and my app crashes:
```
thread 'main' panicked at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dioxus-html-0.5.1\src\transit.rs:41:17:
Failed to deserialize event data for event keydown:  MissingField(
    "char_code",
)
'Map(
    {},
)'
```

**Steps To Reproduce**
- Have an input, with previously entered data or however edge does that.
- Click into the input field, and the autofill should show up
- Click on any of the "Saved Data" and it should crash

**Expected behavior**
For the app not to crash, and the value to be put into the input.

**Screenshots**
![image](https://github.com/DioxusLabs/dioxus/assets/94507929/259bce73-a5b2-49ac-84e9-70faca4a74b5)

**Environment:**
 - Dioxus version:  0.5.1
 - Rust version: 1.79.0-nightly
 - OS info: Windows 10
 - App platform: Desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
If the browser doesn't give us any data for the event, we should probably not fire the event at all. Instead of panicing when deserialization fails, we can just return the serialization error and log it

**Comment by ealmloff** [comment]
Fixed in https://github.com/DioxusLabs/dioxus/pull/2664
