### ISSUE TITLE
Fresh Dioxus project (web, router on, vanilla JS) doesn't work on current `main` branch

### ISSUE THREAD

**Issue by xpe** [DioxusLabs/dioxus#2616]
**Problem**

Code generated by `dx new` doesn't work against Dioxus `main` branch (as of today, July 9).

**Steps To Reproduce**

1. Install `dioxus-cli` from source (`main` branch).
2. Generate a new Dioxus project using: `dx new` > web > router on > vanilla JS.
3. (Note that it works fine as is -- when Dioxus 0.5 stable
4. But if you change the Dioxus dependency as follows in `Cargo.toml`:

```
dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["web", "router"], branch = "main" }
```

5. Then the app won't render when attempting to navigate to /blog/0 ...

Here is the error:

> SecurityError: Blocked attempt to use history.pushState() to change session history URL from http://192.168.0.223:8080/ to http://blog/0. Protocols, domains, ports, usernames, and passwords must match. (same error on both Safari and Chrome, running on macOS) 

**Expected behavior**

The usual behavior -- no error when rendering /blog/0.

**Environment:**

 - Dioxus version: `main`
 - Rust version: `cargo 1.79.0 (ffa9cf99a 2024-06-03)`
 - OS info: macOS
 - App platform: web

**Comment by ealmloff** [comment]
I cannot reproduce this issue on the main branch of Dioxus. Here is the repo I attempted to reproduce the issue with: https://github.com/ealmloff/failed-dioxus-repo-2616

**Comment by xpe** [comment]
@jkelleyrtp I just confirmed this fixes the problem.

(Reminder to self: use `cargo update` liberally when using Dioxus as a git dependency)
