### ISSUE TITLE
v0.5 bundle fails copying resources due to file names

### ISSUE THREAD

**Issue by prasannavl** [DioxusLabs/dioxus#2617]
**Problem**

- `dx new` -> Web application 
- `RUST_BACKTRACE=1 dx bundle -r` 
- Trace below.

```
build desktop done
Adding assets from dist to bundle
thread 'main' panicked at /home/pvl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-cli-0.5.4/src/cli/bundle.rs:193:13:
Failed to bundle project: BundlerError(
    Error {
        context: "Failed to build data folders and files",
        source: BundlerError(
            Error {
                context: "Failed to copy resource files",
                source: IoError(
                    Os {
                        code: 36,
                        kind: InvalidFilename,
                        message: "File name too long",
                    },
                ),
            },
        ),
    },
)
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: dioxus_cli::cli::bundle::Bundle::bundle
   3: tokio::runtime::park::CachedParkThread::block_on
   4: dx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Info: 
- My current pwd looks like this: `/home/pvl/src/dx/dxweb` -- so nothing fancy. 
- The rust builds are all under the expected defaults under ./target, and ./dist with the dioxus and cargo defaults

**Environment:**
 - Dioxus version:  0.5
 - Rust version:  rustc 1.79.0 (129f3b996 2024-06-10)
 - OS info:  Ubuntu-24.04 LTS
 - App platform:  web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This looks like a duplicate of https://github.com/DioxusLabs/dioxus/issues/2239. The git version of `dx bundle` should fix this issue

**Comment by prasannavl** [comment]
Thanks, those seem to be the ones. Closing.
