### ISSUE TITLE
NodeRef seems to have disappeared

### ISSUE THREAD

**Issue by prasannavl** [DioxusLabs/dioxus#2619]
## Summary 

Docs mention `NodeRef` as completed here:

- https://dioxuslabs.com/learn/0.5/contributing/roadmap

Searching for the entire dioxusorg for noderef: https://github.com/search?q=org%3ADioxusLabs%20noderef&type=code, I couldn't find anything that's relevant. 

The only reference appears to be an old doc:  https://github.com/DioxusLabs/docsite/blob/b6fed2675b0046a17672ac4d9295e0bca64d5079/posts/old.md?plain=1#L86 and some md files that appears to be tracking info. 

Should the docs be updated? Would appreciate any info on how to get the node_ref of a mounted node, or if it isn't currently possible without using websys?   

### Context

I'm trying to get a noderef to a canvas from the DOM so I can use it. Couldn't find any info on how to do it, beyond using web_sys and making an assumption that it would be rendered in arbitrary ways and querying the dom. There seems to be no documented way to fetch the node after it has been rendered deterministically.

Related: https://github.com/DioxusLabs/dioxus/issues/69 - This appear to have been closed without any explanation as well.

**Comment by prasannavl** [comment]
Ok, digging a bit deeper into the source, seems using `use_effect` and `use_drop` are the mount / unmount lifecycle equivalents. This seems to do it for now. 

Would still be great to know if there's a better way than doing a get_element_by_id or query selector to find the node.  node_ref would have been a perfect one for this. 

```
    use_effect(|| {
        let window = web_sys::window().unwrap();
        let document = window.document().unwrap();
        let canvas = document.get_element_by_id("cx").unwrap();
        let canvas: web_sys::HtmlCanvasElement = canvas
            .dyn_into::<web_sys::HtmlCanvasElement>()
            .map_err(|_| ())
            .unwrap();
            ... 
        })
```

**Comment by ealmloff** [comment]
You can use the onmounted event to get a web-sys reference to a mounted node. The git version of dioxus has some inline docs about onmounted [here](https://github.com/DioxusLabs/dioxus/blob/156144e8f5b067a2117da883ef7b437adc46473e/packages/html/src/events/mounted.rs#L141-L195) and some more general docs about side effects [here](https://github.com/DioxusLabs/dioxus/blob/156144e8f5b067a2117da883ef7b437adc46473e/packages/hooks/docs/side_effects.md?plain=1#L59-L102). https://github.com/DioxusLabs/docsite/issues/292 is a similar issue about adding docs about web-sys integration to the docsite

**Comment by prasannavl** [comment]
Perfect! Exactly what I was looking for. Thanks for the help :)  -- We can perhaps close this, think people who are looking for the same might stumble on the issue and get the info from there until docs are updated.
