### ISSUE TITLE
Document TUI status and roadmap on docsite

### ISSUE THREAD

**Issue by prasannavl** [DioxusLabs/dioxus#2620]
- TUI is still mentioned in the docs, home page and in many places. However: 

  - As of v0.5, could not find the TUI package in the source code.
  - Examples don't work
  - The last dioxus-tui package seems to be at 0.5-alpha.2 that also appears to have been removed from the main branch in source code.
  -  It seems that the examples were first moved to blitz renderer and found indications that the packages is being moved over there, however the examples appear to have been removed from there as well along with package source. 
  
Question: Could you please clarify on the status of TUI if it's removed entirely or if it's still on the roadmap for Tier 2 as stated in the docs? The code has diverged significantly to the point that the docs, examples and website appears to be misleading now :( Would love to hear any insights on this from the team - was really looking forward to TUI :)

**Comment by mrgzi** [comment]
I also don't know what is current status of TUI. Is it possible to integrate ratatui into dioxus?

**Comment by ealmloff** [comment]
The TUI renderer was briefly moved into blitz, but was removed with the blitz rewrite. The old version of TUI lives [here](https://github.com/DioxusLabs/blitz/tree/legacy/packages/dioxus-tui), but it no longer kept up to date with dioxus. Forks are welcome if anyone is interested in maintaining a version of `dioxus-tui`. Once Dioxus and Blitz are more stable, we might be able to restore dioxus-tui backed by the blitz representation of the dom/layout/styles

**Comment by erlend-sh** [comment]
The v0.6 milestone lists:

> dx rewrite sporting a new TUI

Is this still planned? It sounds more like it’s planned for a later release.

**Comment by ealmloff** [comment]
> The v0.6 milestone lists:
> 
> > dx rewrite sporting a new TUI
> 
> Is this still planned? It sounds more like it’s planned for a later release.

The git version of DX is a TUI today. It uses ratatouille instead of dioxus-tui

**Comment by jkelleyrtp** [comment]
Moving this issue to the docsite 0.6.0 PR - this is done but we're not done with the entire 0.6.0 overhaul

**Comment by JakkuSakura** [comment]
<img width="1146" height="797" alt="Image" src="https://github.com/user-attachments/assets/060b8221-3c1b-4496-b2a9-2e0a3c634386" />
Want to advertise my overhual of dioxus-tui. It works perfect on MacOS with HiDPI support. Multiple modes
https://github.com/JakkuSakura/dioxus-tui

**Comment by musjj** [comment]
@jkelleyrtp 

I can't find the issue in https://github.com/DioxusLabs/docsite

What's the general status of Dioxus TUI?
