### ISSUE TITLE
`dx serve` seems to recompile server dependencies every time

### ISSUE THREAD

**Issue by hampuslidin** [DioxusLabs/dioxus#2622]
**Problem**

When I run `dx serve` on my fullstack project which has the `surrealdb` dependency enabled behind the `server` feature, it will recompile that dependency every time. I choose `surrealdb` as an example because it has a very long compilation time, but I think this applies to any dependency, probably on the `web` feature as well.

**Steps To Reproduce**

- Run `dx new`.
- Choose "Fullstack".
- Call the project "test".
- Choose "true" for using Dioxus router.
- Choose "Vanilla" as CSS.
- Add surrealdb as dependency only on the server feature.
- Run `dx serve --platform fullstack`.
- Make any compilable change in `main.rs` and save.
- Observe `surrealdb` being recompiled.

**Expected behavior**

Only our crate should recompile and none of its dependencies.

**Environment:**
 - Dioxus version:  0.5.1
 - Rust version:    1.79.0
 - OS info:         macOs
 - App platform:    Fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
I cannot reproduce this issue on the `main` branch of dioxus with a simple dependency: https://github.com/ealmloff/dioxus-recompile-test 

This issue may have been fixed or your dependency may have a build script that reruns too often. Build scripts can watch specific parts of your environment for changes and recompile the crate when a change is observed

**Comment by ealmloff** [comment]
I cannot reproduce this with a dependency with a simple build script: https://github.com/ealmloff/dioxus-recompile-test

Build scripts can watch specific parts of your environment and recompile when they change. SurrealDB may be watching something dioxus is chaninging
