### ISSUE TITLE
null is not an object when dealing with loops

### ISSUE THREAD

**Issue by JustSimplyKyle** [DioxusLabs/dioxus#2634]
**Problem**

Dioxus poped out an error saying `null is not an object` when I'm playing with loops, then it subsequently fails to load the main element, therefore not allowing me to display anything.

**Steps To Reproduce**
I tried making a MRE, but I just can't.
So in the meantime you can notice this issue in my repo here.
https://github.com/JustSimplyKyle/prag-portal/tree/dioxus-test

**Expected behavior**

To display my app.

**Screenshots**

Broken behaviour, you can see `main` contains nothing
![image](https://github.com/user-attachments/assets/e7729771-40fe-44bf-b2e5-344485f9db91)
![image](https://github.com/user-attachments/assets/8ec2fb9a-5817-4157-a2c5-961a8c872184)

**Environment:**
 - Dioxus version: master
 - Rust version:    1.79.0
 - OS info:  Arch Linux
 - App platform:   Desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
I'm guessing #2749 will fix this issue, but without a reproduction it is difficult to tell. The repo you linked requires more undocumented setup not in the readme
