### ISSUE TITLE
Define MSRV == 1.58?

### ISSUE THREAD

**Issue by mstone** [DioxusLabs/dioxus#264]
Hiya, https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/events.rs#L29 is also using the format! string variable capture behavior introduced in rust 1.58, similar to the issue in #246 and #189.

Perhaps it is time to state (and test) that rust 1.58 is the MSRV?

**Comment by jkelleyrtp** [comment]
I think we should just remove our use of 1.58 features and then try to find an MSRV that we compile for that's a little bit lower.

I wonder if there's a way we can force features < 1.58  for cfg uses.

**Comment by mstone** [comment]
Sounds like a plan. :-)
