### ISSUE TITLE
Manganis does not copy assets for examples in a lib project.

### ISSUE THREAD

**Issue by vnermolaev** [DioxusLabs/dioxus#2641]
**Problem**

When creating a Dioxus component, it's beneficial to provide examples. My component references a single picture included in the project using Manganis. 
```rust
pub const COOKIE: &str = manganis::mg!(file("assets/cookie.png"));

#[component]
pub fn Cookie() -> Element {
    rsx! {
        img {
            src: COOKIE
        }
    }
}
```

I also include an example that renders the developed component.
```rust
fn main() {
    launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        Cookie {}
    }
}
```

The example is served with `dx serve --example="wrapper"`

While Manganis seems to output the correct path to the image, the image is never copied to the distribution folder, neither with its original name nor under the expected name.

@ealmloff, I hope it's okay that I tagged you, as you are listed as the Manganis crate owner. Thanks :)

**Steps To Reproduce**

A minimal example showcasing this behaviour can be found here https://github.com/vnermolaev/dioxus-with-example

**Expected behavior**

The referenced image must be copied to the distribution folder.

**Environment:**
 - Dioxus version:  `dioxus = { version = "0.5", features = ["web"] }`
 - Manganis version: `manganis = "0.2.2"`
 - Rust version:    rustc 1.79.0 (129f3b996 2024-06-10)
 - OS info:   MacOS Sonoma 14.5 
 - App platform:  `web`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
The repo you linked is fixed in the latest version of manganis and the dioxus cli. You can install the git version of the CLI with:
```
cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli
```
and the git version of manganis with:
```
manganis = { git = "https://github.com/DioxusLabs/manganis" }
```

**Comment by vnermolaev** [comment]
Amazing! This works, thanks.
I hope these improvements will soon be released in crates.io.

**Comment by vnermolaev** [comment]
Hi there,

I'm sorry to say that I'd like to reopen this issue.

About three weeks ago, I followed the guidance provided, and it did resolve my problem at the time. However, I recently had to re-run the command:

`cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli`

Unfortunately, this broke the build. Specifically, my custom styles are no longer included in the final render, which has affected the appearance of the component. However, the actual stylesheet file is copied to the `dist` folder.

You can see the issue in [dioxus-chessboard](https://github.com/vnermolaev/dioxus-chessboard). If you run the example with:

`dx serve --example=showcase --features showcase --hot-reload=true`

you'll notice the page doesn't look as intended. However, if you manually add the following to the head of the generated HTML file:

`<link rel="stylesheet" href="/chessboard.css">`

the appearance improves significantly.

Thanks for your help!

**Comment by ealmloff** [comment]
There have been some breaking changes to manganis since the last release. CSS is no longer automatically injected into the head (this causes issues when libraries include css conditionally). Instead you can link to a css file with manganis and insert it into the head with the `head::Link` element like [this example](https://github.com/DioxusLabs/dioxus/blob/main/examples/crm.rs#L23-L29)

**Comment by vnermolaev** [comment]
Great, thanks!
