### ISSUE TITLE
Race condition in desktop app startup?

### ISSUE THREAD

**Issue by mstone** [DioxusLabs/dioxus#266]
**Problem**

There seems to be a race condition in the current app initialization logic that results in rendering a blank screen (and requiring a reload to display content) whenever rendering the initial app component takes too long.

**Steps To Reproduce**

Consider these two very similar apps:

```rust
fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        div { "Hello, world!" }
    })
}
```

vs

```rust
fn app(cx: Scope) -> Element {
    std::thread::sleep(std::time::Duration::from_millis(1_000));
    cx.render(rsx! {
        div { "Hello, world!" }
    })
}
```

Both apps should produce the same final view (after the indicated delay in the latter case) but today, they don't; the first renders correctly while the second produces an empty window.

**Comment by mstone** [comment]
Quick update: I was eventually able to use `use_future` to move the expensive computation simulated above to work around this issue.

**Comment by nbittich** [comment]
same here. documentation is very poor. compile fine but undefined behavior at runtime (white screen, no error logged). also documentation is not in aync with the actual api
