### ISSUE TITLE
HTML tag INPUT with assigned VALUE property as Signal re-rendering every time

### ISSUE THREAD

**Issue by AnatoliiShliakhto** [DioxusLabs/dioxus#2661]
For example:
`
let mut form_values = use_signal(HashMap::<String, FormValue>::new);
let some_signal = use_signal(|| "something".to_string());

rsx! { 
  form {
   oninput : move |event|  form_values.set(event.values()),
   input { name: "some_name", value: some_signal() } 
}
`

After that INPUT field will stuck cuz INPUT->VALUE always sets to "something" every time....

**Comment by ealmloff** [comment]
If you set the value on an input, that input's value is always set to that value. This is useful for [controlled inputs](https://dioxuslabs.com/learn/0.5/reference/user_input#controlled-inputs). If you only want to set the initial value for the input, you can use the `initial_value` attribute instead:

```rust
let mut form_values = use_signal(HashMap::<String, FormValue>::new);
let some_signal = use_signal(|| "something".to_string());

rsx! {
    form {
        oninput : move |event| form_values.set(event.values()),
        input { name: "some_name", initial_value: "{some_signal}" }
    }
}
```
