### ISSUE TITLE
 failed to run custom build command for `serde v1.0.204`                                                                                                     

### ISSUE THREAD

**Issue by jr-create** [DioxusLabs/dioxus#2662]
**Problem**

Unable to install dioxus-cli                                                                                            

When installing dioxus-cli on windows, I get "Failed to run custom build command for 'Serde v1.0.204'"   
**Steps To Reproduce**
cargo install dioxus-cli --force
![image](https://github.com/user-attachments/assets/c43f8931-8cda-424f-98a2-7dbfa3b92cba)

When you run a cargo command from the command line, the file permissions are automatically modified to read-only

such as :
https://users.rust-lang.org/t/solved-cargo-could-not-execute-process-permission-denied-os-error-13/106531  ||
https://github.com/rust-lang/cargo/issues/6757

**Environment:**
 - Dioxus version:  `master` 
 - Rust version:   cargo 1.79.0 , `stable` 
 - OS info:         Windows

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
Your E drive is your recovery drive on windows, which makes sense as to why it's a read-only filesystem.
Were you trying to install dioxus-cli while in recovery mode?

Serde is not our crate but it's also not the issue here. Make sure you have rust installed properly - it sounds like your AllProject folder is on your E drive when it should be on a normal drive like C://

**Comment by jr-create** [comment]
Yes, I think it should be my computer's problem, I can install and compile Dioxus on other computers. But I don't know what the reason is
![image](https://github.com/user-attachments/assets/30327895-8608-4d1a-8cf0-4a38b1feff56)
At last，same problem on C drive, I'm going to reinstall my system
