### ISSUE TITLE
dx new creates a project with 'unused import: `info` ' warning from clippy

### ISSUE THREAD

**Issue by magikmw** [DioxusLabs/dioxus#2665]
**Problem**

Fullstack (likely other) project templates generate a file with this line:

`use tracing::{info, Level};`

It's flagged by clippy and LSP as:

`unused import: info #[warn(unused_imports)] on by default [unused_imports]`

**Steps To Reproduce**

- dx new
- let rustc / clippy analyze the code

**Expected behavior**

Default project templates shouldn't throw warnings at users (especially new users).

New users are tempted to remove `info` from the use directive only to end up with this line breaking:

`tracing::info!("Client received: {}", data);`

I'm unsure if it's an issue with tracing or dioxus.

**Screenshots**

**Environment:**
 - Dioxus version:  0.5.6 (cli)
 - Rust version:   1.79.0
 - OS info:         Fedora 40, Linux 6.9.9
 - App platform:    `fullstack`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
The tracing log in the server function should be `tracing::info!` instead of `info!` here https://github.com/DioxusLabs/dioxus-template/blob/main/Fullstack/src/main.rs#L90
