### ISSUE TITLE
Change Default Fullstack IP complie error: ERROR dioxus_cli_config: A library is trying to access the crate's configuration, but the dioxus CLI was not used to build the application.

### ISSUE THREAD

**Issue by zuijiaoghb** [DioxusLabs/dioxus#2681]
[root@cpzljc dzsyhp]# cargo run --features server -- --addr 188.188.1.26 --port 8081
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.00s
     Running `target/debug/dzsyhp --addr 188.188.1.26 --port 8081`
Listening on 127.0.0.1:8080
2024-07-23T02:22:12.716952Z ERROR dioxus_cli_config: A library is trying to access the crate's configuration, but the dioxus CLI was not used to build the application.

[root@cpzljc dzsyhp]# dx serve --addr 188.188.1.26 --port 8081
Dioxus @ v0.5.6 [10:28:21]

    > Hot Reload Mode: RSX
    > Watching: [ src, assets, Cargo.toml, Dioxus.toml ]
    > Custom index.html: None
    > Serve index.html on 404: True

    > Build Features: [ server ]
    > Build Profile: Debug
    > Build took: 57 millis

Listening on 127.0.0.1:8080
| 💼 Waiting to start building the project...                                                           
error: unexpected argument '--addr' found

Usage: cargo build --target [<TRIPLE>] --message-format <FMT> --quiet --features <FEATURES>

For more information, try '--help'.
Error: 🚫 Serving project failed:

Caused by:
    No output location found

**Comment by ealmloff** [comment]
Can you provide information about your environment from the template (OS, dioxus-cli version, dioxus version)? `--addr` is a new flag in the git version of the dioxus cli and the versions of the `dioxus-cli` and `dioxus` must match

**Comment by zuijiaoghb** [comment]
OS：centos8
dioxus-cli version:  v0.5.6 or v0.5.4
 dioxus version: version = "0.5.6" , features = ["fullstack","router"]

**Comment by ealmloff** [comment]
The `--addr` is only available in the git version of dioxus. If you are using an older version of dioxus, you can set it in the fullstack config with the [`.addr()`](https://github.com/DioxusLabs/dioxus/blob/v0.5/packages/fullstack/src/config.rs#L54-L60) method
