### ISSUE TITLE
Merging conditional classes broken by #2258

### ISSUE THREAD

**Issue by chungwong** [DioxusLabs/dioxus#2691]
**Problem**

[Discord reference](https://discord.com/channels/899851952891002890/1265128121091358741)
**Steps To Reproduce**
With this new change in the main https://github.com/DioxusLabs/dioxus/commit/88af3e7eff31e919257133e7715f57611b1b252c
The error message is ambigious and I have no idea how to fix it.
```
error: Cannot merge non-fmt literals
       = help: Only formatted strings can be merged together. If you want to merge literals, you can use a format string.
  --> src/client/ui/select.rs:42:17
   |
42 |                 class: if on { "border-indigo-600" } else { "border-transparent" },
   |                 ^^^^^
```
**Expected behavior**
 Dioxus should accept expressions that are text

**Environment:**
 - Dioxus version:  commit at 88af3e7eff31e919257133e7715f57611b1b252c

**Comment by chungwong** [comment]
@ealmloff  With the latest fix, it doesn't cover the following case.  Is it expected?
```rs
let off = "bg-gray-200";
let on = "bg-indigo-600";

error: Cannot merge non-fmt literals
       = help: Only formatted strings can be merged together. If you want to merge literals, you can use a format string.   |
38 |                 class: if state() { right } else { left }
```

**Comment by ealmloff** [comment]
> @ealmloff With the latest fix, it doesn't cover the following case. Is it expected?
> 
> ```rust
> let off = "bg-gray-200";
> let on = "bg-indigo-600";
> 
> error: Cannot merge non-fmt literals
>        = help: Only formatted strings can be merged together. If you want to merge literals, you can use a format string.   |
> 38 |                 class: if state() { right } else { left }
> ```

Yes, we only support merging formatted literals, but you add variables to formatted sections like this: `class: if state() { "{right}" } else { "{left}" }`
