### ISSUE TITLE
Add commit hash to `dx -V`

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus#2693]
## Feature Request

It's impossible to know which exact version is used in the CLI unless a commit hash is also shown.

## Implement Suggestion

Pretty sure it's just some compile-time macro that everyone else uses (maybe a new crate).

**Comment by Andrew15-5** [comment]
I will handle this one.

**Comment by jkelleyrtp** [comment]
We have this info now thanks to our use of the "built" crate - just need it exported
