### ISSUE TITLE
After installing all dependencies on linux specified for Tauri on linux, fails in WSL but works for Windows

### ISSUE THREAD

**Issue by brandonpollack23** [DioxusLabs/dioxus#2694]
**Problem**

Followed the Tauri setup instructions for desktop, installed all dependencies but I get a segmentation fault after some logging on dx serve.

**Steps To Reproduce**

Try running on WSL (I use manjaro)

Empty project, dx serve

**Expected behavior**

Get an X window with WSLg

**Screenshots**

**Environment:**
 - Dioxus version:  .5
 - Rust version:    stable
 - OS info:         WSL windows
 - App platform:    desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by DogeDark** [comment]
If I recall correctly, I had a segmentation fault when using a certain setting for `DISPLAY=`. Setting `DISPLAY=:0` worked for me.

**Comment by brandonpollack23** [comment]
Sadly no luck, I'm running a weird Manjaro thing perhaps it is that...but i have all the arch dependencies

**Comment by brandonpollack23** [comment]
Got it!  Just :0 doesnt work but this command gets teh IP and taht works:
```
export DISPLAY=$(route.exe print | grep 0.0.0.0 | head -1 | awk '{print $4}'):0.0
```
