### ISSUE TITLE
Not able to run the output of a build/bundle for fullstack application

### ISSUE THREAD

**Issue by zacbre** [DioxusLabs/dioxus#2701]
**Problem**

After building or bundling for release, fullstack is not able to run correctly. I looked through tons of documentation/issues/code, and was not able to find what the index_path is for. The index.html file exists in the dist directory. Maybe I'm missing something as far as deploying a fullstack application goes.

**Steps To Reproduce**

- Create a new fullstack project
- run `dx build --platform fullstack --release`
- try to run the dist output binary in the `dist` folder.

**Expected behavior**

The application should run without errors.

**Screenshots**

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/0327efff-bd81-4875-82b4-a31001fd86d3">
<img width="756" alt="image" src="https://github.com/user-attachments/assets/e40ddf31-0ea3-4daf-9aa3-f8446cdeb0c0">

**Environment:**
 - Dioxus version: v0.5.6
 - Rust version:     v1.79.0
 - OS info:             MacOS Sonoma/Debian 12 (Bookworm)
 - App platform:    Fullstack

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
You need to run the binary from the folder above `/dist`. If your folder is at `/a/b/c/dist` and your executable is named `my-project`, you need to run `./dist/myproject` from the working directory `/a/b/c`.

Dioxus should let you run the binary inside of `/dist` and move static assets into a separate folder inside of `/dist/static` for fullstack to serve

**Comment by zacbre** [comment]
Can confirm, this does let me run it. I agree, you should be able to run it from within the dist directory. Glad to see it's being added to the 0.6.0 milestone 🙂
