### ISSUE TITLE
Seperate Client and Server Fails to Build

### ISSUE THREAD

**Issue by wheregmis** [DioxusLabs/dioxus#2704]
**Problem**
Failed to build for web platfrom in fullstack axum_auth example. I am using git version of dioxus

dx build --platform web --features web
Error: 🚫 Building project failed:

Caused by:
    0: Failed to load Dioxus workspace
    1: Failed to find target with name: axum_auth
**Steps To Reproduce**
Tried running axum_auth example from fullstack/examples

- 
- 
- 

**Expected behavior**
Should Run

**Screenshots**

**Environment:**
 - Dioxus version:  
 - Rust version:    
 - OS info:         
 - App platform:    

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
This is likely because you're not in the right folder. The warning here should be more descriptive to give you some options re: which binaries can be ran.
