### ISSUE TITLE
Support `#[layout]` without trailing `#[route]`

### ISSUE THREAD

**Issue by matthunz** [DioxusLabs/dioxus#2709]
**Problem**

Wrapping the last path of a `Route` in a `Router` currently causes a compilation error. I think the macro is currently failing on a missing trailing variant.

**Steps To Reproduce**

```rs
enum Route {
    #[layout(Layout)]
        #[route("/")]
        Home {},
    #[end_layout]
}
```

```
error: expected identifier, found `}`
   |
6  | enum Route {
   |                 ----- while parsing this enum
...
13 | }
   | ^ expected identifier
   |
   = help: enum variants can be `Variant`, `Variant = <integer>`, `Variant(Type, ..., TypeN)` or `Variant { fields: Types }`
```

**Expected behavior**
A quick fix may be to handle where there is no `syn::Variant`.

**Environment:**
 - Dioxus version:  `main`
 - Rust version:    `nightly`
 - App platform:    `all`

**Questionnaire**

- I would like to fix and I have a solution

**Comment by matthunz** [comment]
Anyone else who encounters this, the solution is to remove the trailing `#[end_layout]`

**Comment by beanbean97** [comment]
> Anyone else who encounters this, the solution is to remove the trailing `#[end_layout]`

thank you, you solve my problem
