### ISSUE TITLE
Information leak in the wasm executable

### ISSUE THREAD

**Issue by ThomasCartier** [DioxusLabs/dioxus#2732]
Hi,
I was reading the wasm file generated by dioxus and there is something I don't really like:
it leaks the dev file structure + other info. For example, a line in the file:
`This error is likely caused by trying to use a hook inside a hook which violates the rules of hooks. /home/myuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-core-0.5.1/src/global_context.rs`

It also happens with crates of use in the project!

So people know the structure + crates + versioning I am using.

Is there any way to circumvent this ?
The file is full of system info leaks.
That's an issue. It gives useful info to hackers, and a hint on the update cycles.

Any idea? did I forget a flag ?

**Comment by ealmloff** [comment]
You can [strip debug info](https://doc.rust-lang.org/rustc/codegen-options/index.html#strip) in your build profile to remove caller information

**Comment by ThomasCartier** [comment]
@ealmloff :

I already have this in my cargo.toml:
```
[profile.release]
opt-level = 3
debug = false
lto = true
panic = "abort"
strip = true
incremental = false
```

and
`dx build --features web --release && cargo build --features server --release`

I use the nightly compiler and latest Dioxus cli.

This is why I don't get the output

**Comment by jkelleyrtp** [comment]
Did some playing around - 

This is a general issue with Rust. For more privacy you could consider setting `remap-prefix` in your `.cargo/config` or simply building in CI where the debug strings are anonymized.

If you wanted to take it a step further, you could also set build-std to `panic_immediate_abort` which I just guaranteed will eliminate private strings/paths at the expense of causing an immediate abort on panics (which you probably don't actually want).

```
cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
```

https://dioxuslabs.com/learn/0.5/cookbook/optimizing#unstable

**Comment by ThomasCartier** [comment]
@jkelleyrtp thanks a lot and yes, that would be a nice addendum.

**Comment by ThomasCartier** [comment]
@jkelleyrtp @ealmloff 
So I added
cargo-features = ["trim-paths"] on top of my cargo.toml file and added `trim-paths = true` below my cargo `[profile.release]`
Many info are now gone. Great. But my wasm file has a copy of my cargo.toml, dioxus.toml and other info.
The string to search for is starting with "`{"crate_dir":`".

Navigating the cli source code, I don't think I saw any concatenation of these files, but I may be wrong.

Do you confirm that it's not `dx` concatenating those files and putting it in the final wasm file ?
It doesn't occur for the server binary.
Thanks

**Comment by ealmloff** [comment]
> @jkelleyrtp @ealmloff So I added cargo-features = ["trim-paths"] on top of my cargo.toml file and added `trim-paths = true` below my cargo `[profile.release]` Many info are now gone. Great. But my wasm file has a copy of my cargo.toml, dioxus.toml and other info. The string to search for is starting with "`{"crate_dir":`".
> 
> Navigating the cli source code, I don't think I saw any concatenation of these files, but I may be wrong.
> 
> Do you confirm that it's not `dx` concatenating those files and putting it in the final wasm file ? It doesn't occur for the server binary. Thanks

Dioxus embeds the dioxus.toml into the binary to make some functionality like the base path of the router work. `0.5` also embeds the `cargo.toml`, but that has been removed in the main branch of dioxus

**Comment by ThomasCartier** [comment]
@ealmloff that's great news! Now this issue can be considered solved! Thanks a lot
