### ISSUE TITLE
Can you provide a complete example of uploading images for dioxus0.5?

### ISSUE THREAD

**Issue by ys2rice2yangsong** [DioxusLabs/dioxus#2758]
**Problem**

**Steps To Reproduce**

Can you provide a complete example of uploading images for dioxus0.5?

**Comment by ealmloff** [comment]
There is a file upload example [here](https://github.com/DioxusLabs/dioxus/blob/main/examples/file_upload.rs). To accept images, you just need to modify the accept [field](https://github.com/DioxusLabs/dioxus/blob/main/examples/file_upload.rs#L66) and read the file as bytes instead of a string
