### ISSUE TITLE
login_form example does not work on Debian bullseye

### ISSUE THREAD

**Issue by maurerdietmar** [DioxusLabs/dioxus#276]
When I run the input form example with:

cargo run --release --example login_form

After pressing "Login" button I get:

>thread '<unnamed>' panicked at 'no entry found for key', examples/login_form.rs:17:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Pressing Login again results in a crash:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', packages/desktop/src/lib.rs:138:87
> Segmentation fault (core dumped)

**Comment by jkelleyrtp** [comment]
Looks like the "name" of the inputs got lost in the process. This should be fixed now.

**Comment by maurerdietmar** [comment]
works, thanks!!
