### ISSUE TITLE
prepare_html panic, in main branch

### ISSUE THREAD

**Issue by ThomasCartier** [DioxusLabs/dioxus#2762]
Hi,

There is a panic occurring when compiling with the main branch of the cli (0.6.0 alpha1)

```
thread 'tokio-runtime-worker' panicked at packages/cli/src/builder/prepare_html.rs:164:83:
called `Result::unwrap()` on an `Err` value: StripPrefixError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I have a mix of files and symlinks in my asset folder.

It was valid in v0.5.6.

Also `dx clean` now has a radical behavior. I open another bug report right now on this matter.

**Comment by jkelleyrtp** [comment]
Fixed in #2779 since we don't do as much work prepping html
