### ISSUE TITLE
dx clean, now cleans too much.

### ISSUE THREAD

**Issue by ThomasCartier** [DioxusLabs/dioxus#2763]
Hi,

dx 0.6.0 alpha1 from git.

executing a `dx clean` also deletes the artifacts folder.
On my system, it happens to be a shared artifacts folder (out of tree), so it deletes everything there, even the artifacts of my other projects.

Maybe a test to know if we are located  in the source folder could enable to select if we want to delete the parent folder as well or not.

Thanks!

**Comment by jkelleyrtp** [comment]
We switched to using `cargo clean` which should be better about this
