### ISSUE TITLE
`use_reactive` inside `use_future` doesn't update

### ISSUE THREAD

**Issue by rambip** [DioxusLabs/dioxus#2795]
**Problem**

When using `use_signal(use_reactive(...))`, in some cases a warning is raised (`Write on signal happened at ... while a component was running`). This warning indicates that there is a loop in the dependencies of signal, but it doesn't seem to be any.

In addition, the component is not updated after this warning.

**Steps To Reproduce**

- create a new empty dioxus project targeting web
- use this code:

```rust
#![allow(non_snake_case)]

use dioxus::prelude::*;
use tracing::{Level, info};

fn main() {
    dioxus_logger::init(Level::INFO).expect("failed to init logger");
    launch(App);
}

async fn request(x: String) -> String {
    x
}

#[component]
fn Test(arg: String) -> Element {
    let mut view = use_signal(|| rsx!());

    use_future(use_reactive((&arg,), move |(arg,)| async move {
        let out = request(arg).await;
        *view.write() = rsx!{
            "output of request is {out}"
        }
    }));

    rsx!{
        {view}
    }
}

#[component]
fn App() -> Element {
    let mut arg: Signal<String> = use_signal(|| "empty".to_string());

    rsx! {
        button {
            onclick: move |_| *arg.write() = "foo".to_string(),
            "foo"
        }
        hr {}
        Test {
            arg: arg(),
        }
    }
}
```
- run `dx serve`, open your browser and he console window
- click on the button

You shoud see the following warnings:
```
WARN /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-signals-0.5.7/src/signal.rs:570 Write on signal at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-hooks-0.5.6/src/use_reactive.rs:96:20 happened while a component was running. Writing to signals during a render can cause infinite rerenders when you read the same signal in the component. Consider writing to the signal in an effect, future, or event handler if possible. [dioxus-test.js:449:21](http://localhost:8081/assets/dioxus/dioxus-test.js)
WARN /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-signals-0.5.7/src/signal.rs:583 Write on signal at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-hooks-0.5.6/src/use_reactive.rs:96:20 finished in ReactiveContext(for scope: ScopeId(1, "Test")) which is also subscribed to the signal. This will likely cause an infinite loop. When the write finishes, ReactiveContext(for scope: ScopeId(1, "Test")) will rerun which may cause the write to be rerun again.
HINT:
This issue is caused by reading and writing to the same signal in a reactive scope. Components, effects, memos, and resources each have their own a reactive scopes. Reactive scopes rerun when any signal you read inside of them are changed. If you read and write to the same signal in the same scope, the write will cause the scope to rerun and trigger the write again. This can cause an infinite loop.

You can fix the issue by either:

...
```

And the component renders "output of request is empty"

**Expected behavior**

This warning message should not appear, and the component should output "output of request is foo"

**Environment:**
 - Dioxus version:  0.5.6 (I did try with a more recent version with the same error)
 - App platform:    `web`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
That warning was fixed in https://github.com/DioxusLabs/dioxus/pull/2649. The main branch of dioxus no longer logs warnings while running use_reactive

**Comment by rambip** [comment]
I updated my post. The real problem is that the component it stuck at "output of request is empty"

**Comment by rambip** [comment]
I just tested with the latest version of dioxus from git.
I don't get the warning, but the component is stuck at "output of request is empty"

**Comment by ealmloff** [comment]
`use_future` is not reactive. It just runs once when the component is created. You can use the `use_resource` hook if you need your future to rerun:
```rust
#[component]
fn Test(arg: String) -> Element {
    let mut view = use_signal(|| rsx!());

    _ = use_resource(use_reactive((&arg,), move |(arg,)| async move {
        let out = request(arg).await;
        *view.write() = rsx! {
            "output of request is {out}"
        }
    }));

    rsx! {
        {view}
    }
}
```

You could also make your props reactive instead of using use_reactive. Then they are reactive everywhere in your component:
```rust
#[component]
fn Test(arg: ReadOnlySignal<String>) -> Element {
    let mut view = use_signal(|| rsx!());

    _ = use_resource(move || async move {
        let out = request(arg()).await;
        *view.write() = rsx! {
            "output of request is {out}"
        }
    });

    rsx! {
        {view}
    }
}
```

**Comment by rambip** [comment]
Ok.
Hopefully, I will never encounter the same problem again thank's to the `.suspend()` method of `Resource`s.

But in any case, that would be nice to be clearer in the documentation by saying that 

"""`use_future` only spawns your future once when your component is created, and will not react to any signal change. You can use `use_resource` if you want to react to changes"""
