### ISSUE TITLE
asset loading problem on linux

### ISSUE THREAD

**Issue by maurerdietmar** [DioxusLabs/dioxus#285]
Even the provided example does not work on Linux.

> cargo run --release --example custom_assets

Logo image is not loaded!

This worked a few days before, so it must be a recent commit.

**Comment by mrxiaozhuox** [comment]
I think this demo is using a wrong `include` code ? @jkelleyrtp

**Comment by jkelleyrtp** [comment]
We were filtering assets if they didn't canonically appear in the right path. This should be fixed now. Can you try updating master?

**Comment by maurerdietmar** [comment]
Yes, works again. Thanks!

**Comment by jkelleyrtp** [comment]
Awesome!
