### ISSUE TITLE
CLI: Color-code logs and get rid of tabs

### ISSUE THREAD

**Issue by FragrantArmpit** [DioxusLabs/dioxus#2857]
## Feature Request

Currently, for fullstack projects, we run two `BuildRequest`s simultaneously for two targets `web` and `server` and there is no way to distinguish to which target a particular log pertains to.

This could be resolved by color-coding logs the same way `docker compose` does.

![358838530-2b30d780-5756-4202-bcb5-3c83612bc3b2](https://github.com/user-attachments/assets/d8a3489b-b17b-49bb-b0de-647f0db7813c)

We could have all logs in the same tab (switching between tabs is bad UX) and a different color for each "stream" of logs. For example logs that come from the CLI itself, logs that come from each `BuildRequest` and `cargo` logs (that are currently in the `build` tab).

## Implement Suggestion

This could be implemented by having a special `tracing` span to decide what color the logs should have.

**Comment by Andrew15-5** [comment]
I don't think that tabs should be removed, but in it's current state they do feel useless or excessive. They could be very useful and understandable, but now they both contain mostly the same logs (from what I've seen).

Color coding is interesting, but I should mention that color blindness is a thing and that can make it useless or bad UX. So maybe a text-based solution is a better way.

**Comment by FragrantArmpit** [comment]
> I don't think that tabs should be removed, but in it's current state they do feel useless or excessive. They could be very useful and understandable, but now they both contain mostly the same logs (from what I've seen).

I believe the only difference is that the `build` tab also shows the `cargo` output. It indeed does feel excessive to have a separate tab for that (I would prefer to see the `cargo` output by default) and I don't think we have anything that would produce so much logs that it would require a separate tab (at least right now).

> Color coding is interesting, but I should mention that color blindness is a thing and that can make it useless or bad UX. So maybe a text-based solution is a better way.

An easy text-based solution would be to just add some label (i.e. `BuildRequest` target platform) as a `tracing` span field but aesthetic-wise this probably wouldn't look good. `docker compose` actually not only does color coding but also shows a label at the very left (see my screenshot above). We could do the same.
