### ISSUE TITLE
Overtly verbose "build progress" ouput when running `dx build`

### ISSUE THREAD

**Issue by ochrons** [DioxusLabs/dioxus#2883]
**Problem**

When running `dx build` on a fullstack project, the CLI outputs a ton of "build progress" lines flooding the terminal

```
fullstack build: Build progress 78%
fullstack build: Build progress 78%
fullstack build: Build progress 79%
fullstack build: Build progress 79%
fullstack build: Build progress 79%
fullstack build: Build progress 80%
fullstack build: Build progress 80%
fullstack build: Build progress 91%
fullstack build: Build progress 80%
fullstack build: Build progress 80%
fullstack build: Build progress 80%
fullstack build: Build progress 81%
fullstack build: Build progress 91%
fullstack build: Build progress 81%
fullstack build: Build progress 81%
fullstack build: Build progress 81%
fullstack build: Build progress 81%
fullstack build: Build progress 82%
fullstack build: Build progress 82%
fullstack build: Build progress 82%
fullstack build: Build progress 82%
fullstack build: Build progress 83%
fullstack build: Build progress 83%
```
It also seems to report the two concurrent builds in an interleaved fashion.

**Steps To Reproduce**

- run `dx build` (version 0.6.0-alpha.2)

**Expected behavior**

No verbose output.

**Screenshots**

**Environment:**
 - Dioxus version:  0.6.0-alpha.2
 - Rust version:    1.80.1
 - OS info:         Win11 WSL Ubuntu 22.04
 - App platform:    web, fullstack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by srid** [comment]
This happens when building a static-site (#2891) as well.

**Comment by jkelleyrtp** [comment]
We cleaned this up!
