### ISSUE TITLE
The use of dioxus_desktop 0.5.0 bug

### ISSUE THREAD

**Issue by 1195655796** [DioxusLabs/dioxus#2898]
**Problem**

The use of dioxus_desktop bug

**Steps To Reproduce**

- Try to use dioxus_desktop 0.5.0 to replace dioxus 0.5.0 in making a desktop application but found multiple errors including webviews
- If use dioxus,everything is ok

**Expected behavior**

Use dioxus desktop to create desktop application successfully
**Screenshots**

![3c827486776801e5cbf25645719d24a](https://github.com/user-attachments/assets/17ca9538-5fa5-4ea9-a572-653f59efb844)
![e0177ec3964460bf48319f856e4ce97](https://github.com/user-attachments/assets/ede5c49a-88a5-4552-91a7-754db9a3e36a)
![98b144f57284ea186ab104dadce5035](https://github.com/user-attachments/assets/898aad6f-435f-408d-8cc5-bb57d2357d91)
![f00a0ee3188cd73c1590430cb94049b](https://github.com/user-attachments/assets/acfd29b2-f894-430e-8ca8-19e0076e7a79)

**Environment:**
 - Dioxus version:  0.5.
 - Rust version:    rustc 1.82.0-nightly (a32d4a0e8 2024-08-21)
 - OS info:         Windows
 - App platform:   desktop

**Questionnaire**

- I'm interested in fixing this myself but don't know where to start

**Comment by Be3y4uu-K0T** [comment]
In the first error:
```
compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
```
Are you sure you compile for desktop? Can you please show your `Cargo.toml` file?

**Comment by 1195655796** [comment]
Here is the Cargo.toml file
![486a575b598337f956c2bc29e2b7ae3](https://github.com/user-attachments/assets/b8d0aea8-e345-4eb1-8d7b-d51ff08cbdfb)
![81be44e698e11a9d73a55f0bd9cf573](https://github.com/user-attachments/assets/42c0c3ef-dc91-4a1d-9f4a-91c76b7d6731)

**Comment by Be3y4uu-K0T** [comment]
If you want to compile for desktop, then you don't need to crate `dioxus_desktop` separately. You need to add the `desktop` flag to features in crate `dioxus`. In your case, there may be an error because you are using the `web`.
And maybe you don't need `tokio` in `dev-dependencies` or move to `dependencies`.

try this:
```toml
# ...

[dependencies]
dioxus = { version = "0.6", features = ["desktop", "router"]}

# ...
```

P.S.: Please copy the text of your error instead of adding screenshots.

**Comment by 1195655796** [comment]
I will test the solution today, after solving the problem I will close the issue，thanks!

**Comment by 1195655796** [comment]
Dear [Be3y4uu-K0T] & matthunz ：
Problem solved！Thanks！
