### ISSUE TITLE
Template does not work

### ISSUE THREAD

**Issue by hiro1234omochi** [DioxusLabs/dioxus#2906]
**Problem**

if I execute dixous template, it does not work, and looks like this image.

**Steps To Reproduce**

- cargo install dioxus-cli
- dx new
- dx serve
- it happens with 
- ``` WARN dioxus_desktop::protocol: Assets built with manganis cannot be preloaded (failed to read "C:\\Users\\hirom\\RustroverProjects\\tetris\\test\\__assets_head.html"). This warning may occur when you build a desktop application without the dioxus CLI. If you do not use manganis, you can ignore this warning: 指定されたファイルが見つかりません。 (os error 2).```

**Expected behavior**

I can execute the template successfully.

**Screenshots**

![image](https://github.com/user-attachments/assets/b270c025-a9d5-4725-9669-650e1a396372)

**Environment:**
 - Dioxus version:  v0.5.6 
 - Rust version:    v1.80.1
 - OS info:    Windows 11    
 - App platform:   desktop 

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by hiro1234omochi** [comment]
I think the reason is because asset_dir and out_dir are not loaded.

**Comment by ealmloff** [comment]
Can you provide more information about the options you choose when running `dx new`. I cannot reproduce this issue with these settings: `desktop, no router, vanilla or tailwind css`

**Comment by hiro1234omochi** [comment]
> Can you provide more information about the options you choose when running `dx new`. I cannot reproduce this issue with these settings: `desktop, no router, vanilla or tailwind css`

I chose "desktop, no router, vanila" and this happend.
I tried to do it on windows sandbox, but this happend too.
Is your dioxus version the same as mine?

I tried to install dioxus cli of 0.6.0-alpha2, but Compile errors happend. Therefore I used 0.5.6 version.

**Comment by hiro1234omochi** [comment]
> Can you provide more information about the options you choose when running `dx new`. I cannot reproduce this issue with these settings: `desktop, no router, vanilla or tailwind css`

Or you might be using windows 10

**Comment by u7f8au7fbd** [comment]
I am currently in the same situation.
Trying to find solutions and causes.

Dioxus:0.5.6
OS:Windows11
Rust:1.80.1
Platform:desktop

**Comment by u7f8au7fbd** [comment]
```rs
 link { rel: "stylesheet", href: "./assets/main.css" }
 img { src: "./assets/header.svg", id: "header" }
 ```
 If you add "./assets/" it will load correctly.

**Comment by VillSnow** [comment]
me too

- dioxus 0.5.7
- `rustc 1.79.0
- sub-template: Desctop
- CSS: Vanilla
- router: false
- Windows 11

**Comment by crabdancing** [comment]
Yeah, I get the same issue on NixOS. :/

@hiro1234omochi shouldn't this be reopened? If `dx new` produces broken demo code on some targets, it seems like the sort of thing that ought to be addressed.
