### ISSUE TITLE
Why do you use tokio::time::sleep in docs if it is not supported by wasm?

### ISSUE THREAD

**Issue by gekh** [DioxusLabs/dioxus#2908]
Just some examples, everywhere is `tokio::time::sleep`
https://dioxuslabs.com/learn/0.5/reference/use_coroutine
https://dioxuslabs.com/blog/release-050
https://github.com/DioxusLabs/dioxus/blob/9d099a7f3fa78ee9d87aae06ad1aae03fded6c19/examples/eval.rs#L16

I ended up by using `wasmtimer::tokio::*`, but it took me a lot of time and nerves to find it. 
Why do you have tokio in docs and examples? Why you do not have your own sleep implementation like Leptos?

**Comment by mchant** [comment]
Thanks!! Just ran into this issue myself.

**Comment by Heeten** [comment]
I ran into this issue as well, it's used in the `use_future` doc at https://docs.rs/dioxus/latest/dioxus/prelude/fn.use_future.html
