### ISSUE TITLE
Copied the todomvc example code but not worked

### ISSUE THREAD

**Issue by 1195655796** [DioxusLabs/dioxus#2917]
**Problem**

I Copied the todomvc example code to a single cargo file but not worked

**Steps To Reproduce**

- 
- 
- 

**Expected behavior**
The todomvc example code could successfully work

**Screenshots**
error[E0599]: no method named `prevent_default` found for struct `dioxus::prelude::Event<MouseData>` in the current scope
   --> src/todomvc.rs:180:40
    |
180 |                     onclick: |evt| evt.prevent_default(),
    |                                        ^^^^^^^^^^^^^^^ method not found in `Event<MouseData>`

error[E0599]: no method named `prevent_default` found for struct `dioxus::prelude::Event<MouseData>` in the current scope
   --> src/todomvc.rs:186:29
    |
186 |                         evt.prevent_default();
    |                             ^^^^^^^^^^^^^^^ method not found in `Event<MouseData>`     

error[E0599]: no method named `prevent_default` found for struct `dioxus::prelude::Event<MouseData>` in the current scope
   --> src/todomvc.rs:245:37
    |
245 | ...                   evt.prevent_default();
    |                           ^^^^^^^^^^^^^^^ method not found in `Event<MouseData>`       

For more information about this error, try `rustc --explain E0599`.
error: could not compile `todomvc` (bin "todomvc") due to 3 previous errors
PS F:\todomvc\todomvc> 

**Environment:**
 - Dioxus version:  0.6.0-alpha.0
 - Rust version:    rustc 1.80.1 (3f5fd8dd4 2024-08-06)
 - OS info:         
 - App platform:   desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
The examples are up to date with the git version of dioxus (which is very similar to alpha.2). If you need examples that compile with the alpha.0 release, you can look at the state of the repo when that release was published [here](https://github.com/DioxusLabs/dioxus/tree/0cbcef735f144786f77ac06d97e74690a72f69b6)
