### ISSUE TITLE
dx serve a desktop project panics on latest git version

### ISSUE THREAD

**Issue by TheAlexDev23** [DioxusLabs/dioxus#2927]
**Problem**

Running `dx serve --platform desktop` on a fresh project crashes the program with the following message: 
```
2024-09-04T18:50:58.389478Z  INFO dx::builder::cargo: 🚅 Running build [Desktop] command...
thread 'tokio-runtime-worker' panicked at packages/cli/src/assets.rs:24:47:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Steps To Reproduce**

- Installing latest version of dioxus-cli. `cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli`
- Create a new desktop project `dx new`
- Change the dioxus dependency version to the latest git version in Cargo.toml:
```toml
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "main", features = [
    "desktop",
    "router",
] }
```
- Serve the project `dx serve --platform desktop`

**Environment:**
 - Dioxus version:  master
 - Rust version:  rustc 1.80.0 (051478957 2024-07-21)
 - OS info: Linux
 - App platform: desktop

**Questionnaire**
Unless the fix is very trivial, I could look into it myself if I find the time, unfortunately I'm unfamiliar with the project internals, so a little guidance will be appreciated in that case.

**Comment by jkelleyrtp** [comment]
Should be fixed by #2779
