### ISSUE TITLE
Destructuring tuples panics #[component] macro

### ISSUE THREAD

**Issue by wackazong** [DioxusLabs/dioxus#2958]
**Problem**

This does not compile:

```rust
#[component]
pub fn MyComponent((a,b): (usize, usize)) -> Element {
    rsx! { div {} }
}
```

**Steps To Reproduce**

see code above

**Expected behavior**

It is normal Rust and should compile

**Environment:**
 - Dioxus version: 0.5
 - Rust version: nightly
 - OS info: Mac
 - App platform: web

**Comment by jkelleyrtp** [comment]
There is no way to name the tuple parameter, so maybe the error could be better, but we *do* support destructuring props in the macro. They just need to be structs.
```
#[derive(PartialEq, Clone)]
struct BlahStruct {
    a: String,
    b: String,
}

#[component]
fn Child(BlahStruct { a, b }: BlahStruct) -> Element {
    rsx! {
        div {
            "{a}"
            div { "{b}" }
        }
    }
}
```

**Comment by wackazong** [comment]
Ok, thanks for the explanation.
