### ISSUE TITLE
Implement module namespacing in `routable` derive macro

### ISSUE THREAD

**Issue by mrgzi** [DioxusLabs/dioxus#2968]
The `Routable` derive macro currently does not support initializing components from modules using the Rust double colon (::) syntax.

For example, the following code produces a syntax error:

```rs
#[derive(Clone, Routable, Debug, PartialEq)]
pub enum Route {
    #[route("/")]
    Login::View, // Error: Expected comma
    #[route("/dashboard")]
    Dashboard,
    #[route("/:..route")]
    PageNotFound { route: Vec<String> },
}
```

**Expected Behavior**

`Login::View` should be interpreted correctly by the `Routable` derive macro.

**Comment by ealmloff** [comment]
You can render a component in a module with the `#[route("/path", Component)]` syntax
