### ISSUE TITLE
Blank screen after dx serve

### ISSUE THREAD

**Issue by JohnZolton** [DioxusLabs/dioxus#2987]
**Problem**

```dx serve --hot-reload --platform desktop```

gives a blank screen (normal dx serve gives same results)

**Steps To Reproduce**

- dx new
- * desktop, * tailwind (vanilla has same issue), *Dioxus router: true

**Expected behavior**

run the demo

**Terminal**

```
Dioxus @ v0.5.7 [09:12:36]

    > Hot Reload Mode: RSX
    > Watching: [ src, assets, Cargo.toml, Dioxus.toml ]
    > Custom index.html: None
    > Serve index.html on 404: True

    > Build Features: [  ]
    > Build Profile: Debug
    > Build took: 65396 millis

2024-09-21T13:12:36.128979Z  INFO test2: starting app
Connected to hot reloading 🚀

** (test2:63396): WARNING **: 09:12:36.311: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
2024-09-21T13:12:36.604329Z  WARN dioxus_desktop::protocol: Assets built with manganis cannot be preloaded (failed to read "/home/john/Documents/Programming/rust/deskchat/test2/__assets_head.html"). This warning may occur when you build a desktop application without the dioxus CLI. If you do not use manganis, you can ignore this warning: No such file or directory (os error 2).
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

```
**Environment:**
 - Dioxus version:  v0.5.7
 - Rust version:    rustc 1.79.0 (129f3b996 2024-06-10)
 - OS info: Ubuntu 24.04.1 LTS
 - App platform: desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by JohnZolton** [comment]
solved by:

3. AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

Requires to have ```WEBKIT_DISABLE_DMABUF_RENDERER=1``` in the environment, it seems to only happen on X11

https://github.com/tauri-apps/tauri/issues/9394

**Comment by crabdancing** [comment]
I'd just like the report that this happens on Wayland too, apparently. The window itself isn't going through Xwayland, either. So, if anyone's getting this bug on Wayland, it's worth trying the workaround out. :)
