### ISSUE TITLE
if conditional in component attribute evaluating one leg as &str and other as String, when interpolation in only one leg

### ISSUE THREAD

**Issue by rogusdev** [DioxusLabs/dioxus#2997]
**Problem**

```rust
src: if lang_code() == "en" { "image.png" } else { "{lang_code()}/image.png" }
```

Errors with:
```
error[E0308]: `if` and `else` have incompatible types
...
 expected `&str`, found `String`
```

But this works:
```rust
src: if lang_code() == "en" { "image.png".to_string() } else { "{lang_code()}/image.png" }
```

However @ealmloff agrees that this should be handled automatically by the rsx:
https://discord.com/channels/899851952891002890/1288251857457647698/1288288455960301690

**Environment:**
 - Dioxus version:  main
 - App platform:    web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by chungwong** [comment]
Does it mean the types in the if branches can now be different? Isn't this not very Rusty?
