### ISSUE TITLE
dioxus0.2.0 error[E0599]: no method named `location` found for struct `Window` in the current scope

### ISSUE THREAD

**Issue by hisphone** [DioxusLabs/dioxus#301]
**error[E0599]: no method named `location` found for struct `Window` in the current scope**

error[E0599]: no method named `location` found for struct `Window` in the current scope
   --> /Users/mac/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/dioxus-router-0.2.0/src/service.rs:336:34
    |
336 |             Box::new(self.window.location())
    |                                  ^^^^^^^^ method not found in `Window`

error[E0599]: no method named `location` found for struct `Window` in the current scope
   --> /Users/mac/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/dioxus-router-0.2.0/src/service.rs:341:66
    |
341 |                 url: url::Url::parse(&web_sys::window().unwrap().location().href().unwrap())
    |                                                                  ^^^^^^^^ method not found in `Window`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `dioxus-router` due to 2 previous errors
[ERROR] Build failed!
[ERROR] serve error: Building project failed

**Environment:**
 - Dioxus version: [0.2.0]
 - Rust version: [1.59]
 - OS info: [MacOS]
 - App platform: [`web`]

**Comment by jkelleyrtp** [comment]
Thanks for the report - can you update to Dioxus 0.2.2? Looks like a feature flag slipped through (should be fixed).
