### ISSUE TITLE
expected `Error`, found `RouteParseError<RouteMatchError> when I use reqwest

### ISSUE THREAD

**Issue by davnav** [DioxusLabs/dioxus#3016]
Problem

I was trying to use Route with reqwest in the app component. But keep getting below compilation error.
Trying to solve error handling in the route. But I couldn't and keep getting below error.

    |                 expected `Error`, found `RouteParseError<RouteMatchError>`
    |                 arguments to this enum variant are incorrect

**Steps To Reproduce**

main.rs code attached here .
[main.txt](https://github.com/user-attachments/files/17179806/main.txt)

Expected behavior

I would like know how we can resolve this compilation error.

**Screenshots**

![image](https://github.com/user-attachments/assets/e168c990-d667-4846-b699-d369ae5f45c8)

**Environment:**
 - Dioxus version:  version = "0.5", features = ["web", "router"] 
 - Rust version:    rustc 1.81.0 (eeb90cda1 2024-09-04)
 - OS info:         Windows
 - App platform:   Web

**Comment by davnav** [comment]
The issue resolved when I commented  below line in the import line in main.rs. Seems like reqwest imported its own error which caused the error.
// use reqwest::*;

**Comment by ealmloff** [comment]
This is a bug in dioxus. The macro should not rely on an unscoped error import
