### ISSUE TITLE
Script and head::Link settings for development

### ISSUE THREAD

**Issue by DioxusGrow** [DioxusLabs/dioxus#3024]
If the following sections are removed from the Dioxus.toml file in the next release

```
# include `assets` in web platform
[web.resource]
style = [“/tailwind.css”]
script = []
[web.resource.dev]
script = []
```
add the ability to add resources for development that will not be taken into release during compilation
For example
Script::dev
head::Link::dev

**Comment by ealmloff** [comment]
This should actually be more flexible with the `head` elements! You can use any config statement in rsx to only include assets if you are targeting a specific platform or feature:
```rust
rsx! {
    if cfg!(feature = "dev") {
        head::Link {...}
    }
    if cfg!(debug_assertions) {
        head::Link {...}
    }
    if cfg!(target_arch = "wasm32") {
        head::Link {...}
    }
}
```
