### ISSUE TITLE
head::Style does not add styles inside the head tag

### ISSUE THREAD

**Issue by DioxusGrow** [DioxusLabs/dioxus#3029]
head::Style does not add styles inside the head tag during `dx serve`

```rust
/// # Example
/// rust, no_run
/// # use dioxus::prelude::*;
/// fn RedBackground() -> Element {
///     rsx! {
///         // You can use the style component to render a style tag into the head of the page
///         // This style tag will set the background color of the page to red
///         Style {
///             r#"
///                 body {{
///                     background-color: red;
///                 }}
///             "#
///         }
///     }
/// }
/// 
```
![image](https://github.com/user-attachments/assets/6f5ae621-c88e-46c3-9be3-d93a5c67df7f)

**Environment:**
Dioxus version: dioxus 0.6.0-alpha.2 (d0c9b67) from github 03/10/24
Rust version: rustc 1.81.0 (eeb90cda1 2024-09-04)
OS info: Win11
App platform: web

**Comment by TN19Nworking** [comment]
same problem for me, a posted an example in discord https://discord.com/channels/899851952891002890/1291354543602532472
