### ISSUE TITLE
ondoubeclick/onblur events doesn’t work

### ISSUE THREAD

**Issue by hanpei** [DioxusLabs/dioxus#304]
**Problem**

some event listener did not work on web platform,
e.g "ondoubleclick" / "onblur" / "onfocusout",
but "onclick" / "oninput" works well.

```
 label {
            ondoubleclick: move |e| {
                info!("double click");
                editing.set(*id);
            },
            "{title}",
        }

input {
         onblur: move |_| {
              editing.set(0);
              info!("onblur")
          },
}
```

**Environment:**
 - Dioxus = { version="0.2.3", features=["web"] }
 - Rust version: [e.g. 1.59.0, `stable `]
 - OS info: [e.g. MacOS]
 - App platform: [e.g. `web`]

**Comment by mpfaff** [comment]
> You can use `onfocusin` and `onfocusout` instead to get the same effect.

`onfocusout` panics for me:

```
panicked at 'unsupported event type', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-web-0.2.1/src/dom.rs:378:13
```

**Comment by rMazeiks** [comment]
@mpfaff, I've made https://github.com/DioxusLabs/dioxus/pull/422 to address the issue with `onfocusin` and `onfocusout` on the web. Until it gets merged (maintainer on vacation), you can use my fork if you trust me :smile: :

```
[patch.crates-io]
dioxus = { git = "https://github.com/rMazeiks/dioxus.git", branch="fix-web-missing-event-types" }
```
