### ISSUE TITLE
Improve cargo workspace support - hot reloading not working across workspaces

### ISSUE THREAD

**Issue by enricoschaaf** [DioxusLabs/dioxus#3042]
**Problem**

When setting up a cargo workspace and changing a rsx macro in another workspace dx serve performs a normal hot reload. The watching of the other workspaces is achieved with [..]. If this is not desired I would suggest that maybe better workspace support can be added another way. The sub_package field in config seems to do nothing.

**Steps To Reproduce**

https://github.com/enricoschaaf/dioxus-cargo-workspaces

- checkout repo
- run `dx serve --package development --nightly --skip-assets --hot-reload=true`
- change component in web

**Expected behavior**

the macro hot reloads

**Screenshots**

**Environment:**
 - Dioxus version:  0.6.0-alpha.2
 - Rust version:   1.83.0-nightly
 - OS info:        MacOS
 - App platform:    web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
Just added this in #2779 - should be generally better. We don't traverse every "step-sibling" dependencies (ie a dep of a dep) but we do now traverse into your direct dependencies.

**Comment by enricoschaaf** [comment]
Hi @jkelleyrtp Thanks for tackling this. I tried again with 0.6.0-alpha.3 both for the application and the cli but I still get a full reload when doing

[web.watcher]
watch_path = [".."]

and no reload when omitting this. the dependency is defined like this web = { path = "../web" }.  Could you explain me more about how the direct dependency traversing works or point me somewhere?

Also happy to update the repo again to make it reproducible.
