### ISSUE TITLE
hot reload do not work with style.css

### ISSUE THREAD

**Issue by LuckyTurtleDev** [DioxusLabs/dioxus#3045]
**Problem**

If I change the `style.css`, the project do not hot reload. Instead  the whole project will be recompiled.

**Steps To Reproduce**

-
```bash
git clone https://github.com/LuckyTurtleDev/mstickerpicker.git
git checkout e7ac422a9d86bdea9cae7ee4ee62347fe621f232
dx serve --hot-reload
```
-  open localhost:8080
- and change color inside `assets/style.css`  with a text editor and save

source code backup: [mstickerpicker-dioxus.zip](https://github.com/user-attachments/files/17311686/mstickerpicker-dioxus.zip)
**Expected behavior**

hot reload changes and not recompile

**Screenshots**

**Environment:**
 - Dioxus version:   v0.5.6
 - Rust version:    rustc 1.81.0 (eeb90cda1 2024-09-04)
 - OS info:         arch linux
 - App platform:    full-stack

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
should be fixed in #2779
