### ISSUE TITLE
Needs significantly better instructions for compiling a desktop application

### ISSUE THREAD

**Issue by cybergazer** [DioxusLabs/dioxus#3049]
Dioxus is impossible to compile in my case. I've tried cargo build to compile Dioxus for desktop and it runs into a lot of dependency errors. Some of them I was able to figure out like libgtk3 but there were many others that I can't figure out. There is nothing in the official docs explaining what specific libraries you need so you just run into errors, this leaves a bad first impression for Dioxus especially for people coming from other frameworks. 

Another thing it was missing was soup3-sys which is a required dependency to compile it, it had to be installed manually with cargo add

**Comment by jkelleyrtp** [comment]
In our [docs](https://dioxuslabs.com/learn/0.5/getting_started#platform-specific-dependencies) we link to Tauri's system dependencies guide
https://tauri.app/start/prerequisites/

which lists the various packages you need for developing on various platforms. Mac/Windows require nothing special but your linux distro might require something specific.
