### ISSUE TITLE
onsubmit is not called when form is child of router

### ISSUE THREAD

**Issue by stevenliebregt** [DioxusLabs/dioxus#305]
**Problem**

When using a router and a separate function (Component?) with a form in it, the `onsubmit` is never called.

**Steps To Reproduce**

- Have the below code

```rust
use dioxus::prelude::*;

fn main() {
    dioxus::desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx! (
        Router {
            ul {
                Link { to: "/", li { "Home" } },
            }
            Route { to: "/" Home {} },
        }
    ))
}

fn Home(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            h1 { "Form" }
            form {
                onsubmit: move |ev| println!("Submitted {:?}", ev.values),
                oninput: move |ev| println!("Input {:?}", ev.values),
                input { r#type: "text", name: "username" }
                input { r#type: "text", name: "full-name" }
                input { r#type: "password", name: "password" }
                button { "Submit the form" }
            }
        }
    })
}

```

- Type something in the input fields, you'll see some console output as expected
- Press the submit button, you should see a "Submitted ..." in the console, but nothing is there

**Expected behavior**

I expect the onsubmit to be called  even if the form is in a separate function.

**Screenshots**

Not applicable

**Environment:**
 - Dioxus version: 0.2.3
 - Rust version: 1.59
 - OS info: Linux Mint
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
Hmmm, I'm testing this code locally and it's the presence of the <a> tag (the link) that's interrupting the onsubmit. If I remove the Link component the form submits properly. Does it have something to do with how HTML forms work? I know buttons in forms take on the submit role by default by some configurations can prevent that default from kicking in.

**Comment by jkelleyrtp** [comment]
@stevenliebregt Can you see if #310 fixes this setup for you? Took a little while to figure it out and I'm sure there are more edge cases to catch.

**Comment by stevenliebregt** [comment]
Yeah that one fixes it
