### ISSUE TITLE
From `dioxus-cli 0.6.0-alpha.3` error occurred while running the "dx build --release" command.

### ISSUE THREAD

**Issue by RyanCho-0** [DioxusLabs/dioxus#3072]
**Problem**

When executing the "dx build --release" command from `dioxus-cli` 0.6.0-alpha.3`, an error message appears stating that the `--profile` flag and the `--release` flag cannot be used together.

**Steps To Reproduce**

- cargo install dioxus-cli --version 0.6.0-alpha.3
- dx init
- dx build --release

**Expected behavior**

Release build was successfully generated

**Screenshots**

![error](https://github.com/user-attachments/assets/7538f9e3-ae10-46ec-8e6f-2c616e87cf9e)

`$ dx build --release
 INFO dx::builder::cargo: Running build [web] command... 
 INFO dx::builder::cargo: Running build [server] command... 
fullstack build: --- Compiling ---
error: the argument '--release' cannot be used with '--profile <PROFILE-NAME>'

Usage: cargo rustc --message-format <FMT> --release --quiet --features <FEATURES> --bin [<NAME>] [ARGS]...

For more information, try '--help'.
fullstack build: --- Optimizing Assets ---
 INFO dx::builder::cargo: Copying public assets to the output directory... 
 INFO dx::builder::cargo: Build completed: [/home/choggernaut/build/test/dist] 
fullstack build: --- Finished ---
fullstack build: --- Compiling ---
error: the argument '--release' cannot be used with '--profile <PROFILE-NAME>'

Usage: cargo rustc --message-format <FMT> --release --quiet --features <FEATURES> --target [<TRIPLE>] --bin [<NAME>] [ARGS]...

For more information, try '--help'.
fullstack build: --- Optimizing Assets ---
ERROR dx::builder::cargo: the asset manifest was not provided by manganis and we were not able to collect assets 
Error: 🚫 Building project failed:

Caused by:
    0: Failed to post process build
    1: asset manifest was not provided by manganis
   `
  
**Environment:**
 - Dioxus version:  0.6.0-alpha.2 and  0.6.0-alpha.3
 - Rust version:    1.18.0
 - OS info:         Ubuntu 22.04, MacOS 15.1 Beta
 - App platform:    web, fullstack
 
**Questionnaire**

![code](https://github.com/user-attachments/assets/6f3c27f2-52dc-4c09-9709-d2925062bff6)

I wasn't sure where the `--profile` flag was being set, but by ensuring it didn't overlap with the `--release` flag, I was able to successfully complete the build.
While this isn't a fundamental solution, it worked for me.

**Comment by DogeDark** [comment]
Fixed in #3078
