### ISSUE TITLE
`VNode::from_html_dangerous`  to load html directly

### ISSUE THREAD

**Issue by oovm** [DioxusLabs/dioxus#311]
## Specific Demand

I have many svg icons and I would like some convenient mechanism to get VNode/LazyNodes directly.

The expected usage is as follows:

```rust
unsafe {
    VNode::from_html_dangerous::(include_str!("some.svg"))
}
```

The final result needs to be bare, and Fragment cannot use dangerous_inner_html

```log
55 |                 dangerous_inner_html: "{out}",
   |                 ^^^^^^^^^^^^^^^^^^^^ method not found in `core::properties::FragmentBuilder<'_, false>`
```

## Implement Suggestion

None

**Comment by jkelleyrtp** [comment]
Right now your only option is wrapping the raw html in an HTML element. Due to how templates work, we can't do any better :/
