### ISSUE TITLE
Inconsistent UI on Refresh 🔄

### ISSUE THREAD

**Issue by abhi3700** [DioxusLabs/dioxus#3116]
**Problem**

There is inconsistency in the UI shown when reloaded the same binary without any command run.

**Steps To Reproduce**

- `dx serve --platform web` on this [project](https://github.com/abhi3700/My_Learning-Rust/blob/48e84049d8847048183f62707b2cf8bd3b9bfb89/libs/dioxus/playg) 

**Expected behavior**

The UI on refresh shows standard elements instead of CSS styles.

**Screenshots**

Attaching the video herewith:

https://github.com/user-attachments/assets/3bb96e21-ee0e-4fef-b45f-461671298bbd

<img width="457" alt="image" src="https://github.com/user-attachments/assets/00bfc655-2165-4119-ae7d-5ce66c810641">

**Environment:**
 - Dioxus version: `0.6.0-alpha.3-6c69c29`
 - Rust version:    1.79.9 (nightly) 
 - OS info:         MacOS
 - App platform:    `web`

**Comment by jkelleyrtp** [comment]
Hi! The path handling for `asset!()` changed in the most recent merge of the CLI.

```
asset!("./assets/")

is now

asset!("/assets/")
```

this is likely causing the stylesheet hotreload system to load an old version of the stylesheet and/or change the path when you navigate.

The asset!() macro needs to reject the `./` form if the asset doesn't exist, which is a bug. I'll change the title of this issue, but if you want to work around it you need to switch to the new absolute form (which is more consistent with how you would normally handle assets on the web).
