### ISSUE TITLE
New hook dependency abstractions very confusing and not working properly

### ISSUE THREAD

**Issue by tgrushka** [DioxusLabs/dioxus#3135]
**Problem**

I want to create a `use_update_effect` like in Flutter Hooks (i.e., exactly the same as `use_effect`, but runs only on subsequent rebuilds, not first build).
https://pub.dev/documentation/flutter_use/latest/flutter_use/useUpdateEffect.html

All I want is to do something like this, which works, but want to drop build_count and just call `use_update_effect` and have that encapsulate the build_count or did_run or whatever:
```rs
#[derive(PartialEq, Props, Clone)]
pub struct DialogProps {
    id: String,
    show_modal: Signal<i32>,
}

#[component]
pub fn Dialog(props: DialogProps) -> Element {
    let props_clone = props.clone();
    let build_count = use_hook(|| Rc::new(RefCell::new(0)));

    let build_count_clone = build_count.clone();
    use_update_effect(move || {
        let id = props_clone.id.clone();
        tracing::info!("In use_effect show modal {:?}", props_clone.show_modal);
        if *build_count_clone.borrow() > 0 {
            spawn(async move {
                show_modal(&id);
            });
        }
        *build_count_clone.borrow_mut() += 1;
    });

    rsx! {
        dialog { id: props.id,
            h1 { "Dialog" }
            p { "This is a dialog" }
        }
    }
}
```

So I started with:
```rs
#[track_caller]
pub fn use_update_effect(callback: impl FnMut() + Clone + 'static) -> Effect {
    let callback = use_callback(callback);
    use_effect(move || {
        callback();
    })
}
```
which worked just like `use_effect`.

Then tried stuff like this, and went from there, with no luck (`use_effect` never runs with this):
```rs
#[track_caller]
pub fn use_update_effect(callback: impl FnMut() + Clone + 'static) -> Effect {
    let callback = use_callback(callback);
    let ran_once = use_hook(|| Cell::new(false));
    use_effect(move || {
        if ran_once.get() {
            callback();
        } else {
            ran_once.set(true);
        }
    })
}
```

Then fought **the whole day** with ChatGPT o1-preview (started over at least once) to try to figure out what was needed (over-hyped AI, doesn't even understand Rust's clear rules, even when I provide dioxus 0.5 source code):

https://chatgpt.com/share/67201883-881c-8001-95a5-7fa44783b3bc

## The bug is: missing docs or broken dependency checking in `use_hook` and friends.

**Steps To Reproduce**

- Try to define a `use_update_effect` method that will:
>         // Spawn a task that will run the effect when:
>        // SKIP THIS: 1) The component is first run
>        // 2) The effect is rerun due to an async read at any time
>        // 3) The effect is rerun in the same tick that the component is rerun: we need to wait for the component to rerun before we can run the effect again

- Note that, no matter what you try, the effect will not run with any conditionals when you wrap the user's callback.

**Expected behavior**

- Something this simple should be straightforward.
- If I wrap a user's callback and check whether build has run, that I can call the user's callback inside my wrapper conditionally based on whether the effect has run.
- These functions should probably be included, but that's a feature request. I expect as a developer-user, that I should be able to figure out on my own how to implement them without needing a new feature.

**Environment:**
 - Dioxus version:  0.5.7
 - Rust version:  1.82.0
 - OS info:    macOS 15.0.1
 - App platform:   fullstack

**Comment by tgrushka** [comment]
P.S. Another thing I tried:

Copied `use_effect` code, including `Effect` return struct, and renamed to `use_update_effect`.

- Commented out first call to `queue_effect_for_next_render();` -- result: no callback, ever.
- Added `let did_run = Rc::new(Cell::new(false))` etc. and then checked for it within `rc.run_in`, wrapping callback. Nothing.
- Several other things I can't recall which may or may not appear in my o1-preview chat link above.

It seems dioxus is insisting that, whenever I wrap the original user's callback, that it hasn't changed, even though I've introduced a `build_count` or `did_run`, etc. "dependency" into the wrapper that should change.

Using `use_signal` is obviously not an option either, as that causes an infinite loop.

So it is totally unclear even what a "dependency" is in the context of these hooks, how it considers these, and whether anything other than a Signal is even considered.

**Comment by ealmloff** [comment]
`use_hook` does not have dependency tracking. It is the core hook primitive without any state management systems built in. All hooks in dioxus_hooks (`use_signal`, `use_memo`, `use_resource`, etc) do have dependency tracking. The new docs have a more complete explanation of reactivity including how to deal with non-reactive state [here](https://dioxuslabs.com/learn/0.6/essentials/state#working-with-untracked-state)
