### ISSUE TITLE
https://dioxuslabs.com/blog/release_060

### ISSUE THREAD

**Issue by StoleUn** [DioxusLabs/dioxus#3143]
![Uploading Screenshot 2024-10-30 at 13.05.58.png…]()
**Problem**

return nothing

**Steps To Reproduce**

- 
- 
- 

**Expected behavior**

**Screenshots**

**Environment:**
 - Dioxus version:  
 - Rust version:    
 - OS info:         
 - App platform:    

**Questionnaire**

**Comment by jkelleyrtp** [comment]
Migrated to a new system for releasing the blog that didn't have support for drafts 😅
