### ISSUE TITLE
Failed to load .env file

### ISSUE THREAD

**Issue by abhi3700** [DioxusLabs/dioxus#3164]
### Discussed in https://github.com/DioxusLabs/dioxus/discussions/3163

<div type='discussions-op-text'>

<sup>Originally posted by **abhi3700** November  2, 2024</sup>
Hi!
I was trying to load the .env file using [dotenv](https://crates.io/crates/dotenv) crate. But somehow it was not getting set. I am not sure what i am missing.

- [main.rs](https://github.com/abhi3700/dioxus-playground/blob/7c79fc11c3382e5828ae985d524aecab51617b4d/src/main.rs).
- Want to use it inside [img_gen.rs](https://github.com/abhi3700/dioxus-playground/blob/7c79fc11c3382e5828ae985d524aecab51617b4d/src/img_gen.rs) which is one of the routes.

What am I missing?
Anyone please?</div>

**Comment by abhi3700** [comment]
I found that we can't load env vars in runtime in case of wasm. So, we need to create a build.rs file with some code to load the env vars.

Found this [blog](https://dev.to/javiasilis/how-to-pass-environment-variables-to-a-rust-wasm-application-like-yew-dioxus-and-leptos-as-a-typescript-developer-ond).

**Comment by abhi3700** [comment]
Found a workaround:
Add this line in code/function to access value during compile-time:
```rust
let api_key = env!("API_KEY");
```

And then we can run the App in CLI:
```sh
API_KEY="..." dx serve
```

Open to more thoughts/ideas on this..

**Comment by DogeDark** [comment]
`env!()` is the way to go currently.

**Comment by rogusdev** [comment]
As a reminder, eng vars are an os thing. There are no env bars in a browser.

So, if you need compile time config, use `env!`. But if you want run time config, you need to send an http request for that config, or something like that.

**Comment by rogusdev** [comment]
Build.rs is fine, that is compile time config. That said, it is more elaborate than the alternative, and meant for more complex calculations, in general. But it can do the trick so if you're happy with it, you're good.

https://doc.rust-lang.org/cargo/reference/build-scripts.html

The main point being that none of this has anything to do with dioxus, other than the fact that you are running dioxus in a browser, and thus have no env vars. But that's not dioxus, that's browsers.

**Comment by rogusdev** [comment]
As a minor sidenote, dotenv was abandoned years ago. You should be using `dotenvy` (note the final `y`)
