### ISSUE TITLE
playground demo doesn't work with zero changes

### ISSUE THREAD

**Issue by JohnAllen** [DioxusLabs/dioxus#3183]
Your playground demo doesn't work with zero changes. Makes it hard to use this if this is the first experience with Dioxus. This is the third time I have considered using it (over 1+years) 
<img width="1595" alt="Screenshot 2024-11-06 at 10 21 58 AM" src="https://github.com/user-attachments/assets/7b21a6a9-6017-4f48-b073-546997d07dd9">
and the first step always has bugs.

**Comment by DogeDark** [comment]
Playground never really worked and has not been officially released (despite being available on the website). It's currently undergoing a big overhaul, which will fix it. 

https://github.com/DioxusLabs/playground/pull/13

**Comment by DogeDark** [comment]
The playground was temporarily removed from the website until the overhaul is ready.
