### ISSUE TITLE
Can I call filesystem API to write file in desktop env?

### ISSUE THREAD

**Issue by cxgreat2014** [DioxusLabs/dioxus#319]
Hi, I'm new to dioxus, I wrote a small program with tauri and react, for some reason, I want to replace react with wasm so found our project, can I use filesystem api in our dioxus desktop app (Rust/ Tauri/WebAPI) ?

**Comment by jkelleyrtp** [comment]
> Hi, I'm new to dioxus, I wrote a small program with tauri and react, for some reason, I want to replace react with wasm so found our project, can I use filesystem api in our dioxus desktop app (Rust/ Tauri/WebAPI) ?

From WASM/Tauri - no. But if you use regular Dioxus desktop then yes - check out the file explorer example for some demo code.
