### ISSUE TITLE
There should have a space between elements

### ISSUE THREAD

**Issue by liigo** [DioxusLabs/dioxus#3190]
```
p {
    a { href: "a.html", "A" }
    a { href: "a.html", "B" }
}
```

it renders "AB" (no space).

VS

```html
<p>
    <a href="a.html">A</a>
    <a href="b.html">B</a>
</p>
```

it renders "A B" (note the space).

**Comment by ealmloff** [comment]
HTML has significant whitespace, but the rsx macro does not. The rsx that is exactly equivilent to the html you posted would be this:
```rust
p {
    "\n    "
    a { href: "a.html", "A" }
    "\n    "
    a { href: "a.html", "B" }
    "\n    "
}
```

That renders with a space between the two links because there is a text node between the two links with whitespace

**Comment by liigo** [comment]
Most frontend users konw HTML well, why was rsx decided to behave differently?

**Comment by liigo** [comment]
When I writing JSX, I think I'm writing HTML. and when I'm writing rsx, I think I'm writing JSX or HTML. Of course I'm wrong. Closing.
