### ISSUE TITLE
`dioxus-web` requires `web-sys` minimum version bump for `ScrollIntoViewOptions`

### ISSUE THREAD

**Issue by EndilWayfare** [DioxusLabs/dioxus#3197]
**Problem**

`ScrollIntoViewOptions::set_behavior` method was introduced in `web-sys` 0.3.70, but the `Cargo.toml` only requests 0.3.56

**Steps To Reproduce**

- Have an existing project with a committed `Cargo.lock`
- Upgrade to 0.6.0-alpha.4
- Wait for `rust-analyzer` to be sad

**Environment:**
 - Dioxus version:  0.6.0-alpha.4

**Comment by ealmloff** [comment]
This was fixed by https://github.com/DioxusLabs/dioxus/pull/3256
