### ISSUE TITLE
Improve GenerationalRef and GenerationalRefMut docs

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#3205]
## Feature Request

The documentation for generationalref and generationalrefmut are pretty sparse today. Generally, they should act like the inner type, but I have seen people in the discord run into issues trying to match on the ref type instead of the inner value. It should be possible to use dioxus relatively early into learning rust, so people may not have used types like `RefCell` and `RwLock` before

## Implement Suggestion

Add documentation about:
- Dynamically checked borrows
- How to get the inner `&T` data with deref
- Matching on the ref

**Comment by mattdm** [comment]
Yes please. I am running into exactly this. :)
