### ISSUE TITLE
[Feature/Question] How to Add Middleware to Axum in Full Stack

### ISSUE THREAD

**Issue by wiseaidev** [DioxusLabs/dioxus#3210]
Hiya (* ^ ω ^)ノ,

While working on [our first open-source, full-stack, production-ready template](https://github.com/opensass/aibook), I noticed there’s no clear way to [add middleware to Axum](https://docs.rs/axum/latest/axum/middleware/index.html) in the server setup. Middleware would be particularly useful for tasks like storing JWT tokens as cookies in Axum’s request/response flow for login sessions.

Currently, a workaround is to [store the JWT token in session storage](https://github.com/opensass/aibook/blob/b2b8bdfeb7b825e836d6b12221043bfaae20fc5b/src/pages/login.rs#L89-L90), but it’s not ideal and ain't secure if leaked.

So my question is: Is there a way to add middleware to Axum that allows injecting cookies into requests when calling the server?

Best

**Comment by ryo33** [comment]
There is an extension method on `axum::Router`, https://docs.rs/dioxus/0.6.0-alpha.4/dioxus/prelude/trait.DioxusRouterExt.html#tymethod.serve_dioxus_application, and it allows any setup of axum application.

**Comment by wiseaidev** [comment]
> There is an extension method on `axum::Router`, https://docs.rs/dioxus/0.6.0-alpha.4/dioxus/prelude/trait.DioxusRouterExt.html#tymethod.serve_dioxus_application, and it allows any setup of axum application.

Thanks for the response! It looks like this feature isn’t available in the latest stable version yet. Good to know it’s being tracked; Looking forward to the 0.6 stable release!

**Comment by ryo33** [comment]
> It looks like this feature isn’t available in the latest stable version yet.

It should also available in the 0.5.6 through the dioxus_fullstack crate, but I cannot figure out how to see it on docs.rs (it's weird).

**Comment by ealmloff** [comment]
> It should also available in the 0.5.6 through the dioxus_fullstack crate, but I cannot figure out how to see it on docs.rs (it's weird).
Docs.rs accepts a list of features to build the docs with. The dioxus 0.5 docs were built with no default features, so many items are not documented. You can run `cargo doc --features server --open` to generate documentation for all the crates you pull in with the server feature enabled which should have that item

You can also add middleware per function with the [middleware](https://dioxuslabs.com/learn/0.5/reference/fullstack/middleware) attribute on server functions

**Comment by wiseaidev** [comment]
> You can also add middleware per function with the [middleware](https://dioxuslabs.com/learn/0.5/reference/fullstack/middleware) attribute on server functions

Thanks! That's some next-level attribute wizardry (ﾉ>ω<)ﾉ :｡･:*:･ﾟ☆

I was searching the homepage for middleware but couldn’t find any. Hence this issue. It seems like the search functionality is not working as expected. Same for `dioxus` and `dioxus-fullstack` docs rs pages.

![middleware](https://github.com/user-attachments/assets/07adbcaf-cfe7-4bf3-9536-2f93c2b87232)

**Comment by yanshay** [comment]
> It should also available in the 0.5.6 through the dioxus_fullstack crate, but I cannot figure out how to see it on docs.rs (it's weird).

This example shows how to do it in 0.5.6

https://github.com/DioxusLabs/dioxus/blob/7210d333cdcd6e1499926dc184b6a244db376baf/packages/fullstack/examples/axum-auth/src/main.rs
