### ISSUE TITLE
Long logs are trimmed

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#3219]
**Problem**

Lines longer than ~2500 characters are trimmed by the CLI. 

**Steps To Reproduce**

- Create a hello world dioxus application with the git version of dioxus
- Enable tracing with `RUST_LOG=trace`
- Run the application with the CLI

**Expected behavior**

The entire text of logs should be printed

**Screenshots**

![Screenshot 2024-11-15 at 8 32 59 AM](https://github.com/user-attachments/assets/c3135c89-cdc2-4124-aa91-d3e0f2997281)

**Environment:**
 - Dioxus version:  `main`
 - Rust version:    `nightly`
 - OS info:         Macos
 - App platform:    CLI

**Questionnaire**

**Comment by jkelleyrtp** [comment]
Ahh probably because we only allocate 3000 chars for the line width

https://github.com/DioxusLabs/dioxus/blob/main/packages/cli/src/serve/output.rs#L937
