### ISSUE TITLE
[Bug]: Incorrect Handling of `onsubmit` Event in Forms

### ISSUE THREAD

**Issue by wiseaidev** [DioxusLabs/dioxus#3232]
Hiya (⌒‿⌒),

The `onsubmit` event in a form is being triggered by any button, regardless of its `type` attribute. This occurs even for buttons without `type: "submit"`, contrary to expected behavior where only buttons explicitly set as `type: "submit"` should trigger form submission. For example:

```rust
use dioxus::prelude::*;

#[derive(Clone, Routable, Debug, PartialEq)]
pub enum Route {
    #[route("/")]
    Login {},
}

fn Login() -> Element {
    let handle_login = move |_| {
        dioxus_logger::tracing::info!("Submit!");
    };
    rsx! {
        div {
            form {
                onsubmit: handle_login,
                button {
                    onclick: move |_| {},
                    "show pass"
                }
                button {
                    r#type: "submit",
                    "login"
                }
            }
         }
    }
}

fn main() {
    dioxus_logger::init(dioxus_logger::tracing::Level::INFO).expect("failed to init logger");
    launch(|| rsx! { Router::<Route> {} })
}
```

In this example, clicking the "show pass" button (which lacks a `type` attribute) triggers the `onsubmit` event, just like the "login" button that is explicitly set as `type: "submit"`.

Best!

**Comment by jkelleyrtp** [comment]
This is actually how HTML works - any button in a form causes the form to submit.

Either move the button out of the form or call prevent_default() in the onclick handler.

**Comment by wiseaidev** [comment]
> Either move the button out of the form or call prevent_default() in the onclick handler.

That's one way to fix it. But, I realized that the default `type` of a button is "submit". By setting its type to "button" is the proper way to fix it like so:

```rust
    rsx! {
        div {
            form {
                onsubmit: handle_login,
                button {
                    r#type: "button",
                    onclick: move |_| {},
                    "show pass"
                }
                button {
                    r#type: "submit",
                    "login"
                }
            }
         }
    }
```

html skill issue spotted
