### ISSUE TITLE
have a bug in script {}?

### ISSUE THREAD

**Issue by zhtanjj** [DioxusLabs/dioxus#3238]
**Problem**
it can't run  "window.addEventListener" in script .

**Steps To Reproduce**
1,Steps
```rust
       script{"
        alert('begin test window.addEventListener DOMContentLoaded');
        window.addEventListener('DOMContentLoaded', function () {{
            alert(' window.addEventListener DOMContentLoaded');
        }});
       "}
```
2,Steps
```rust
       script{"
         alert('begin test window.addEventListener DOMContentLoaded');        
         alert(' window.addEventListener DOMContentLoaded');        
       "}
```
**Expected behavior**
in 1 step: it can run `alert('begin test window.addEventListener DOMContentLoaded');` ,but can't run `alert(' window.addEventListener DOMContentLoaded');`

 in 2 step:  remove `window.addEventListener('...`, it can  run `alert(' window.addEventListener DOMContentLoaded');`

**Screenshots**

**Environment:**
 - Dioxus version:  
 - Rust version:    
 - OS info:         
 - App platform:

**Comment by ealmloff** [comment]
The content of the page may have already finished loading before the script runs. You can check  if the page has already loaded before adding the listener like [this](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#checking_whether_loading_is_already_complete)

For example, the content always appears as already fully loaded with this code (on the git version of dioxus):
```rust
use dioxus::prelude::*;

fn Home() -> Element {
    const SCRIPT: &str = r#"if (document.readyState === "loading") {
  // Loading hasn't finished yet
  document.addEventListener("DOMContentLoaded", function() {alert("DOM loaded")});
} else {
  // `DOMContentLoaded` has already fired
  alert("DOM was already fully loaded");
}"#;

    use_effect(|| {
        document::eval(SCRIPT);
    });

    rsx! {
        "hello"
    }
}

fn main() {
    launch(Home)
}
```

**Comment by zhtanjj** [comment]
THK
