### ISSUE TITLE
Pull out Manganis CLI support into a separate crate

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#3258]
# Refactor Request

The code to support manganis assets and asset optimization currently lives in the CLI (introduced in #3195). This means we don't need a stable API and it is fairly easy to integrate, but it makes it difficult to use manganis from other CLIs and it adds a lot of required dependencies to the CLI

It would be nice to pull out the optimization into a separate crate to make the CLI easier to maintain and could make it easier to move manganis optimization under a feature flag

**Comment by jkelleyrtp** [comment]
Oh forgot I did this - https://github.com/DioxusLabs/dioxus/pull/3273

It's named specific to dioxus but could/should be renamed to something manganis-specific.
