### ISSUE TITLE
Wrong realease date on website?

### ISSUE THREAD

**Issue by JonasCir** [DioxusLabs/dioxus#327]
Hi there thank you for creating this awesome library! 

I just noticed that if you go to the project [website](https://dioxuslabs.com/) and scroll all the way down to the release notes, it reads 2021 in all the two releases, I guess it should be 2022 according to the GitHub release?

![dioxus](https://user-images.githubusercontent.com/20031875/159518867-59b56d65-b832-4aab-82d4-d7b230b0be5c.png)

**Comment by mrxiaozhuox** [comment]
https://github.com/DioxusLabs/docsite

**Comment by JonasCir** [comment]
Missed that repo, thanks!

Seems to be fixed now...

**Comment by jkelleyrtp** [comment]
Thanks for the report - I fixed it but forgot to update this issue :)

**Comment by JonasCir** [comment]
Haha all good! Thanks again and keep up the good work! :rocket:
