### ISSUE TITLE
[Feature/Question] How to disable API URL randomization for a specific endpoint in fullstack?

### ISSUE THREAD

**Issue by wiseaidev** [DioxusLabs/dioxus#3283]
Hiya (*・ω・)ﾉ,

[I'm working on a new unique SASS template](https://github.com/opensass/nano-og) (our third (* ^ ω ^)!); Essentially a web app that lets users generate [OG](https://en.wikipedia.org/wiki/Facebook_Platform#Open_Graph_protocol) images in the browser locally using [**Gemini Nano**](https://deepmind.google/technologies/gemini/nano/). It involves [converting HTML to images](https://github.com/opensass/nano-og/blob/7db28c16b22b8940d9e30e57949fb01074abfd70/src/components/dashboard/ogs/create.rs#L70) with [`html2canvas`](https://github.com/opensass/nano-og/blob/7db28c16b22b8940d9e30e57949fb01074abfd70/Dioxus.toml#L41-L43) in JavaScript, which are then [converted to Base64](https://github.com/opensass/nano-og/blob/7db28c16b22b8940d9e30e57949fb01074abfd70/src/components/dashboard/ogs/create.rs#L77-L78) and sent via [`fetch`](https://github.com/opensass/nano-og/blob/7db28c16b22b8940d9e30e57949fb01074abfd70/src/components/dashboard/ogs/create.rs#L81) to an **Axum endpoint**, like so:

```rust
    fn save_preview_as_image() {
        client! {
            eval(r#"
                const element = document.getElementById('preview-section');
                if (element) {
                    html2canvas(element).then((canvas) => {
                        const base64Image = canvas.toDataURL('image/png');
                        const imageData = base64Image.replace(/^data:image\/png;base64,/, '');
                        const payload = `req[image_url]=${encodeURIComponent(imageData)}`;

                        // TODO: file an issue to disable api randomization
                        fetch('/api/upload_og6094941039135047799', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded'
                            },
                            body: payload
                        })
                        .then(response => {
                            dioxus.send(response);
                        })
                        .then(data => {
                        })
                        .catch(error => {
                        });
                    }).catch((error) => {
                    });
                } else {
                }
            "#);
        }
```

The issue is: with **Dioxus fullstack**, Dioxus/Axum is randomizing the API path URL at compile time (about every hour). To work around this, [I've been calling](https://github.com/opensass/nano-og/blob/7db28c16b22b8940d9e30e57949fb01074abfd70/src/components/dashboard/ogs/create.rs#L106-L115) [the server function](https://github.com/opensass/nano-og/blob/7db28c16b22b8940d9e30e57949fb01074abfd70/src/server/og/controller.rs#L205) to reveal the URL in the Network tab and then hardcoding it into the JS code:

![network tab](https://github.com/user-attachments/assets/240f556c-e4fb-4371-aecc-c5d6414f16bf)

This feels...hacky. 😬 Is there a way to **disable path randomization** for a specific endpoint while keeping the rest of the endpoints intact?  

Best! 🙏

**Comment by ealmloff** [comment]
You can set the endpoint parameter in the server function macro like this:
```rust
#[server(
  endpoint = "upload_og",
)]
```
