### ISSUE TITLE
Add empty tailwind.css to assets

### ISSUE THREAD

**Issue by RustGrow** [DioxusLabs/dioxus#3285]
When creating a project, just add creating an empty tailwind.css file to assets folder so you don't get a missing file error that bogs you down right away.

![image](https://github.com/user-attachments/assets/3b4c8d8c-4d73-4c34-85ba-f138441d84a5)

Dioxus version: 0.6.0-rc.0
Rust version: 1.83
OS info: WSL
App platform: fullstack web

**Comment by ealmloff** [comment]
Closing this as a duplicate of https://github.com/DioxusLabs/dioxus-template/issues/51
