### ISSUE TITLE
Render scheduled during previous render not commited to DOM

### ISSUE THREAD

**Issue by rMazeiks** [DioxusLabs/dioxus#338]
**This can't be reproduced on `master` so perhaps this bug has already been addressed. Since I've already written the report I'll post it anyway, in case this wasn't noticed, and for others who may stumble across this.**

I was expecting the code below to render the current timestamp, schedule a new render, and render the new timestamp:

```rust
use std::time::{SystemTime, UNIX_EPOCH};
use dioxus::prelude::*;

fn main() {
    dioxus::desktop::launch(App);
}

fn App(cx: Scope) -> Element {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("Time went backwards").as_nanos();

    cx.use_hook(|_|{
        let update_fn = cx.schedule_update();
        (update_fn)();
    });

    println!("Rendering with {nanos}");
    cx.render(rsx! (
        div {
            "{nanos}"
        }
    ))
}
```

As expected, the component is rendered twice with 2 different timestamps:

```
Rendering with 1648897039528600736
Rendering with 1648897039528797320
```

However, only the initial value is actually committed to the DOM:

![Screenshot: window containing 1648897039528600736](https://user-images.githubusercontent.com/11248241/161380177-ccff0f3c-1e23-44bc-b463-57a42e811b5d.png)

Instead, the latest value should be rendered.

It seems this can only be reproduced if an update is scheduled during render – if it is scheduled as part of some event (e.g. button click), everything is fine.

**Environment:**
 - Dioxus version: 0.2.3 (can't be reproduced on `master`)
 - Rust version: 1.59
 - OS: Ubuntu 20.04
 - App platform: desktop

**Comment by jkelleyrtp** [comment]
This is fixed on master, but I haven't released the new version yet. Some other PRs need to be merged too, but I expect to release by the end of the weekend.

**Comment by rMazeiks** [comment]
Awesome, thank you! I'll wait for the release then :)
