### ISSUE TITLE
File engine does not exist on the server

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus#3383]
**Problem**

This code should compile:
```rust
// dioxus = { version = "0.6", features = ["server", "fullstack"] }
use dioxus::prelude::*;
use dioxus_elements::FileEngine;

fn main() {}
```

**Environment:**
 - Dioxus version:  `master`
 - Rust version:    `nightly`
 - OS info:         MacOS
 - App platform:    html based platforms

**Questionnaire**

**Comment by Nathy-bajo** [comment]
Hi @ealmloff 

I wanted to clarify this issue, as I tested the provided code snippet in a fresh project, and it compiles successfully on my end with the following setup:

Dioxus version: 0.6 (from crates.io) or master branch (tried both)
Feature flags enabled: server, fullstack
Rust version: nightly
Environment: macOS

Was there any specific expectation that the code would fail to compile?
Are there additional steps or configurations required to reproduce the problem?
