### ISSUE TITLE
Unused import Clippy warnings despite being used in a server function

### ISSUE THREAD

**Issue by matous-volf** [DioxusLabs/dioxus#3449]
**Problem**

Clippy emits warnings about unused imports, even though they are in fact used and required for a successful build. This happens when the code using the import is inside a Dioxus server function.

**Steps To Reproduce**

1. Run
  ```
  dx new dioxus-unused-import
  ```
  - bare-bones
  - fullstack: true
  - router: true
  - Tailwind CSS: true
  - platform: web

2. Run
  ```
  cargo add dotenvy
  ```

3. Import `dotenvy::dotenv` and use it inside a Dioxus server function (the auto-generated one in this case):
  ```rs
  use dotenvy::dotenv;
  
  #[server(EchoServer)]
  async fn echo_server(input: String) -> Result<String, ServerFnError> {
      let _ = dotenv();
      Ok(input)
  }
  ```

4. Run
  ```
  cargo clippy
  ```

5. Observe the warning:
  ```
warning: unused import: `dotenvy::dotenv`
   --> src/main.rs:2:5
    |
  2 | use dotenvy::dotenv;
    |     ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default
  ```

I've done this in a [reproduction repo](https://github.com/matous-volf/dioxus-unused-import). The warnings get emited for many more imports than just `dotenv`, e.g. in [this repo](https://github.com/matous-volf/todo-baggins).

Removing `#[server(EchoServer)]` fixes the warning, but of course breaks the functionality. This may be a Clippy issue – I don't have the insight into the macro to judge.

**Expected behavior**

The warning should not be emited, as the import is used.

**Environment:**
 - Dioxus version:  0.6.1
 - Rust version:    1.83.0
 - OS info:         Docker `rust:1.83-bookworm` image
 - App platform:    web

**Comment by ryo33** [comment]
This document would be helpful.

https://dioxuslabs.com/learn/0.6/guides/fullstack/managing_dependencies#managing-binary-specific-imports

**Comment by matous-volf** [comment]
Absolutely spot on. Thanks!
