### ISSUE TITLE
web component example

### ISSUE THREAD

**Issue by Eliot00** [DioxusLabs/dioxus#367]
## Specific Demand

I want to use web components in dioxus, but the `<dash-name>` is not Rust ident.

**Comment by jkelleyrtp** [comment]
We added one here:

https://github.com/DioxusLabs/dioxus/blob/master/examples/custom_element.rs

Though, it frankly could be a bit better :)

**Comment by davidhmays** [comment]
What is the current way to implement custom elements in Dioxus? (Link above is dead.)

**Comment by ealmloff** [comment]
> What is the current way to implement custom elements in Dioxus? (Link above is dead.)

Here is the updated example: https://github.com/DioxusLabs/dioxus/blob/8ea7f076e5ff2b0a4ccc06cbfb93e93428d41b4b/examples/web_component.rs#L9
