### ISSUE TITLE
QoL improvements in the form of an extesion/CLI

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#368]
## Specific Demand

- [x] Translate HTML to RSX with extraction
    -  [x] Identify repitition and do some mapping
- [ ] Extract some rsx to its own component
- [ ] Extract repetitive rsx and convert it to an array map
- [x] Add some linting for improper use of hooks
- [x] Add linting for hooks, keys, and memoization
- [x] publish the vscode extension and promote it more in the docs
- [x] Autoformat rsx (and handlers/internal code with prettyplease)
- [ ] hover to preview rsx calls (like slint)

**Comment by trevyn** [comment]
>- Autoformat rsx (and handlers/internal code with prettyplease)

Would be cool if this also respected the `tab_spaces` setting in the project's `rustfmt.toml` if present :)

**Comment by jkelleyrtp** [comment]
Closing this since it's not super descriptive - will split these out into their own features.
