### ISSUE TITLE
Window configuration API

### ISSUE THREAD

**Issue by blemelin** [DioxusLabs/dioxus#372]
## Specific Demand

On the desktop platform, the `tao::window::WindowBuilder` is re-exported so the developer can configure how he wants his window to be (initial size, decorations, title, etc.). If I remember correctly, this was something that needed to be addressed in the future, since re-exporting APIs can cause problems in the long run.

## Implement Suggestion

Right now, the `DesktopConfig` struct owns a `WindowBuilder`. I propose to replace it with a new `WindowConfig` struct, but before I submit a PR about that, I would like to know the maintainers vision.

EDIT : [This fork](https://github.com/blemelin/dioxus/tree/new-window-builder) has a rough implementation of what I think would be interesting. I made sure to prevent breaking changes by providing convenience methods.

**Comment by jkelleyrtp** [comment]
I think we want to adopt a more imperative API for configuring the window - I want to keep this open with the intention of keeping a WindowConfig struct.
