### ISSUE TITLE
How to support video streaming?

### ISSUE THREAD

**Issue by i11010520** [DioxusLabs/dioxus#373]
Is there some plans to support video streaming and playing?
No relevant information in the roadmap feature list.

**Comment by jkelleyrtp** [comment]
Sorry for not getting to this earlier - did you figure it out?

**Comment by i11010520** [comment]
> 

@jkelleyrtp Thanks for your attention.
What I considered was how to implement the cross platform component interface of streaming media.
And how to optimize the performance? We can see that the web browser  consumes so much cpu resources while playing video streaming.
