### ISSUE TITLE
``write_silent`` in fermi is not silent

### ISSUE THREAD

**Issue by koptan** [DioxusLabs/dioxus#375]
**Problem**

``write_silent`` function in Fermi crate is not silent and it's asking the component to re-render 

**Expected behavior**

if I update the state using ``write_silent`` the component should not re-render 

**Environment:**
 - Dioxus version: `master`
 - Rust version: `rustc 1.60.0`
 - OS info:  `Linux-Ubentu`
 - App platform:  `web`
 - 
**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start

**Comment by mrxiaozhuox** [comment]
I think it's because the code isn't fully implemented:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/41265098/165220760-6828a13f-3ebe-4b52-8cee-81c6031324ac.png">

https://github.com/DioxusLabs/dioxus/blob/master/packages/fermi/src/hooks/atom_ref.rs#L73-L81

**Comment by jkelleyrtp** [comment]
The "force update" line needs to be removed if you're willing to make that PR.
