### ISSUE TITLE
Right and Middle mouse button stick (tui)

### ISSUE THREAD

**Issue by Demonthos** [DioxusLabs/dioxus#407]
**Problem**
Right and middle mouse button stick on tui. I had the same issue when initially building the mouse events, but it was removed when the mouse event was reworked. I have a fix that works on windows, but I want to verify other people have the same issue, before adding it back in.

**Steps To Reproduce**

- cargo run --example tui_keys
- press the right or middle mouse button

**Expected behavior**

The mouse button should show as pressed and then released.

**Environment:**
 - Dioxus version: master
 - Rust version: 1.60.0
 - OS info: Windows 11 (Windows terminal)
 - App platform: Tui

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by rMazeiks** [comment]
Woah, sorry about that! I guess some of the useless code I deleted wasn't that useless after all :/

On Linux it is working as-is, for both the middle and right mouse button. I had no idea it would vary by platform... crossterm was supposed to be cross-platform.

> I have a fix that works on windows

Great, I can test on linux if needed

**Comment by rMazeiks** [comment]
In the previous code, I found some notes about strange behavior, presumably on windows. Given that this doesn't happen on linux, could this be a bug in crossterm?

**Comment by rMazeiks** [comment]
Indeed, there's [this suspicious code](https://github.com/crossterm-rs/crossterm/blob/master/src/event/sys/windows/parse.rs#L307) in crossterm windows:

```
        EventFlags::PressOrRelease => {
            if button_state.release_button() {
                // in order to read the up button type, we have to check the last down input record.
                Some(MouseEventKind::Up(MouseButton::Left))
            } else {
                Some(MouseEventKind::Down(button))
            }
        }
```

It seems the comments is saying that they would need to maintain some state to properly determine which button was released. They actually do have state in  the `EventSource` but it doesn't get passed down. So as a workaround, they just assume that whenever a button is released, it's the left button? idk.

**Comment by Demonthos** [comment]
https://github.com/crossterm-rs/crossterm/pull/665 should fix it

**Comment by Demonthos** [comment]
This is not really an issue with dioxus it is an issue with crossterm.

**Comment by rMazeiks** [comment]
Awesome!
