### ISSUE TITLE
Is it possible to update style without recompiling the code

### ISSUE THREAD

**Issue by gfreezy** [DioxusLabs/dioxus#408]
## Specific Demand

Style changes automatically update without recompiling.

## Implement Suggestion

1. Watch for source code changes with inotify
2. Extract the style related code from the changed file
3. Parse the styles
4. Update internal state

**Comment by rMazeiks** [comment]
I haven't tried it myself, but the [Dioxus CLI](https://github.com/DioxusLabs/cli) claims to support hot CSS reload.

**Comment by jkelleyrtp** [comment]
> I haven't tried it myself, but the [Dioxus CLI](https://github.com/DioxusLabs/cli) claims to support hot CSS reload.

I don't think the CSS is only hot reloaded, but it would be fairly straightforward to support both in desktop and in web.

**Comment by rMazeiks** [comment]
@trevyn unfortunately, I doubt the `class` attribute can be easily updated without recompiling, since it is directly emitted by Rust code (like any other attribute).

**Comment by Demonthos** [comment]
With the cli serving with the ``` --hot-reload ``` flag and the ``` hot-reload ``` feature enabled in dioxus this is now possible 🎉
