### ISSUE TITLE
Krausest Benchmark Implementation

### ISSUE THREAD

**Issue by erichulburd** [DioxusLabs/dioxus#418]
## Specific Demand

I’m currently shopping Rust WASM web frameworks. Dioxus is very appealing for its multi platform approach.

One of my considerations is web interaction performance. WASM in theory definitely has a lot of potential, but I’ve heard in informal conversations that actual implementation can yield surprising results and I’ve seen even strong Rust advocates fallback to React after some initial attempts to build their UIs with WASM (specifically Yew).

As a shopper of WASM frameworks, it would be great to see more WASM representation on recognized benchmarking suites. For instance, it’s encouraging to see Yew climb the ranks of the [Krausest benchmarks](https://github.com/krausest/js-framework-benchmark). Compare the [current results](https://krausest.github.io/js-framework-benchmark/current.html) to [these results from 2018](https://stefankrause.net/js-frameworks-benchmark8/table.html).

## Implement Suggestion

I’ve not implemented the benchmarks from any framework myself and it seems knowledge of the framework would be desirable to represent the framework well, but at the same time, table row updates, swaps, and additions don’t seem too complicated to implement.

Is Dioxus interested in representation on the Krausest benchmarking results? Is this something a core Dioxus contributor would take up? If not, why and what alternative benchmarks would you suggest I consider?

**Comment by jkelleyrtp** [comment]
There are a few examples called "js framework benchmark" that implement this particular benchmark. However, I have had issues with integrating Dioxus with the benchmarking tool itself - the tool stalls even when Dioxus updates the page properly. If you're interested, maybe try taking the existing example benchmark code and try to get it working in the benchmark rig?

**Comment by erichulburd** [comment]
@jkelleyrtp Thanks, I wasn't aware of that example. Long weekend coming up, so I may try to set it up. That said, the hardware differences won't give a complete picture until we get the authors of the benchmark to include it, so ideally, we can make an overture over there at some point.

**Comment by lukechu10** [comment]
Also I believe the implementation currently found here https://github.com/DioxusLabs/dioxus/blob/master/examples/framework_benchmark.rs does not conform to the benchmark spec.    Specifically, the line: https://github.com/DioxusLabs/dioxus/blob/fe1279a1c591a9ba57feb82a5162e076c940817b/examples/framework_benchmark.rs#L55
replaces the last word with `!!!` when it should be appending it instead.

I don't know if that could be the problem with why the bench harness doesn't work with dioxus. Also normally the harness prints out the errors for why it didn't work at the end.

**Comment by lukechu10** [comment]
And lastly the counter here:
https://github.com/DioxusLabs/dioxus/blob/fe1279a1c591a9ba57feb82a5162e076c940817b/examples/framework_benchmark.rs#L20
should be a global counter, not one that is reset everytime a new list is created.

**Comment by erichulburd** [comment]
Ok, I'm having a few issues getting the framework benchmark to compile.

1.  Running `cargo run --example framework_benchmark` in webview, I get:

```ts
                 //Unhandled Promise Rejection: SyntaxError: Unexpected token '?'
                  } else {
                    // @ts-ignore
                    contents.values[name] =
                      element.value ?? element.textContent;
                  }
```

2. Following the [web platform instructions](https://dioxuslabs.com/reference/platforms/web) it doesn't seem entirely straightforward how I would run the framework benchmark through Trunk, as I take it `trunk` expects a binary Cargo package setup? Should I set this up as a separate package rather than an example?

**Comment by jkelleyrtp** [comment]
> Ok, I'm having a few issues getting the framework benchmark to compile.
> 
> 
> 
> 1.  Running `cargo run --example framework_benchmark` in webview, I get:
> 
> 
> 
> ```ts
> 
>                  //Unhandled Promise Rejection: SyntaxError: Unexpected token '?'
> 
>                   } else {
> 
>                     // @ts-ignore
> 
>                     contents.values[name] =
> 
>                       element.value ?? element.textContent;
> 
>                   }
> 
> ```
> 
> 
> 
> 2. Following the [web platform instructions](https://dioxuslabs.com/reference/platforms/web) it doesn't seem entirely straightforward how I would run the framework benchmark through Trunk, as I take it `trunk` expects a binary Cargo package setup? Should I set this up as a separate package rather than an example?

Can you trying forking the example projects repo and getting the folder working? There's a folder in that repo Dioxuslabs/example-projects that has jsframework benchmark but it's just not working.

**Comment by erichulburd** [comment]
OK I think what I'll do is create a separate standalone project that works with `trunk serve` (we're good on that front). Once I get the benchmark framework working I'll share the results here (probably just comparing to Yew on my local MBP), give you the opportunity to make any adjustments, and then open an MR with a working setup in https://github.com/krausest/js-framework-benchmark.

**Comment by erichulburd** [comment]
I've come _close_ to getting everything queued up for a benchmark run; I ran `npm run isKeyed -- keyed/dioxus` and addressed all of the issues, but Selenium decided to crap out on my machine before actually running the check again. 

<details>
<summary>Click to toggle contents of `code`</summary>
```
$ npm run isKeyed -- keyed/dioxus

> webdriver-ts@1.0.0 isKeyed ~/Code/open_source/js-framework-benchmark/webdriver-ts
> cross-env LANG="en_US.UTF-8" ts-node src/isKeyed.ts "keyed/dioxus"

args.framework undefined true
Frameworks that will be checked dioxus-v0.19.3-keyed
ERROR running dioxus-v0.19.3-keyed WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=102.0.5005.61)
    at Object.throwDecodedError (~/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (~/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:549:13)
    at Executor.execute (~/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:475:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Driver.execute (~/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/webdriver.js:735:17)
    at async runBench (~/js-framework-benchmark/webdriver-ts/src/isKeyed.ts:264:7) {
  name: 'WebDriverError',
  remoteStacktrace: '0   chromedriver                        0x00000001010612c9 chromedriver + 5120713\n' +
    '1   chromedriver                        0x0000000100fefe33 chromedriver + 4656691\n' +
    '2   chromedriver                        0x0000000100bdf158 chromedriver + 393560\n' +
    '3   chromedriver                        0x0000000100bd8e75 chromedriver + 368245\n' +
    '4   chromedriver                        0x0000000100bca81d chromedriver + 309277\n' +
    '5   chromedriver                        0x0000000100bcb5cd chromedriver + 312781\n' +
    '6   chromedriver                        0x0000000100bcaa87 chromedriver + 309895\n' +
    '7   chromedriver                        0x0000000100bc9ff7 chromedriver + 307191\n' +
    '8   chromedriver                        0x0000000100bc8efa chromedriver + 302842\n' +
    '9   chromedriver                        0x0000000100bc92a2 chromedriver + 303778\n' +
    '10  chromedriver                        0x0000000100be0c6a chromedriver + 400490\n' +
    '11  chromedriver                        0x0000000100c446df chromedriver + 808671\n' +
    '12  chromedriver                        0x0000000100c31482 chromedriver + 730242\n' +
    '13  chromedriver                        0x0000000100c43f41 chromedriver + 806721\n' +
    '14  chromedriver                        0x0000000100c31373 chromedriver + 729971\n' +
    '15  chromedriver                        0x0000000100c07609 chromedriver + 558601\n' +
    '16  chromedriver                        0x0000000100c08635 chromedriver + 562741\n' +
    '17  chromedriver                        0x0000000101033b1d chromedriver + 4934429\n' +
    '18  chromedriver                        0x0000000101038295 chromedriver + 4952725\n' +
    '19  chromedriver                        0x000000010103d3cf chromedriver + 4973519\n' +
    '20  chromedriver                        0x0000000101038cba chromedriver + 4955322\n' +
    '21  chromedriver                        0x000000010101337c chromedriver + 4801404\n' +
    '22  chromedriver                        0x0000000101052c68 chromedriver + 5061736\n' +
    '23  chromedriver                        0x0000000101052def chromedriver + 5062127\n' +
    '24  chromedriver                        0x00000001010685e5 chromedriver + 5150181\n' +
    '25  libsystem_pthread.dylib             0x00007fff5897e2eb _pthread_body + 126\n' +
    '26  libsystem_pthread.dylib             0x00007fff58981249 _pthread_start + 66\n' +
    '27  libsystem_pthread.dylib             0x00007fff5897d40d thread_start + 13\n'
}
```
</details>

So... Here is a link to the repo; I may raise an issue in the js-framework-benchmark repo to deal with Selenium, but at the least it's close.

**Comment by erichulburd** [comment]
Here are the results I've run locally.

[JsFrameworkResults.pdf](https://github.com/DioxusLabs/dioxus/files/8871800/JsFrameworkResults.pdf)

The metrics where Dioxus stands to improve the most are:

* Swap rows
* Select row
* Partial update
* Clear rows
* Total kilobyte weight

Yew performed ok and even better than React on some of these metrics, so there's definitely potential for Rust WASM to perform on par or better than the JS frameworks.

If you want to take a crack at optimizing any of this, feel free to leave notes here or submit an MR to: https://github.com/krausest/js-framework-benchmark, though the purpose of the benchmark is to benchmark idiomatic rather than optimized code.

In any case, I hope this is useful to you. This framework looks _awesome_ and with some well directed optimizations and support for keying, I will definitely consider it in the future.

System:

* Node v16.10
* MacOS 10.14.6
* 2.5GHz Intel Core i7
* 16 GB 1600MHz DDR3

**Comment by lukechu10** [comment]
> If the keyed behavior isn't directly supported by Dioxus, then I'll submit the benchmark implementation as non-keyed.

It seems like dioxus does support keyed https://github.com/DioxusLabs/dioxus/blob/fe1279a1c591a9ba57feb82a5162e076c940817b/packages/core/src/diff.rs#L618

**Comment by jkelleyrtp** [comment]
> @lukechu10 thank you, I stand corrected. Looks like the original implementation [didn't set the key on the tr element](https://github.com/DioxusLabs/dioxus/blob/ea4eb218ab1cc32ab4622a91fe88647750eab2ba/examples/framework_benchmark.rs#L71). I've made that update in my implementation [here](https://github.com/erichulburd/js-framework-benchmark/blob/23ad0313057c433a1330bcec57e31ccba73d41d2/frameworks/keyed/dioxus/src/main.rs#L116). The compiled application now passes the `isKeyed` test. Here is a comparison of results of a select few keyed frameworks.
> 
> WRT the Total Kilobyte Weight, I'm not familiar with Trunk. Is there some way I can build a compressed binary that isn't so large?
> 
> <img alt="Screen Shot 2022-06-10 at 8 58 24 AM" width="1440" src="https://user-images.githubusercontent.com/3526083/173106132-62adb42c-8cb3-4bca-8850-661c48d987a9.png">
> 
> <img alt="Screen Shot 2022-06-10 at 8 58 19 AM" width="1440" src="https://user-images.githubusercontent.com/3526083/173106150-e12fdd6e-4322-43ac-8dd0-ba151e151e99.png">
> 
> <img alt="Screen Shot 2022-06-10 at 8 58 27 AM" width="1440" src="https://user-images.githubusercontent.com/3526083/173106163-112d0d00-39f1-4141-96f2-82cfcb43413d.png">

You need to enable wasm-opt and release mode. 

https://trunkrs.dev/assets/

https://github.com/DioxusLabs/docsite/blob/17a393ed9bf8ec301ff2b01d02c202a45f2f83cc/index.html#L48

**Comment by jkelleyrtp** [comment]
I made 4 PRs that include various different optimizations (release flags, wasm-opt, interning, etc) 

https://github.com/erichulburd/js-framework-benchmark/pulls

**Comment by erichulburd** [comment]
@jkelleyrtp great i will take a look over the next few days, run locally, and share results here.

**Comment by erichulburd** [comment]
Amazing - optimizations made a huge difference. If these results look good to you and you've got no other downstream changes to make, I'll go ahead and get these into https://github.com/krausest/js-framework-benchmark

One QQ - it seemed this [`OTHER` variable](https://github.com/erichulburd/js-framework-benchmark/pull/4/files#diff-6d6648df2ce8e85df39edea0925e0da0c5b6f6be50731d280e58259826f1704fR12) was undefined, so I just removed it. Let me know if there was an intention there I missed.

<img width="1440" alt="Screen Shot 2022-06-17 at 9 58 33 AM" src="https://user-images.githubusercontent.com/3526083/174344064-15294d35-7f81-40a0-9e67-58d57a72fcec.png">


<img width="1440" alt="Screen Shot 2022-06-17 at 9 58 42 AM" src="https://user-images.githubusercontent.com/3526083/174344051-124cbada-8939-418a-bfab-042ea01906bd.png">


<img width="1440" alt="Screen Shot 2022-06-17 at 9 58 58 AM" src="https://user-images.githubusercontent.com/3526083/174344028-be26791f-57a3-49a6-83ec-49686c75c317.png">

**Comment by jkelleyrtp** [comment]
I just realized that this implementation of TodoMVC is not actually how you'd want to do lists like this in Dioxus. You would really want to use components for rows, not rebuilding them each frame :)

I'm going to submit another patch to your branch and you should see some really big speedups.

**Comment by erichulburd** [comment]
Some marginal improvements, nothing major.

FYI I also had to fix the keying in the implementation: https://github.com/erichulburd/js-framework-benchmark/commit/8074e07f78a60526d80afc5c2ce40406fc805c4f#diff-6d6648df2ce8e85df39edea0925e0da0c5b6f6be50731d280e58259826f1704f


I've open a PR to add our implementation to the official benchmark: https://github.com/krausest/js-framework-benchmark/pull/1061

<img width="1440" alt="Screen Shot 2022-06-30 at 11 32 02 AM" src="https://user-images.githubusercontent.com/3526083/176752199-db73a8ce-799a-432d-b680-b4f001bf2a9b.png">
<img width="1440" alt="Screen Shot 2022-06-30 at 11 31 58 AM" src="https://user-images.githubusercontent.com/3526083/176752220-9681cf20-78df-478f-881f-75e0e46ce0a9.png">
<img width="1440" alt="Screen Shot 2022-06-30 at 11 32 05 AM" src="https://user-images.githubusercontent.com/3526083/176752231-455566cb-52cc-4214-af85-701d76253350.png">
