### ISSUE TITLE
How to center app on screen?

### ISSUE THREAD

**Issue by HristoGochevPersonal** [DioxusLabs/dioxus#419]
As far as I'm aware tauri has the ability to center windows and dioxus uses tauri behind the scenes. So how can I access the functionality to center my app's window?

**Comment by rMazeiks** [comment]
hi!

I didn't try this myself, however:

`launch_with_props` accepts a third parameter which allows you to modify a `DesktopConfig`.

this has a `with_window` method, which lets you modify a `WindowBuilder`. and the window builder has a `position` attribute, among others. this should let you move the window wherever you want.

to center it, you'd probably have to get the screen size somehow and do the math with the window's size.

**Comment by HristoGochevPersonal** [comment]
Thank you! Kind of pain to do on Linux however because dual screens there are considered as one big screen.
