### ISSUE TITLE
Failed compile desktop app in release mode

### ISSUE THREAD

**Issue by akhilman** [DioxusLabs/dioxus#424]
**Problem**

The  `open_devtools()` method [is disabled by default in webview](https://github.com/tauri-apps/wry/blob/34b6cbca76811966cedf8050ae0d0fa18c84aa34/src/webview/webkitgtk/mod.rs#L369) in release mode, but dioxus-desktop still requires it.

**Steps To Reproduce**

- Try to compile any desktop example (e.g. todomvc) in release mode;
- Fail.

**Expected behavior**

Devtools should be behind a feature flag [same way as in wry](https://github.com/tauri-apps/wry/blob/34b6cbca76811966cedf8050ae0d0fa18c84aa34/src/webview/webkitgtk/mod.rs#L369).

**Screenshots**

```
$ cargo build --release --example todomvc
Compiling dioxus-desktop v0.2.3 (/home/user/dioxus/packages/desktop)
error[E0599]: no method named `open_devtools` found for reference `&WebView` in the current scope
   --> packages/desktop/src/desktop_context.rs:215:28
    |
215 |         DevTool => webview.open_devtools(),
    |                            ^^^^^^^^^^^^^ method not found in `&WebView`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `dioxus-desktop` due to previous error
```

**Environment:**
 - Dioxus version: `master`
 - Rust version: 1.61.0
 - OS info: GNU Linux
 - App platform: `desktop`

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
fixed by https://github.com/DioxusLabs/dioxus/pull/434
