### ISSUE TITLE
Add support for native system dialog

### ISSUE THREAD

**Issue by st-little** [DioxusLabs/dioxus#426]
## Specific Demand

Add support for native system dialog such as [electron dialog](https://www.electronjs.org/docs/latest/api/dialog)

**Comment by rMazeiks** [comment]
Agreed, this would be a nice feature!

In the meantime, consider workarounds:

- Using a library for these dialogs. [native-dialog](https://lib.rs/crates/native-dialog) sounds like what you're looking for
- For files, `<input type="file">` might do what you need

**Comment by mrxiaozhuox** [comment]
> I recommend using NFD directly in handlers - we will be integrating NFD into file input elements in a future release.

use `NFD` replace `<input type="file">` or just add a file-dialog component ?

**Comment by jkelleyrtp** [comment]
> > I recommend using NFD directly in handlers - we will be integrating NFD into file input elements in a future release.
> 
> use `NFD` replace `<input type="file">` or just add a file-dialog component ?

Our `input` element used in desktop will need to support onlick -> NFD (which it doesn't) and register a background file-handler with wry for drag-and-drop onto it.

**Comment by jkelleyrtp** [comment]
In #692 , we finally run the VirtualDom on the main thread, unlocking this capability.

**Comment by jkelleyrtp** [comment]
This has been somewhat added, but we recommend deferring to RFD directly.
