### ISSUE TITLE
is it possible to use Tauri to replace electron

### ISSUE THREAD

**Issue by JCAjason** [DioxusLabs/dioxus#427]
tauri is smaller than electron and faster. check it out.

**Comment by Demonthos** [comment]
Dioxus uses wry which is a webview library that tauri is build on. It does not use electron. :)

**Comment by jkelleyrtp** [comment]
I think we might need to add even *more* clarification about what Dioxus is. But I'm afraid that clashes with Tauri's marketing - until recently they have called themselves "build desktop apps with Rust and the web" which.... is very similar to Dioxus' messaging. But they're two completely different ways of building apps. Dioxus is designed for Rust programmers to stay 100% in Rust while Tauri is meant to bring in the entire web frontend community.
