### ISSUE TITLE
How to interact with clipboard, without JS?

### ISSUE THREAD

**Issue by i11010520** [DioxusLabs/dioxus#429]
I wanna fill a button "onclick" callback, to copy some element content to clipboard.
Without Javascript, just by native Rust.

Could somebody give me some hints?
Thanks!

**Comment by rMazeiks** [comment]
Hi! What platforms do you need to support? For native windows/mac/linux, [artboard](https://lib.rs/crates/arboard) might be what you're looking for. For wasm, I don't know. I haven't done any of this myself.

Also, take a look at other [clipboard crates on lib.rs](https://lib.rs/keywords/clipboard)!

**Comment by rMazeiks** [comment]
Searching for clipboard+wasm, I found `yew-hooks` – not what you need, but it has a [`use_clipboard`](https://github.com/jetli/yew-hooks/blob/11387ce9a9c8ab27e07b98315309de8c3a55dd7a/crates/yew-hooks/src/hooks/use_clipboard.rs#L126) hook, which we can use as reference.

They use [`wasm_bindgen`](https://rustwasm.github.io/docs/wasm-bindgen/) to access the clipboard from WASM. In my understanding it generates the JS + WASM bindings automatically based on [this black magic](https://github.com/jetli/yew-hooks/blob/11387ce9a9c8ab27e07b98315309de8c3a55dd7a/crates/yew-hooks/src/web_sys_ext.rs#L74). No Javascript required.

You could copy-paste fragments of that as a starting point.

**Comment by i11010520** [comment]
> Searching for clipboard+wasm, I found `yew-hooks` – not what you need, but it has a [`use_clipboard`](https://github.com/jetli/yew-hooks/blob/11387ce9a9c8ab27e07b98315309de8c3a55dd7a/crates/yew-hooks/src/hooks/use_clipboard.rs#L126) hook, which we can use as reference.
> 
> They use [`wasm_bindgen`](https://rustwasm.github.io/docs/wasm-bindgen/) to access the clipboard from WASM. In my understanding it generates the JS + WASM bindings automatically based on [this black magic](https://github.com/jetli/yew-hooks/blob/11387ce9a9c8ab27e07b98315309de8c3a55dd7a/crates/yew-hooks/src/web_sys_ext.rs#L74). No Javascript required.
> 
> You could copy-paste fragments of that as a starting point.

That's a very good reference!
Thanks! @rMazeiks

**Comment by rMazeiks** [comment]
Welp, apparently there's an easier way

>```let clipboard = window()?.navigator().clipboard()?;```

https://docs.rs/web-sys/latest/web_sys/struct.Clipboard.html

**Comment by i11010520** [comment]
> Welp, apparently there's an easier way
> 
> > `let clipboard = window()?.navigator().clipboard()?;`
> 
> https://docs.rs/web-sys/latest/web_sys/struct.Clipboard.html


As the `yew-hooks`' inline comment said:

```
//! ClipboardEvent in web-sys is unstable and
//! requires `--cfg=web_sys_unstable_apis` to be activated,
//! which is inconvenient, so copy the binding code here for now.

```
