### ISSUE TITLE
Website does not load on Safari Version 14.0.3

### ISSUE THREAD

**Issue by omnisci3nce** [DioxusLabs/dioxus#450]
**Problem**

Website does not load on Safari version 14.0.3 . Works fine on my Google Chrome install.

**Steps To Reproduce**

- Open https://dioxuslabs.com on Safari 14.0.3
- Open developer tools

**Expected behavior**

Page should load.

**Screenshots**

<img width="712" alt="Screen Shot 2022-06-18 at 11 20 07 pm" src="https://user-images.githubusercontent.com/17525998/174439567-b42621db-e3c6-4ad8-bbcf-3c59fc9cd324.png">

**Environment:**
 - OS info: Mac OS Big Sur

**Comment by Ar37-rs** [comment]
that has to be platform specific issue, even react js has the same isssue on that specific platform (so it's highly recommended to use firefox or chromium based browser): https://stackoverflow.com/questions/72837979/referenceerror-cant-find-variable-biguint64array
