### ISSUE TITLE
Database access from local server?

### ISSUE THREAD

**Issue by nekomatamune** [DioxusLabs/dioxus#464]
Disclaimer: Newbie here to running a rust web server / targeting rust to WASM.

I want to build a website with backend database access.I followed the [Getting Started: Web](https://dioxuslabs.com/reference/platforms/web.html) guide to set up and run a web server on `localhost:8080`, and that went just fine. 

Then I naively added the [mongodb crate](https://docs.rs/mongodb/latest/mongodb/) to Cargo.toml (without adding anything to the source code), and immediately the `trunk serve` command failed with the following error message

```
➜  dioxus-test git:(master) ✗ trunk serve
2022-06-29T07:30:27.226920Z  INFO 📦 starting build
2022-06-29T07:30:27.230982Z  INFO spawning asset pipelines
2022-06-29T07:30:28.370786Z  INFO building dioxus-test
warning: unused manifest key: dependencies.mongodb.featuers
   Compiling socket2 v0.4.4
   Compiling take_mut v0.2.2
   Compiling bitflags v1.3.2
   Compiling strsim v0.10.0
error[E0583]: file not found for module `sys`
   --> /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:124:1
    |
124 | mod sys;
    | ^^^^^^^^
    |
    = help: to create the module `sys`, create file "/Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/sys.rs" or "/Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/sys/mod.rs"

   Compiling getrandom v0.2.7
error: Socket2 doesn't support the compile target
   --> /Users/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:127:1
    |
127 | compile_error!("Socket2 doesn't support the compile target");

...
…(omitting the middle parts)
...

Some errors have detailed explanations: E0061, E0308, E0412, E0422, E0425, E0432, E0433, E0583, E0599.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `socket2` due to 185 previous errors
2022-06-29T07:30:31.587178Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error during cargo build execution
    2: cargo call returned a bad status
```

So I did some digging on the web. The issue appears to be due to the fact that the `socket2` crate, which `mongodb` crate depends on, doesn’t support WASM. 

My question is, how would I be able to build a Dioxus web app with access to database? Dioxus must be running a server locally on my machine that listens on `localhost:8080` to serves the webpage to the browser. Is there a way to do database queries on that local server and then serve the webpage with the query result?

Thanks,

**Comment by rMazeiks** [comment]
Hi!

> I want to build a website with backend database access

The code you write with Dioxus will run in the browser. Sure, there is a server-side rendering part, but after that, the browser needs to be able to re-render it.

And typically, in a web app, the browser will never have direct access to the database. If it did, a h4Ck3R could use this access to do anything they want (get sensitive information, or even delete all data). For this reason, I doubt there is anything that runs on WASM that connects to a database (even if you just want it to run locally which would be fine).

Instead, there is usually an API server between the browser and the database – a separate program (won't use Dioxus). The server would expose any API you need - for example, an endpoint for creating an account, one for logging in, and one for sending a PM. Then, you can use this API in the Dioxus code by making a request to the API (see [this example](https://github.com/DioxusLabs/dioxus/blob/master/examples/suspense.rs)).

This isn't really specific to Dioxus, it's just how a lot of the web works.

**Comment by jkelleyrtp** [comment]
What @rMazeiks said is spot on.

BUT, if you are interested in getting your hands dirty, Dioxus LiveView is meant for this exact usecase. No WASM, just render everything on the server with direct DB access. No REST or GraphQL, etc etc. All events are shuttled from the browser to the server. Even better when deployed with fly.io or Cloudflare for getting your app closer to the users.

**Comment by nekomatamune** [comment]
From the sound of it, it does seem that LiveView is what I would need in order to get to do the DB reading on the server side (like Next.js I suppose). I will dig more into it.

Thanks @rMazeiks and @jkelleyrtp for addressing my questions!
