### ISSUE TITLE
Custom property defaults

### ISSUE THREAD

**Issue by inf0rm4tik3r** [DioxusLabs/dioxus#472]
## Specific Demand

Reading https://dioxuslabs.com/guide/components/propsmacro.html, it does not seem possible to specify a particular default value for a property. `#[props(default)]` will always use the types `Default` implementation to infer the value.

Lets say we want the following boolean property to default to `true` (instead of bools default value `false`):

```
#[derive(Props, PartialEq)]
pub struct MyProps {
    #[props(default)]
    active: bool,
}
```

Did I miss something and this is already possible?

Otherwise: Is something like `#[props(default(true))]` possible?

Yew does that with its `#[prop_or(value)]` annotation (for reference: https://yew.rs/docs/concepts/components/properties).

**Comment by jkelleyrtp** [comment]
Sorry, we actually do have this ability but I guess it's just not documented.

Check out the typed-builder crate were we borrow some of the proc macro code from:

https://github.com/idanarye/rust-typed-builder

**Comment by Demonthos** [comment]
This is now documented [here](file:///C:/Users/Desktop/github/dioxus/docs/nightly/guide/en/describing_ui/component_props.html#default-props)
