### ISSUE TITLE
Hot reload: Elements with custom attributes fail to render

### ISSUE THREAD

**Issue by rMazeiks** [DioxusLabs/dioxus#479]
This works fine:

```
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    dioxus::desktop::launch(App);
}

fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "Hello, world!"
        }
    })
}
```

Adding a custom attribute makes the element disappear (it's not even in the DOM):

```
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    dioxus::desktop::launch(App);
}

fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "customAttr": "whatev",
            "Hello, world!"
        }
    })
}
```

Disturbingly, I saw no error messages.

If I use the same syntax with an existing attribute (e.g. `class`) it works fine.

**Comment by Demonthos** [comment]
It's worth noting that this is only broken if the ```hot-reload``` feature is enabled. The feature is enabled by default in the dev-dependencies, so the svg example is broken, but any applications that use dioxus currently are not effected.

#481 fixes silent failure.
#482 allows custom attributes.

**Comment by rMazeiks** [comment]
@Demonthos possibly related: with `hot-reload`, if I specify a raw literal attribute, it is prefixed with `_`. E.g:

```
input { r#type: "submit", }
```

Renders:

```
<input _type="submit">
```

Expected (works without hot-reload):

```
<input type="submit">
```

**Comment by Demonthos** [comment]
> @Demonthos possibly related: with `hot-reload`, if I specify a raw literal attribute, it is prefixed with `_`. E.g:
> 
> ```
> input { r#type: "submit", }
> ```
> 
> Renders:
> 
> ```
> <input _type="submit">
> ```
> 
> Expected (works without hot-reload):
> 
> ```
> <input type="submit">
> ```
> 

I'm not at my computer right now, so I can't test this, but it looks like the svg global attributes has r#type mapping to _type which is conflicting with the input attribute r#type that maps to type. I think #473 should fix this. It only applies svg attributes to svg elements. I'm unsure what the _type attribute is used for in svg's, and I can't find anything online, I just copied it from the dioxus-html implementation.
