### ISSUE TITLE
Stop ignoring doctests

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#493]
## Specific Demand

Up to tis point, doc examples have been a "useful thing to have but not that important." Now that Dioxus has matured some, it's time we start getting doc tests compiling. Hopefully #387 will make this easier since most places we care about doc tests can directly import rsx now.

## Implement Suggestion

Stop adding "ignore" to doctests.

**Comment by ealmloff** [comment]
We ignore a lot less doctests now but there are still a few places with ignore that would be nice to test: https://github.com/search?q=repo%3ADioxusLabs%2Fdioxus+%60%60%60ignore&type=code
