### ISSUE TITLE
Documentation Question - mount point element ID for web

### ISSUE THREAD

**Issue by supetronix** [DioxusLabs/dioxus#498]
Hi,

I tried to search both the documents and examples but didn't find answer to below, I hope someone can direct me to the resource. 

As per Web documentation, i.e.:
https://dioxuslabs.com/reference/platforms/web.html

Quote:
"Make sure your "mount point" element has an ID of "main" (this can be configured later)"

How can I change that? Or specify a different "id" name for my "div" tag?

Thanks

**Comment by rMazeiks** [comment]
https://docs.rs/dioxus-web/0.2.1/dioxus_web/fn.launch_cfg.html

https://docs.rs/dioxus-web/0.2.1/dioxus_web/struct.WebConfig.html#method.rootname

sorry I'm on mobile

**Comment by supetronix** [comment]
@rMazeiks - thanks for your help. 

I will give it a try and comment back here (and close this ticket if it works).

**Comment by supetronix** [comment]
It worked! I will close this ticket.

I used below for testing:

`    dioxus::web::launch_cfg(app, |config| config.rootname("main_app"));
`
