### ISSUE TITLE
Router push_route does not update title

### ISSUE THREAD

**Issue by tvallotton** [DioxusLabs/dioxus#499]
**Problem**

Pushing a new route with `push_route` does not update title. 

**Steps To Reproduce**

```
clone https://github.com/tvallotton/dioxus-router-title
cd dioxus-router-title
trunk serve
```

**Expected behavior**
The expected behavior would be for the title to be updated when the button is clicked. 

**Screenshots**

**Environment:**
 - Dioxus version:  `"0.2.4"`
 - Rust version: 1.62.0
 - OS info:  MacOS
 - App platform: `web`

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
The router has been rewritten and the dioxus version has been bumped several times since this issue. Closing this as stale for now, but feel free to reopen this if you can still reproduce the issue
