### ISSUE TITLE
How to build Redirect routing path dynamically?

### ISSUE THREAD

**Issue by i11010520** [DioxusLabs/dioxus#502]
When building Redirect, the static path is ok:
```
cx.render(rsx! {
    Redirect { to: "/abc" }
})
```

But when joining pieces of String to create dynamic path, like:
```
let id = "id1";
let url = format!("/abc:{}", id).as_str();
cx.render(rsx! {
    Redirect { to: url }
})
```
It will alert the following error:
```
cannot return value referencing temporary value
returns a value referencing data owned by the current functionrustc[E0515](https://doc.rust-lang.org/error-index.html#E0515)
```

How to create a dynamic routing path?
Thanks.

**Comment by Demonthos** [comment]
The macro automatically converts formatted values to &str. You can just inline the formatting and it will be resolved:
```rust
let id = "id1";
cx.render(rsx! {
    Redirect { to: "/abc:{id}" }
})
```

**Comment by i11010520** [comment]
> The macro automatically converts formatted values to &str. You can just inline the formatting and it will work:
> 
> ```rust
> let id = "id1";
> cx.render(rsx! {
>     Redirect { to: "/abc:{id}" }
> })
> ```

I had tried this way before,
but `id` variable cannot been recognized by the inline formatter,
and the rendered routing path was `/abc:%7Bid%7D`.
:(

**Comment by Demonthos** [comment]
The macro is missing code to allow formatting for the last attribute. #504 should fix this

**Comment by i11010520** [comment]
> The macro is missing code to allow formatting for the last attribute. #504 should fix this. This think this does work if you have a trailing comma.

So quick fix!
Thanks!
