### ISSUE TITLE
Notcurses backend

### ISSUE THREAD

**Issue by olanod** [DioxusLabs/dioxus#503]
[Notcurses](https://nick-black.com/dankwiki/index.php/Notcurses)([showcase](https://www.youtube.com/watch?v=dcjkezf1ARY)) is a library for building rich TUIs that make you forget you are running in a terminal and has [Rust bindings](https://crates.io/crates/notcurses) available. As Dioxus already has interest in TUI support this could be an interesting option to explore to bring more capabilities to terminal users.

**Comment by dxps** [comment]
This could definitely have a use case in [Dioxus CLI](https://github.com/DioxusLabs/cli).
