### ISSUE TITLE
How to update local state once async remote data arrived, without refreshing constantly?

### ISSUE THREAD

**Issue by i11010520** [DioxusLabs/dioxus#505]
When rendering a component, 
I need a local state to update some elements involving interactive sub-components,
and the local state should be initialized by requesting remote serving data.

But, when I used `use_future` response data to update the local state variable, like following:
```
let a_state = use_state(&cx, || 0);
let serving = use_future(&cx, (), move |_| {
};

```

**Comment by i11010520** [comment]
Could someone delete this issue?

**Comment by rMazeiks** [comment]
Looks like you made an updated version in #506 .

In the future, consider editing the existing issue instead. Anyway, don't worry about it, I think it's fine (I can't delete personally).
