### ISSUE TITLE
How to update local state once async remote data arrived, without refreshing constantly?

### ISSUE THREAD

**Issue by i11010520** [DioxusLabs/dioxus#506]
When rendering a component, 
I need a local state to update some elements involving interactive sub-components,
and the local state should be initialized by requesting remote serving data.

But, when I used `use_future` response data to update the local state variable, like following:
```
let a_state = use_state(&cx, || 0);
let res = use_future(&cx, (), move |_| {
    to_owned![url];
    async move {
        reqwest::get(url)
            .await
            .unwrap()
            .json::<MyModel>()
            .await
    }
});
let m0 = MyModel::default();
let model_info = match res.value() {
    Some(Ok(v)) => {
        a_state.set(v.id);
        v.to_owned()
    },
    Some(Err(err)) => {
        m0
    },
    None => {
        m0
    },
};

tracing::info!("model_info: {:?}", model_info);
tracing::info!("a_state: {:?}", a_state);
```
The local state variable `a_state` updated accordingly,
but this procedure ran on and on, with flooded flushed tracing infos.
While fortunately, there was just one successful HTTP GET record.

So, how can I set the local state just once time?
Thanks.

**Comment by rMazeiks** [comment]
The issue is that you're calling `.set` in the render function, which schedules another render, indefinitely.

If you really must update the state, consider moving the `.set` inside the future's closure:

```rust
// inside the future:

// you'll have to `.clone` the `a_state`, and move the clone to use it here

let response = reqwest::get(url)
            .await
            .unwrap()
            .json::<MyModel>()
            .await;
a_state.set(response.id);
```

However, based on your code, I would recommend avoiding the additional state altogether. In this case, I think you can do something like:

```rust
let default_model = MyModel::default();
let model_info = res.unwrap_or(default_model);
let id = model_info.id;
```

Note that this will construct a new `MyModel` instance on every render. This might be expensive, so I would also suggest working directly with the `Result<MyModel,_>`, and handling the error case separately. Something like

```rust
match response {
   Err(error) => todo!("render error case")
   Ok(response) => todo!("render whatever")
}
// note: response.clone() and ::default() not needed at all
```

**Comment by i11010520** [comment]
> The issue is that you're calling `.set` in the render function, which schedules another render, indefinitely.
> 
> If you really must update the state, consider moving the `.set` inside the future's closure:
> 
> ```rust
> // inside the future:
> 
> // you'll have to `.clone` the `a_state`, and move the clone to use it here
> 
> let response = reqwest::get(url)
>             .await
>             .unwrap()
>             .json::<MyModel>()
>             .await;
> a_state.set(response.id);
> ```

Fine description and nice suggestion!
Thanks indeed!
