### ISSUE TITLE
Question about Router and Link

### ISSUE THREAD

**Issue by supetronix** [DioxusLabs/dioxus#508]
Hi,

I looked at "docs" for router and the crate documentation but didn't find an answer to below, so hopefully I didn't overlook something.

In "docs" folder, one example uses "Link" inside the router. I was able to make it work before reading the documentation but issue is that how to use "Link" outside the "Router" component?

For example, if all "Links" were to be displayed at top or in a menu then this approach is fine but in a regular SPA application we will need links (or navigation option) at many different places i.e. we will have a button on page or tab bar link athat will let us move from one component to another component. I cannot place them all as a "Link" component in "Router". 

I tried to wrap "Link" with an empty "Router" component, so one Router component to define all the routes and another router component to stop application from panicking. That helped to stop runtime panic but "Link" in empty "Router" doesn't do anything. It will change the URL to that route but it will not load the "component" that we are supposed to load at a specific URL.

Using "Link" without "Router" gives below error:

`panicked at 'Cannot call use_route outside the scope of a Router component`

I am sure I am not the only one trying to build this so how did you guys handle it? I tried using "a" tag but it will refresh whole page. Tried using "prevent default" but not sure what to use in "click" event then. "use_router" panics at runtime as well and requires "Router" component.

If I missed some documentation or there is any solution to it then please share.

Thanks,

**Comment by rMazeiks** [comment]
Hi!

You can render things inside `Router`, but outside any `Route`s. Then, they will be rendered unconditionally:

```rust
fn App(cx: Scope) -> Element {
    cx.render(rsx!(
        Router {
            header {
                Link { to: "/", div { "Go home" } },
                Link { to: "/blog", div { "Go blog" } },
                Link { to: "/contact", div { "Go contact" } },
            }

            Route { to: "/", div { "Homepage" } },
            Route { to: "/blog", div { "Blog here" } },
            Route { to: "/contact", div { "Contacts" } },
        }
    ))
}
```

**Comment by supetronix** [comment]
@rMazeiks 

Appreciate your quick feedback but my apologize if I didn't explain the issue well. 

I should have included my working code in original post, sorry about that, but here it is and it is same as your code:


```
cx.render(rsx! {
        header {
            Router {
                Link{to: "/",
                    class: "text-3xl font-bold pl-4 py-2",
                 "My new Home"}

                Route { to: "/", home::home {}}
                Route { to: "/create-account", create_account::create_account{}}
            }
        }
    })
```

as you can see it is almost same as your code. 


**Issue:**
This works fine if all my route definition and navigation is one place, e.g. a top level navbar or menu. But this won't work in below scenario:

Let's take your route example so I have a "Blog here" component or page loaded. That component has bunch of text (or other HTML elements, doesn't matter) and then there is a "link" or "button" that is supposed to take me to "Contacts" page. And then I may have another set of HTML tags or text.

How should I create this "Link" for a route in this situation? (i.e. at random place on page, to navigate to any route that I might have defined at start).


Oh and I am on version "0.2.4".

**Comment by rMazeiks** [comment]
Hmm could you provide the code sample that doesn't work please?

Also please check if it works with the latest git version of Dioxus. There have been some bug fixes I think. Note that `dioxus-desktop` is a separate package there.

**Comment by supetronix** [comment]
Sure, here is what is not working.

1. I created a "routes.rs" file, with below contents:
```
pub fn create_routes(cx: Scope) -> Element {
    cx.render(rsx! {
        Router {
            Route { to: "/", home::home {}}
            Route { to: "/create-account", create_account::create_account{}}
        }
    })
}
```

Idea here is that I have this rust file that will just define routes and nothing else. 

2. I created a "navbar.rs", which will provide top navigation (menus etc.):

```
pub fn Navbar(cx: Scope) -> Element {
    cx.render(rsx! {
        header {
            h1 {
                class: "text-3xl font-bold pl-4 py-2 border-b-2 dark:border-slate-500",
                "To Do App!"
            }

            Lib_links{}
        }
    })
}
```

idea here is that it will draw the top navbar and any menu or links, in this case I am using "Lib_links" to create some links within navbar.

3. "Lib_links" is simple but it could be different options for top level navigation e.g. blogs, posts, admin etc.

```
pub fn Lib_links(cx: Scope) -> Element {
    cx.render(rsx! {
         Link{to: "/", "My new Home"}
    })
}
```

4. Then I add them to main app:

```
pub fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        Navbar{}

        routes::create_routes{}
    })
}
```


and that is where the problem is. Since "Link" from "Lib_links" is inside "Navbar", which is not inside "Routes" so it website breaks with below error:
panicked at 'Cannot call use_route outside the scope of a Router component



so to make it work now I have to put "routes" inside "NavBar":

```
pub fn Navbar(cx: Scope) -> Element {
    cx.render(rsx! {
        header {
            Router {
                Link{to: "/",
                    class: "text-3xl font-bold pl-4 py-2",
                 "My new Home"}
                 div{
                    class: "border-b-2 dark:border-slate-500 pt-2"
                 }

                Route { to: "/", home::home {}}
                Route { to: "/create-account", create_account::create_account{}}
            }
        }
    })
}
```

this works now and at best I can keep "Router" inside NavBar while pulling in "Link" and "Route" from separate component.

One good thing from my test is that if I have a "Link" inside "create_account" component to go back to "home" then somehow it works fine (i.e. without "Router"). I am assuming it is working fine since "Route" is sending to "Create account" and "Link" is allowed in there.

**Comment by ghostnumber7** [comment]
How about doing the app like 
```rust
pub fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        Router { // moved Router here to wrap everything
            Navbar{}

            routes::create_routes{}
        }
    })
}
```

and then in routes like 
```rust
pub fn create_routes(cx: Scope) -> Element {
    cx.render(rsx! {
        Route { to: "/", home::home {}}
        Route { to: "/create-account", create_account::create_account{}}
    })
}
```

I think that should make it work. You don't need to have `Router` as an immediate parent of routes, so you can wrap everything that will ever need to use it (or not) inside

**Comment by supetronix** [comment]
@ghostnumber7  - thanks, that will do it and keep it cleaner. I was thinking to use same thing inside NavBar but your suggestion is cleaner and liked it better for code organization.

Appreciate help from both of you.
