### ISSUE TITLE
DesktopConfig should be exported

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [DioxusLabs/dioxus#511]
The `DesktopConfig` structure is publicly usable via the `dioxus_desktop::launch_cfg` function, but is not exported, so no documentation is generated for it.

**Comment by malaire** [comment]
Yes, this doesn't seem to be documented anywhere.

https://docs.rs/dioxus-desktop/latest/dioxus_desktop/ says
> To configure the webview, menubar, and other important desktop-specific features, checkout out some of the launch configuration in the [API reference](https://docs.rs/dioxus-desktop/).

But there is no such "launch configuration" documentation anywhere.
