### ISSUE TITLE
Support something like React's componentDidMount and related hooks

### ISSUE THREAD

**Issue by autarch** [DioxusLabs/dioxus#517]
## Specific Demand

I'm trying to implement infinite scroll for a page. As part of that, I want to trigger loading more elements when the bottom X elements are visible. On the web, this can done by using an [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver). However, the `IntersectionObserver.observe` method takes elements, not ids. That means I cannot create an observer until after the component is in the DOM.

**Comment by backtolife2021** [comment]
I think what is actually needed here should be the node refs feature
