### ISSUE TITLE
Cross-platform support for the IntersectionObserver web API

### ISSUE THREAD

**Issue by autarch** [DioxusLabs/dioxus#518]
## Specific Demand

In order to implement an infinite scroll, I need to know when the bottom X elements in a list are in view so I can start loading more elements. There is a web API called [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) that provides this. As a stopgap, I can use this directly via `web-sys`, but longer-term it would be much nicer if Dioxus provided this sort of API across all platforms it supports.

**Comment by jkelleyrtp** [comment]
We added onresize and onvisible which should address this particular usecase.
