### ISSUE TITLE
Cross-platform support for the MutationObserver API

### ISSUE THREAD

**Issue by autarch** [DioxusLabs/dioxus#519]
## Specific Demand

There is a web API called [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) that provides this. As a stopgap, I can use this directly via `web-sys`, but longer-term it would be much nicer if Dioxus provided this sort of API across all platforms it supports.

**Comment by rMazeiks** [comment]
Hmm.. if I understand correctly, the mutation observer is for tracking changes in the DOM. What's your use case for this?

As far as I can tell, there is little need for observing mutations in a declarative framework such as Dioxus, where the framework controls the entire DOM.

**Comment by autarch** [comment]
Yeah, I added this simply because I was reading about it and the IntersectionObserver together, but on reflection I'm not sure what use this would be either. I'll close this.

**Comment by autarch** [comment]
I'm happy to see it reopened. But I'd like to leave it up to the project maintainers.
