### ISSUE TITLE
Problem: missing router api to go to page directly

### ISSUE THREAD

**Issue by leejw51** [DioxusLabs/dioxus#520]
how about adding router function to go to page directly
currently, it seems to be only possible inside rsx!

**Comment by rMazeiks** [comment]
Hi,

The Dioxus Router has a [`use_router`](https://docs.rs/dioxus-router/latest/dioxus_router/fn.use_router.html) hook, which returns an `Arc<RouterCore>`. You can call methods like [push_route](https://docs.rs/dioxus-router/latest/dioxus_router/struct.RouterCore.html#method.push_route) and [replace_route](https://docs.rs/dioxus-router/latest/dioxus_router/struct.RouterCore.html#method.replace_route) on it. These let you navigate programmatically.

Is this what you were looking for? If not, please describe the desired feature in detail.

**Comment by leejw51** [comment]
thanks, that's what i need
