### ISSUE TITLE
Problem: video mp4 is not working on linux

### ISSUE THREAD

**Issue by leejw51** [DioxusLabs/dioxus#523]
i tried to display mp4 file ,
windows, mac ok 

but linux, not working
installed all codec, in linux ( ubuntu )

would it be possible to support mp4 or webm?

some document for how to control video, such as play, stop etc.
also would be useful

**Comment by rMazeiks** [comment]
can I see the code pls

**Comment by leejw51** [comment]
i copied mp4 file to assets, and include inside `rsx!`
            ```
            div {
                video { src: "assets/640.mp4",autoplay:"true" },
            }
            ```
            
mac, windows working fine. (mp4, webm both working fine)

**Comment by ghostnumber7** [comment]
Just my two cents:
mp4 is a container format, so you need to know the codecs inside (normally h264 + aac). Playback depends on having the right codecs, and Ubuntu normally needs to have `ubuntu-restricted-extras` installed to play proprietary things like mp3 and h264 (both patented).
You could try to play the same video in a chromium browser and see if it plays to discard a codec issue
