### ISSUE TITLE
Whether a system tray can be created using dioxus?

### ISSUE THREAD

**Issue by allenli178** [DioxusLabs/dioxus#524]
I want to implement the system tray function for my desktop app，but I cant find any  related API  in dioxus.

**Comment by rMazeiks** [comment]
Hi,

As far as I'm aware, Dioxus unfortunately does not currently support using the system tray.

Thanks for the feature suggestion – I agree that this would be useful.

**Comment by rMazeiks** [comment]
You can leave the issue open to track this missing feature if you wish. It's helpful for contributors to see what kinds of features are not implemented yet.

**Comment by MrWolf-K9** [comment]
If you add a feature `tray` to the dioxus in cargo.toml you can use use dioxus_desktop::tao::system_tray.

**Comment by LighghtEeloo** [comment]
> If you add a feature tray to the dioxus in cargo.toml you can use use dioxus_desktop::tao::system_tray.

I'm trying to use it, but `dioxus_desktop::tao::SystemTrayBuilder` requires an `&EventLoopWindowTarget<UserWindowEvent>` to `build()`, which is currently not exposed in `dioxus_desktop::launch_with_props`. I'm not sure whether it's usable at the moment. Below is my attempt:

```
use dioxus_desktop::{
    tao::{
        system_tray::{SystemTray, SystemTrayBuilder},
        window::Icon,
    },
    Config, WindowBuilder,
};

fn main() -> anyhow::Result<()> {
    let icon = image::open("icons/tray.ico")?;
    let tray = SystemTrayBuilder::new(
        Icon::from_rgba(icon.to_rgba8().into_vec(), icon.width(), icon.height())?,
        None,
    )
    .build(unimplemented!("needs an &EventLoopWindowTarget<UserWindowEvent>"))
    .expect("failed to build system tray");

    dioxus_logger::init(log::LevelFilter::Info).expect("failed to init logger");
    dioxus_desktop::launch_with_props(App, (), Config::new());

    Ok(())
}
```

Maybe I should open a new issue to track it? Or with `wry/tray` on its way to being stable we can expect it working soon?
