### ISSUE TITLE
New guide example for stopping event propagation doesn't show stopping event propagation

### ISSUE THREAD

**Issue by TeFiLeDo** [DioxusLabs/dioxus#525]
**Problem**

In the event listener chapter (nightly), when describing how to [stop propagation](https://dioxuslabs.com/nightly/guide/interactivity/event_handlers.html#stopping-propagation), the example doesn't show how to stop propagation. It is identical to the previous example.

**Steps To Reproduce**

- Go to the [aforementioned section](https://dioxuslabs.com/nightly/guide/interactivity/event_handlers.html#stopping-propagation)
- Look at the example

**Expected behavior**

An example that shows the actual code to stop event propagation.

**Comment by rMazeiks** [comment]
Thanks for catching this! I had included the wrong example there.
