### ISSUE TITLE
Dioxus-cli fails to compile when installing

### ISSUE THREAD

**Issue by teken** [DioxusLabs/dioxus#531]
**Problem**

When installing the cargo package, the cli fails to compile providing back an E0061 error

**Steps To Reproduce**

1. Run `cargo install dioxus-cli`

**Expected behavior**

for the dioxus-cli to install successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/1248314/184540122-97354712-a30f-4371-8d59-3d6f75fbc190.png)

**Environment:**
 - Dioxus version: 0.1.4
 - Rust version: 1.63.0
 - OS info: Windows 10
 - App platform: N/A

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by dxps** [comment]
@teken This issue has been addressed and for now (before the next release) you can install it from git using:
```
cargo install --git https://github.com/DioxusLabs/cli
```

**Comment by teken** [comment]
thank you, installed seemed to work fine
