### ISSUE TITLE
Black screen on minimize after maximize

### ISSUE THREAD

**Issue by Kaltxi** [DioxusLabs/dioxus#532]
**Problem**

When I add my own title bar, using minimize button after the windows is maximized results in black screen when you open the window back using OS task bar. The app does not freeze - it is possible to recover from this using OS commands (on Windows: Win+Down -> Win+Up first returns the window to initial size and removes black screen and then maximizes the window again).

**Steps To Reproduce**
With the following code:
```rust
fn App(cx: Scope) -> Element {
    let window = use_window(&cx);
    window.set_decorations(false);

    rsx!{cx,
        main { class: "Main",
            div {
                class: "TitleBar",
                
                div {
                    class: "TitleBar_Title",
                    onmousedown: move |_| { window.drag(); },
                    span {"Title"}
                }

                button {
                    class: "TitleBar_Button",
                    onclick: |_| {
                        window.set_minimized(true);
                    },

                    img {
                        class: "TitleBar_Icon",
                        src: "./images/minimize.png",
                        alt: "—",
                        
                    }
                }

                button {
                    class: "TitleBar_Button",
                    onclick: |_| {
                        window.toggle_maximized();
                    },
                    img {
                        class: "TitleBar_Icon",
                        src: "./images/maximize.png",
                        alt: "+",
                    }
                }

                button {
                    class: "TitleBar_Button",
                    onclick: |_| {
                        window.close();
                    },
                    img {
                        class: "TitleBar_Icon",
                        src: "./images/close.png",
                        alt: "x",
                    }
                }
            }
        }
    }
}
```

- Press maximize button
- Press minimize button
- Click on the app using the task bar (Windows)
- The window is now maximized but black with white rectangle

**Expected behavior**

It is expected that app will return in its maximized form with proper rendering and not black screen.

**Screenshots**
This is how black screen looks like
![Fail to open after minimize](https://user-images.githubusercontent.com/11351899/185792087-3069e175-51fc-4d7f-bad9-3f0ab7c78e00.png)

**Environment:**
 - Dioxus version: v0.2.4
 - Rust version: 1.63.0
 - OS info: Windows 11
 - App platform: desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ghostnumber7** [comment]
Seams to be fixed in https://github.com/tauri-apps/tao/pull/462 (released ~20 days ago) ... maybe tao needs to be updated in dioxus_desktop

**Comment by Demonthos** [comment]
I'm having a hard time reproducing this on my machine. I also have windows 11, Rust 1.63.0, dioxus: 0.2.4.

Dioxus desktop depends on wry, which [depends on tao 0.12](https://github.com/tauri-apps/wry/blob/wry-v0.19.0/Cargo.toml#L43) (without a minor version) so it should automatically update to 0.12.2. You could try cargo update to update to a to the latest version of tao.

**Comment by Kaltxi** [comment]
I am using Edge and 0.6.4 too. Testing various versions, versions 0.6.0-3 do not have the black screen problem, but the minimize button doesn't work after one minimize after maximize, which 0.6.4 seems to fix judging by the patch notes.

Testing newer versions of tao would be interesting, but not sure how to do that.

**Comment by ghostnumber7** [comment]
> Testing newer versions of tao would be interesting, but not sure how to do that.
I don't know if there is a better way (more rust friendly), but you could:
* clone dioxus repo
* clone wry repo
* point your wry dependency to your local wry clone in dioxus desktop
* point your tao dependency to the version you want to test in wry

**Comment by Kaltxi** [comment]
Ok, so I did the following after some meandering:

It seems like the current main branch already has desktop depend on wry v0.19.0, so I cloned that. And added it to my toml:
```toml
[dependencies]
dioxus = {path = "D:/Rust/dioxus/packages/dioxus", features = ["desktop"]}
```

For some reason in this version of dioxus there is no feature "desktop", so I added it:

`dioxus/packages/dioxus/Cargo.toml`:
```toml
[dependencies]
dioxus-desktop = { path = "../desktop", optional = true}

[features]
desktop = ["dioxus-desktop"]
```

`dioxus/packages/dioxus/src/lib.rs`:
```rust
#[cfg(feature = "desktop")]
pub use dioxus_desktop as desktop;
```

This way my project compiles and the problem appears to be fixed. I guess just need to wait for new version of dioxus.
