### ISSUE TITLE
`KeyCode` doesn't get reported properly

### ISSUE THREAD

**Issue by lectromoe** [DioxusLabs/dioxus#544]
**Problem**

event `onkepress::key_code` doesn't get reported for `KeyCode::Backspace` and others

**Minimal Reproducable Example**

```rust 
cx.render(rsx!(
    div {
        onkeypress: move |evt| {
            let key_code = &evt.key_code;
            match key_code {
                // Never gets triggered
                KeyCode::Backspace => { panic!(); },
                _ => (),
            }
        },
    }
))
```

**Expected behavior**

On `Backspace` key press, the program should panic

**Environment:**
 - Dioxus version: 0.2.4
 - Rust version: 1.64.0-nightly
 - OS info: Ubuntu 20.04.4 LTS
 - App platform: web32_unknown_unknown

Not sure if machine-specific or an actual bug, more test data is needed

**Comment by Demonthos** [comment]
onkeypress only triggers for events that produce a character. This example works if you use onkeydown instead.

**Comment by lectromoe** [comment]
using `onkeydown` resolves it for `KeyCode::Backspace`, but it doesn't get called for `KeyCode::Space` for some reason? as a suggestion, since `onkeypress` doesn't get called with non-character key presses, shouldn't we use a different version of `KeyboardData` structure with it?

**Comment by Demonthos** [comment]
> using `onkeydown` resolves it for `KeyCode::Backspace`, but it doesn't get called for `KeyCode::Space` for some reason?

On 0.2.4 space is being detected as unknown. If you update to master the problem is resolved.

> as a suggestion, since `onkeypress` doesn't get called with non-character key presses, shouldn't we use a different version of `KeyboardData` structure with it?

That's a good idea. Currently we are using the keyboard-types crate to handle key events. I think we could create a wrapper over [KeyboardEvent](https://docs.rs/keyboard-types/latest/keyboard_types/struct.KeyboardEvent.html) for onkeypress that provides the same functionality with a smaller enum.

**Comment by lectromoe** [comment]
resolved by switching to master. a separate issue for `KeyboardEvent` wrapper is probably needed.
