### ISSUE TITLE
Links are broken in https://dioxuslabs.com/guide/setup.html

### ISSUE THREAD

**Issue by yatesco** [DioxusLabs/dioxus#559]
At the bottom of https://dioxuslabs.com/guide/setup.html there are a bunch of links:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/181469/190898498-6e8e5b00-8b58-4058-a3f2-2b1aeaf8b8c2.png">

Each of these goes to 404 (e.g. the first one goes to https://dioxuslabs.com/guide/Testing.html).

That's all :-).

**Comment by rMazeiks** [comment]
Thanks for the report!

The docs at `/guide` are a bit outdated. We have a "work in progress" site for the latest documentation (written for `master` Dioxus, not the latest release). It can be found at https://dioxuslabs.com/nightly/guide/index.html and it will be deployed to /guide on the next release.

Looks like the links have already been removed.
