### ISSUE TITLE
`use_const` hooks/init only once hooks

### ISSUE THREAD

**Issue by DrSloth** [DioxusLabs/dioxus#571]
## Specific Demand
Its sometimes necessary to share state between components, which is only initialised once and later only read. One case where this arised is after fetching something and displaying this content in multiple components. The data is shown on the page but not really changed.

This can be done relatively simply with borrowing, but these can not be memoized. One way to do this easily would be using something like an Rc.

I don't exactly know wether this is would be considered unidiomatic and should be solved using borrowing, utilizing the parent components as a "barrier". But that seems definitely harder...

## Implement Suggestion
An easy way would be providing a `use_const` hook which gives some `UseConst` value, that just contains an `Rc` which implements `PartialEq` using [`Rc::ptr_eq`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.ptr_eq)

Thanks for your time :)

**Comment by jkelleyrtp** [comment]
We basically have this now with use_signal() which can decompose into ReadOnlySIgnal via an Into conversion.

Closed by #1791
