### ISSUE TITLE
Flaky rsx!

### ISSUE THREAD

**Issue by locriacyber** [DioxusLabs/dioxus#589]
**Problem**

Not all Rust expressions can be used in `rsx!` quote directly

**Steps To Reproduce**
Compile the following code:
```
// main.rs
use dioxus::prelude::*;

fn main() {
    //dioxus::liveview::launch(app);
    dioxus::desktop::launch(app);
}

struct Todo {
    text: String
}

impl Todo {
    fn new(text: impl Into<String>) -> Self { Self { text: text.into() } }
}

fn app(cx: Scope) -> Element {
    let todos = vec![Todo::new("Buy fruit")];

    cx.render(rsx!(
        h1 {
            "TodoMVC: {todos.len()}"
        }
    ))
}
```

You should see this error:

```
error: unexpected token
  --> src/main.rs:29:15
   |
29 |       cx.render(rsx!(
   |  _______________^
...  |
43 | |     ))
   | |     ^ in this macro invocation
   | |_____|
   | 
```

**Expected behavior**

It should compile

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by locriacyber** [comment]
Currently the brackets `{ }` are used for
1. inline Rust syntax inside `rsx!`
2. Element like `h1 { }`
3. Literal interpolation like `"{hello}"`

**Comment by Demonthos** [comment]
On 0.2.4 expressions in strings were limited to variables and members, this limitation is removed on master. This example should work on master, we now accept any arbitrary expression!

**Comment by locriacyber** [comment]
Nice!
I saw the "Styling" part of the documentation is still missing.

Here's my attempt at using inline style with Tailwind.
https://git.envs.net/iacore/dioxus-todo-mvc/src/branch/main/src/main.rs#L54

**Comment by Demonthos** [comment]
> Nice! I saw the "Styling" part of the documentation is still missing.
> 
> Here's my attempt at using inline style with [Tailwind](https://docs.rs/tailwind-css/latest/tailwind_css/). https://git.envs.net/iacore/dioxus-todo-mvc/src/branch/main/src/main.rs#L54 https://git.envs.net/iacore/dioxus-todo-mvc/src/branch/main/src/macros.rs
> 
> Is there a way to scan all the nodes for class names? This would make styling easier.

The links are private so I can't see the code. If you want a compile time solution you could use the rsx crate to parse the rsx and then search attributes for classes. If you want to parse the entire workspace the cli has some code that extracts rsx that could be useful. (It might be better to move this discussion to the [discord](https://discord.gg/XgGxMSkvUM))
