### ISSUE TITLE
Atoms cannot be made mutable via make_mut()

### ISSUE THREAD

**Issue by arqalite** [DioxusLabs/dioxus#592]
## Specific Demand

In Dioxus 0.2, Fermi's Atoms cannot be made mutable by make_mut(), making the app panic on runtime with an "make mut not support for atom values yet" message.

In apps which rely a lot on global state management via Fermi, it leads to a lot of repeating boilerplate code just to get a way to mutate the atom's underlying value.

For me, that boilerplate ended up being with_mut(). For example, in an app I'm working on, I have 20+ blocks of code similar to this:

```rust
    let state = use_atom_state(&cx, STATE);

    let new_game = |_| {
        state.with_mut(|mut_state| {
            mut_state.players = Vec::new();
            mut_state.screen = Screen::PlayerSelect;
        });
    };
```

With make_mut(), that would turn to:

```rust
    let state = use_atom_state(&cx, STATE).make_mut();

    let new_game = |_| {
        state.players = Vec::new();
        state.screen = Screen::PlayerSelect;
    };
```

Which is a little shorter and nicer to read.

This isn't affecting functionality in any way, it's more of a nice-to-have for readability and having concise code, so it's certainly not a priority.

## Implement Suggestion

I'm still fairly new to Dioxus so I'm not able to provide a good solution for this yet. However I see that in Fermi's crate there was an attempt on implementing make_mut() so maybe I can start experimenting with that and see what I can do over the next week or so. 

If anyone knows what was the issue with that attempt or any blocking issues for this (or just tips in general), let me know.

**Comment by arqalite** [comment]
I forked the repo and tried giving it a shot - but I'm having issues figuring stuff out. I need to get a `RefMut` out of a `Rc` which as far as I can tell needs to be done via a `RefCell`. The standard library suggests I stick a `RefCell` into the `Rc` instead, somehow.

Ignoring the fact that `RefCells` aren't thread-safe, I still have to deal with making sure the `RefCell` exists as long as the atom does, which might mean changing a lot of code just to make this work. I'm not skilled enough to tackle this I think - unless I'm missing something really basic.

I considered maybe changing the return type of make_mut() to something else besides a `RefMut` but I can't find a good replacement. Probably that Rc<RefCell> is our key, but that would require changing a lot of code.

**Comment by saicu** [comment]
You could also use `use_atom_ref`:
https://dioxuslabs.com/guide/state/fermi.html#atomref

And then do
```
state.write().players = Vec::new();
state.write().screen = ...
```

Or something like this
```
state.write().update_state(..);
```

**Comment by jkelleyrtp** [comment]
> I forked the repo and tried giving it a shot - but I'm having issues figuring stuff out. I need to get a `RefMut` out of a `Rc` which as far as I can tell needs to be done via a `RefCell`. The standard library suggests I stick a `RefCell` into the `Rc` instead, somehow.
> 
> 
> 
> Ignoring the fact that `RefCells` aren't thread-safe, I still have to deal with making sure the `RefCell` exists as long as the atom does, which might mean changing a lot of code just to make this work. I'm not skilled enough to tackle this I think - unless I'm missing something really basic.
> 
> 
> 
> I considered maybe changing the return type of make_mut() to something else besides a `RefMut` but I can't find a good replacement. Probably that `Rc<RefCell>` is our key, but that would require changing a lot of code.

Check out the UseState hook and the make_mut method there. It's also fine to change the return type - it's an incomplete method with an incomplete syntax.

**Comment by arqalite** [comment]
Fermi's API changed in 0.3, this issue is no longer relevant I think.
