### ISSUE TITLE
[Question] Call JavaScript from Rust

### ISSUE THREAD

**Issue by scottbot95** [DioxusLabs/dioxus#593]
#### Background
The web and desktop renders are both essentially just webpages. The web target, however, gets compiled to WASM and run directly inside the users browser. This enables usage of tools like [wasm_bindgen](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/) to run JavaScript code. However AFAIK this is not possible with the desktop renderer since the rust code gets compiled natively and is somehow sending the generated DOM to a native WebView.

#### Question
I am trying to use a CSS library that requires you to call some JS functions that are added to the `window` object for certain actions (like opening/closing a modal). Is it possible to use something like `wasm_bindgen` to be able to call JS from my rust code for the Desktop renderer? I can *kinda* achieve what I want by dynamically adding/removing `<script>` tags, but I **strongly** do not like that approach.

**Comment by scottbot95** [comment]
This is somewhat similar to #134 so something that provides access to the `Document` object, may also lead to a good way to call arbitrary JS.

**Comment by saicu** [comment]
You can use the use_eval hook to execute Javascript on deskop and web.

https://docs.rs/dioxus-desktop/0.2.3/dioxus_desktop/fn.use_eval.html

**Comment by scottbot95** [comment]
Oh cool! It seems like this hooks is all-but undocumented.

Based on the type signature, it seems I can do something like the following?

```rust
let eval = use_eval(cx.scope);
eval("do_the_thing()");
eval("do_something_else()");
```

**Comment by saicu** [comment]
Yea, like that.

You can also do mulitple lines of JS at once:
```
let eval = use_eval(&cx);

eval("console.log('1'); console.log('2');");
```
L

**Comment by scottbot95** [comment]
Sweet thanks!

I haven't had the chance to mess with it yet and I'm a bit of a rust noob still, but `use_eval` returns an `Fn` not an `FnOnce`, so presumably it should be safe to call multiple times, right? If not, the type signature should probably be changed to reflect to true contract of `use_eval`

**Comment by saicu** [comment]
Yea true, just checked and I was just wrong :D
