### ISSUE TITLE
idiomatic way of uploading files

### ISSUE THREAD

**Issue by neevek** [DioxusLabs/dioxus#595]
Hi,
I am using Dioxus to write a simple file server, which is designed to support uploading multiple files at once, I tried to handle the upload action with a normal `onsubmit` event handler, when I select multiple files, `event.values` contains only once file with a weird file path, which looks like a file path on Windows, but I am testing on a Mac:
```
{"file": "C:\\fakepath\\testfile.txt"}
```

I have the following code for the form:
```rust
form {
    prevent_default: "onsubmit",
    onsubmit: handle_upload_files,
    method: "post",
    enctype: "multipart/form-data",
    input {
        r#type: "file",
        name: "file",
        multiple: "true",
    }
    input {
        r#type: "submit",
        value: "Upload"
    }
}
```

And how do I upload files with that file path?

**Comment by santokalayil** [comment]
Same issue here.. Help us to find a solution.
