### ISSUE TITLE
support rendering bitmaps or textures

### ISSUE THREAD

**Issue by dvc94ch** [DioxusLabs/dioxus#598]
Is there an example showing how to create and display an ImageBitmap?

- [0] https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap

**Comment by dvc94ch** [comment]
seems like streaming a video from ffmpeg or a webcam feed or even just an image buffer is not possible at the moment. my particular use case involves displaying and scanning qrcodes on mobile. Looks like I might be able to get away without this by rendering the qrcode in svg and using existing apps for qrcode scanning.

```rs
use dioxus::prelude::*;
use qrcode::render::svg;
use qrcode::QrCode;

#[allow(non_snake_case)]
#[inline_props]
pub fn Svg(cx: Scope, xml: String) -> Element {
    let svg = xml
        .strip_prefix(r#"<?xml version="1.0" standalone="yes"?>"#)
        .unwrap_or(&xml);
    cx.render(rsx! {
        div {
            script {r#"
                const parent = document.currentScript.parentElement;
                parent.innerHTML = '{svg}';
            "#}
        }
    })
}

#[allow(non_snake_case)]
#[inline_props]
pub fn Qrcode<'a>(cx: Scope<'a>, data: &'a [u8]) -> Element<'a> {
    let code = QrCode::new(data).unwrap();
    let svg = code.render::<svg::Color>().build();
    cx.render(rsx! {
        Svg {
            xml: svg,
        }
    })
}
```

**Comment by dvc94ch** [comment]
so qrcode scanning works great on android by handling it in kotlin and using some jni calls to start the qrcode scanning activity and get the results.

I don't see how this would work on ios as the webview is launched in full screen. I need some way of transitioning from a webview screen to a native screen and then back to a webview screen. any ideas on how that could work?

**Comment by jkelleyrtp** [comment]
Sorry this issue sat so long - there's not really a clear issue here per se other than 
- how to do qrcode rendering
- how to render an image on android/ios
- how to do multiple non-webview views 

I've split these issues out into their own things (1 is virtual files, 2 is dynamic assets, 3 is alternative mobile views). Technically all of this is possible today but we just don't have any guides for it, so I've moved it into our docs checklist.
