### ISSUE TITLE
how to start a timer/Interval in use_effect scope?

### ISSUE THREAD

**Issue by jieinchina** [DioxusLabs/dioxus#599]
somehow i need start a Interval when document is ready, and the callback will access  variable in use_state, seems no way to do that now？！hope get your comments!

**Comment by saicu** [comment]
For targeting web, you can have a look at https://crates.io/crates/gloo-timers
This seems to work on 0.2.4 as well as on master.
```rust
fn app(cx: Scope) -> Element {
    let interval_started = use_state(&cx, || false);
    let state = use_state(&cx, || 0);

    let (is, s) = (interval_started.clone(), state.clone());
    if !*interval_started.get() {
        is.set(true);
        gloo_timers::callback::Interval::new(1_000, move || {
            s.with_mut(|s| *s+=1);
        }).forget();
    }

    cx.render(rsx! {
        div {
            "{state}"
        }
    })
}
```

**Comment by jieinchina** [comment]
cool, that's what i need! Thank you budy!

**Comment by jieinchina** [comment]
hi,guys,
   it works when only one Interval. but seems like to create two Interval, one is 1_1000 and the other is 300, it will not work, complain the `cx` escapes the function body, how to fix it?

**Comment by saicu** [comment]
I guess because you need to clone the state (reference) a second time for the new closure, which moves it in:
```rust

if !*interval_started.get() {
    interval_started.set(true);
    let state = state.clone();
    let state2 = state.clone();
    gloo_timers::callback::Interval::new(1_000, move || {
        state.with_mut(|s| *s+=1);
    }).forget();
    gloo_timers::callback::Interval::new(1_000, move || {
        state2.with_mut(|s| *s+=1);
    }).forget();
}
```

**Comment by jieinchina** [comment]
morning,budy,yeah. it fixed like you say!
