### ISSUE TITLE
store closure in state

### ISSUE THREAD

**Issue by neevek** [DioxusLabs/dioxus#601]
I am trying to implement an AlertDialog, which contains two buttons, when the buttons are clicked, a closure stored in state will be called, the problem arises when I call `cx.spawn()` in closure, the code fails to compile because `UseState` requires its contained state be `'static`, but `cx` is bound to lifetime other than `'static`: 

```rust
let alert_params_state: &UseState<Option<AlertParams>> = use_state(&cx, || None);
rsx!(
  a {
    onclick: move |_| {
      alert_params_state.set(Some(AlertParams(
        positive_button: Box::new(move |_| {
          cx.spawn(async move |_| {
            // may initiate a request to remote server
          }),
        // other params ....
      }))))
    }
  }
)
```

```rust
447 |                                   positive_button: Box::new(move |_| {
    |  ____________________________________________________^
449 | |                                    // code removed for brevity
...   |
455 | |
456 | |                                 }),
    | |__________________________________^ cast requires that `'a` must outlive `'static`
```

If this is not possible to be implemented with `use_state`, what is the proper way?

**Comment by jkelleyrtp** [comment]
UseState can be `to_owned` or `cloned` into a `'static` value, which should solve this specific problem.

However the general case is to use a child component's lifecycle to do callbacks without needing a `'static` closure in the first place.

**Comment by neevek** [comment]
Thanks for the reply. 

> UseState can be `to_owned` or `cloned` into a `'static` value, which should solve this specific problem.

It's not about UseState being bound to `'static` or not, it's about the `Scope` object being not bound to `'static`, I need to call `cx.spawn()` in the closure, since `cx` has lifetime `'a`, which will make the entire closure bound to `'a`, calling `to_owned` or `clone` on UseState does not change that.

> 
> However the general case is to use a child component's lifecycle to do callbacks without needing a `'static` closure in the first place.

Would you elaborate on this one? I read through the guide and all the examples, unable to find solutions that suit my needs.

**Comment by traxys** [comment]
It is possible to hack something like this, but it seems to require a bit of adapting: 
I made the following props: 

```rust
// Use a lifetime because our type does not implement PartialEq
#[derive(Props)]
struct ClosureProps<'a> {
    callback: Rc<dyn Fn(SomeType)>,
    // For the lifetime to work
    #[props(default = PhantomData)]
   _ph: PhantomData<&'a ()>,
}

fn TakeCallback<'a>(cx: Scope<'a, ClosureProps<'static>>) -> Element<'a> {
   let on_click = move |_| {
      let cb = cx.props.callback.clone();
      cx.spawn(async move {
          (cb)(....); 
     });
   };
}
```

If you have a state `let state = use_state(cx, || ....)` you can do the following: 

```rust
let callback = {
    to_owned![state];
    Rc::new(move |_| {
        state.set(....);
    }
};

cx.render(rsx! {
    TakeCallback{callback: callback}
});
```

It's a bit tricky to avoid taking any `'a` lifetimes though.
