### ISSUE TITLE
Building production

### ISSUE THREAD

**Issue by timanagement** [DioxusLabs/dioxus#603]
## Building

I am knowing dioxus now and when compiling is it normal to appear a prompt when I run the generated binary or is there any parameter I should use during compilation? 

From now on, i grade
![image](https://user-images.githubusercontent.com/104225732/197619881-a3a0b7d2-8acf-4144-a978-5b4965e39529.png)

**Comment by Demonthos** [comment]
If I understand the question, you want to not show the terminal when you launch the application?
It depends on the platform, but if you are on windows adding ```#![windows_subsystem = "windows"]``` to the top of your main.rs file will remove the terminal and just show the app.

**Comment by timanagement** [comment]
Yes, that was exactly it. The prompt no longer appears.

Thank you very much.

![image](https://user-images.githubusercontent.com/104225732/197883393-c22f53c3-7e2f-4e95-9034-b8e7234bad0c.png)
