### ISSUE TITLE
desktop: Contained text is missing

### ISSUE THREAD

**Issue by tv42** [DioxusLabs/dioxus#606]
**Problem**

Text content of a button is missing from the desktop GUI.

For example,

```
button {
            "hello, desktop!"
}
```

shows a tiny button with nothing inside it.

Change the button to `div` and text is there.

Change the string literal to `img { src: "https://demo.invalid" }` and you get a broken image icon.

This may or may not be related: At startup, the program logs  "Could not determine the accessibility bus address". (See also https://github.com/tauri-apps/tauri/issues/4315)

**Steps To Reproduce**

- Make a dioxus desktop app with text in a button
- OR, run file-explorer example and observe an error: that error notification is missing the "x" close button: https://github.com/DioxusLabs/example-projects/blob/52d93021f04dd99bee8dda36e9e6065e5dc9f2e4/file-explorer/src/main.rs#L56

**Expected behavior**

```html
<button>hello, desktop!</button>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/419909/198147007-1b79e260-3c8d-42b6-bf42-aa640f3d92a2.png)

**Environment:**
 - Dioxus version: 0.2.4
 - Rust version: 1.64.0
 - OS info: Linux NixOS
 - App platform: desktop

**Comment by jkelleyrtp** [comment]
<img width="465" alt="Screenshot 2022-12-22 at 12 13 02 PM" src="https://user-images.githubusercontent.com/10237910/209189668-c5af164a-1303-41cf-a4a0-35be498bd4d3.png">

Seems fixed on master!
