### ISSUE TITLE
Docs and GitHub Readme disagree about Android support.

### ISSUE THREAD

**Issue by olafurw** [DioxusLabs/dioxus#613]
This page says only iOS:

https://github.com/DioxusLabs/dioxus/blob/6ea076fa7f4b672d1fa4a7c594f5446b1756214a/docs/guide/src/en/getting_started/mobile.md

Also your guide, only iOS:

https://dioxuslabs.com/guide/

While your readme says both iOS and Android.

https://github.com/DioxusLabs/dioxus/blob/master/README.md

**Comment by jkelleyrtp** [comment]
This needs to be updated - Tao/Wry recently gained Android support and the readme page was updated to reflect said support, but none of the docs have been updated as well.

**Comment by DogeDark** [comment]
The [nightly guide](https://dioxuslabs.com/nightly/guide) index page doesn't mention iOS or Android, only that Dioxus supports mobile platforms.

However, the nightly [mobile page](https://dioxuslabs.com/nightly/guide/getting_started/mobile.html) mentions that only iOS is supported by Dioxus. 
Same with the nightly [reference page](https://dioxuslabs.com/nightly/reference/platforms/mobile.html)

The relevant guide file that needs updating in GitHub: [guide](https://github.com/DioxusLabs/dioxus/blob/master/docs/guide/src/en/getting_started/mobile.md)
Can't find the `mobile.md` reference page though. Might've been removed as it looks like an older copy of the new guide version.

I'll open up a PR to update the header of the guide; I'm not sure if any of the guide's instructions have changed.
