### ISSUE TITLE
README - significantly more performant RN?

### ISSUE THREAD

**Issue by j-mendez** [DioxusLabs/dioxus#615]
Hello, I was wondering if you have any benchmarks on what parts are more performant than react-native? React-native runs native and uses memory references to native modules in ^v0.70.0. A native app runs more performant than a WebView which is what I think the dioxus does for mobile.

**Comment by DogeDark** [comment]
I don't have benchmarks, but I know mobile has the most support with WebView. There is an [experimental renderer](https://github.com/DioxusLabs/blitz) using WGPU in development, although I'm unsure how far progressed it is.
