### ISSUE TITLE
Custom keys in list panic

### ISSUE THREAD

**Issue by boyswan** [DioxusLabs/dioxus#617]
**Problem**

Rerendeing with custom keys in a list causes a panic

**Steps To Reproduce**

```rust
pub fn main(cx: Scope) -> Element {
    let state: &UseState<Vec<String>> = use_state(&cx, || Vec::default());

    let onclick = move |_| state.set(vec!["a".to_string(), "b".to_string(), "c".to_string()]);

    let items = state.iter().map(|s| {
        rsx! { li { key: "{s}", "{s}" } }
    });

    cx.render(rsx! {
        div { ul { items }, button { onclick: onclick, "Click" } }
    })
}

```

Clicking the button once renders the items, but clicking the button again results in a panic.
```
panicked at 'called `Option::unwrap()` on a `None` value', /***/.cargo/git/checkouts/dioxus-1e619ce595d3799d/5c996f2/packages/core/src/template.rs:477:9
```

Removing custom keys solves the issue, but displays error in console.

**Environment:**
 - Dioxus version: `master`
 - Rust version: `nightly`
 - OS info: `MacOS`
 - App platform: `web`

**Comment by Demonthos** [comment]
This issue is fixed in the 0.3 release
