### ISSUE TITLE
Select "multiple" does not work, only the first value selected is returned

### ISSUE THREAD

**Issue by stevenliebregt** [DioxusLabs/dioxus#625]
**Problem**

Using a `select` with `multiple: "true"` does give the correct UI, but the selecting behavior does not return multiple values when they are selected, just the one that is first in the list of selected items.

**Steps To Reproduce**

- Create a `select { multiple: "true", }` with a couple of options
- Listen in the `onchange` or `oninput` or even in the `onsubmit` of a `form` above it and print the event to the stdout
- See that only the first value (as it appears in the list) of the selected entries is printed as value

**Expected behavior**

I expect to either get a list of selected values, or at the very least a comma separated string containing all my selected values.

**Screenshots**

Code snippet:
![image](https://user-images.githubusercontent.com/17197587/202855995-9f9495d6-273d-4520-9291-1a73b63b77a3.png)

Relevant UI: first selected "TRA", then "TRB"
![image](https://user-images.githubusercontent.com/17197587/202856019-4bbfe7fa-9c9b-4f5b-b9a8-9ea573c63591.png)

Output in stdout:
![image](https://user-images.githubusercontent.com/17197587/202856036-1cde7190-665f-40c0-9fcf-b8abeecca6ed.png)

**Environment:**
 - Dioxus version: 0.2.4
 - Rust version: 1.65 stable
 - OS info: Ubuntu 
 - App platform: Desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by MGlolenstine** [comment]
I can confirm this is still an issue with 0.3.2.

**Comment by ryukoposting** [comment]
Seems like this problem still exists in 0.4.0. Here's a minimal example:

```rs
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        select {
            multiple: "true",
            size: 4,
            oninput: move |ev| {
                println!("value={:?} keys={:?} values={:?}", ev.value, ev.values.keys(), ev.values.values());
            },

            for i in 1..10 {
                option {
                    value: i as i64,
                    "{i}"
                }
            }
        }
    })
}
```

and some sample output while trying to select multiple items:
```
value="3" keys=[] values=[]
value="3" keys=[] values=[]
value="1" keys=[] values=[]
value="1" keys=[] values=[]
```
