### ISSUE TITLE
[TUI] Any way to NOT clear the terminal?

### ISSUE THREAD

**Issue by mattoni** [DioxusLabs/dioxus#629]
## Specific Demand

It'd be awesome if we could have the choice on whether or not to clear the terminal, especially after quitting. For example, maybe I'd like to list something with one cli arg, quit, and still see the list (how a 'normal' CLI would do it) but in other cases I may want to take up the full screen (graphs, inputs, etc).

## Implement Suggestion

Unsure if this is possible/inline with the goal of the TUI renderer, but would be neat to make more beautiful 'normal' CLIs too.

**Comment by Demonthos** [comment]
The TUI renderer relies on the tui crate to draw to the terminal. It looks like the latest version allows you to control the viewport: https://docs.rs/tui/latest/tui/terminal/struct.Viewport.html

**Comment by jkelleyrtp** [comment]
Specifically here, we're taking full control of the terminal.

https://github.com/DioxusLabs/dioxus/blob/master/packages/tui/src/lib.rs#L128

This could be locked behind a field on the TUI cfg.

**Comment by jkelleyrtp** [comment]
TUI has been moved/deprecated/is "on ice" for the time being
