### ISSUE TITLE
Actix Support for LiveView and LiveComponents

### ISSUE THREAD

**Issue by Algorab** [DioxusLabs/dioxus#636]
**Problem**

The Liveview and LiveComponents Box in the main webpage promise support for the actix webframework. In the live view package isn't any indication that is supported, implemented and no example.

**Steps To Reproduce**

See the Liveview and LiveComponents Box in the main webpage. Look at the https://github.com/DioxusLabs/dioxus/tree/master/packages/liveview

**Expected behavior**

Documentation and example how to use dioxus-web with actix

**Screenshots**

![image](https://user-images.githubusercontent.com/1868927/205071709-3ea780b1-a23f-4517-bfd8-c8359d126de1.png)

**Environment:**
 [- Dioxus version: `master`](https://github.com/DioxusLabs/dioxus/tree/master/packages/liveview)

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
Coming in #667 !

**Comment by jkelleyrtp** [comment]
I removed the references to actix in the docs. I think we might've had it at one point but the actix API has changed a bit and websockets seem really complex. I don't have the time to dig into adding actix support, but we refactored the LiveView crate a bit and all you need is a handle to a socket that implements Stream/Sink.
