### ISSUE TITLE
cfg.rs with_resource_directory's parameter 

### ISSUE THREAD

**Issue by Rick9622092** [DioxusLabs/dioxus#638]
pub fn with_resource_directory(mut self, path: impl Into<PathBuf>) -> Self {
        self.resource_dir = Some(path.into());
        self
    }

====>
pub fn with_resource_directory(&mut self, path: impl Into<PathBuf>) -> Self {
        self.resource_dir = Some(path.into());
        self
    }

**Comment by dvc94ch** [comment]
did you check that that compiles? `Self` is an owned value, `&mut self` is a mutable reference and `Self` is not `Copy`. Pretty sure that rustc will tell you something along the lines of "trying to move a value out of a mutable reference" after you resolved the type error, you need to dereference self.
