### ISSUE TITLE
Formatting with rustfmt

### ISSUE THREAD

**Issue by hf29h8sh321** [DioxusLabs/dioxus#66]
Currently, `rustfmt` fails on code using the `rsx!` macro. Would it be possible for this to work?

Alternatively, is there any way to create markup without using the macro?

**Comment by jkelleyrtp** [comment]
Unfortunately, not without support in the VSCode extension. I tried, but some of our syntax deviates just slightly enough to be un rustmft-able. Though, it shouldn't be too hard to add extension support.

You can use the [NodeFactory](https://docs.rs/dioxus-core/0.1.6/dioxus_core/struct.NodeFactory.html) api to create nodes by hand, thought there aren't a ton of functions that make it super ergonomic yet.

**Comment by jgillich** [comment]
Is there a way to auto-format now? I wonder why this is closed

**Comment by jkelleyrtp** [comment]
Oh, yes. The master version of the Dioxus CLI has a fmt command! I've worked out a ton of bugs in it but feel free to report anything.

**Comment by jgillich** [comment]
I see, thanks!

**Comment by dijith-481** [comment]
Hey, If any NeoVim  users come across this thread. here is a   lua snippet  for auto-formatting the Dioxus `rsx!`

```lua
vim.api.nvim_create_autocmd("BufWritePost", {
	pattern = "*.rs",
	callback = function()
		local cwd = vim.fn.getcwd()
		if vim.fn.filereadable(cwd .. "/Dioxus.toml") == 1 then
			local command = "dx fmt"
			vim.cmd("silent ! " .. command)
			--vim.notify("dx fmt")
		end
	end,
})

```

**Comment by sluedecke** [comment]
> Hey, If any NeoVim users come across this thread. here is a lua snippet for auto-formatting the Dioxus `rsx!`

Awesome, I was looking for this for some days now!

I use [LSP a lot with rustaceanvim](https://github.com/mrcjkb/rustaceanvim) and I have some subfolders like `src/components`, so this works for me ([gets root folder of project from lsp](https://github.com/neovim/nvim-lspconfig/issues/320#issuecomment-749191982), formats current file only):

```lua
vim.api.nvim_create_autocmd("BufWritePost", {
  pattern = "*.rs",
  callback = function()
    local cwd = vim.lsp.buf.list_workspace_folders()
    if not (cwd == null) then
      if vim.fn.filereadable(cwd[1] .. "/Dioxus.toml") == 1 then
        local command = "dx fmt --file %"
        -- vim.notify(command)
        vim.cmd("silent ! " .. command)
      end
    end
  end,
})


```

I can see further now, thank you @dijith-481

**Comment by ripytide** [comment]
Adding to the compendium after finding this in my search.

This is my setup for neovim using LazyVim with the built-in conform.nvim:

Filename: `lua/plugins/conform.lua`
```lua
return {
	"stevearc/conform.nvim",
	opts = {
		notify_on_error = true,
		formatters_by_ft = {
			rust = { "dx_fmt", lsp_format = "first" },
		},
		formatters = {
			dx_fmt = {
				command = "dx",
				args = {"fmt", "--file", "$FILENAME"},
				stdin = false,
			}
		}
	}
}
```
