### ISSUE TITLE
Website globalstate.rs fermi example use_state instead of use_atom

### ISSUE THREAD

**Issue by stubbi** [DioxusLabs/dioxus#660]
**Problem**

On https://dioxuslabs.com/, there are the codesnippets early on the page, one of them is `globalstate.rs` with the content

```
//! Use Fermi to easily manage global state with a simple Atom-based API

// Define an atom of state
static COUNT: Atom<i32> = |_| 0;

// Read it anywhere
fn Demo(cx: Scope) -> Element {
    let count = use_read(&cx, || COUNT);

    render!("Count: {count}")
}

// Or write to it from anywhere
fn Increment(cx: Scope) -> Element {
    let mut count = use_atom(&cx, COUNT);

    render!(button { onclick: move |_| count += 1, "Increment" } )
}

```

The line `let mut count = use_atom(&cx, COUNT);` has to be changed to either `use_set` or `use_atom_state` (I believe) to compile. It's also this way on the [GitHub Readme of fermi](https://github.com/DioxusLabs/dioxus/tree/master/packages/fermi).

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

## Edit

I just noticed it's also documented with `use_atom` [here](https://dioxuslabs.com/guide/state/fermi.html). Also, documentation is not consistent about how to use it. on crates.io, the README and the guide all have different instrucitons:

[crates.io:](https://crates.io/crates/fermi)
```
[depdencies]
fermi = { git = "https://github.com/dioxuslabs/fermi" }
```

[README](https://github.com/DioxusLabs/dioxus/tree/master/packages/fermi)
```
[dependencies]
fermi = { git = "https://github.com/dioxuslabs/dioxus" }
```

[Guide](https://dioxuslabs.com/guide/state/fermi.html)
```
[dependencies]
dioxus = { version = "0.2", features = ["desktop", "fermi"] }
```

**Comment by arqalite** [comment]
I'll tackle this one - seems like a good intro to contributing.

Task list:
- [ ] Update docsite example
- [ ] Update README.md for fermi crate

I think that should be it, right?
