### ISSUE TITLE
Feature: LiveView hydration 

### ISSUE THREAD

**Issue by DusterTheFirst** [DioxusLabs/dioxus#678]
## Specific Demand

The ability to use live-view while also server side rendering in conjunction.

Currently, I have a setup like the following:
```handlebars
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Creators for a Cause | Live Creators</title>
    </head>
    <body>
        <div id="main">
            {{ ssr|safe }}
        </div>
    </body>
    {{ glue|safe }}
</html>
```
Where `{{ glue|safe }}` is replaced by the string generated by `dioxus_liveview::interpreter_glue`, and `{{ ssr|safe }}` is replaced by the output of a call to `render` on a vdom of the dioxus app. And my dioxus app is:
```rs
pub(super) fn dashboard(cx: Scope<CreatorsWatcher>) -> Element {
    cx.render(rsx! {
        div {
            "hello axum!"
        }
    })
}
```

My expectation is that when the liveview glue kicks in on the client, it will only hydrate the existing html in the `div#main`, but I end up with the following `div#main`.
```html
<div id="main">
    <div>hello axum!</div>
    <div>hello axum!</div>
</div>
```
which seems to look like the liveview glue is just appending its vdom onto the existing children of `div#main` rather than replacing/modifying the existing children.

My exact usage can be seen in the following snippet:

https://github.com/DusterTheFirst/creatorsforacause/blob/f1f18b66e0af460c0cc4de1aa7bb2299a4176947/src/web.rs#L48-L129

## Implement Suggestion

The LiveView glue javascript could read the existing DOM in the `div#main` and replace it or modify it with the changes from the liveview. This could also be implemented in conjunction with allowing the user to provide an existing (pre-hydrated) vdom to the liveview websocket handler.

**Comment by jkelleyrtp** [comment]
Yes! This is a thing that's missing. We need to somehow cache the app between initial request and websocket upgrade. The issue here is that these are usually two events and it's unclear how long an upgrade will take and how long we should keep the app that's been SSR-ed around.

**Comment by DusterTheFirst** [comment]
It may make sense to give this to total control of the user, ie. make them hold on to the app between the initial request and the web socket connect. This would allow them to select a timeout, or have their own way to deal with the state (ex. tie the state to a user id). This would give the most extensibility and flexibility for the future, but would require a bit more work on the users end, especially with a `Send + Sync` web framework like axum which would require synchronization primitives and the like.

This could also allow for the user to have a "default" state that all SSRs render, and all liveviews are populated with that, allowing for very little need for synchronization

**Comment by DusterTheFirst** [comment]
Another solution could be to have the client send its VDOM over the websocket as its first message and then the server can use that to start with. This would move the burden of storing the vdom to the client, and could also be used in cases of websocket reconnection.

**Comment by imbolc** [comment]
> We need to somehow cache the app between initial request and websocket upgrade

This way an app become easily DDos-able causing out-of-memory state as each get request, even not intentionally malicious (e.g. from web crawlers), would create an vdom instance which would never be requested.

Another solutions could be:

1. passing serialized (is it hard to make it serializable) vdom to client with the initial request and then, after handshake passing it back to server through the socket (what's about safety)
2. just replacing html after handshaking without proper hydration, is it really that bad? I guess we can disable inputs and scrolling and enable them back after the replacement.

**Comment by Demonthos** [comment]
> > We need to somehow cache the app between initial request and websocket upgrade
> 
> This way an app become easily DDos-able causing out-of-memory state as each get request, even not intentionally malicious (e.g. from web crawlers), would create an vdom instance which would never be requested.

We could cache the VDom based on the root props, and set a maximum size for the cache. If the VDom is not found in the cache, we can either give up or re-run the initial render like we do for web hydration to get to the same state.

> Another solutions could be:
> 
> 1. passing serialized (is it hard to make it serializable) vdom to client with the initial request and then, after handshake passing it back to server through the socket (what's about safety)

Making the VDom serializable would require every hook that is passed into the vdom to implement serialize (as well as the internals) which is not possible for many types. In addition to that some types like event handlers you pass in as closures will never be serializable

> 2. just replacing html after handshaking without proper hydration, is it really that bad? I guess we can disable inputs and scrolling and enable them back after the replacement.

Hydration is a lot quicker than re-rendering the whole page, and prevents the issues you mentioned entirely, but you could probably roll your own solution that re-renders the whole page right now.

**Comment by imbolc** [comment]
> We could cache the VDom based on the root props

I guess it would put additional requirements on the props to be hashable. In case of liveview it's especially painful as props could be anything from your server side api.

> re-run the initial render like we do for web hydration to get to the same state

I didn't know that hydration works this way, wouldn't this lead to bugs if the state is changed between requests? That was my reason to suggest re-rendering.

**Comment by jkelleyrtp** [comment]
We're going to drop liveview eventually and instead move to a data-channels type approach using fullstack, so this won't be planned.
