### ISSUE TITLE
Can't use file system in image src

### ISSUE THREAD

**Issue by DasLixou** [DioxusLabs/dioxus#687]
**Problem**

I have a image on my drive and i can't load it in a image tag.

**Steps To Reproduce**

- Create a file `/tmp/book_cover-code.google.com.epub-samples.linear-algebra.png`

```rust
rsx! {
    img {
        src: "/tmp/book_cover-code.google.com.epub-samples.linear-algebra.png" // or "file:///tmp/book_cover-code.google.com.epub-samples.linear-algebra.png"
    }
}
```

it doesn't display the image and says:

![grafik](https://user-images.githubusercontent.com/82600264/209857490-8f4ac757-86a0-40c7-8577-82e75d98de86.png)

**Expected behavior**

Display the image

**Screenshots**

It shows:
![grafik](https://user-images.githubusercontent.com/82600264/209857641-071dc36f-a53c-48bc-b277-57c24f56c074.png)

**Comment by DasLixou** [comment]
I currently have a workaround: using `base64` and just converting it to a base64 and putting `data:image/png;base64,` before.

**Comment by jkelleyrtp** [comment]
This is because we're explicitly returning forbidden for images not contained within the app.

https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/protocol.rs#L76-L81

I think we can just lift this limitation.
