### ISSUE TITLE
cant compile a simple dioxus example for android

### ISSUE THREAD

**Issue by alexzanderr** [DioxusLabs/dioxus#688]
# cant build a simple dioxus example for android

hello

first of all, having this `dioxus = { version = "*", features = ["mobile"] }` inside `Cargo.toml`, doesnt work at all and these errors are showed
```shell
error: failed to select a version for `dioxus`.
    ... required by package `dioxus-example v0.1.0 (path)`
versions that meet the requirements `*` are: 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.0

the package `dioxus-example` depends on `dioxus`, with features: `mobile` but `dioxus` does not have these features.
```

when im selecting the latest version (0.2.4) this error happens: no such feature, mobile:
```shell
error: failed to select a version for `dioxus`.
    ... required by package `dioxus-example v0.1.0 (path)`
versions that meet the requirements `^0.2.4` are: 0.2.4

the package `dioxus-example` depends on `dioxus`, with features: `mobile` but `dioxus` does not have these features.
```

then i looked in the IOS example on the examples-projects repo and i replaced the version with the one from the example: `dioxus = { features = ["mobile"], version = "0.1.8" }
`

still getting the same error:
```
error: failed to select a version for `dioxus`.
    ... required by package `dioxus-example v0.1.0 ()`
versions that meet the requirements `^0.1.8` are: 0.1.8

the package `dioxus-example` depends on `dioxus`, with features: `mobile` but `dioxus` does not have these features.
```

ok, after keeping only dioxus with desktop feature (`dioxus = { version = "0.2.4", features = ["desktop"] }
`) the app runs on native very well, but when trying to compile for android doesnt work:
```shell
error[E0433]: failed to resolve: use of undeclared type `WebContextImpl`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.13.3/src/webview/web_context.rs:40:14
   |
40 |     let os = WebContextImpl::new(&data);
   |              ^^^^^^^^^^^^^^ use of undeclared type `WebContextImpl`

error[E0433]: failed to resolve: use of undeclared type `WebContextImpl`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.13.3/src/webview/web_context.rs:61:14
   |
61 |     let os = WebContextImpl::new(&data);
   |              ^^^^^^^^^^^^^^ use of undeclared type `WebContextImpl`

error[E0433]: failed to resolve: use of undeclared type `InnerWebView`
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.13.3/src/webview/mod.rs:309:19
    |
309 |     let webview = InnerWebView::new(window.clone(), self.webview, self.web_context)?;
    |                   ^^^^^^^^^^^^ use of undeclared type `InnerWebView`

error[E0412]: cannot find type `WebContextImpl` in this scope
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.13.3/src/webview/web_context.rs:29:18
   |
29 |   pub(crate) os: WebContextImpl,
   |                  ^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `InnerWebView` in this scope
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.13.3/src/webview/mod.rs:322:12
    |
322 |   webview: InnerWebView,
    |            ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `platform_webview_version` in this scope
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.13.3/src/webview/mod.rs:431:3
    |
431 |   platform_webview_version()
    |   ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

```
desktop feature because dioxus said mobile just reexports desktop so basically is the same, without desktop feature nothing really works

`WebContextImpl` and `InnerWebView` do exist in the codebase of wry crate, but they are imported based on cfg features and there is no `android` as target_os feature. seems like wry wont compile for android ...

what is happening? what am i missing? i just want to run the simplest dioxus example on android.

dioxus team said: only ios is supported by default, but for android  follow the `cargo-mobile` guide ( so i thought there would be a workaround), after i went and searched there is no dioxus example/workaround for android

what i've discovered so far:
- the docs are wrong or seem to be wrong, there is no feature `mobile`, not even in the oldest version of dioxus
- there is a crate `dioxus_mobile v0.0.3` which doesnt work and cant be used with `dioxus --features desktop` in the same crate because of this error: 
```shell
error: failed to select a version for `webkit2gtk-sys`.
    ... required by package `wry v0.13.1`
    ... which satisfies dependency `wry = "^0.13.1"` of package `dioxus-desktop v0.2.3`
    ... which satisfies dependency `dioxus-desktop = "^0.2.3"` of package `dioxus v0.2.4`
    ... which satisfies dependency `dioxus = "^0.2.4"` (locked to 0.2.4) of package `dioxus-example v0.1.0 (path)`
versions that meet the requirements `^0.17` are: 0.17.0

the package `webkit2gtk-sys` links to the native library `web_kit2`, but it conflicts with a previous package which links to `web_kit2` as well:
package `webkit2gtk-sys v0.14.0`
    ... which satisfies dependency `ffi = "^0.14"` (locked to 0.14.0) of package `webkit2gtk v0.14.0`
    ... which satisfies dependency `webkit2gtk = "^0.14"` (locked to 0.14.0) of package `wry v0.12.2`
    ... which satisfies dependency `wry = "^0.12.2"` (locked to 0.12.2) of package `dioxus-desktop v0.1.6`
    ... which satisfies dependency `dioxus-desktop = "^0.1.5"` (locked to 0.1.6) of package `dioxus-mobile v0.0.3`
    ... which satisfies dependency `dioxus-mobile = "^0.0.3"` (locked to 0.0.3) of package `dioxus-example v0.1.0 (path)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='webkit2gtk-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `webkit2gtk-sys` which could resolve this conflict
```
some dependency conflict, anyway if you use `dioxus_mobile` just with `dioxus` no-features the project wont compile because of wry errors which are the same as the above ones (some struct that is imported behind a feature and for android target os its not imported)

- there is no single smallest and simplest example possible with dioxus UI that is actually working for android
- this example from `https://dioxuslabs.com/reference/mobile/` is really outdated or wrong and doesnt work

## to reproduce the simplest example for android
the project is made with cargo mobile init, but winit replaced with dioxus

### cargo.toml
```toml
[package]
name = "dioxus-example"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "dioxus-example-desktop"
path = "gen/bin/desktop.rs"

[dependencies]
mobile-entry-point = "0.1.0"
dioxus = { version = "0.2.4", features = ["desktop"] }



[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.9.0"
log = "0.4.11"
ndk-glue = "0.2.1"

[target.'cfg(not(target_os = "android"))'.dependencies]
simple_logger = "1.11.0"
```

### lib.rs
```rust
use dioxus::prelude::*;
use mobile_entry_point::mobile_entry_point;

#[mobile_entry_point]
pub fn main() {
    dioxus::desktop::launch(app);
}

pub fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "hello world!"
        }
    })
}
```

### specs
```shell
❱  cargo -Vv
cargo 1.65.0-nightly (6da726708 2022-08-23)
release: 1.65.0-nightly
commit-hash: 6da726708a4406f31f996d813790818dce837161
commit-date: 2022-08-23
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Manjaro 21.3.6 (Ruah) [64-bit]

```

```shell
❱  rustc -vV
rustc 1.65.0-nightly (eaadb8947 2022-08-27)
binary: rustc
commit-hash: eaadb8947b850a025404082f6297766c4680a42a
commit-date: 2022-08-27
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0

```

```shell
❱  cargo mobile --version
cargo-mobile v0.1.0
Contains commits up to "Add pod-options to platform config (#102)"

❱  cargo android --version
cargo-android v0.1.0
Contains commits up to "Add pod-options to platform config (#102)"
```

```shell
❱  echo $NDK_HOME/
~/Android/SDK/ndk/22.1.7171670/
```

```shell
❱  echo $ANDROID_SDK_ROOT
~/Android/SDK
```

```shell
❱  neofetch --json
{
    "OS": "Manjaro Linux x86_64",
    "Kernel": "5.15.57-2-MANJARO",
    "Shell": "zsh 5.9",
    "DE": "Xfce 4.16",
    "WM": "Xfwm4",
    "CPU": "Intel i7-7700HQ (8) @ 3.800GHz",
    "GPU": "Intel  HD Graphics 630",
    "GPU": "NVIDIA GeForce GTX 1050 Mobile",
    "GPU": "NVIDIA GeForce GTX 1050 Mobile",
    "Memory": "7037MiB / 15884MiB",
}
```

also, i have NDK under 23, as specified in the cargo mobile readme

note: the simplest winit example is working for me on android, but the dioxus one is not, so its not a system related problem

the problem is: the compilation of the dioxus project for android target_os

i hope someone is willing to help

thanks in advance!

**Comment by jkelleyrtp** [comment]
Since its release, Dioxus mobile supported iOS only. In master we should have support for android since wry/tao has been updated.

Can you try running the latest version of master and see if you can get things working? We're just about to cut the next version, so you shouldn't have to wait too long.

**Comment by dvc94ch** [comment]
To get wry working on android you need to setup quite a few things. Simplest way is to let xbuild take care of it for you if you don't want to mess around with gradle. `cargo install xbuild && x new example` should get you started. You need to set wry: true, gradle: true in manifest.yaml for xbuild to work.

**Comment by alexzanderr** [comment]
> Can you try running the latest version of master and see if you can get things working? We're just about to cut the next version, so you shouldn't have to wait too long.

you mean to have this in cargo toml? :
```toml
dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["desktop"] }
```

**Comment by alexzanderr** [comment]
ok so, i've cloned the repo and added as local dep:
```toml
dioxus-mobile = { path = "./dioxus_latest/packages/mobile" }
dioxus = { path = "./dioxus_latest/packages/dioxus" }
```
and the compilation is success and also `cargo android check` is success, but after deploying the app to phone, it prints just a black screen.

on linux its printing the `hello world` message, but on the phone not.

(the `cargo-mobile` method doesnt work till the end)

anyway, i've (tried your suggestions):
- installed `cargo-xbuild`
- ran `x new project-name`
- ran `cargo run` in the project (its working on desktop native linux)
- ran `x run --device <my-phone-id>` (and its working like a charm on the phone, i do even get touch logs from the finger touch, wow)

the `cargo-xbuild` method works till the end

thanks a lot guys for the help, i've strached my head for 3 days, was so frustrating and now `it just works`

and thank you for your time
