### ISSUE TITLE
Router not working in SSR - webasm execution crashes server

### ISSUE THREAD

**Issue by mattoni** [DioxusLabs/dioxus#689]
**Problem**

I'm using SSR to build my app. When trying to add the router, everything compiles successfully, but refreshing the page causes a panic on the server.

```
thread 'tokio-runtime-worker' panicked at 'cannot call wasm-bindgen imported functions on non-wasm targets', /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.60/src/lib.rs:5520:9
```

**Steps To Reproduce**

- Create an SSR axum server that serves out a shared app rsx
- In the app rsx, use the Router component

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5110855/210002535-ebee48f4-84c2-4368-a7b7-692b0e724ed7.png)

**Environment:**
 - Dioxus version:  v0.2.4
 - Rust version: 1.65.0
 - OS info: Linux x86 64
 - App platform: `web`, `ssr`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
There are features you need to setup on the router. By default I think it chooses web, but you need to specify the right features for the platform you are targeting.

**Comment by mattoni** [comment]
Yep, that was it. Thank you.
