### ISSUE TITLE
Canvas API support?

### ISSUE THREAD

**Issue by planet0104** [DioxusLabs/dioxus#69]
Any examples of using the canvas to draw graphics?

**Comment by jkelleyrtp** [comment]
Only the Dioxus web can access the canvas directly, unfortunately. We might be able to build a shim over the canvas through RPC/FFI, or a declarative renderer for Dioxus that understands canvas (like React-Three-Fiber), but currently you can't get an imperative handle to the canvas.

**Comment by Zageron** [comment]
Does this mean in WASM I cannot get a handle to the canvas to draw to it from rust?

**Comment by John0x** [comment]
@jkelleyrtp is there any update on this or why has the issue been closed?
I'd need to be able to use the canvas for a project, that I'm currently planning

**Comment by kud1ing** [comment]
I think other Rust web frameworks don't support access to the canvas either.

What I've seen is that projects select the canvas and draw on it via `web-sys` directly.
