### ISSUE TITLE
Blank desktop applications on OS X 10.14.6

### ISSUE THREAD

**Issue by jprider63** [DioxusLabs/dioxus#699]
**Problem**

On OS X (10.14.6), desktop applications are blank. This seems similar to #215. Here's the error message from inspecting the page. I'll update my OS, but I figured you might want to know. It might make sense to display an error message to the user when this happens. 

```
[Error] Unhandled Promise Rejection: SyntaxError: Unexpected token '?'
	(anonymous function) (index.js:275)
	promiseReactionJob
```

**Steps To Reproduce**

- Run the desktop examples on OS X 10.14.6. 

**Expected behavior**

The GUI should load, not display a blank page on error.

**Environment:**
 - Dioxus version: 0.2.4
 - Rust version: 1.66.0
 - OS info: OS X 10.14.6
 - App platform: desktop

**Comment by jkelleyrtp** [comment]
Does this happen on 0.3 or master for you? I think we might've released the fix.

**Comment by jprider63** [comment]
I'm not sure. I've upgraded my OS so I can't test it anymore. I'll close this for now.
