### ISSUE TITLE
Web Hydration Example with Axum and build pipeline

### ISSUE THREAD

**Issue by Wicpar** [DioxusLabs/dioxus#705]
## Specific Demand

There is a big gap in the documentation on how to implement a properly hydrated web implementation.
Absolutely no project i found had a good implementation. All just had a loader for the wasm and none had proper pre-rendered html.

It would be nice to have a starter template that sets up a core-frontend-backend arch with out of the box dev tools.
Or maybe at least document how it is expected to be handled.
The questions:
- Should the backend handle the frontend compilation ?
- How to pre-render routes and hydrate them properly ?
 
and probably many more i'll discover.

## Implement Suggestion

I'll maybe publish a template if i find a way to get it to work nicely.

**Comment by Demonthos** [comment]
https://github.com/DioxusLabs/dioxus/pull/916 adds fullstack examples for `axum`, `salvo`, and `warp` that illustrate how server functions, ssr, and hydration work together. It also includes a example to illustrate how SSR + Hydration work with the router
