### ISSUE TITLE
exe took long to display result on win10

### ISSUE THREAD

**Issue by coolit** [DioxusLabs/dioxus#71]
After installing webview2 runtime, the demo worked. But in the demo file-explorer, it took several seconds to display the result. And the exe generated a folder called file-explorer.exe.WebView2, and there were many files inside.

**Comment by jkelleyrtp** [comment]
Thanks for the report!

I think I've fixed it.

Can you check is #84 works for you?

```
git checkout https://github.com/DioxusLabs/dioxus.git
git pull
git checkout jk/windows-lag
cargo run --example readme --features "desktop"
```

It should load immediately now.

**Comment by coolit** [comment]
I didnt use git. Instead I saved the code folder to local as E:/rust/dioxus as a local lib, and in the project cargo.toml I used
[dependencies]
dioxus = { path="E:/rust/dioxus", features = ["desktop"] }

but the result was the same, there was major lag at startup.

**Comment by jkelleyrtp** [comment]
Great! I I'll merge that PR and then try to figure out what's causing the 2/4 s. I see it too, but I'm working on windows through a VM so it's less noticeable.

**Comment by jkelleyrtp** [comment]
It looks like the webview takes a few seconds to load on Windows, and is slightly better in release mode.

I don't think there's anything we can do to make this process any faster than it already is :/
