### ISSUE TITLE
[question] how to specify window size, fullscreen and spawn alignment

### ISSUE THREAD

**Issue by alexzanderr** [DioxusLabs/dioxus#710]
hello

i want to tell dioxus to spawn the app `right-split` or left split or fullscreen or custom width and height with position specified.

how can i do that?

i didnt see something like this in the docs.

**Comment by Demonthos** [comment]
Dioxus desktop has a [launch_cfg](https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/lib.rs#L80) function that allows you to change the settings of the webview. You can use the [with_window](https://github.com/DioxusLabs/dioxus/blob/master/packages/desktop/src/cfg.rs#LL73C19-L73C19) function  along with wry's [WindowBuilder](https://docs.rs/wry/latest/wry/application/window/struct.WindowBuilder.html) to change the window size and position.

See also: [The overlay example](https://github.com/DioxusLabs/dioxus/blob/dde4fb31b2e80fbbc6aee5afe09976af47fd5c30/examples/overlay.rs#L61)

**Comment by alexzanderr** [comment]
`Ok()`, nice, i can confirm that it worked.

thanks for the response!
