### ISSUE TITLE
Support for no_std

### ISSUE THREAD

**Issue by D1plo1d** [DioxusLabs/dioxus#731]
## Specific Demand

Add no_std support so that web apps can be bundle size-optimized by not needing to include the standard lib in their wasm binaries.

## Implement Suggestion

No specific suggestions, I more wanted to get a sense of the Dioxus developers' feeling on this - whether this was possible or not and whether this is a desired direction for Dioxus.

Edit: I should say I'm assuming dioxus would still require alloc.

**Comment by Demonthos** [comment]
Dioxus uses the standard library extensively in it's virtual dom implementation so I'm not sure this would be feasible. For binary size, there are probably other ways we can reduce binary size without omitting the standard library that would make a larger difference like removing dependencies and moving optional code behind feature flags.

One thing that could be interesting to look at for reducing the binary size is statically linking the standard library: https://github.com/johnthagen/min-sized-rust#optimize-libstd-with-build-std which should allow dead code elimination for parts of the standard library that Dioxus does not use
