### ISSUE TITLE
Web bundle size optimization / wasm build best practices

### ISSUE THREAD

**Issue by D1plo1d** [DioxusLabs/dioxus#732]
According to the readme:

> Simple "hello world" at about 65kb, comparable to React

I have not been able to find any documentation on how to achieve such a small bundle size.

### My Results
I've written a simple hello world which compiles with `trunk build --release`, `lto = true`, and `opt-level="z"` down to  275 KB:

```rust
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(App);
}

fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "Hello world"
        }
    })
}
```

This is 4 times the size of the 65KB Readme bundle size. My build size also grows quite quickly to 600KB for a small single page app mockup with just a few simple pages, a router and without any IO.

What best practices are the Dioxus devs applying to get a 64KB build size?

**Comment by Demonthos** [comment]
Building using the nightly compiler, gzip, [trunk wasm opt](https://trunkrs.dev/assets/#rust), and a few tricks from [min-sized-rust](https://github.com/johnthagen/min-sized-rust) you can get the wasm size of the above app to 143 KB, which is 62 KB GZIPed: https://github.com/Demonthos/tiny-dioxus

It would be great to either link to min-sized-rust, or provide a guide on how to get binary sizes smaller for WASM specifically in the future

**Comment by D1plo1d** [comment]
I must be doing something wrong or perhaps there's still a further difference between our setups that I'm not aware of - I've cloned tiny-dioxus and built it with `trunk build --release` but I'm seeing a 205 KB wasm file in my dist directory. It's much better but not yet 143 KB for some reason.

**Comment by ealmloff** [comment]
This was documented in https://github.com/DioxusLabs/docsite/pull/132
