### ISSUE TITLE
Incorrect minimum supported rust version in dioxus 0.3.1

### ISSUE THREAD

**Issue by joeperri95** [DioxusLabs/dioxus#733]
**Problem**
The minimum supported rust version of dioxus is 1.60 but dioxus-core makes use of std::backtrace which becomes stable in 1.65

**Steps To Reproduce**
Install any version of rust between 1.60 and 1.64 and attempt to build a project using dioxus

**Expected behavior**
The project will build successfully 

**Environment:**
 - Dioxus version: [0.31]
 - Rust version: [1.64]
 - OS info: [Linux]
 - App platform: [should apply to all]

**Questionnaire**
- [*] I would like to fix and I have a solution

If there are no objections I could simply bump the msrv to 1.65. 
Alternatively the use of std::backtrace can be removed from core/src/arena.rs

**Comment by Demonthos** [comment]
Closed via #740
