### ISSUE TITLE
Update public documentation

### ISSUE THREAD

**Issue by campbellcole** [DioxusLabs/dioxus#735]
## Specific Demand

No rush, but I noticed that the documentation on the website is out of date, which caused some problems for me when starting a new project because `cargo add` added `0.3.1` and the features are not there anymore.

## Implement Suggestion

Just run your workflow for documentation whenever convenient for you.

As a side note, I made a quick repository which serves the up to date documentation locally as a quick fix for now. If anybody runs in to this problem before it is fixed, feel free to try the little script I made here:
https://github.com/campbellcole/dioxus-docs-nix

**Comment by campbellcole** [comment]
I just noticed the reference documentation is not in english yet, so I apologize for assuming it was ready to be published.

**Comment by Demonthos** [comment]
The latest docs are up on the nightly url: https://dioxuslabs.com/nightly/guide/en/
We need to bump this to stable and then update everywhere that links the /guide to /guide/en

**Comment by tiann** [comment]
Please update the docs to stable, I am confused a lot by github docs/crates.io/official website

**Comment by d4h0** [comment]
If it is going to take some time to update the docs – which would be totally fine – it would be great if someone could add a warning at the top of the outdated docs, that redirects readers to the up-to-date docs.

I just went through the outdated guide and reference that's liked from the website, and now I need to read the (updated) guide again, it seems.

Thanks to @campbellcole, for creating this issue. I was just about to start to play with Dioxus (which might have been confusing/frustrating without the information in this issue).

To end on a positive note: Dioxus looks pretty amazing so far! :)

**Comment by Demonthos** [comment]
@jkelleyrtp Any concerns about bumping the docs to stable? This shouldn't break any links this time because the docs route changes from .../guide to .../guide/en. In the future we can change the main guide route to redirect to a specific version, but it should be fine for the 0.3 release

**Comment by Demonthos** [comment]
🎉 The docs are live at https://dioxuslabs.com/docs/0.3/guide/en/!
