### ISSUE TITLE
liveview websockets tend to disconnect after inactivity

### ISSUE THREAD

**Issue by DusterTheFirst** [DioxusLabs/dioxus#738]
**Problem**

When a liveview based application is idle for a period of time ~10 minutes, the websocket tends to get disconnected. Since the websocket does not re-connect automatically, the app becomes unresponsive with the only recourse being refreshing the page.

**Steps To Reproduce**

- Use a live-view renderer for a dioxus app using axum as the web framework
- wait 10 minutes
- observe websocket disconnect

**Expected behavior**
The web socket should attempt to stay connected even across disconnects as the user experience relies on the websocket connection. The websocket should also avoid timing out through the sending of heartbeat messages to keep the websocket alive.

**Screenshots**

**Environment:**
 - Dioxus version: `0.3.1 (live-view 0.3.0)`
 - Rust version: `rustc 1.67.0-beta.2 (352eb59a4 2022-12-13)`
 - OS info: `Linux 6.0.16-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Dec 31 16:47:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - App platform: `live-view`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
Which backend framework are you using liveview with? I think the framework itself and the browser should be able to do ping/pong on its own without requiring any intervention from Diouxs.

**Comment by DusterTheFirst** [comment]
I am using axum
