### ISSUE TITLE
use_coroutine causes deadlock on android

### ISSUE THREAD

**Issue by dvc94ch** [DioxusLabs/dioxus#742]
To reproduce take a dioxus app that works on android and add the following line:
```rust
use_coroutine(cx, |_: UnboundedReceiver<()>| async { loop {} });
```
The result is that only a white background gets rendered.

Regression from https://github.com/DioxusLabs/dioxus/commit/1e99e35572f6cf4f3ae09e1d0290b6e43838518d to 0.3.1

**Comment by jkelleyrtp** [comment]
Also, you can use yield_now from futures-util to let the executor breathe.

**Comment by dvc94ch** [comment]
not sure this issue is fixed.

1. this worked fine previously
2. UseAtomRef is not Send
3. this is only a minimal repro case which I didn't realize breaks desktop, but this bug is android specific

**Comment by dvc94ch** [comment]
actually, seems like it isn't the use_coroutine that causes the deadlock, but `UseAtomRef::write`.
