### ISSUE TITLE
format rsx using rustfmt

### ISSUE THREAD

**Issue by dvc94ch** [DioxusLabs/dioxus#747]
Opened an issue here https://github.com/rust-lang/rustfmt/issues/5656, although the P-low label doesn't give me much confidence that it will be implemented soon. Thought it might be of interest, feel free to close, since there is nothing immediately actionable.

**Comment by Demonthos** [comment]
There are a few long standing issues related to formatting macros in rustfmt (https://github.com/rust-lang/rustfmt/issues/3705, https://github.com/rust-lang/rustfmt/issues/5254). This would be great!... but I don't expect it to be implemented for a while if it ever is. I think there was another issue where this was specifically not planed which is why Dioxus autofmt was created instead of a more general solution, but I can't find it now

**Comment by dvc94ch** [comment]
alternatively could autofmt be turned into a cli tool called rsxfmt? so in ci I could run rsxfmt && rustfmt. would also fit my workflow better to have a standalone tool, as I don't use vscode.

**Comment by paultiplady** [comment]
This is timely; I'm just starting exploring Dioxus (fairly new to Rust) and this is an immediately obvious issue with the Rust toolchain vs. the standard modern JSX experience.

My dream solution would be something that can be tied into the IDE autocomplete functionality as well as just providing auto-formatting.

**Comment by jkelleyrtp** [comment]
The dioxus CLI tool has a `fmt` command used by the CLI to format individual pieces of rsx. We could/should change the default behavior of `dioxus fmt` to format your project in the same way that rustfmt does.

**Comment by jkelleyrtp** [comment]
> @jkelleyrtp is there any guide/doc how to use it? My `dioxus-cli` unfortunatelly doesn't seem to have `fmt` command.
> 
> ```
> → dioxus fmt
> error: Found argument 'fmt' which wasn't expected, or isn't valid in this context
> ```

Dioxus fmt is in the most recent version of the CLI (0.3).You might need to update using `cargo install --force dioxus-cli`.

**Comment by jkelleyrtp** [comment]
I just put up a draft PR on the CLI tool that enables project autoformatting. I have yet to enable mod descending, but right now it uses .gitignore. It also queues all the files in an async stream so tokio will naturally multithread the formatting process.

https://github.com/DioxusLabs/cli/pull/92

**Comment by jkelleyrtp** [comment]
We can't really do anything about this without rustfmt adding hooks, so, use `dioxus fmt`
