### ISSUE TITLE
Disable reload context menu

### ISSUE THREAD

**Issue by UARTman** [DioxusLabs/dioxus#75]
Running a basic "Hello World" app in Linux I notices a bunch of strange stuff going on:

- Multiple-second load times for the content after the window is initialized (might be inherent to platform, not sure if can be fixed)
- Weird menus: App has two menus in the menubar: "First menu" and "Second menu". First menu gives a number of options like "About App", "Quit", etc., but they do nothing. Second menu creates a strange blank menu that has low width and big height.
- Right-clicking in the window shows a menu with greyed out "Forward", "Stop", and "Backward", as well as working "Reload" and "Inspect Element". Hitting reload breaks the app.

The menus might be intended, but reload breaking stuff is clearly not.

**Comment by jkelleyrtp** [comment]
Thanks for the report!

- I've identified why 1) is happening - GTK/Windows don't receive a MainEventsCleared on startup.
- Menus are a result of poor config merging, this is sorted out in the master branch
- The context menu on right-click is a result of the platform/Tao (not inserted by us) and should be disabled in release mode of your app. I know the inspect menu goes away in release menu. Forward/back is the result of poor config merging.

The one thing I don't exactly know how to fix is reloading the page, so I think we need to override that manually.

<img width="823" alt="Screen Shot 2022-01-07 at 1 16 03 AM" src="https://user-images.githubusercontent.com/10237910/148500645-4dc7840e-64d5-4340-8477-98f8044c6c22.png">

**Comment by jkelleyrtp** [comment]
> Running a basic "Hello World" app in Linux I notices a bunch of strange stuff going on:
> 
> * Multiple-second load times for the content after the window is initialized (might be inherent to platform, not sure if can be fixed)
> * Weird menus: App has two menus in the menubar: "First menu" and "Second menu". First menu gives a number of options like "About App", "Quit", etc., but they do nothing. Second menu creates a strange blank menu that has low width and big height.
> * Right-clicking in the window shows a menu with greyed out "Forward", "Stop", and "Backward", as well as working "Reload" and "Inspect Element". Hitting reload breaks the app.
> 
> The menus might be intended, but reload breaking stuff is clearly not.

Can you check is #84 works for you?

```
git checkout https://github.com/DioxusLabs/dioxus.git
git pull
git checkout jk/windows-lag
cargo run --example readme --features "desktop"
```

It should load immediately now.

**Comment by UARTman** [comment]
> Can you check is #84 works for you with respect to startup lag?

It does, now there is no lag between starting up the WebView and displaying the app.

> - Menus are a result of poor config merging, this is sorted out in the master branch
> - The context menu on right-click is a result of the platform/Tao (not inserted by us) and should be disabled in release mode of your app. I know the inspect menu goes away in release menu. Forward/back is the result of poor config merging.

This is great news! 

> The one thing I don't exactly know how to fix is reloading the page, so I think we need to override that manually.

Then I think we should probably rename the issue and keep it open until this particular quirk is resolved.

Anyway, thank you for the prompt answer and for writing this library in general. I'm looking forward to using it, and potentially even contributing when I have more free time.

**Comment by jkelleyrtp** [comment]
Reload context menu is now disabled in production apps. We don't have a way of customizing the context menu, so it functionally serves no purpose in desktop apps beyond the default actions for things like selected text.

This functionality can be enabled/disabled through the cfg.
