### ISSUE TITLE
Project Showcase

### ISSUE THREAD

**Issue by Adrian-Blandin** [DioxusLabs/dioxus#756]
Could we open and pin an issue to showcase some real projects built with Dioxus?

The idea is copied from the following Iced's issue: https://github.com/iced-rs/iced/issues/355

This would allow people to quickly see what is possible with Dioxus through images and videos, and with links to the repositories, they could also see the code that was used to create them.

This is very useful when someone wants to decide between Rust frameworks, without having to try building some test applications and running examples themselves.

Note: I also like the way examples are presented in Iced, i.e. in a folder with a README.md and a video (e.g.: https://github.com/iced-rs/iced/tree/master/examples/styling)

**Comment by arqalite** [comment]
That would be great - especially to see how other devs handle situations that aren't mentioned in the documentation or sample projects.

I guess to get things started, I could also shamelessly self-plug my own Dioxus app, Rummy Nights - a dumb little project to make my boyfriend and I's games of rummy a little easier: https://github.com/arqalite/rummy-nights

**Comment by Adrian-Blandin** [comment]
Since no one on the project answered, I plan to close this issue soon in order to not clutter the issues.
I still hope that an official place to showcase what can be achieved with Dioxus will be provided, but I understand that this may not be a top priority right now.

**Comment by Demonthos** [comment]
We have a few different places to share project you have built:
1) For libraries and templates: https://github.com/DioxusLabs/awesome-dioxus
2) For projects you have built with Dioxus: [I made a thing channel in discord](https://discord.com/channels/899851952891002890/943190901159768136)

If we move from the discord channel to Github it could be more visible to anyone new to the project. We could also link to the issue at the end of the guide. Discord allows threads which makes it much nicer to discuss projects in an organized way.

**Comment by Adrian-Blandin** [comment]
For anyone who stumbles upon this issue: to access the [channel #i-made-a-thing](https://discord.com/channels/899851952891002890/943190901159768136) on Discord, you may need to first join the [Dioxus Labs server](https://discord.gg/XgGxMSkvUM) referenced on the [website](https://dioxuslabs.com/).

**Comment by ealmloff** [comment]
This is being added to the website here: https://github.com/DioxusLabs/docsite/pull/142!
