### ISSUE TITLE
Window.scroll for desktop

### ISSUE THREAD

**Issue by kurotych** [DioxusLabs/dioxus#768]
Is there any way to do [scroll](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll) programmatically for Desktop (Linux)? 

There is [MouseWheel](https://github.com/tauri-apps/tao/blob/dev/src/event.rs#L419) event in tao. Maybe I need somehow to construct this event and send to tao through window proxy?

```rust
    let window = use_window(cx);
    window.proxy.send_event(...)
```

**Comment by Demonthos** [comment]
You can use the [use_eval](https://docs.rs/dioxus-desktop/latest/dioxus_desktop/fn.use_eval.html) hook and run `eval(format!("window.scroll({x}, {y})"))`

**Comment by kurotych** [comment]
Thank you! It looks like what I need
