### ISSUE TITLE
component event bind failed

### ISSUE THREAD

**Issue by mrxiaozhuox** [DioxusLabs/dioxus#77]
In the docs, the event handler bind like:

```rust
#[derive(Props)]
struct ClickableProps<'a> {
    onclick: EventHandler<'a, MouseEvent>
}

fn clickable(cx: Scope<ClickableProps>) -> Element {
    cx.render(rsx!(
        a { 
            onclick: move |evt| cx.props.onclick.call(evt)
        }
    ))
}
```
But in the current version, the `EventHandler` don't need the second arg: `MouseEvent`, and the `evt` type is `UiEvent<MouseData>` but the `onclick.call` must be have the type of `AnyEvent`.

**Comment by jkelleyrtp** [comment]
Ah - this is an upcoming feature that has slipped into the Docs too early.

Thanks for reporting this - we'll get the feature in ASAP.

**Comment by mrxiaozhuox** [comment]
so, is there any demo can help me to create a `event` ?

thank you!

**Comment by jkelleyrtp** [comment]
> so, is there any demo can help me to create a `event` ?
> 
> thank you!

Hi! 

I've actually added the feature to support the EventHandler syntax as shown in the docs.

Once the tests pass we can merge it in.
