### ISSUE TITLE
Documentation is incorrect for building hello-world desktop app

### ISSUE THREAD

**Issue by nishraptor** [DioxusLabs/dioxus#773]
**Problem**

The documentation is incorrect for building the hello-world desktop app. 

**Steps To Reproduce**

- Follow the hello-world tutorial

**Expected behavior**

The dioxus app should compile and run normally. This is because the dioxus-desktop app is not added with cargo add. Additionally, the dioxus::desktop::launch needs to be changed to dioxus_desktop::launch

**Screenshots**

**Environment:**
 - Dioxus version: 0.3.1
 - OS info: Windows
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by d4h0** [comment]
This was already reported in https://github.com/DioxusLabs/dioxus/issues/735.

There was a recent update, but the docs on the website were not updated, yet.

You can find the updated guide at https://dioxuslabs.com/nightly/guide/en/
