### ISSUE TITLE
Dependency injection pattern

### ISSUE THREAD

**Issue by wackazong** [DioxusLabs/dioxus#784]
How would you recommend to re-use services via dependency injection? Suppose I have a pooled network client that I want to instantiate only once. For testing it would be nice to be able to define it in the context. How would you do that? I imagine you would wrap the client into an `Arc` and a `Mutex` and then somehow inject it into the global context?

**Comment by Demonthos** [comment]
Depending on if you want that value to hook into the reactive system or not you can use [fermi](https://github.com/DioxusLabs/dioxus/tree/master/packages/fermi) (which is still a WIP) or [OnceCell](https://docs.rs/once_cell/latest/once_cell/index.html)
