### ISSUE TITLE
`cargo add dioxus --features web` would return `error: unrecognized features: ["web"]`

### ISSUE THREAD

**Issue by Firfi** [DioxusLabs/dioxus#785]
**Problem**

According to https://dioxuslabs.com/reference/web/#tooling paragraph, I should be able to run `cargo add dioxus --features web` 

**Steps To Reproduce**

- create an empty Rust project with cargo init
- run `cargo add dioxus --features web`

**Expected behavior**

No error

**Screenshots**

```
cargo add dioxus --features web

    Updating crates.io index
      Adding dioxus v0.3.1 to dependencies.
             Features:
             + dioxus-core-macro
             + dioxus-hooks
             + dioxus-html
             + dioxus-rsx
             + hooks
             + html
             + macro
             + web
error: unrecognized features: ["web"]
```

**Environment:**
 - Dioxus version: 0.3.1
 - Rust version: 1.64.0
 - OS info: OSX
 - App platform: Desktop

**Comment by Firfi** [comment]
Bumped Rustc to 1.66.1 issue persists

**Comment by Demonthos** [comment]
The reference has been combined with the guide. See here for the updated web guide: https://dioxuslabs.com/nightly/guide/en/getting_started/web.html

**Comment by jessezwd** [comment]
got an error:
[INFO] 📖 Start to init plugin library ...
[ERROR] 🚫 Plugin system initialization failed: No such file or directory (os error 2)

**Comment by Demonthos** [comment]
> according to nightly guide, got an error:
> [INFO] 📖 Start to init plugin library ...
> [ERROR] 🚫 Plugin system initialization failed: No such file or directory (os error 2)

See this issue: https://github.com/DioxusLabs/cli/issues/93
