### ISSUE TITLE
Access to raw web_sys::Event

### ISSUE THREAD

**Issue by theduke** [DioxusLabs/dioxus#793]
Is there a way to get access to a raw web_sys::Event?

My concrete need is that I need to work with files in the browser, and the API provided by `FileEngine` is way too limited.

**Comment by jkelleyrtp** [comment]
Not yet, but I'm working on a change that will add this to be released in the next bump of Dioxus.

**Comment by gbj** [comment]
Duplicate of #93 if it’s helpful to know — always feels good to close two issues at once!

**Comment by ealmloff** [comment]
done in https://github.com/DioxusLabs/dioxus/pull/1402
