### ISSUE TITLE
How to support framebuffer show gui, Embedded Linux is usually low in performance, and there is no way to use X11.

### ISSUE THREAD

**Issue by zhang-wenchao** [DioxusLabs/dioxus#799]
I am trying to use dioxus on an embedded system with 32M RAM and 128M ROM. there is no way to install x11 on the embedded system, usually only framebuffer is available. Is there a way to bypass x11 or VM and display it directly through framebuffer?

**Comment by Demonthos** [comment]
Dioxus does not currently support embedded devices (and does not support no std enviorments). The main desktop renderer relies on the system's webview.

This could potentially be supported in the future in native renderers like [freya](https://github.com/marc2332/freya) or [blitz](https://github.com/DioxusLabs/blitz) that do not rely on a webview

**Comment by zhang-wenchao** [comment]
Embedded Linux is a complete Linux, and it can even include WebView, just because resource restrictions cannot use X11 and other WMs. I'm looking for a way to display it directly.

**Comment by jkelleyrtp** [comment]
We rely on wry/tao which need a lot more "system" to work. 

https://webkitgtk.org is a flag available on tao/wry that might work for some embedded devices but not one with 32M RAM.

**Comment by zhang-wenchao** [comment]
I have successfully operated on a RISC-V SBC with a 64M memory, and via TinyDRM + Weston Composition + SPI Display.
