### ISSUE TITLE
use_ref and write() causes an infinite loop

### ISSUE THREAD

**Issue by kurotych** [DioxusLabs/dioxus#801]
**Problem**

Code that looks quite legal causes an infinite loop 

**Steps To Reproduce**

```rust
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

struct Content {
    content: Option<String>,
}

impl Content {
    fn new() -> Self {
        Content {
            content: Some("".to_string()),
        }
    }
}

fn app(cx: Scope) -> Element {
    println!("Here we go again");
    let contentState = use_ref(cx, Content::new);
    contentState.write().content = Some("Oh ho".to_string());
    cx.render(rsx!{
        contentState.read().content.as_ref().map(|err| {
            rsx! {
                div {
                    content: "{err}"
                }
            }
        })
    })
}
```

**Expected behavior**

Don't fall into an infinite loop 

**Screenshots**

![image](https://user-images.githubusercontent.com/20345096/215203126-d9ac7c85-4956-4185-bd91-40c53084e60c.png)

**Environment:**
 - Dioxus version: master
 - Rust version: 1.65.0 (897e37553 2022-11-02)
 - OS info: Linux
 - App platform: desktop

**Questionnaire**

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
The write function causes the component to rerender. If you rerender the component unconditionally, it will cause an infinite loop.

See also: https://dioxuslabs.com/nightly/guide/en/best_practices/antipatterns.html#avoid-updating-state-during-render

**Comment by kurotych** [comment]
Hello @Demonthos and thank you for your answer. 

Is there a way to prevent this situation by compiler error or panic in runtime?
If there is no way to improve the current trap ticket can be closed.

**Comment by Demonthos** [comment]
I don't think there is any good way of detecting if the write function is called only a finite number of time or infinitely. (It is the halting problem)
