### ISSUE TITLE
use_eval with scrolling after component is rendered 

### ISSUE THREAD

**Issue by kurotych** [DioxusLabs/dioxus#804]
## Specific Demand

I want to execute eval each time after the component is rendered (I want to make scroll to a particular object) 
In the code below scrolling doesn't work. I think because eval executes before HTML is rendered. 

Looks like it's not implemented https://github.com/DioxusLabs/dioxus/issues/631 https://github.com/DioxusLabs/dioxus/issues/517 but maybe you can suggest me any better workaround that I have? 
Because I've found nothing better than just sleeping in the "Component" function  

```rust
    let eval = dioxus_desktop::use_eval(cx);
    let res = cx.render(rsx! {
        div {
            dangerous_inner_html: "{html}"
        }
    });
    eval(JsScroll.to_string()); // document.querySelector(...).scrollIntoView({behavior: 'smooth'})
    res
```

### Workaround 1
```rust
    static JsScroll: &str = r#"
      setTimeout(function(){
      document.querySelector(`[data-sourcepos='138:1-138:14']`).scrollIntoView({behavior: 'smooth'})
      }, 100);
    "#;

    let eval = dioxus_desktop::use_eval(cx);
    let res = cx.render(rsx! {
        div {
            dangerous_inner_html: "{html}"
        }
    });
    eval(JsScroll.to_string());
    res
```
 
### Workaround 2 
I use `use_effect` where I "update" Component with the same value, it triggers "Component function" again and scrolling (eval call) works a second time as expected  

```rust
static MARKDOWN_CONTENT: Atom<String> = |_| "".to_string();
static JsScroll2: &str = r#"
document.querySelector(`[data-sourcepos='138:1-138:14']`).scrollIntoView({behavior: 'smooth'})
"#;
#[inline_props]
pub fn Markdown(cx: Scope<'a>) -> Element {
    let con = use_read(cx, MARKDOWN_CONTENT);
    let setContent = use_set(cx, MARKDOWN_CONTENT).clone();

    use_effect(cx, con, |con| async move {
        setContent(con);
    });

    let parser = &mut markdown_it::MarkdownIt::new();

    let html = parser.parse(con).render();
    let eval = dioxus_desktop::use_eval(cx);
    let res = cx.render(rsx! {
        div {
            dangerous_inner_html: "{html}"
        }
    });
    eval(JsScroll2.to_string());
    res
}
```

**Comment by terhechte** [comment]
I think you can just use push_future. From the docs:

> Pushes the future onto the poll queue to be polled after the component renders.
 https://github.com/DioxusLabs/dioxus/blob/d521da1991719760e271457dfe4f9ddf281afbb3/packages/core/src/scopes.rs#L413

``` rs
    let eval = dioxus_desktop::use_eval(cx).clone();
    cx.push_future(async move {
        eval("document.write('hello');".to_string());
    });
```

**Comment by kurotych** [comment]
Yeap! Exactly what I need. Thank you,  @terhechte

I didn't find it in the documentation because it mentioned only once and in another context 

>  Futures are Rust's version of promises that can execute asynchronous work by an efficient polling system. We can submit new futures to Dioxus either through **push_future** which returns a TaskId or with spawn.


And I can't find the `push_future` description in docs/guide* maybe there is someplace to mention the description of this feature with the words "after the component renders."

P.S. Issue can be closed
