### ISSUE TITLE
Yew started to support SSR

### ISSUE THREAD

**Issue by Madoshakalaka** [DioxusLabs/dioxus#81]
https://github.com/yewstack/yew/pull/2335

So the comparison in README needs to update :D

**Comment by jkelleyrtp** [comment]
> [yewstack/yew#2335](https://github.com/yewstack/yew/pull/2335)
> 
> So the comparison in README needs to update :D

Huzzah! Funny enough - I started working on Dioxus after trying to integrate SSR with Yew and failing.

It looks like their SSR supports suspense - but ours does not (yet).

Anyways, I'll leave this issue open until that PR is merged. If you want to subscribe and then ping this thread again we can update the README once their PR is merged.

**Comment by jkelleyrtp** [comment]
> merged 😎

Updated the readme!
