### ISSUE TITLE
File drag and drop support

### ISSUE THREAD

**Issue by higumachan** [DioxusLabs/dioxus#83]
Thank you very much for making such a wonderful crate.

Does dioxus support `<input type="file">`?

From what little research I've done, `dioxus-desktop` and others don't seem to support it.

--- 

My idea is to handle `wry::WebViewBuilder::with_file_drop_handler` properly and create `dioxus` own events to handle it.

**Comment by jkelleyrtp** [comment]
No - but it's easy to add support for that. 

We need to expose more of the webview configuration through desktop. I'll add this in the next release (0.1.7)

**Comment by higumachan** [comment]
Thank you for very quick response.

This is the change I was looking for.
I'll wait for the next release with pleasure.

Is it better to close this issue?
Or should I leave it until the next release resolves it?

**Comment by jkelleyrtp** [comment]
We'll leave it open until the next release is out. Maybe another day or two?

**Comment by higumachan** [comment]
Wow, I surprised for very quick release. (I thought I would have to wait for about 1~2 weeks.)

**Comment by jkelleyrtp** [comment]
Support is added in #95 but I'm not done making it ergonomic.

**Comment by higumachan** [comment]
Thanks! I will try this feature.

**Comment by jkelleyrtp** [comment]
#95 has been merged!
