### ISSUE TITLE
"Get Started" button on main website does not work.

### ISSUE THREAD

**Issue by dev-callum-hopkins** [DioxusLabs/dioxus#833]
**Problem**

When pressing the "Get started" button on the main website, I am redirected to /guide which results in a 404 error.

**Steps To Reproduce**

- Navigate to https://dioxuslabs.com/
- Press "Get started"

**Expected behavior**

The user should be taken to https://dioxuslabs.com/docs/0.3/guide/en/

**Screenshots**

**Environment:**
 - Dioxus version: N/A
 - Rust version: N/A
 - OS info: Fedora Linux 37
 - App platform: web

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
https://github.com/DioxusLabs/docsite/pull/56 fixes this
