### ISSUE TITLE
Can't get hot reload to work on the web

### ISSUE THREAD

**Issue by norbertkeri** [DioxusLabs/dioxus#849]
**Problem**

Hot reload does not seem to work, the content in my browser never updates, even if I do a manual refresh, I still see the old content. If I force a full recompilation by changing rust code, the browser correctly updates.

I see no network requests made by the browser, and I see no errrors in the browser console.

**Steps To Reproduce**

```sh
cd /tmp
cargo init mything
cd mything
dioxus create frontend
cd frontend
dioxus serve --hot-reload
```

I see:
```
Dioxus @ v0.1.5 [16:44:58] 

	> Local : http://localhost:8080/
	> NetWork : http://192.168.1.100:8080/

	> Profile : Debug
	> Hot Reload : RSX
	> Index Template : Default
	> URL Rewrite [index_on_404] : False

	> Build Time Use : 12233 millis

[INFO] A perfect compilation!

[INFO] 🔥 Hot Reload WebSocket connected
[INFO] 🔮 Finding updates since last compile...
[INFO] finished
```

Then I open the browser at localhost:8080, and change the line in src/main.rs:

```rust
// from:
  p { "Dioxus is a portable, performant, and ergonomic framework for building cross-platform user interfaces in Rust." }
// to:
  p { "Hello world" }
```

The console prints a line saying:

```
[INFO] 🪁 reloading rsx
```

**Expected behavior**

The browser updates without a manual refresh.

**Environment:**
```
dioxus 0.3.2
dioxus-web 0.3.1
rustc 1.67.0 (fc594f156 2023-01-24)
arch linux
```

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
The issue here seems to be related to the template id in the CLI and macro not matching. The [file](https://doc.rust-lang.org/std/macro.file.html) macro outputs the file including the crate directory when it is in a workspace, but excludes it when the package is not in a workspace. The CLI assumes that the id always does not include the crate directory

**Comment by Demonthos** [comment]
The published version of the cli uses the old protocol for hot reloading. The git version has the new protocol, we just need to create a new release.

If you install the cli from the [git version](https://github.com/DioxusLabs/cli#install-from-git-repository), I think this issue should be fixed

**Comment by norbertkeri** [comment]
Thank you, you are correct, it works if I compile it from git.
