### ISSUE TITLE
Need for synchronous PreventDefault across Tao/Wry boundary

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#85]
Unfortunately, there's no way today to conditionally call PreventDefault across the Tao/Wry boundary.

Developers should be able to disable default in a way that's not just hardcoded fields - IE allowing default behavior when right-clicking links in the browser.

The FFI boundary is particularly challenging because we cannot synchronously handle the event.

I *think* the solution is to *always* trap the event and prevent default.

Then, ff 1) the event has default behavior and 2) the user didn't prevent that default behavior in their Dioxus handler, then we should craft the event again and push it back in the real dom.

**Comment by valyagolev** [comment]
> we should craft the event again and push it back in the real dom.

from my (maybe flawed) testing in the chrome console, synthetic events still manage to have a different behaviour:

```
(function(a) {
    document.body.appendChild(a);
    //a.setAttribute('href', 'https://github.com');
    a.setAttribute('target', '_blank');
    a.dispatchEvent((function(e) {
        e.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, 
                         true, false, false, false, 0, null);
        return e
    }(document.createEvent('MouseEvents'))))
}(document.querySelector('a[href^=http]')))
```

This opens a new tab and *focuses* it, as opposed to opening it in the background when the cmd-click is done using the real mouse

**Comment by ealmloff** [comment]
We cannot create an event that is identical to the event triggered by the browser. Events that are triggered by a user are [trusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted). Events that are modified by javascript will not be trusted

**Comment by bishoyroufael** [comment]
Is there any current workaround for calling prevent default on an event conditionally? I am particularly interested for desktop platform.

**Comment by nicoburns** [comment]
Relevant Wry issue: https://github.com/tauri-apps/wry/issues/454. Looks like there are potential APIs for this, but Wry has no plans to expose them. So possibilities are:
- Synchronous HTTP requests (not nice, but would probably work decently so long as the webviews don't remove support)
- Waiting until webviews implement better APIs which Wry then picks up

**Comment by ealmloff** [comment]
From the mdn docs:
> [Notes](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault#notes)
Calling preventDefault() during any stage of event flow cancels the event, meaning that any default action normally taken by the implementation as a result of the event will not occur.

It sounds like it can just be a flag on Event which is set in event handlers. We don't need to stay in lock step with the browser which makes this much easier to implement
