### ISSUE TITLE
`cx.spawn_forever()` is not persistent or i don't get it?

### ISSUE THREAD

**Issue by serzhiio** [DioxusLabs/dioxus#851]
if i do `cx.spawn()` i expect it to respawn each time component renders, but `cx.spawn_forever()` is not expected to be respawned or it should not be prefixed with `_forever`. Am i wrong?

**Comment by serzhiio** [comment]
So if you run forever loop inside `.spawn_forever()`, you will just increase number of  spawned futures.
Still strange for me.

**Comment by Demonthos** [comment]
Yes, it is documented [here](https://docs.rs/dioxus/latest/dioxus/prelude/struct.ScopeState.html#method.spawn_forever). Only hooks (functions that start with use_*) will ever persist state between renders in Dioxus
