### ISSUE TITLE
Using SharedState inside coroutine...

### ISSUE THREAD

**Issue by serzhiio** [DioxusLabs/dioxus#858]
Using of `use_shared_state::<ControlServer>(cx).unwrap()` result inside coroutine leads to error: `The hook list is already borrowed: This error is likely caused by trying to use a hook inside a hook which violates the rules of hooks.: BorrowMutError'`.
```
let data: &Coroutine<Signal> = use_coroutine(cx, |mut rx| {
        let conn_state = conn_state.to_owned();
        let server = use_shared_state::<ControlData>(cx).unwrap();
        async move {
              server.write().data = "value".into()
        }
});
```
Any ideas how to avoid this?

**Comment by Demonthos** [comment]
You cannot use hooks inside of hooks because it violates the [rules of hooks](https://dioxuslabs.com/docs/0.3/guide/en/interactivity/hooks.html#rules-of-hooks). You need to move the use_shared_state out of the use_coroutine and clone then move it into the coroutine

**Comment by serzhiio** [comment]
Unfortunately, `.inner()` does not notifying subscribers.
And if we `.clone()` or just `.unwrap()`, nothing is working again.

**Comment by serzhiio** [comment]
The error:
```
[ERROR] error: lifetime may not live long enough
   --> src/main.rs:97:9
    |
87  |   fn App(cx: Scope) -> Element {
    |          -- has type `&'1 Scoped<'1>`
...
97  | /         async move {
98  | |             let rx = &mut rx;
99  | |             loop {
100 | |                 //log::debug!("--- Coroutine {:?}", conn_state.current());
...   |
214 | |             }
215 | |         }
    | |_________^ returning this value requires that `'1` must outlive `'static`
```

**Comment by Demonthos** [comment]
We should probably change use_shared_state to return a &'a State where state is Clone which would solve the above issue

**Comment by serzhiio** [comment]
It would be nice

**Comment by serzhiio** [comment]
And it would be nice also, to have an option to get `SharedState` without registering particular `scope_id`.
Bc i dont want the main componenet to be rerendered each time i write some data into.
But i want other children which are using thi `SharedState` to rereder.

**Comment by serzhiio** [comment]
`.inner()` is working with updated code as below.
we need just make `.notify_consumers()` fully public(without `pub (crate)`).
```
pub struct ProvidedStateInner<T> {
    value: Rc<RefCell<T>>,
    notify_any: Arc<dyn Fn(ScopeId)>,
    consumers: HashSet<ScopeId>,
}

impl<T> ProvidedStateInner<T> {
    pub fn notify_consumers(&self) {
        for consumer in self.consumers.iter() {
            (self.notify_any)(*consumer);
        }
    }

    pub fn write(&self) -> RefMut<T> {
        self.value.borrow_mut()
    }

    pub fn read(&self) -> Ref<T> {
        self.value.borrow()
    }
}
```

**Comment by serzhiio** [comment]
I believe it's a nice feature to not add current context as event subscriber if it is not supposed.
Maybe implementing like this:
```
pub fn use_shared_state<T: 'static>(cx: &ScopeState, to_subscribe: bool) -> Option<&UseSharedState<T>> {
    let state: &Option<UseSharedStateOwner<T>> = &*cx.use_hook(move || {
        let scope_id = cx.scope_id();
        let root = cx.consume_context::<ProvidedState<T>>()?;
        if to_subscribe {
            root.borrow_mut().consumers.insert(scope_id);
        }

        let state = UseSharedState { inner: root };
        let owner = UseSharedStateOwner { state, scope_id };
        Some(owner)
    });
    state.as_ref().map(|s| &s.state)
}
```

**Comment by serzhiio** [comment]
By the way i have error even on last release:
```
web_ui.js:410 panicked at 'The hook list is already borrowed: This error is likely caused by trying to use a hook inside a hook which violates the rules of hooks.: BorrowMutError', /home/serzh-dev/.cargo/git/checkouts/dioxus-1e619ce595d3799d/5b61cbb/packages/core/src/scopes.rs:644:61
```
