### ISSUE TITLE
How to solve "error: linking with `cc` failed: exit status: 1" in Mac OS

### ISSUE THREAD

**Issue by litieqq** [DioxusLabs/dioxus#86]
I encountered the problem when I try to launch the demo in Mac OS, the details below:
error: linking with `cc` failed: exit status: 1
  = note: Undefined symbols for architecture x86_64:
            "_UCKeyTranslate", referenced from:
                tao::platform_impl::platform::event::get_modifierless_char::h82c48132d8e4db04 in libtao-4d0591e38d01f123.rlib(tao-4d0591e38d01f123.tao.f570f3ca-cgu.2.rcgu.o)
            "_CGDisplayCreateUUIDFromDisplayID", referenced from:
                _$LT$tao..platform_impl..platform..monitor..MonitorHandle$u20$as$u20$core..cmp..PartialEq$GT$::eq::h2b490f1950e1775b in libtao-4d0591e38d01f123.rlib(tao-4d0591e38d01f123.tao.f570f3ca-cgu.0.rcgu.o)
                tao::platform_impl::platform::monitor::MonitorHandle::ns_screen::h7a220b61d2167bf2 in libtao-4d0591e38d01f123.rlib(tao-4d0591e38d01f123.tao.f570f3ca-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me and explain the reason if possible

**Comment by jkelleyrtp** [comment]
Hi, thanks for the report!

What version of macOS are you running?

The bug is seems to be in the underlying windowing library https://github.com/tauri-apps/tao.

Can you try to run one of their examples and see if you get the same error?

**Comment by litieqq** [comment]
Hi，thanks for helping!

my macOS version is 10.15.4

I tried to run the tao's example as you required and found the same problem

I also use cargo command as you list but is not work.

**Comment by jkelleyrtp** [comment]
I looked on the tauri repo and the problem seems to arrive from nightly?

https://github.com/tauri-apps/tao/issues/246

Can you try making sure you're on stable?

If so, then (following their instructions), make a `build.rs` with these contents:

```rust
fn main() {
println!("cargo:rustc-link-lib=framework=ColorSync");
}
```
If that fixes it, we can add that to our build.rs. 

If not then we need to reopen that issue.

**Comment by litieqq** [comment]
as you say, I have solved the problem by change the rust version to **stable**  version!! 

Thanks for helping
