### ISSUE TITLE
Missing `html!` macro?

### ISSUE THREAD

**Issue by Zagitta** [DioxusLabs/dioxus#861]
**Problem**

I personally don't really care for rsx as it's yet another syntax to learn and want to be able to copy/paste snippets of html while I'm iterating as I'm not a frontend-enjoyer 😉
In my pursuit of  this I saw a whole bunch of references to a seemingly non-existant `html!` macro that I was hoping would solve my voes:

- https://github.com/DioxusLabs/dioxus/blob/5b61cbb9a0f37c5582c81fbaaa09b0385c996940/docs/guide/src/en/__unused/advanced-guides/10-concurrent-mode.md#L77
- https://github.com/DioxusLabs/dioxus/blob/5b61cbb9a0f37c5582c81fbaaa09b0385c996940/docs/guide/src/en/__unused/advanced-guides/11-arena-memo.md#L15
- https://github.com/DioxusLabs/dioxus/blob/5b61cbb9a0f37c5582c81fbaaa09b0385c996940/docs/guide/src/en/__unused/advanced-guides/rsx.md#L36
- https://github.com/DioxusLabs/dioxus/blob/5b61cbb9a0f37c5582c81fbaaa09b0385c996940/packages/core/src/properties.rs#L71
- https://github.com/DioxusLabs/dioxus/blob/5b61cbb9a0f37c5582c81fbaaa09b0385c996940/packages/html/src/elements.rs#L376

Was this removed at some point? It's not clear from the changelog as that only mentions it being done but never removed...
On a separate note all the links in the change log are wrong as they look like this: `https://github.comgit//DioxusLabs/dioxus/commit/....` notice the `comgit//`.

So my question is what happened to the `html!` macro/feature? and arethere any plans to implement it? 

Thanks in advance!

**Comment by Zagitta** [comment]
Some further git archeology work indicates it was removed here: https://github.com//DioxusLabs/dioxus/commit/9f7eb0f6002156d3e6e14ea2cb24829133b531c5
but sadly there's no explanation for why 😞

**Comment by Demonthos** [comment]
It still exists, it just got moved into a different repository: https://github.com/DioxusLabs/dioxus-html-macro
The tooling around dixous is specific to RSX, so tools like hot-reloading, and formatting will not work with the html-macro

**Comment by Zagitta** [comment]
Perfect, thank you!
