### ISSUE TITLE
Figure out windows webview2 distribution

### ISSUE THREAD

**Issue by jkelleyrtp** [DioxusLabs/dioxus#87]
For windows users, they must have webview2. This is not so insurmountable.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

We can either package webview with the app or send along a bootstrapper.

Other apps have done this before, so maybe we can steal some thoughts from them.

What are people's general thoughts regarding webview2 access on Windows? Should we just fallback to MSHTML if the user doesn't have edge installed?

**Comment by Demonthos** [comment]
It looks like the tauri bundler exposes options for embedding webview2 in the installer: https://docs.rs/tauri-utils/1.4.0/tauri_utils/config/enum.WebviewInstallMode.html. We now expose this as part of the bundler config

**Comment by heyrict** [comment]
One remaining issue is that the configuration in `Dioxus.toml` is not on par with that documented in tauri bundler.
As dioxus uses toml for configuration, [the `Option<PathBuf>` makes no sense](https://github.com/DioxusLabs/dioxus/blob/c9790860a5fe410362a706c4fd7def78e202bfd5/packages/cli/src/config.rs#L390) in `wix.language` as we cannot provide a null value in toml. What do you think about reuse `tauri_utils::config::WixLanguage`, or even the whole `tauri_utils::config::BundleConfig` directly in our configuration?
