### ISSUE TITLE
Single-Page Web App Router - Hash URLs 

### ISSUE THREAD

**Issue by jpoles1** [DioxusLabs/dioxus#872]
## Specific Demand

Thanks for all the amazing work on Dioxus! I am interested in using the library to create web apps, in particular SPA, however I'm running into issues with the router updating urls. As I understand it, the router currently tracks its state/URL internally, however on browser window refresh this internal state/URL is wiped and the user returns to the home page. 

I may be missing it, but is there currently any way to update the browser url when using the router in a SPA?

## Implement Suggestion

One way to use URLs for SPA is to use hash urls (ie: https://website.com/#/homepage/2). If this is implemented into the router, I think it would help really complete the functionality for web. I unfortunately don't have the know-how yet to take on such a task myself; I'm still a bit of a fledgling rustacean. 

Thanks for your consideration!

**Comment by Demonthos** [comment]
The router should update the url of the current page if the `web` feature is enabled. If the web feature is not enabled, it will default to a in-memory history.

I believe #637 adds a hash history provider in addition to the normal URL history currently supported

**Comment by jpoles1** [comment]
How can one enable hash histories? I can't seem to figure it out...

**Comment by Demonthos** [comment]
> How can one enable hash histories? I can't seem to figure it out...

Hash histories are currently not supported. To enable normal URL histories, you can enable the web feature on the router

**Comment by dxps** [comment]
@Demonthos The `web` feature is enabled by default on `dioxus-router`, according to this:
```
❯ cargo add dioxus-router
    Updating crates.io index
      Adding dioxus-router v0.3.0 to dependencies.
             Features:
             + gloo-events
             + js-sys
             + query
             + serde
             + serde_urlencoded
             + wasm-bindgen
             + web
             + web-sys
             - wasm_test
❯ 
```

However, after upgrading to Dioxus 0.3 and now using the (externalized) `dioxus-router`, I see that:
1. "deep links" such as `http://localhost:8080/signin` are not working anymore: the result is always the homepage.
   - The routing is working fine, though: clicking on a link points correctly to the corresponding page. 
3. The URL doesn't get updated.

As reference and reproducible case, please find [here](https://github.com/dxps/fullstack-rust-axum-dioxus-rwa/tree/main/frontend) the whole example.

Thanks!

**Comment by Demonthos** [comment]
> @Demonthos The `web` feature seems to be enabled by default on `dioxus-router`, according to this:
> 
> ```
> ❯ cargo add dioxus-router
>     Updating crates.io index
>       Adding dioxus-router v0.3.0 to dependencies.
>              Features:
>              + gloo-events
>              + js-sys
>              + query
>              + serde
>              + serde_urlencoded
>              + wasm-bindgen
>              + web
>              + web-sys
>              - wasm_test
> ❯ 
> ```

The [only default feature](https://github.com/DioxusLabs/dioxus/blob/master/packages/router/Cargo.toml#L41) for the router is the query feature. It would be great if we could include this as a default feature for web targets, but there is no separate target for applications that target wasm on the server, so the feature would have no way of telling between the two.
I'm not entirely sure what happened with the command you listed. I did notice that if you run:
```rust
cargo add dioxus-router --features web
cargo add dioxus-router
```
The second command lists the web feature as enabled.


> However, after upgrading to Dioxus 0.3 and now using the (externalized) `dioxus-router`, I see that:
> 
> 1. Directly hitting specific routes - such as `http://localhost:8080/signin` - is not working anymore.
>    
>    * The result is always the homepage.
>    * However, the routing is working fine: clicking on a link points correctly to the corresponding page.
>    * Even the "fallback 404 page" (set according to [this](https://dioxuslabs.com/docs/0.3/guide/en/interactivity/router.html) doesn't seem to work.
> 2. The URL doesn't get updated while navigating through the different paths.
> 
> As reference and reproducible case, please find [here](https://github.com/dxps/fullstack-rust-axum-dioxus-rwa/tree/main/frontend) the whole example.
> 
> Shall I create a distinct issue for this?
> 
> Thanks!

Cloning the repo and adding the web feature explicitly to the cargo.toml in the frontend package seemed to fix these issues for me, but if it remains an issue feel free to open a new issue

**Comment by dxps** [comment]
@Demonthos  Lovely! :partying_face:   Really appreciate the quick feedback! :pray: 
I can confirm it's all working as expected (both routes reflected in the URL and directly accessible, plus the not found page delivered on unknown paths).
