### ISSUE TITLE
 Why the element event like onclick: move |evt| {} evt don't have element reference attribute ?

### ISSUE THREAD

**Issue by BarryYan** [DioxusLabs/dioxus#88]
I find when trigger a event like `click`,  the `rpc.call` will send the `event` as a `UserEvent`, but the `onclick` callback get the `UIEvent`, it only includes a `data`attribute with type `MouseEvent`

How does it design?

I just think if I want to get the element position like the html element which can use `getBoundingClientRect` to get `top`, `left` ...

**Comment by mrxiaozhuox** [comment]
look like: #77

**Comment by jkelleyrtp** [comment]
Hi! 

The docs were "ahead of the times".

This has been fixed and will be released soon in 0.1.7. For now you can either use the existing `&dyn Fn(Event)` syntax or upgrade to the master once the PR has been merged.

I've actually added the feature to support the EventHandler syntax as shown in the docs. In #91

Once the tests pass we can merge it in.

**Comment by jkelleyrtp** [comment]
This has been resolved - and will release in 0.1.7. Thanks for reporting!

You can either wait for 0.1.7 or update to master.

**Comment by BarryYan** [comment]
Thank you explain. I am a beginner of Rust
Can you give a demo about `&dyn Fn(Event)`? I can't find any doc or demo in the project

**Comment by jkelleyrtp** [comment]
> @jkelleyrtp Thank you explain. I am a beginner of Rust
> Can you give a demo about `&dyn Fn(Event)`? I can't find any doc or demo in the project

0.1.7 has been released so the EventHandler syntax is now available.

However, the `&dyn Fn(Event)` syntax is essentially just a closure (callback) that uses [dynamic dispatch](https://www.cs.brandeis.edu/~cs146a/rust/doc-02-21-2015/book/static-and-dynamic-dispatch.html) to be called.

**Comment by BarryYan** [comment]
I upgrade it. but I think I don't say it clear before.
Actually, I mean I want to get the `dom` element instance from event object when I click a dom element. I just see the callback will pass the param with type UIEvent which don't have any element info even the UserEvent has got the Element(id).
just like js
```js
<div onclick={evt => console.log(evt.target)}>  // the target is element self
```
I want to get the element, but I find it doesn't implement.
