### ISSUE TITLE
eval never finishes

### ISSUE THREAD

**Issue by terhechte** [DioxusLabs/dioxus#883]
**Problem**

When running the `eval.rs` example:

``` rs
cx.spawn(async move {
  if let Ok(res) = eval(script.to_string()).await {
    output.set(res.to_string());
  }
});
```

The generated `LocalTask` never finishes. It seems the `await` on the `eval(..).await` causes this.
A future without `await` works, but doesn't allow retrieving the outcome from the operation.

e.g. (pseudo code):

``` rs
eval("document.getElementById('a').style.display = 'none'");
```

works (e.g. ignoring the return value of eval by not even awaiting for it.

but

``` rs
cx.spawn(async move {
  let r = eval("do_something_that_returns()").await;
  ... // process
});
```

just adds the future to the tasks vec and then nothing happens.

I've added some logging and it looks like `handle_task_wakeup` is only called once, right after the task has been added. Then, it is still pending. But `handle_task_wakeup` is never called again thereafter.

**Steps To Reproduce**

I've just run the `eval.rs` example on current master. That already doesn't work.

**Comment by Demonthos** [comment]
Make sure you include return in the code you run. `eval("do_something_that_returns()").await;` will not work, but `eval("return do_something_that_returns()").await;` should work
