### ISSUE TITLE
desktop open window as non floating

### ISSUE THREAD

**Issue by alkeryn** [DioxusLabs/dioxus#889]
## Specific Demand

so i'm using a tiling manager and by default dioxus window is run as floating which is kinda annoying, there should be an option to set it to non floating or automatic.
and generally have a way to provide window settings such a dimension, position etc...

**Comment by Demonthos** [comment]
You can provide a custom [window builder](https://docs.rs/wry/latest/wry/application/window/struct.WindowBuilder.html) illustrated in this [example](https://github.com/DioxusLabs/dioxus/blob/master/examples/overlay.rs#L61). You can also control this at runtime with [use_window](https://docs.rs/dioxus-desktop/latest/dioxus_desktop/fn.use_window.html) and change many of the settings in [the window it returns](https://docs.rs/dioxus-desktop/latest/dioxus_desktop/struct.DesktopContext.html#deref-methods-Window).

**Comment by alkeryn** [comment]
@Demonthos thanks i couldn't find the doc.
