### ISSUE TITLE
Support custom elements

### ISSUE THREAD

**Issue by hamza1311** [DioxusLabs/dioxus#893]
## Specific Demand

Custom elements are part of [Web Component](https://developer.mozilla.org/en-US/docs/Web/Web_Components) spec. They are used by popular libraries. For example, [Material Web](https://github.com/material-components/material-web/) to provide framework agnostic implementations of their design.

## Current Behavior 

Not only are custom elements not supported, trying to use them results in a very unhelpful error message

```rust
// src/main.rs
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    // launch the web app
    dioxus_web::launch(App);
}

fn App(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "Hello, world!"
            mat-button {
                "Click me"
            }   
        }
    })
}
```

```
>> cargo build --target wasm32-unknown-unknown
   Compiling dioxus-demo v0.1.0 (/home/hamza/code/dioxus-demo)
error: expected identifier or integer
  --> src/main.rs:14:17
   |
14 |                 "Click me"
   |                 ^^^^^^^^^^

error: could not compile `dioxus-demo` due to previous error
```

**Comment by zoechi** [comment]
I found https://github.com/gbj/custom-elements which might be helpful. It only has an example for Yew and vanilla
