### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by JordanStuckings** [DioxusLabs/dioxus#897]
**Problem**

When following [Getting Started - Web](https://dioxuslabs.com/docs/0.3/guide/en/getting_started/web.html) guide and then [Hot Reloading](https://dioxuslabs.com/docs/0.3/guide/en/getting_started/hot_reload.html) guide, project fails to hot reload on saving new rsx code modifications.

**Steps To Reproduce**

- `cargo new --bin demo`
- `cd demo`
- `cargo add dioxus`
- `cargo add dioxus-web`
- `dioxus serve --hot-reload`
- visit http://localhost:8080/
- edit rsx and save

**Expected behavior**

Page reloads with new rsx just saved

**Screenshots**
Example Gif:
![2023-03-20 19-51-00](https://user-images.githubusercontent.com/29854368/226299368-d2eb38a9-d92c-4bcf-af72-e9ddd67bc066.gif)

**Environment:**
 - Dioxus version: 0.3.2
 - Rust version: 1.68.0
 - OS info: windows
 - App platform: web

**Questionnaire**
- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
There have been some bugfixes since the last release of the CLI, you could try installing the master version of the CLI and rerunning `dioxus serve --hot-reload`:
`cargo install --git https://github.com/DioxusLabs/cli`

**Comment by norbertkeri** [comment]
I had the same problem as described here, and got the same advice. Using the latest master cli solved it.

**Comment by JordanStuckings** [comment]
installed latest release of cli and it fixed the issue

`cargo install --git https://github.com/DioxusLabs/cli`
