### ISSUE TITLE
Cross build from mac to windows 10 cannot be launched with 'cannot find webview2loader.dll'

### ISSUE THREAD

**Issue by AllenDang** [DioxusLabs/dioxus#899]
**Problem**

I cross build from mac to windows with following command.

```
cargo build --release --target=x86_64-pc-windows-gnu
```

Launch it on windows 10 give me an error message says "cannot find webview2loader.dll".

I followed the instruction on `https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section` and installed the edge webview2 runtime.

Issue persists.

**Expected behavior**

Application could be launched normally on windows 10.

**Environment:**
 - Dioxus version: 0.3.2
 - Rust version: 1.68
 - OS info: windows 10
 - App platform: desktop

**Comment by AllenDang** [comment]
@Demonthos mcvc toolchain cannot run in macOS, at least I didn't find a proper way, do you know how?

**Comment by arqalite** [comment]
@AllenDang Check out https://github.com/rust-cross/cargo-xwin.

`cargo xwin build --target x86_64-pc-windows-msvc` works on Linux and generates a working EXE binary. I don't own any Apple devices so I can't test on macOS.

**Comment by shivaraj-bh** [comment]
> I don't own any Apple devices so I can't test on macOS.

I can confirm that it works on macOS too

**Comment by pascalbehmenburg** [comment]
Running the suggested setup as follows on macos:

```sh
rustup target add x86_64-pc-windows-msvc
cargo install cargo-xwin
cargo xwin build --target x86_64-pc-windows-msvc
```

The binary is compiles perfectly fine as you can see here (running on windows):

![explorer_UmrGsmLskg](https://github.com/DioxusLabs/dioxus/assets/26353707/8a001331-ceda-44f1-a143-230ae5b5980b)

This issue may be closed. One could consider documenting these steps to cross-compile, although I'd say this is a pretty standard approach to cross-compilation when targeting msvc. Maybe one could state somewhere that Tauri does only compile for msvc target, so it is more obvious.
