### ISSUE TITLE
Allow loading local css files

### ISSUE THREAD

**Issue by alepez** [DioxusLabs/dioxus#900]
During development, I would like to quickly play with a .css file without needing to recompile (or even hot-reload). I just want to change something in a css and refresh the view. It would be even better if hot reloading would update just the css.

Using `with_custom_head` I can inject the `link` tag to load a local css, but this causes an error in the webview "Not allowed to load local resource: file:///..."

To make it working, I have to spawn a local http server and use something like this:

```rs
    let config = DesktopConfig::new()
        .with_window(window)
        .with_custom_head("<link rel=\"stylesheet\" href=\"http://localhost:8000/style-sandbox.css\" />".to_owned());
```

So my question is: is there any smarter way to achieve this? I just want to do this during development, while I'm perfectly fine using `include_str!("style.css")` (which requires a rebuild) for the release version.

**Comment by Demonthos** [comment]
This should definitely be possible. If this is not working on your system it is likely a bug. Could you provide some more information about your system and the code you tested so that we can track this issue?

I tested this example (modified from [the custom assets example](https://github.com/DioxusLabs/dioxus/blob/master/examples/custom_assets.rs)) on Windows 11 and it loaded the stylesheet:

```rust
use dioxus::prelude::*;
use dioxus_desktop::Config;

fn main() {
    // link to the style example/assets/style.css
    dioxus_desktop::launch_cfg(
        app,
        Config::new().with_custom_head(
            r#"<link rel="stylesheet" href="examples/assets/calculator.css">"#
            .into(),
        ),
    );
}

fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            "This should show an image:"
            img { src: "examples/assets/logo.png" }
        }
    })
}
```

**Comment by alepez** [comment]
Oh! It was so simple. I was using `file:///asbolute/path/to/style.css` with the `file://` prefix.

**Comment by ealmloff** [comment]
> Using a similar setup. I'm able to see the styles when running `dx serve` but not when running the MacOS app after `dx build --release && dx bundle --release`. Should I see the `assets` folder in the Package Contents?

Currently, bundling doesn't include any folders by default. You need to add any folders you want to include for bundling or serving.

https://github.com/DioxusLabs/dioxus/pull/1369 unifies the asset system between serving on the web, running on desktop and bundling which should make it easy to bundle any assets that you serve
