### ISSUE TITLE
Problems encountered in building/deploying a release web-app

### ISSUE THREAD

**Issue by pat0026** [DioxusLabs/dioxus#909]
**Problem**

According to the documentation, you just need to run trunk build --release ( included  index.html with basic content due to Error: error getting canonical path to source HTML file "index.html") but it did not render the app that I made.  
Tried using dioxus-cli and removed the index.html. Works fine but how do I modify the index.html before build?

Is there an updated guide on how to deploy/build a released version, should we use trunk or should we use dioxus-cli?  

If via trunk:
- why doesn't it render the application I made? (served it via caddy and shows only white/blank page)  

If via dioxus-cli:
- how do I modify the information in the generated index.html. If I place a basic index.html in the root directory, it just copies it in the dist without modification regarding the release build assets. 

**Steps To Reproduce**

- place index.html with basic content
- trunk -v build --release

or

- place index.html with basic content
- dioxus build

**Expected behavior**

- via trunk: render the app
- via dioxus-cli: modify the index.html upon build, render the app

**Environment:**
 - Dioxus version: 0.3.2
 - Rust version: 1.68.1
 - OS info: win11
 - App platform: web

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
For trunk and the Dioxus CLI you need to include a div with an id of "main" for Dioxus to render into ([example](https://github.com/Demonthos/tiny-dioxus/blob/main/index.html#L8)). Trunk also has a great guide that provides information about configuration options [here](https://trunkrs.dev/).
For the Dixous CLI, you currently also need to include some template boilerplate to include the WASM and Javascript files in the output ([example](https://github.com/DioxusLabs/cli/issues/106#issuecomment-1441897080)).

**Comment by pat0026** [comment]
Thank you for the fast reply. Closing this issue.

Note: It might be better to add this to the current documentation so that newbies like me won't be surprised by these additional steps, whether using trunk or dioxus-cli.
