### ISSUE TITLE
Responsive Table and Detail View

### ISSUE THREAD

**Issue by hanusek** [DioxusLabs/dioxus#921]
Hello!

I'm looking for an example with Responsive Table like it: https://codepen.io/hbuchel/pen/jOGbGE
How to do it in Dioxus? (CSR)

**Comment by Demonthos** [comment]
Dioxus allows you to use plain HTML, attributes and CSS to style your application. You should be able to port an implementation almost directly from the example you linked.

Something that could be useful to look at is the js-framework-benchmark implementation for Dioxus which uses a table view with css and event handlers: https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/dioxus/src/main.rs
