### ISSUE TITLE
onsubmit example doesn't behave as expected.

### ISSUE THREAD

**Issue by kylerlaird** [DioxusLabs/dioxus#924]
**Problem**

When I use the code in https://dioxuslabs.com/docs/0.3/guide/en/interactivity/user_input.html#uncontrolled-inputs, I do not see the expected output.

**Steps To Reproduce**

```
use dioxus::prelude::*;

fn main() {
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx!(
        body {
            form {
                onsubmit: move |event| {
                    println!("Submitted! {event:?}")
                },
                input { name: "name", },
                input { name: "age", },
                input { name: "date", },
                input { r#type: "submit", },
            }

        }
    ))
}
```

`dioxus serve`

Press "Submit Query".

**Expected behavior**

`Submitted! UiEvent { data: FormData { value: "", values: {"age": "very old", "date": "1966", "name": "Fred"} } }`

**Observed behavior**

Immediate HTTP GET request.  I don't see any evidence of the onsubmit action.

**Environment:**
 - Dioxus version: v0.3.0
 - Rust version: 1.68.1
 - OS info: Linux
 - App platform: web

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by benwh1** [comment]
I just encountered this same problem and asked in the discord server. The answer I got was that the event is actually being sent, it's just that the output of `println!` doesn't go anywhere for some reason. You can use the `wasm_logger` crate as a workaround.

**Comment by Demonthos** [comment]
> 

That is definitely be an issue here as well 🙂, but in this case there is also a bug in Dixous. The page is redirecting after the form is submitted (like a normal HTML form does), so even if the print was a log to the console it wouldn't show up. We already override this behavior on desktop but we were not overriding this on the web renderer (#926 fixes this)
