### ISSUE TITLE
Make hooks more ergonomic

### ISSUE THREAD

**Issue by pickfire** [DioxusLabs/dioxus#929]
## Specific Demand

Reduce typing and import needs for hooks. Instead of

```rust
let count = use_state(cx, || 0);
```

Do

```rust
let count = cx.state(|| 0);
```

## Implement Suggestion

I think maybe can `impl ScopeState`?

**Comment by Demonthos** [comment]
1) Hooks are extensible, you should be able do implement your own hooks based off of the core cx.use_hook(|| 0) hook. If we did adopt this approach, to define a custom hook you would need to create a new extension trait and implement it on the ScopeState. This trait would still need to be imported to be used.
2) The use_ prefix is important to visually indicate where the [rules of hooks](https://dioxuslabs.com/docs/0.3/guide/en/interactivity/hooks.html#rules-of-hooks) apply.
