### ISSUE TITLE
Audio & video player examples

### ISSUE THREAD

**Issue by itsezc** [DioxusLabs/dioxus#933]
## Specific Demand

No examples exist for audio & video players for Dioxus, this is very useful for building apps that are multi media heavy.

## Implement Suggestion

Create examples for a simple audio and video players for both the web and native platforms

**Comment by talksik** [comment]
how would you accomplish this? Would have you have a basic idea on how one would do this? It seems like a core feature

**Comment by Demonthos** [comment]
If you want to play a static video, you can use a custom asset. [example](https://github.com/DioxusLabs/dioxus/blob/master/examples/custom_assets.rs)

For dynamic video streams, I think it is possible with a custom protocol, but it isn't documented well currently. If you are interested in helping create such an example, you could use a custom protocol in wry (https://docs.rs/dioxus-desktop/latest/dioxus_desktop/struct.Config.html#method.with_custom_protocol). This could also potentially be useful: https://github.com/tauri-apps/wry/blob/87b331a7d4c169814d2b6a1f8a06d976ad7565bc/examples/stream_range.rs#L25

**Comment by ealmloff** [comment]
There is a video player example here: https://github.com/DioxusLabs/dioxus/blob/663296ae45918e28d5ae5bd7a79cdf53f53828da/examples/video_stream.rs#L11
