### ISSUE TITLE
Dioxus-tui compiles but no works under Windows 10

### ISSUE THREAD

**Issue by anatoly62** [DioxusLabs/dioxus#948]
**Problem**

Dioxus-tui compiles but no works under Windows 10. There are escape sequences output only. Tui-rs (0.19) examples works fine.

**Environment:**
 - Dioxus version: [0.2.4]
 - Rust version: [1.68.0`]
 - OS info: [Windows 10 pro ]
 - App platform: [tui]

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
What terminal are you running the Dioxus TUI application in and what application have you tested? The TUI renderer uses escape sequences to render to the terminal. The TUI renderer defaults to full rgb color, but depending on the terminal you may need to change the [rendering mode](https://docs.rs/dioxus-tui/latest/dioxus_tui/struct.Config.html#method.with_rendering_mode) to ANSI colors for broader support.

**Comment by anatoly62** [comment]
Bash (Git  for Windows). Cmd works fine.

fn app(cx: Scope) -> Element {
    cx.render(rsx!{
        div {
            width: "100%",
            height: "10px",
            background_color: "red",
            justify_content: "center",
            align_items: "center",
            "Hello world!"
        }
    })
}

**Comment by Demonthos** [comment]
It appears bumping the cross term version we could fix this issue. https://github.com/crossterm-rs/crossterm/issues/656 was closed and released, but we currently use an older version of crossterm that does not have this fix.

**Comment by Demonthos** [comment]
#981 Bumps the crossterm version. I have confirmed that rendering now works in git bash for windows, but events do not work. This is either a limitation of crossterm or that terminal
