### ISSUE TITLE
Document how to use the CLI with a cargo workspace

### ISSUE THREAD

**Issue by orf** [DioxusLabs/dioxus#956]
## Specific Demand

I was struggling to work out how to use the CLI with a cargo workspace, where one sub-crate is the dioxus frontend. Digging through the CLI code it seems I need to add a `sub_package` key to the `[application]` section ([see here](https://github.com/DioxusLabs/cli/blob/9ce5fc508d0b512100c8f251a1993024438afdba/src/config.rs#L165))

## Implement Suggestion

It would be great to document this in the getting started guide, maybe something simple like "run `dioxus config init .` then add a `sub_package` key like so":

```
[application]
sub_package = "foobar"
```

**Comment by Demonthos** [comment]
This is now documented in the configuration docs [here]( https://github.com/DioxusLabs/dioxus/blob/9cef71b6b98ae071291fe8fb026436bcfa0f1776/packages/cli/docs/src/configure.md?plain=1#L43)
