### ISSUE TITLE
Support for Lunatic and Submillisecond

### ISSUE THREAD

**Issue by Nialisc** [DioxusLabs/dioxus#963]
## Specific Demand

Coming from Erlang and Elixir, I'm using the [Lunatic](https://github.com/lunatic-solutions/lunatic) runtime to run my app with the amazing actor model.

In this ecosystem, I'm using a web framework called [Submillisecond](https://github.com/lunatic-solutions/submillisecond) which is using all the features of the runtime and implement a Websocket too.

Would it be possible to support Submillisecond has a first class citizen for SSR and Liveview use cases ?

I'm really seeing the Lunatic runtime has a huge step in the right direction and possibly a revolution in the rust backend ecosystem. So since Dioxus is exactly that for the frontend, it would be great to pair them.

## Implement Suggestion

Submillisecond has already a [Liveview implementation](https://github.com/lunatic-solutions/submillisecond-live-view). So maybe we can take it has inspiration to use their Websocket logic ?

**Comment by jkelleyrtp** [comment]
Seems like lunatic dev has slowed and this is not a huge priority for us anymore. It's easy to make your own liveview adapters! Just wrap the websocket types in your own stream transformation.
