### ISSUE TITLE
Make Documentation More Approachable from a non-web Background

### ISSUE THREAD

**Issue by Demonthos** [DioxusLabs/dioxus#964]
## Specific Demand

Currently the guide assumes the reader is familiar with web development. It is focused on users who have learned rust and are switching either from a Javascript or Rust web framework. We could do more to make the documentation approachable for developers who are not familiar with web development concepts by explaining more terms and linking to in depth external documentation.

## Implement Suggestion

Specific areas that need improvement:
- In the getting started [guide](https://dioxuslabs.com/docs/0.3/guide/en/getting_started/index.html) we can add more details to help new users pick a renderer with the tradeoffs between Client side rendering, Liveview, and SSR with hydration.
- In the [describing the UI](https://dioxuslabs.com/docs/0.3/guide/en/describing_ui/index.html) section we currently only explain how Dioxus interacts with HTML. We could also link to resources that explain more about how to use html ([w3schools](https://www.w3schools.com/html/default.asp), [mdn](https://developer.mozilla.org/en-US/docs/Learn/HTML)), and how to style your page with CSS, or [Tailwind](https://github.com/DioxusLabs/dioxus/pull/912).

General Guidelines:
- The guide can cover some simple web dev concepts and concepts that are specific to Dioxus (like picking between renderers), but it shouldn't contain general web dev resources like an overview of HTML. Where we reference general web dev knowledge (HTML, CSS, etc) that deserve there own section, we should instead link to external documentation so that the guide doesn't grow too large.
> All of the additional sections should be clearly separated from the web-dev focused docs (potentially with boxes like this) so that readers can skip over the sections that they are already familiar with.

**Comment by GlenDC** [comment]
I can pick this issue up as part of my learning Dioxus, while I also start to use it for 1 or 2 projects.
Is there any PR I should way for or branch of, to ensure I get the full context?
Anything else version wise I need to be aware of.

I'll open a PR as soon as possible so we can collaborate together on this, with me writing and you giving iterative feedback. How does that sound?

**Comment by Demonthos** [comment]
> Is there any PR I should way for or branch of, to ensure I get the full context? Anything else version wise I need to be aware of.

#916 adds a new guide section documenting the [setup for a fullstack Dioxus application](https://github.com/DioxusLabs/dioxus/pull/916/files#diff-b68c00b0ea7156af750a4d26bcece88f7f85af3207af324317e23807f731d91c) and adds some [examples](https://github.com/Demonthos/dioxus/tree/server-fn/packages/server/examples) with SSR, hydration, and server functions. It very briefly mentions the benefits of SSR and hydration, but we can go into more depth.

Main addition of that PR is server functions and helper traits for the server. Server functions change how any client communicates with the server, and the helper traits will change how the server serves web applications. It might be best to come back to documenting SSR and the tradeoffs between SSR and liveview after that PR is reviewed.

#912 could be useful to link to when discussing tailwind styling if it gets merged.

> I'll open a PR as soon as possible so we can collaborate together on this, with me writing and you giving iterative feedback. How does that sound?

Sounds great! I'm also happy to help out with writing, but your perspective as you first learn Dioxus could be more useful here

**Comment by GlenDC** [comment]
Hi.For now I am out I am sorry. I’m afraid this project no longer align with my goals. I’m therefore out, please unassign this to me.

might come back later to the project when it has continued to evolve, for now I have way to much on my plate already.

**Comment by Urthor** [comment]
Highly agree with the issue of OP.

My feedback: I'm a back-end dev approaching front-end for the first time ever.

>     * In the getting started [guide](https://dioxuslabs.com/docs/0.3/guide/en/getting_started/index.html) we can add  
>     * The guide can cover some simple web dev concepts and concepts that are specific to Dioxus (like picking between renderers), but it shouldn't contain general web dev resources like an overview of HTML. Where we reference general web dev knowledge (HTML, CSS, etc) that deserve there own section, we should instead link to external documentation so that the guide doesn't grow too large.

My POV: this x10.

Some perspective.

Bugs I've faced:

- Altering the exposed port of Dioxus isn't done using Dioxus.toml.  It's done via a command line parameter to Dioxus serve.
- Routes are mildly complicated if you've got zero previous webdev experience. https://dioxuslabs.com/docs/0.3/router/guide/building-a-nest.html#site-navigation is a great resource.
- Dioxus' approach to logging to console.log was hard to find examples for.
- Dioxus is very new, so it's not cached in ChatGPT's training set.

Nothing *complicated*.  But, I'm humble enough to say that they each took 20+ minutes for me to diagnose and resolve.

https://github.com/DioxusLabs/dioxus/pull/916/files

This is excellent IMO.

![image](https://user-images.githubusercontent.com/112486996/236660134-e52d8431-f7d3-473c-92e0-53e2a88d7206.png)

One thing I'd add.  For the "user journey picking up Dioxus for the first time."  They'll expect all relevant resources to be in the above tab.

I don't mean any of the above as criticism of maintainers.  Dioxus is an enormous quantity of excellent work, shouldered by extremely few people.

My feedback is, "assume your users know *nothing*" about webdev.  Don't underestimate users' inexperience.

**Comment by Urthor** [comment]
Some notes to add.  I'm a back-end dev picking up front-end for the first time.

Bugs I've faced:

- Exposing ports isn't done via Dioxus.toml.  A command line utility parameter, `dioxus serve`, exposes the port.
- Dioxus generates index.html automatically.  Locally hosted assets get placed in a folder defined in Dioxus.toml (not something immediately obvious to a non-webdev).
- Routes are extremely complicated with zero previous webdev experience. https://dioxuslabs.com/docs/0.3/router/guide/building-a-nest.html#site-navigation is a great resource and a good start. 

I still spent considerable time learning Router functions/components cannot be nested inside other components.  There's bound to be other intricacies.

- Dioxus/Rust's approach towards logging to console.log was hard to find examples for.

Above took 20+ minutes of hacking and searching for examples to resolve. 

Additionally:
- Dioxus is very new, so it's not cached in ChatGPT's training set.
![image](https://user-images.githubusercontent.com/112486996/236665361-c2d797e6-1ded-4292-bac9-81e308fc18cb.png)

99% of people, I speculate, will *only* use documentation as a learning resource.

Examples inside the git repo of the project.  Opening up the docsite repo to learn project layouts.  Is... not necessarily something most folk do.  

Overall, the experience is good after I've learn the features it up.  Don't take the above as criticism, just observations, Dioxus is clearly a lot of work by very few people.  

Mostly, I'd just add, "assume your users know nothing."  Don't underestimate users' inexperience.

**Comment by stephenandary** [comment]
I would also like to include an opinion that good Diagrams are very important to good documentation. Visuals are spoken language agnostic, concise, and easy to understand. Conducive to faster learning.

**Comment by stephenandary** [comment]
<3
