### ISSUE TITLE
Question: How to change location of WebView2 folder on Windows? 

### ISSUE THREAD

**Issue by sdwoodbury** [DioxusLabs/dioxus#966]
Hello,

I'm preparing to release a Windows application named `uplink`. I found that on windows, a folder is created next to the executable, named `<application name>.exe.WebView2`. This prevents me from installing the executable in the `ProgramFiles` directory because the `exe` doesn't have write access to that directory. Is there a way I can tell Dioxus to create this `WebView2` folder somewhere else? 

![image](https://user-images.githubusercontent.com/8636602/233095542-f7fb53df-9eb7-4edb-babe-56cd80c4322f.png)

This issue is somewhat important to me because if I use the installer to uninstall the app, it won't delete the `C:\uplink` directory. This is because the `WebView2` folder was added. If I then re-run the installer, the installer may install the new `.exe` because the old one is still there. In other words, if someone uninstalls `uplink`, downloads a installer for a different version, and runs the installer, they would still have the old version. Also, the app would look more professional if it could be installed in the `ProgramFiles` directory instead of whatever the `LocalAppData` folder happens to be (usually the last letter drive).

**Comment by Demonthos** [comment]
You can use the with_data_directory function on the desktop config on the master branch after #905:

```rust
dioxus_desktop::launch_cfg(
    App,
    dioxus_desktop::Config::new().with_data_directory("C:/Uplink/"),
);
```

**Comment by sdwoodbury** [comment]
great! thank you!
