### ISSUE TITLE
Hosted demos 

### ISSUE THREAD

**Issue by Immortalin** [DioxusLabs/dioxus#969]
**Problem**

Most client side frameworks have a hosted demo to show off features and performance 
**Steps To Reproduce**
See current landing and documentation 

**Expected behavior**
Hosted demos for all web compatible examples in the repo. There should also be a kitchen sink demo showing off all the features together with in-line copy and pastable self contained code snippets (with a copy and paste button that automatically copies the code to the browser clipboard).

**Comment by Demonthos** [comment]
That would be a nice addition. The examples in the main repo are mostly showing concepts, not full projects. The full projects in the [examples-projects](https://github.com/DioxusLabs/example-projects) repo could be more compelling demos to host.

For this repo combining something like https://svelte.dev/examples with code sandbox could be interesting. It appears you cannot publish cloud sandboxes automatically (https://github.com/codesandbox/codesandbox-importers/issues/171) right now. If that is implemented, linking to sandbox demos would be nice

**Comment by Demonthos** [comment]
This has somewhat improved with the new docs rewrite. The docs now have hosted demos embedded inline! The code for the demos are included as well so that you can copy-paste it.

Example: https://dioxuslabs.com/learn/0.4/guide
