### ISSUE TITLE
`crossterm::event::poll()` causing delayed key inputs in Dioxus TUI

### ISSUE THREAD

**Issue by willothy** [DioxusLabs/dioxus#978]
**Problem**

When using text input widgets, key events register with a noticeable delay. Moving the mouse causes buffered / backlogged key events to flush, but typing without mouse movement is extremely slow.

- Clone the dioxus repo
- Run the `widgets` example in the `dioxus_tui` package 
- Enter the text or number input widget
- Type

**Expected behavior**

Typed characters should register immediately, without noticeable delay.

**Environment:**
 - Dioxus version: master (459d8d6)
 - Rust version: 1.69 stable
 - OS info: Linux
 - App platform: TUI

Mix of these two:
- [X] I'm interested in fixing this myself but don't know where to start
- [X] I would like to fix and I have a solution (Idea, but not solution)

I decreased the poll timeout from 1000ms to 10ms on line 101 of packages/rink/lib.rs for testing, and the key delays were significantly improved. There wasn't a noticable increase in CPU usage (in htop, at least), but I'm assuming the 1000ms timeout was implemented for performance-related reasons, so I'm not sure whether or not changing that would have significant drawbacks.

Happy to contribute a PR if wanted :)

**Comment by Demonthos** [comment]
> I decreased the poll timeout from 1000ms to 10ms on line 101 of packages/rink/lib.rs for testing, and the key delays were significantly improved. There wasn't a noticable increase in CPU usage (in htop, at least), but I'm assuming the 1000ms timeout was implemented for performance-related reasons, so I'm not sure whether or not changing that would have significant drawbacks.
> 
> Happy to contribute a PR if wanted :)

I'm not sure why the polling rate was changed to 1 second? Changing it back to 10ms would work. I can confirm it doesn't effect the CPU usage on windows. A PR would be great!

**Comment by willothy** [comment]
Sounds good!

**Comment by willothy** [comment]
Done! May also look into using crossterm's EventStream, as reading events asynchronously could improve perf even more. Could be good to have as an optional feature for people who are already using tokio in their TUI apps :)
