### ISSUE TITLE
dioxus-ssr 0.3.0, the latest published to crates.io does not escape text nodes

### ISSUE THREAD

**Issue by DusterTheFirst** [DioxusLabs/dioxus#979]
**Problem**

Using dioxus-ssr with text nodes containing `<` and `>` results in unintentional html injection. This is *very* bad behavior. Since text nodes are escaped by all other dioxus renderers and described as such in the documentation, this can lead to many users of dioxus-ssr unknowingly implementing XSS vulnerabilities.

This has already been fixed in https://github.com/DioxusLabs/dioxus/commit/c9f9b8b0fa71a8fabc6a216a8a7771a1f686d936 it just has not been pushed to crates.io

**Steps To Reproduce**

- use dioxus-ssr 0.3.0 (the latest published version)
```rs
assert_eq!(
  dioxus_ssr::render_lazy(rsx! {
    "<h1>this should not be interpreted as HTML</h1>"
  }),
  "<h1>this should not be interpreted as HTML</h1>"
)
```

**Expected behavior**

```rs
assert_eq!(
  dioxus_ssr::render_lazy(rsx! {
    "<h1>this should not be interpreted as HTML</h1>"
  }),
  "&lt;h1&gt;this should not be interpreted as HTML&lt;/h1&gt;"
)
```

**Environment:**
 - Dioxus version: 0.3.2
 - Dioxus-ssr version: 0.3.0 (latest)
 - Rust version: rustc 1.70.0-beta.1 (1b7dd2252 2023-04-19)
 - OS info: Fedora release 37 (Thirty Seven)
 - App platform: `dioxus-ssr`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [x] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Solution**

Publish a minor version bump of dioxus-ssr, and yank the current `0.3.0` version.

**Comment by Demonthos** [comment]
[Comparing the current and 0.3 release](https://github.com/DioxusLabs/dioxus/compare/2075ff3039feb1efb576d8f2ed5a2c4d0c554731...1adccc057357fa11c21327d18298f442bc6528e4), there have been no breaking changes in the SSR crate, so we should be able to bump the minor version

**Comment by Demonthos** [comment]
Dioxus 0.4 has been released along with the newest version of the ssr renderer
