### ISSUE TITLE
CLI stuck compiling fnv

### ISSUE THREAD

**Issue by boohba** [DioxusLabs/dioxus#982]
**Problem**
![image](https://user-images.githubusercontent.com/58115165/234109287-b878ce8e-997f-4781-ba15-9b075ad8156b.png)

**Steps To Reproduce**

- Run `dioxus serve --hot-reload`

**Expected behavior**

    Change some code within a rsx or render macro
    Open your localhost in a browser
    Save and watch the style change without recompiling

**Environment:**
 - Dioxus version: 0.3.2
 - Rust version: rustc 1.70.0-nightly (a41fc00ea 2023-04-13)
 - OS info: Arch Linux 6.2.12
 - App platform: desktop

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by Demonthos** [comment]
I know there have been issues with the CLI before that have caused it to infinitely loop when it encounters an error in the first compile cycle. Testing a hello world example on the git version of the CLI, I don't run into the issue.

Some additional information would be very helpful to make debugging this easier:
- What version of the CLI did you run into this error with?
- Can you post a minimum reproducible example (with directory structure, configs, and code) that shows the error?

Until the CLI issue is fixed, you can run `cargo check --target wasm32-unknown-unknown` to see what the real error is

**Comment by boohba** [comment]
Nevermind, I was trying to use `dioxus serve --hot-reload` (it's a web only thing, right?) with a desktop app.

**Comment by Demonthos** [comment]
Yes, Dioxus serve is web only. You can pass a platform flag to build for desktop but there isn't any advantage over using cargo directly. If you are interested in hot reloading for desktop you can use the [hot-reload](https://github.com/DioxusLabs/dioxus/tree/master/packages/hot-reload) crate with the git branch of dioxus desktop
