### ISSUE TITLE
Hot Reload broken on macos

### ISSUE THREAD

**Issue by dignifiedquire** [DioxusLabs/dioxus#998]
I followed the docs on getting started with dioxus-web and hot reloading, using current `master` for the cli. 
The initial compile works fine, but when I modify a file this happens:

<img width="1416" alt="Screenshot 2023-04-30 at 14 55 35" src="https://user-images.githubusercontent.com/790842/235354144-e7d220e0-202b-4d2e-862b-30fa9c4adfad.png">

**Environment:**
 - Dioxus version: `0.3.2` (cli: `master`)
 - Rust version: `1.68.1`
 - OS info: macos
 - App platform: web
 - Editor: emacs

**Comment by Demonthos** [comment]
This issue was fixed in https://github.com/DioxusLabs/dioxus/pull/839, we just need to bump the Dioxus version in the CLI to the git version or wait for a new Dioxus RSX release

**Comment by Demonthos** [comment]
Now that the Dioxus CLI is pulled into the main dioxus repo, this should be fixed for the git version of the CLI
